### ISSUE TITLE
us-mn-st_louis_county - parcel data

### ISSUE THREAD

**Issue by mmdolbow** [openaddresses/openaddresses#1001]
This county has open data for download on their website here: http://www.stlouiscountymn.gov/LANDPROPERTY/Maps/Data.aspx

And this is a service layer with parcels:
http://gis.stlouiscountymn.gov/arcgis/rest/services/Planning/Cadastral/MapServer/33

But unlike other sources in the Parcel Wiki, this layer DOES have a situs address, with "PHYS*" fields. Here is an example: http://gis.stlouiscountymn.gov/arcgis/rest/services/Planning/Cadastral/MapServer/33/8774072
PHYSADDR: 1726 N 7th Ave E
PHYSCITY: Duluth
PHYSZIP: 55805

Should this go in the parcel wiki under a new heading?

**Comment by geobrando** [comment]
@mmdolbow Looks like the link you posted is stale, but a source with a working data link is currently present. https://github.com/openaddresses/openaddresses/blob/master/sources/us/mn/st_louis.json

But in general, any parcel layer with situs addresses is acceptable.
