### ISSUE TITLE
eval makeloveland.com parcel data

### ISSUE THREAD

**Issue by sbma44** [openaddresses/openaddresses#1002]
@iandees @ingalls @lxbarth the MLL guys have gotten us some sample data:
- https://www.dropbox.com/s/pa19p494317y0uw/_fl_alachua.csv?dl=0
- https://www.dropbox.com/s/agzvc133h50wnyl/_fl_baker.csv?dl=0

I'm going to invite them to collaborate on this ticket. A couple of questions:
- these have very different schemas -- can you guys speak to that?
- `_fl_alachua` has street number and name in the same field -- is it possible to split those out on export? we can post-process this, but if it's present in the DB as separate fields that'll be more reliable (I'm guessing it isn't in the DB that way)

**Comment by dexterslu** [comment]
hey all, sorry for the delay. 

-sorry about the confusion here, mistake on my part. the full export will have the same schema, it looks like I accidentally sent the entire table instead of clipping just the needed columns
-just for some context - this data is a compilation assembled by the department of revenue sent out annually by each county. some counties have the split street number and name and some do not. where this isn't present we can make sure to denote that. 

please let me know if you've got any other questions/needs - otherwise I'll start working on a full export.

**Comment by sbma44** [comment]
@dexterslu sounds good to me!

**Comment by sbma44** [comment]
Hey @dexterslu, is this still something that you guys are interested in working on with us?

**Comment by dexterslu** [comment]
Hey @sbma44 ! sorry for the delay on this, just exported out the entire state into one (csv) with the data structure as follows:

-Parcelnumber
-Geoid
-State 
-County
-City
-Phy_addr1(address)
-Centroid

Will that work? [Here's a link to the file](https://www.dropbox.com/s/0yf30t7t1s70sj5/oa_fl.csv.zip?dl=0)

**Comment by ingalls** [comment]
@dexterslu this format looks absolutely perfect! Thanks so much for getting this to us, this will be an absolutely massive boost for the project! I'll get the file processed and post back here with the results.

**Comment by dexterslu** [comment]
Fantastic, we've also got a nice little list of apis from around 800 or so counties across the countries you [might want to check out](https://www.dropbox.com/s/g0qq57nz8aye7o6/oa_api.csv?dl=0)

**Comment by ingalls** [comment]
Wow! This is fantastic! I notice you don't have a lot for kansas in the list, I'd welcome you to checkout https://github.com/ingalls/Kansas-ORKA, which contains a ton of data.

**Comment by migurski** [comment]
Cool!

**Comment by ingalls** [comment]
I've processed the data and pushed it to our s3 cache. A PR is currently being validated by Travis/Machine here: https://github.com/openaddresses/openaddresses/pull/1142

**Comment by dexterslu** [comment]
awesome work @ingalls if you've got any feed back on that file please let me know. It definitely needs a bit of normalization, there are quite a few points with the same addresses. I've noticed that this primarily happens right at the shoreline...

**Comment by justinelliotmeyers** [comment]
@dexterslu or @ingalls is this something we can continue to get data for? Thanks!

**Comment by ingalls** [comment]
Thanks a ton to the MakeLoveland folks for kickstarting FL.  Going to close this ticket as non-actionable
