### ISSUE TITLE
Open Data for Zurich, Switzerland

### ISSUE THREAD

**Issue by luca-dall** [openaddresses/openaddresses#1025]
Hallo!

Starting from this year all the adresses of the city of Zurich, Switzerland are open data!
https://www.stadt-zuerich.ch/portal/de/index/ogd/daten/adressen.html#description1
Shapefiles as well as Geojson are free to download.

The page is written in german, if you need some help just ask!

Luca

**Comment by slibby** [comment]
This is now added: https://github.com/openaddresses/openaddresses/pull/1276
