### ISSUE TITLE
Newton, MA data

### ISSUE THREAD

**Issue by GuidoS** [openaddresses/openaddresses#1027]
https://github.com/NewtonMAGIS/GISData/tree/master/Addresses

Thanks for the talk at #OSMUS

**Comment by geobrando** [comment]
@iandees Think we removed all of the local Mass sources a while back in favor of a statewide layer. Should we be adding these back?

**Comment by iandees** [comment]
In principal I would love to have data that's as close to the source as possible (in case statewide layers are only updated every couple years or something). But we don't really have a great deduplication plan...

Let's go ahead and add it for now and worry about it later.
