### ISSUE TITLE
France

### ISSUE THREAD

**Issue by MiniCodeMonkey** [openaddresses/openaddresses#1034]
http://adresse.data.gouv.fr

**Comment by migurski** [comment]
Looks like a clickthrough ODbL license. I’m downloading the file.

**Comment by migurski** [comment]
Translation says “Cette version de la BAN ne contient pas de données ODbL, et peut être utilisée gratuitement, sous réserve de repartage des contributions.” (“This version of the NAO does not contain ODbL data, and can be used free of charge, subject to redivision of contributions.”), so perhaps not ODbL.

**Comment by migurski** [comment]
Apparent column meanings:

- `nom_commune` - city name
- `code_post` - postcode
- `lat`, `lon` - WGS84
- `numero` - street number
- `nom_voie` - street name, lowercase
- `nom_afnor ` - street name, all-caps, [possible AFNOR relation?](https://en.wikipedia.org/wiki/AFNOR)
- `libelle_acheminement` - city name, all-caps, possible routing use?
- `code_insee` - [possible INSEE relation?](https://en.wikipedia.org/wiki/INSEE_code)
