### ISSUE TITLE
ca-nb new licence

### ISSUE THREAD

**Issue by berniejconnors** [openaddresses/openaddresses#1059]
Service New Brunswick has changed their data licence to a version of the Open Government Licence.  The new licence can be found here - http://geonb.snb.ca/documents/license/geonb-odl_en.pdf.  The json file should be updated (i don't know how) - https://github.com/openaddresses/openaddresses/blob/master/sources/ca-nb.json

**Comment by migurski** [comment]
Thank you!

**Comment by ingalls** [comment]
Thanks @berniejconnors !
