### ISSUE TITLE
us-md-montgomery postcodes

### ISSUE THREAD

**Issue by michaelblyons** [openaddresses/openaddresses#1062]
According to [the sample][mc-sample], the [`us-md-montgomery` data][mc-config] has city names, but is missing zip codes on some (lots?) of its addresses. When you download the `csv`, though, the zips are missing for _all_ addresses.

1. There's a bug in the `us-md-montgomery` processing somewhere.
2. I endorse adding city names (#230) to the csv output. The data source has those, and without them _or_ the zips, you're left guessing which Maple Avenue you're talking about.

[mc-sample]: http://data.openaddresses.io/runs/1436335974.402/index.html#us-md-montgomery-sample-data
[mc-config]: https://github.com/openaddresses/openaddresses/blob/master/sources/us-md-montgomery.json

**Comment by geobrando** [comment]
@michaelblyons Not sure what was going on before but I just downloaded the montgomery csv from [ci.openaddresses.io](http://ci.openaddresses.io/) and it contains both cities and postcodes.  Look ok to you?
