### ISSUE TITLE
csv data filtering

### ISSUE THREAD

**Issue by tkardi** [openaddresses/openaddresses#1078]
In the Estonian dataset there is the whole hierarchical  address tree presented: all levels have their corresponding address-locations described. Is there a need for somehow filtering those (like admin levels' addresspoints, cities and settlements, flats) out so only house numbers / parcel names remain?

**Comment by NelsonMinar** [comment]
I think we're discussing this question as part of #1077, specifically my [recommended option 1](https://github.com/openaddresses/openaddresses/issues/1077#issuecomment-122336550). If I'm wrong  could you please clarify the question?

**Comment by tkardi** [comment]
It is a different question. What I meant was that if the datasource has the whole address tree present there will be a lot of "noise". For example from the Estonian data an appartment bulding adress tree might look like:

row | type | A1 | A2 | A3 | A4 | A5 | A6 | A7 | A8
----|----|----|----|----|----|-----|-----|-----|-----
1 | A | Tartu maakond | | | | | | | 
2 | B | Tartu maakond | Tartu linn | | | | | | 
3 | C | Tartu maakond | Tartu linn | | | Pikk tn | | | 
4 | D | Tartu maakond | Tartu linn | | | Pikk tn | | 84 | 
5 | E | Tartu maakond | Tartu linn | | | Pikk tn | | 84 | 1
6 | E | Tartu maakond | Tartu linn | | | Pikk tn | | 84 | 2
7 | E | Tartu maakond | Tartu linn | | | Pikk tn | | 84 | 3
... | E | Tartu maakond | Tartu linn | | | Pikk tn | | 84 | ...
m | E | Tartu maakond | Tartu linn | | | Pikk tn | | 84 | n

Therefore if the housenumber/streetname are the main concern rows 1-3 from this example produce meaningless results. Also there's the issue whether appartments/flats/house-parts (type == E) be included or not. 

There's some other issues here aswell. The dataset might be on "addressable objects" not addresses per se. For example my home address has 4 addressable objects: house, cadastral unit, and two "uninhabited buildings" (not sure about the correct term for that in English, sorry). They are all present in the dataset and all have the same address but are distinguished by their objet type value and have different coordinates. 

That's the reason I was talking about "filtering out" - compose a kind of conditional sentence e.g. if this property equals this-or-that then include (or exclude) the data row.

**Comment by NelsonMinar** [comment]
Thanks for clarifying your question. Our code has no way to filter these out; it writes one row of output for every row of input. I think the best thing to do for the Estonian data is just not worry about it. For now, users of our OpenAddresses output will have to filter this out themselves. We should look into improving this along with other changes to make our output easier to use.
