### ISSUE TITLE
Summit County, Ohio as Parcel Data

### ISSUE THREAD

**Issue by skorasaurus** [openaddresses/openaddresses#1085]
Contributing.md says to put parcel data into the wiki but the wiki only has a dataset without situs addresses. 

Even after looking at a couple data sources in there, I'm unsure whether this set has "situs addresses" or not. 

URL download: https://fiscaloffice.summitoh.net/index.php/documents-a-forms/finish/68-parcels/503-parcels
FROM: https://fiscaloffice.summitoh.net/index.php/documents-a-forms/viewdownload/68-parcels/503-parcels

**Comment by geobrando** [comment]
Thanks @skorasaurus.  If a source has two address fields then it's likely that one is an owner address and one is a situs address.  These will differ for some records, and the owner address might actually be out of state. This sources looks to be one of those. I'm adding it.

Sometimes you'll see a separate "Tax address" (address for the person that's paying the tax bill). I've seen some parcel sources that have a tax and a owner address but no situs.  But these are rare.
