### ISSUE TITLE
Raw data for Louisville, KY

### ISSUE THREAD

**Issue by schnuerle** [openaddresses/openaddresses#1094]
Raw: 
ftp://ftp.lojic.org/pub/federal/Address%20Sites.zip

Directory:
ftp://ftp.lojic.org/pub/federal/

Attribution:
"Data provided by permission of the LOJIC partners"

License: 
ftp://ftp.lojic.org/pub/federal/Disclaimer.pdf

We at the www.civicdataalliance.org have already imported this, along with buildings into Open Street Map, FYI.

**Comment by schnuerle** [comment]
Oh here's Louisville (Jefferson County, from same source: LOJIC) already there, but not imported yet. https://github.com/openaddresses/openaddresses/blob/master/sources/us-ky-jefferson.json  

Not sure if the direct FTP link is better than this or not.

**Comment by geobrando** [comment]
Thanks @schnuerle.  Looks like this source has been added.

https://github.com/openaddresses/openaddresses/blob/master/sources/us/ky/jefferson.json

**Comment by iandees** [comment]
Thanks!
