### ISSUE TITLE
Retail Location Data

### ISSUE THREAD

**Issue by rhaussmann** [openaddresses/openaddresses#1111]
We work with distributing retail locations. Is this acceptable? How should it be handled?

**Comment by iandees** [comment]
How are the latitude and longitude of the retail locations captured? If their addresses are run through a geocoder to get the lat/lon, then we can't really use it in our data set.

**Comment by rhaussmann** [comment]
In most cases, we manually look up the locations and drop pins on the
building (rather than the curb).

**Comment by sbma44** [comment]
If you have rights to the data, I'd certainly be interested in seeing how it could be added to OA. Do you have a sample you can share?
