### ISSUE TITLE
ca-qc-gatineau License url change

### ISSUE THREAD

**Issue by james2432** [openaddresses/openaddresses#1130]
The url of the license agreement for Gatineau Quebec has changed to:
http://gatineau.ca/donneesouvertes/telecharger_en.aspx?url=%2fupload%2fdonneesouvertes%2fADRESSE.zip

Not sure how else to contribute this information other than opening an issue.
The shape file url remains the same

Also License must be accepted before you can download the .zip, or it will fail to download

**Comment by geobrando** [comment]
Thanks @james2432.  License looks to be the same but just accessible through two urls.  Your point about the clickthrough is noted and I'm adding a `skip:` tag for now.
