### ISSUE TITLE
investigate NSW APIs

### ISSUE THREAD

**Issue by sbma44** [openaddresses/openaddresses#1152]
CC-BY licensed, let's see if there's anything here

http://spatialservices.finance.nsw.gov.au/mapping_and_imagery/lpi_web_services

cc @ingalls

**Comment by iandees** [comment]
http://maps.six.nsw.gov.au/arcgis/rest/services/public/NSW_Property/MapServer

Looks like parcel-like things with address-like things here.

**Comment by sbma44** [comment]
OpenAddresses' ESRI capabilities are a black box to me, I will have to defer to you guys on this one...

**Comment by justinelliotmeyers** [comment]
this source looks good, might have to pull it from each resource:
http://maps.six.nsw.gov.au/arcgis/rest/services/public/NSW_Property/MapServer/1
http://maps.six.nsw.gov.au/arcgis/rest/services/public/NSW_Property/MapServer/2
http://maps.six.nsw.gov.au/arcgis/rest/services/public/NSW_Property/MapServer/3
http://maps.six.nsw.gov.au/arcgis/rest/services/public/NSW_Property/MapServer/4

http://maps.six.nsw.gov.au/arcgis/rest/services/public/NSW_Property/MapServer/4 has over 3 million records!!

**Comment by andrewharvey** [comment]
> I've reached out to clarify that point, I'll update what they come back with.

So long as we aren't continuously adding a lot of load to their server, they mentioned it will be okay.
