### ISSUE TITLE
Western Australia

### ISSUE THREAD

**Issue by sbma44** [openaddresses/openaddresses#1154]
WA has published its open data policy which is great, including a presumption that resources are open by default: http://www.data.wa.gov.au/open-data-policy

Eventually open data will live at: http://www.data.wa.gov.au/

It promises a future open data portal that currently directs users to SLIP: http://slip.landgate.wa.gov.au/

SLIP includes address info at web service endpoints, but their "open data" page is still empty:
http://slip.landgate.wa.gov.au/Pages/SLIP-Property-Street-Address-Subscription-Service.aspx

Existing license on the site points to personal use only, but I suspect this just hasn't been updated. I've emailed their customer service address to ask for clarification.

**Comment by sbma44** [comment]
Also found this README which implies everything is CC-(something): https://github.com/Landgate/GovHack-2015/blob/master/README.md

I've emailed the author

**Comment by slibby** [comment]
Full GNAF is now available via https://github.com/openaddresses/openaddresses/pull/1588 but I think this issue can stay open in the hope that WA provides their own complementary set.

**Comment by justinelliotmeyers** [comment]
closing as per: https://github.com/openaddresses/openaddresses/issues/3677
