### ISSUE TITLE
Weld County, CO - click-thru URL

### ISSUE THREAD

**Issue by slibby** [openaddresses/openaddresses#1184]
Weld County has points on Sharefile:

http://www.co.weld.co.us/Departments/GIS/GISData.html

_which leads to_

https://weldcounty.sharefile.com/share#/download/s605bee99e574342a

_which leads to_

https://storage-usnw-2.sharefile.com/download.ashx?dt=dt4b53216d9b1e45bda6cd94d436611ea3&h=zNYBdwAdXSrvn2Przn9%2b2%2ffQ%2b5SDt%2fry6LcdbPm%2byz8%3d

Wondering if this final link is durable or whether there needs to be a way to work around the click-thru.

**Comment by ingalls** [comment]
Hey looks like we were both working on the same thing. I've actually got weld county here: 
https://github.com/openaddresses/openaddresses/blob/master/sources/us/co/weld_county.json

In these cases just ask one of the project maintainers to manually upload it to the cache.

**Comment by justinelliotmeyers** [comment]
Updated data:https://gishub.weldgov.com/datasets/1483cb91e097462383929f6aecb61649_0/explore

**Comment by iandees** [comment]
We actually pull from that data already :+1:
