### ISSUE TITLE
Tracking completion status by geographic area

### ISSUE THREAD

**Issue by slibby** [openaddresses/openaddresses#1201]
@iandees @migurski @ingalls Is there a good way that the project could track the completion of states/countries now that they're in subfolders? I thought that if there was a "status.txt" file in the Colorado folder for example, it could include a list of all the counties and/or cities and their status (found, successfully imported, unavailable, locked in other system, etc).

Would the machine ignore a .txt in this case? I think this would save on duplicative research that people are doing (i.e. trying to find county gov't websites) such as when @ingalls and I were both working on Colorado.

**Comment by ingalls** [comment]
@slibby I'm definitely for avoiding duplicate research. What I personally use for coverage is: https://github.com/ingalls/openaddresses-coverage

It will generate a coverage map that can be opened in qgis allowing one to quickly see what counties/states don't yet have coverage.

**Comment by slibby** [comment]
Itneresting, that's cool and definitely works well from a personal perspective -- I guess where I'm coming from is that if the project is looking for community contributions, and the main way to do that is identifying areas that aren't covered by looking at data.openaddresses.io and then comparing to a long list of .json files, that's not super efficient, nor is there any way to tie previous requests for data that others have already submitted or efforts on searching for data back to that status. 

I believe the existing/recommended method for that is to create Github issues for new dataset searches or when a request has been made to local gov't, but I've found that searching for a Github issue is not the easiest/most reliable way of tracking status, though that may just be me.

**Comment by iandees** [comment]
I agree that there needs to be an easier way to keep track of progress.

Maybe we could build a separate page that shows progress from coverage data in existing sources combined with links to Github issues that track missing sources. There's also [a Google Doc](https://docs.google.com/spreadsheets/d/1HFm0YbFDC5YKkHKFt89EKdhpyaCCIo_CiDFjBNq4PoI/edit) that @NelsonMinar created where we could keep this status manually.

**Comment by slibby** [comment]
Discussion is stale, closing.
