### ISSUE TITLE
Glendale Arizona Address Data

### ISSUE THREAD

**Issue by TheDutchMan13** [openaddresses/openaddresses#1223]
I found this data awhile back. Didn't have a github account to submit it. Now i do. I have no clue what the license is but i'm pretty sure it open.
Here's the link http://gis.glendaleaz.com/gis/

**Comment by iandees** [comment]
Thanks for tracking this down! [We've got this source in our list](https://github.com/openaddresses/openaddresses/blob/master/sources/us/az/glendale.json), we just need to add a [conform object](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#conform-object) to it so it'll show up in our data outputs.

**Comment by TheDutchMan13** [comment]
I apologise for that, had no clue. Uploaded this issue at work from my phone so i wasn't able to check the prior sources beforehand. Thanks for taking care of the issue right away.

**Comment by iandees** [comment]
No need to apologize! Thank you for pointing out the data. Keep looking for other data sets :smile:.
