### ISSUE TITLE
Add and render US place FIPS codes?

### ISSUE THREAD

**Issue by geobrando** [openaddresses/openaddresses#1225]
I've been adding FIPS codes to US Census objects for city and town sources but then after looking at the [`render.render()`](https://github.com/openaddresses/machine/blob/master/openaddr/render.py#L270) I realized that these do not render on the status maps.  So adding them really only has the effect of removing the "incomplete coverage" error message from http://results.openaddresses.io/.

Cities with geometry objects are rendered and are visible on the US status map.  Should we be allowing FIPS for cities, towns, etc and rendering them?  Related to this, should machine throw an error when a source has a complete coverage object but is not able to be rendered?

![rendered-point](https://cloud.githubusercontent.com/assets/1833870/9664343/1938906c-5237-11e5-962b-adaae1ad1ad1.png)

**Comment by migurski** [comment]
I don’t think it should throw an error, but we probably do want to show Census places on the map.
