### ISSUE TITLE
California parcels

### ISSUE THREAD

**Issue by aaronlidman** [openaddresses/openaddresses#1250]
http://egis3.lacounty.gov/dataportal/2015/09/11/california-statewide-parcel-boundaries/

![collection_2112-14-791x1024](https://cloud.githubusercontent.com/assets/58878/9937810/4d147eec-5d30-11e5-96eb-4f204b2dd7f8.png)

Highlights:
- [GeoDB download](http://egis3.lacounty.gov/dataportal/wp-content/uploads/ShapefilePackages/Parcels_CA_2014.zip)
- Parcel boundaries for 51 (out of 58) counties in the State of California.
- CA_Merged file with the parcels merged into a single file
- this data does not include attributes beyond the parcel ID number (PARNO)

**Comment by migurski** [comment]
Wow, nice one.

**Comment by migurski** [comment]
I see some coverage above and beyond what [we’ve currently got](http://results.openaddresses.io/sets/18859/):

<img width="250" alt="ca" src="https://cloud.githubusercontent.com/assets/58730/9938028/28b6a114-5d18-11e5-926f-8015dc6c5157.png">

**Comment by iandees** [comment]
I think we've looked at this dataset before and it doesn't include anything beyond the parcel number. We can definitely use it for our upcoming parcel boundaries dataset, but I don't think there are any usable addresses.
