### ISSUE TITLE
Newcastle UK

### ISSUE THREAD

**Issue by ingalls** [openaddresses/openaddresses#126]
We currently have no UK addresses mostly due to the fact that there is a huge monopoly on address data in the UK.

I have managed to find this source:
Data: http://gisweb1ng.newcastle.gov.uk/ArcGIS/rest/services/YHN_GIS004/MapServer/15
Website: http://www.newcastle.gov.uk/

Does anyone know what the deal is with addressing and copyright in the UK?

**Comment by garfbradaz** [comment]
Can you source the data here for the UK?

https://alpha.openaddressesuk.org/

**Comment by nvkelso** [comment]
Spending 5 minutes with the data, those mostly seem to be postal codes
(down to street level), not address points. Can you provide an example of a
street number address in their dataset, please? Generally but also for
Newcastle?

**Comment by justinelliotmeyers** [comment]
@ingalls I'm going to close this out if that is okay with you? We aren't doing anything in the UK any time soon as per their crazy copyright restrictions. That okay?
