### ISSUE TITLE
[WIP] Colorado County Status

### ISSUE THREAD

**Issue by slibby** [openaddresses/openaddresses#1300]
An attempt at tracking status for a state:

| County | County seat | Status | Comments |
| --- | --- | --- | --- |
| Adams County | Brighton | :+1: | http://www.adcogov.org/index.aspx?NID=793 |
| Alamosa County | Alamosa |  | several services available here but no SITUS addresses: http://services1.arcgis.com/zH7gQ37AKcpvTX6d/ArcGIS/rest/services |
| Arapahoe County | Littleton | :+1: |  |
| Archuleta County | Pagosa Springs | :+1: |  |
| Baca County | Springfield |  | http://bacacountyco.gov/assessor.html |
| Bent County | Las Animas |  | http://bentcounty.org/ |
| Boulder County | Boulder | Parcel Data does not contain address, it's queried <br> through another web service. Could email for listings.   <br> | http://www.bouldercounty.org/property/info/pages/mountainaddress.aspx |
| City and County of Broomfield | Broomfield | :+1: |  |
| Chaffee County | Salida |  |  |
| Cheyenne County | Cheyenne Wells |  | Should request parcel data from:<br> http://www.co.cheyenne.co.us/countydepartments/assessor.htm |
| Clear Creek County | Georgetown | :+1: |  |
| Conejos County | Conejos | :+1: |  |
| Costilla County | San Luis |  |  |
| Crowley County | Ordway |  | http://qpublic.net/co/crowley/ |
| Custer County | Westcliffe |  | http://qpublic.net/co/custer/ |
| Delta County | Delta | :+1: |  |
| City and County of Denver | Denver | :+1: |  |
| Dolores County | Dove Creek |  | Partial county-wide addresses. Reticent to release, I'm working on them! - @slibby. |
| Douglas County | Castle Rock | :+1: |  |
| Eagle County | Eagle | :+1: |  |
| El Paso County | Colorado Springs |  |  |
| Elbert County | Kiowa |  |  |
| Fremont County | Cańon City | :+1: |  |
| Garfield County | Glenwood Springs | :+1: |  |
| Gilpin County | Central City | :+1: |  |
| Grand County | Hot Sulphur Springs | :+1: |  |
| Gunnison County | Gunnison | :+1: |  |
| Hinsdale County | Lake City | :x: | Has no digital data on addresses or parcels |
| Huerfano County | Walsenburg | has parcels: http://www.huerfano.us:8008/onlinemaps/ | emailed 10/21/2015 |
| Jackson County | Walden |  |  |
| Jefferson County | Golden | :+1: |  |
| Kiowa County | Eads |  |  |
| Kit Carson County | Burlington |  |  |
| La Plata County | Durango | :+1: |  |
| Lake County | Leadville |  |  |
| Larimer County | Fort Collins | :+1: |  |
| Las Animas County | Trinidad |  |  |
| Lincoln County | Hugo |  |  |
| Logan County | Sterling |  | viewer, secured service: http://loganco.mygisonline.com/ |
| Mesa County | Grand Junction | :+1: |  |
| Mineral County | Creede | :+1: |  |
| Moffat County | Craig | :+1: |  |
| Montezuma County | Cortez | :+1: |  |
| Montrose County | Montrose | :+1: |  |
| Morgan County | Fort Morgan |  | Contacted 1/27/2016 |
| Otero County | La Junta |  | Contacted 1/27/2016 |
| Ouray County | Ouray |  | Contacted 1/27/2016 |
| Park County | Fairplay | :+1: |  |
| Phillips County | Holyoke |  |  |
| Pitkin County | Aspen | :+1: |  |
| Prowers County | Lamar |  | Contacted 1/27/2016 |
| Pueblo County | Pueblo | :+1: |  |
| Rio Blanco County | Meeker | :+1: |  |
| Rio Grande County | Del Norte |  | Parcels available via REST, but no addresses: http://maps.co.pueblo.co.us/outside/rest/services/riogrande/riogrande_county_parcels_april2015/MapServer |
| Routt County | Steamboat Springs | :+1: |  |
| Saguache County | Saguache |  |  |
| San Juan County | Silverton |  |  |
| San Miguel County | Telluride | :+1: |  |
| Sedgwick County | Julesburg |  |  |
| Summit County | Breckenridge |  | 14,000 points available for $400 fee: <br> http://www.co.summit.co.us/DocumentCenter/Home/View/265 |
| Teller County | Cripple Creek | :+1: |  |
| Washington County | Akron | :+1: |  |
| Weld County | Greeley | :+1: |  |
| Yuma County | Wray |  |  |

**Comment by osMatt** [comment]
A collection of Colorado addresses is available at https://data.colorado.gov/Transportation/2015-Colorado-Address-Layer-Public-/n7je-akky. Since these are taken from other available data sources, many of these might already be included. I have not checked all counties, but a difference is that Boulder county (see also #411) is included in this data source.

**Comment by iandees** [comment]
More info about the statewide project: http://oit.state.co.us/broadband/colorado-state-address-dataset

**Comment by justinelliotmeyers** [comment]
@slibby can i close this, or should we keep open?  Thanks!

**Comment by slibby** [comment]
@justinelliotmeyers yes I have not worked on this in some time, it can be closed.

**Comment by justinelliotmeyers** [comment]
thanks @slibby !!
