### ISSUE TITLE
Indiana Statewide

### ISSUE THREAD

**Issue by slibby** [openaddresses/openaddresses#1306]
Available as REST service here: http://maps.indiana.edu/arcgis/rest/services/Infrastructure/Streets_Address_Points_IDHS/MapServer/0
3,191,230 points reported, probably too many to scrape with machine.

file GDB available in current source json:http://maps.indiana.edu/download/Infrastructure/Streets_Address_Points_IDHS.zip

caching doesn't support filegdb (yet).

**Comment by ingalls** [comment]
@slibby want to add the REST endpoint as a source anyway? There are talks about changing how the timeout works with ESRI values so it would be good to have this ready to test out.

**Comment by slibby** [comment]
Will do.

Sent from my mobile phone.

On Sep 24, 2015, at 10:23 PM, Nick <notifications@github.com<mailto:notifications@github.com>> wrote:


@slibby<https://github.com/slibby> want to add the REST endpoint as a source anyway? There are talks about changing how the timeout works with ESRI values so it would be good to have this ready to test out.

**Comment by slibby** [comment]
closed by https://github.com/openaddresses/openaddresses/issues/1364
