### ISSUE TITLE
Bermuda

### ISSUE THREAD

**Issue by slibby** [openaddresses/openaddresses#1309]
Would this fall under sources/uk/bermuda.json? 
http://www.arcgis.com/home/item.html?id=218b6315a903439c99761fd7f85396e4

**Comment by geobrando** [comment]
Since Bermuda has its own ISO 3166-1-alpha-2 I would say it would go under sources/bm/statewide.json or sources/bm/nationwide.json

**Comment by slibby** [comment]
@geobrando Sounds good, I'll do that when I add it.

**Comment by slibby** [comment]
closed by https://github.com/openaddresses/openaddresses/pull/1318
