### ISSUE TITLE
Australia

### ISSUE THREAD

**Issue by ingalls** [openaddresses/openaddresses#132]
http://data.gov.au/dataset/launceston-city-council-addresses

CCBY3.0: Australia
http://mapping.launceston.tas.gov.au/arcgis/rest/services/Public/Addresses/MapServer/0

**Comment by wboykinm** [comment]
@sbma44 This is hella-superseded by #1470, right?

**Comment by sbma44** [comment]
yeah, but we generally keep duplicate sources. I see a `tas-launceston.json` in sources, though, so I think this can be closed.
