### ISSUE TITLE
Boston, MA

### ISSUE THREAD

**Issue by mapmeld** [openaddresses/openaddresses#1328]
Hey, I just noticed you were missing Boston. They have their data in ArcGIS Server, and release parcel data, but when I worked there we were reluctant to publish addresses because it changes often & we didn't want to run a public geocoder. I think OpenAddresses is a good alternative.

@mlevans @nsjacob @CurtSavoie is this data open, like parcels are?
 
Here's a sample query into SAM
http://maps.cityofboston.gov/ArcGIS/rest/services/Live_SAM_Addr_BKP/MapServer/0/query?text=&geometry=&geometryType=esriGeometryPoint&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&objectIds=&where=1%3D1&time=&returnCountOnly=false&returnIdsOnly=false&returnGeometry=true&maxAllowableOffset=&outSR=4326&outFields=&f=pjson

**Comment by slibby** [comment]
@mapmeld it looks like that service doesn't exist or is secured.

Would one of these work?
http://maps.cityofboston.gov/ArcGIS/rest/services/Basemaps/basemap_LAGAN/MapServer/6
http://maps.cityofboston.gov/ArcGIS/rest/services/Basemaps/basemap_LAGAN/MapServer/7
http://maps.cityofboston.gov/ArcGIS/rest/services/SAM/DYNAMIC_ADDRESSES/MapServer/0

Any idea on which is the best/most up-to-date to use?

**Comment by ajturner** [comment]
This is the recommended service - http://gis.cityofboston.gov/arcgis/rest/services/SAM/Live_SAM_Address/MapServer/0

Metadata http://bostonopendata.boston.opendata.arcgis.com/datasets/b6bffcace320448d96bb84eabb8a075f_0

**Comment by iandees** [comment]
D'oh I forgot to close this ticket in https://github.com/openaddresses/openaddresses/pull/1549.
