### ISSUE TITLE
New Dataset: Cape Town - South Africa 

### ISSUE THREAD

**Issue by Firefishy** [openaddresses/openaddresses#1340]
https://web1.capetown.gov.za/web1/OpenDataPortal/DatasetDetail?DatasetName=Street%20addresses

**Comment by slibby** [comment]
Is there any comparison to https://github.com/openaddresses/openaddresses/blob/master/sources/za/wc/cape_town.json ?

**Comment by Firefishy** [comment]
Ah! Already exists.
