### ISSUE TITLE
State Law Preventing Free Distribution of Parcel Data?

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#1352]
Louisville's CfA Brigade Captain recently said "KY state law either prevents the free distribution of property parcel data, or explicitly requires it to be sold."

I'm going to do some research, but I figured perhaps this was the best place to ask first.
Does anyone know if this is true?
Has anyone run into something similar? Where?

Thanks!
Cheers.
Albert

**Comment by jalbertbowden** [comment]
I want to say that since Lexington is serving it up it is not a law....
http://data.lexingtonky.gov/dataset/parcel

**Comment by migurski** [comment]
That sounds reasonable to me, wonder what @eeeschwartz might know about this.

**Comment by eeeschwartz** [comment]
I'm not actually sure how all of the legalities shake out unfortunately.

**Comment by Pazoles** [comment]
Louisville’s LOJIC (GIS Consortium) website explicitly points to this as the legal basis for their fee: http://www.lojic.org/main/products/pdfs/krs61.pdf

**Comment by jalbertbowden** [comment]
seems like if anything, this is local and not state law.
thanks for that

**Comment by jalbertbowden** [comment]
@Pazoles actually i take that back, it looks statewide. however the state has a more current document
http://www.lrc.ky.gov/lrcpubs/openmtgsrecords.pdf
need to do a diff to find differences, but offhand, wondering why they're using an outdated document. 
or am i missing something?
