### ISSUE TITLE
Add "unit" to accepted conform tags

### ISSUE THREAD

**Issue by migurski** [openaddresses/openaddresses#1380]
@iandees: “This will be things like apartment number, unit number, etc.”

Context: https://github.com/openaddresses/machine/issues/232

**Comment by migurski** [comment]
With https://github.com/openaddresses/machine/issues/232 closed and machine 2.9.0 released, we can add this to documentation.

**Comment by slibby** [comment]
How's this look: https://github.com/openaddresses/openaddresses/pull/1481

**Comment by migurski** [comment]
Oops, "unit" needs to be present in the unit tests as well. I always forget this step.
