### ISSUE TITLE
Add parcel data for Kent County (home of Grand Rapids, MI)

### ISSUE THREAD

**Issue by orangejulius** [openaddresses/openaddresses#1389]
Kent County has shapefiles of parcel data for every city in the county, including Grand Rapids.

They're available at https://www.accesskent.com/GISLibrary/#Parcels&Streets

I'll probably try to get to it some time in the next few days, unless someone else really wants to do it :)

**Comment by slibby** [comment]
This service should work (found from map viewer): http://gis.kentcountymi.gov/prodarcgis/rest/services/External/MapServer/6

**Comment by orangejulius** [comment]
Nice. There's also http://gis.kentcountymi.gov/prodarcgis/rest/services/External/MapServer/5 which has parcel geometry as well as address info
