### ISSUE TITLE
The Netherlands - suggestion for resource

### ISSUE THREAD

**Issue by justb4** [openaddresses/openaddresses#1400]
I see that the addresses CSV for The Netherlands is lacking several fields like Postal codes, City, Province, WGS84 coordinates,  etc. I scanned several issues on this subject: #93, #233 and #800. 

From what I noticed is the NodeJS script https://github.com/openaddresses/openaddresses/blob/master/scripts/nl/nl-data.js that parses the raw address-data provided by the Dutch government (Kadaster, PDOK) at http://geodata.nationaalgeoregister.nl/inspireadressen/extract/inspireadressen.zip will not render complete addresses. Worse: as also history is included in the source data (using begin-end dates and other attributes) , it may render many duplicates. 

This is not to blame anyone, since the Dutch government made it *very* hard for us to derive  complete addresses from their source data :-( called the "BAG" (Base Registry for Addresses and Buildings). Apart from the history-issue, the dataset "BAG" comprises both buildings and "addressable objects" in a complex, normalized XML schema but lacking "Gemeentes" (like Counties) and Provinces and is using a local projection (EPSG:28992).

For some years, as Bert Spaan @bertspaan has indicated in one of the issues, we run a local Open Source project called NLExtract (http://nlextract.nl) to provide tools to extract the BAG and other Dutch geo-datasets mainly into PostGres/GIS. For the BAG this is a dedicated Python program with several SQL scripts to enrich the data with Counties, Provinces and more.

As running the NLExtract scripts for addresses may be a bit complex and time-consuming (couple of hours), we are also making the end-results available as downloads. The data is refreshed each month by PDOK via an RSS URL: http://geodata.nationaalgeoregister.nl/inspireadressen/atom/inspireadressen.xml
We have a daemon running that detects that a new BAG-version is available. It will run NLExtract for BAG and make the results available as a PostGIS dump or, what I think is useful for OA a zipped CSV of adresses. The download URL is  http://data.nlextract.nl/bag/csv/
(I now see that the date is in the CSVs, we may change this to "latest").

So all in all I would suggest to harvest Dutch addresses from http://data.nlextract.nl/bag/csv. For this I guess some changes are needed. Let me know if I can help, possibly via a PR.

**Comment by sbma44** [comment]
This sounds like an excellent suggestion, @justb4 -- thank you for taking the time to dig into the problem. Replacing the existing NL source sounds like a good idea.

At a glance, it looks like the NLExtract output produces a monthly CSV. I suspect that building a conform object to point to one of these would be fairly simple (though I am unsure if we presently support gzip). Do you feel comfortable taking a pass at this, using an existing conform object as an example?

**Comment by migurski** [comment]
Also unsure about gzip support, since this is a content-type and not HTTP content-encoding. We do support .zip, so I think it would be an easy addition. May be tricky to handle dates in the names; there’s some significant overlap with https://github.com/openaddresses/machine/issues/206.

**Comment by sbma44** [comment]
flexibility in URL construction would be very powerful but I'm not actually sure of the best way to support it (even having read that ticket)

**Comment by migurski** [comment]
Yeah, it’s complex. I’m thinking to slowly build up a catalog of date structures in URLs, and have the fetcher check dates in turn. Medium-crazy.

**Comment by justb4** [comment]
Thanks for all the replies. We also strive to make automatic downloads easier for our users. We already had a symlink to  the latest PostGIS dump. Now I have added that as well to the CSV. The link is 
http://data.nlextract.nl/bag/csv/bag-adressen-laatst.csv.zip. Also replaced .gz compression with .zip as that is more common anyway. So that is at least a start.

The structure of the CSV is straightforward, though the fields have Dutch names:

	openbareruimte ('public space', basically streetname),
	huisnummer, (house nr)
	huisletter, (house letter, e.g. 9A)
	huisnummertoevoeging, (house number addition e.g. 9A2)
	postcode, (postal code)
	woonplaats, (~city)
	gemeente, (~county)
	provincie, (province/state)
	object_id (BAG id, internal object ID)
	object_type (BAG object type, Object Type)
	nevenadres (f=nee, t=ja) (subaddress?)
	x, (local projection EPSG:28992 X)
	y, (local projection EPSG:28992 Y)
	lon, (WGS84)
	lat (WGS84)

I have to dive into how `conform objects` are constructed, but I think the above two changes were needed anyway.

**Comment by slibby** [comment]
@justb4 PR opened here with your suggestions: https://github.com/openaddresses/openaddresses/pull/1471

**Comment by slibby** [comment]
@justb4 The processing was quite slow, so I ended up reducing file size by removing these fields:
- object_id
- object_type
- nevenadres
- x
- y

Then uploading the file to dropbox and pulling it from there. Will keep working on another solution that processes more quickly.

**Comment by justb4** [comment]
@slibby thanks for pulling this forward! Yes, strictly, for international addresses you won't need the fields you removed.
