### ISSUE TITLE
regions without official street addresses

### ISSUE THREAD

**Issue by perrygeo** [openaddresses/openaddresses#1406]
_Not an actionable ticket, just a theoretical question that will be important as this database grows past the developed world_

I am currently living in Grenada in the Caribbean. We don't have postal codes or street addresses - the postal service doesn't deliver so there has never been a need for it. At best people refer to the their residence by street name, informal neighborhood name, parish and country (I live at `Ocean Breeze Drive,  L'anse Aux E'pines, St. Georges, Grenada` - that's literally what I put as my official address). It's obviously not unique as my neighbors all share the same address. To differentiate, many businesses will request an additional description ("third house on the left with a white roof") that stands in for house numbers.

Is there a way to fit these less formal, fuzzy, non-unique addresses in the openaddresses data model?

 I'd imagine that many places in the developing world will have this issue so it would be good to include guidance on how/if it's appropriate to incorporate them.

**Comment by migurski** [comment]
In theory, the "number" would be the place for the extra information. This is how I might represent such an address in OpenAddresses output:

```
NUMBER        STREET
third house   Ocean Breeze Drive
```

**Comment by slibby** [comment]
Just reviewing issues and came across this. It's an interesting discussion, I think the UPU/International opinion would be "most things need actual number addresses eventually" for various service delivery needs but I can see a lot of cases where that's overkill/unnecessary. @perrygeo what do you know about the current state of digital cadastre and/or building footprint mapping in Grenada? Those two initiatives are usually the precursors to address requirements in my experience.

**Comment by perrygeo** [comment]
I'm not sure about digital cadastre but I strongly suspect not. Most government operations here that I've dealt with (customs, visa, vehicle registration, insurance, etc.) are paper-based. 

Many of the roads don't even have names, let alone house numbers. There is no mail or parcel delivery service (it's a small island, everyone travels to their local post office to pick up mail) so presumably not much need for a formal address system. I'm not sure about emergency services but most taxi drivers and long-time residents can recall the location of individual houses based on a description.

**Comment by ingalls** [comment]
Going to close as stale - feel free to open again if we want to continue discussion
