### ISSUE TITLE
Abbreviation expansion is expanding the streetname "La Avenida" into "Lane Avenida"?

### ISSUE THREAD

**Issue by orangejulius** [openaddresses/openaddresses#1456]
This was found in pelias looking at [1065 La Avenida, Mountain View, Santa Clara County, California, 94043](http://pelias.github.io/compare/#/v1/search%3Fsize=2&sources=oa&text=1065%20La%20Avenida,%20Mountain%20View,%20Santa%20Clara%20County,%20California,%2094043), which wasn't appearing correctly.

The relevant OA data shows Lane Avenida as well:
```
julian@julian-mapzen ~/data/openaddresses-collected/us/ca $ grep -i "Avenida" santa_clara_county.csv | grep "MOUNTAIN VIEW" | grep 1050
-122.0700381,37.4136338,1050,Lane Avenida Avenue,MOUNTAIN VIEW,,,94043,
```

I dug into the actual Santa Clara county data, and La Avenida is in there correctly:
![screenshot from 2015-11-13 16 34 54](https://cloud.githubusercontent.com/assets/111716/11158227/c4684570-8a24-11e5-97a2-1f325bdc8d02.png)

Is it possible that somewhere OA is expanding La to Lane?

Edit:
See also the same thing in [Houston](http://pelias.github.io/compare/#/v1/search%3Fsize=1&sources=oa&text=lane%20avenida,%20houston) and [Dallas](http://pelias.github.io/compare/#/v1/search%3Fsize=3&sources=oa&text=lane%20avenida,%20dallas)

**Comment by migurski** [comment]
Yes, and it’s probably wrong to do so. Linking to this discussion for completeness: https://github.com/openaddresses/machine/issues/32

**Comment by orangejulius** [comment]
@migurski: now that openaddresses/machine#32 is well resolved, is it possible to rebuild sources that haven't changed in a while? All the cases listed in this issue are not fixed (although another case mentioned in pelias/pelias#232 _is_ fixed).

**Comment by migurski** [comment]
Everything should get rebuilt on a near-weekly basis, unless there's a failure and we use a previously-successful run. Looks like Santa Clara, CA is up-to-date as of today in https://results.openaddresses.io.

**Comment by orangejulius** [comment]
Hey @migurski,
I was just looking into this issue today, and strangely the street names are correct in the city of Mountain View and Santa Clara county individual downloads, but the global file (that Pelias uses) _still_ has `Lane Avenida` as a streetname. Is something stuck somewhere, and if so, can it be fixed? :pray:

**Comment by migurski** [comment]
So we are still doing street name expansions in the US; from that post: "moves name expansion to periodic collections instead". Periodic collections are the big files. What would you like to have happen instead?

**Comment by migurski** [comment]
FYI, here’s where street name expansion happens: https://github.com/openaddresses/machine/blob/2.21.4/openaddr/ci/collect.py#L274-L292

**Comment by orangejulius** [comment]
Ohhhh, I didn't realize it would be treated differently for the periodic collections. Okay, In this case we can close this issue and Pelias will switch to using the small files.
