### ISSUE TITLE
Update Tasmania info

### ISSUE THREAD

**Issue by ljbade** [openaddresses/openaddresses#1457]
The information on Tasmania should be updated to reflect that it is now possible to easily download all the address points for Tasmania from http://listdata.thelist.tas.gov.au/opendata/index.html#LIST_Address_Points

It is broken up by council boundaries into separate files.

/cc @sbma44

**Comment by ljbade** [comment]
Working on a PR. Not sure how to get this to update data now it is split by council area.

A few corrections:
- updated licence field to new format
- ensure the street number post-fix is joined
- add city/district/postcode/state fields
- ensure the street suffix is joined, eg "SOMEWHERE" "ST" "EAST" (only a few roads have these)
- id

A number of addresses I am not sure how we handle:
- place name instead of number + street, e.g. name of a farm (uses separate column)
- unit numbers, e.g. apartments, 12/33 blah street (unit in separate column from street number)
- street address ranges - block might have a range of street numbers, e.g. 14-15 blah street (end street number in seperate column)
- quality/source ids - there are columns for determining how the address was created

Full details on each field is in http://listdata.thelist.tas.gov.au/public/LIST_Address_Points_information.pdf

**Comment by ljbade** [comment]
Exactly how one can use the new data with our system is not clear as it is split into multiple files by council area.

A cache file will still likely be needed which combines the shape files into a single file.

**Comment by iandees** [comment]
The easiest thing to start with is probably to give each council file its own source in OpenAddresses.
