### ISSUE TITLE
Update Queensland info

### ISSUE THREAD

**Issue by ljbade** [openaddresses/openaddresses#1458]
The Queensland data is now available from https://data.qld.gov.au/dataset/property-address-queensland--data-package

Still requires an email flow, but is listed again as CC-BY

**Comment by ljbade** [comment]
Working on a PR. Will upload a new cache of October 2015 data.

A few corrections:
- updated licence field to new format
- ensure the street number post-fix is joined
- add city/district fields

A number of addresses I am not sure how we handle:
- place name instead of number + street, e.g. name of a farm (uses separate column)
- unit numbers, e.g. apartments, 12/33 blah street (unit in separate column from street number)
- street address ranges - block might have a range of street numbers, e.g. 14-15 blah street
- unique id - possibly from plan and lot number columns
- quality/source ids - there are columns for determining how the address was created
- "XXXX" addresses, can find this in the street prefix at times

**Comment by ljbade** [comment]
I also emailed the department that looks after this data to see if they have a better description then the one included in the metadata page. It is missing a number of codes etc. Even if we don't use them we should at least attach to this issue for future reference.

**Comment by ljbade** [comment]
@sbma44 When using COLUMNx for the field name, does it start count at 0 or 1?

**Comment by ljbade** [comment]
Hmm, not sure how to upload a new cache file.

**Comment by sbma44** [comment]
@ljbade I can give you a hand uploading the new cache file

**Comment by porjo** [comment]
http://results.openaddresses.io/ is showing the following error in the log output (instead of 'Show Sample Data' button)
```
2015-12-04 23:15:41,639  WARNING: Error doing excerpt; skipping
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openaddr/__init__.py", line 167, in conform
    data_sample, geometry_type = task3.excerpt(decompressed_paths, workdir, conform)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/conform.py", line 220, in excerpt
    layer = datasource.GetLayer()
AttributeError: 'NoneType' object has no attribute 'GetLayer'
```

**Comment by sbma44** [comment]
@porjo Australia has announced that it'll be releasing a nationwide dataset in February that will supersede this one; I think we should consider `au-*` deprecated until that arrives.
