### ISSUE TITLE
Australia's G-NAF (national) file

### ISSUE THREAD

**Issue by wboykinm** [openaddresses/openaddresses#1470]
Per [this excellent news](https://blog.data.gov.au/news-media/blog/geocoded-national-address-data-be-made-openly-available), every address geocode in Australia will become available in pipe-delimited format come February 2016. In the meantime it might be worthwhile to spec the data using samples [available from resellers](http://web.pb.com/datasample-gnafaus/?utm_source=pbs&utm_medium=mapinfodotcom-data-catalog&utm_campaign=mapinfo-data-catalog&lead_source_details=Online%20Marketing) or [this data model document](https://www.psma.com.au/sites/default/files/g-naf_product_description.pdf) from the primary contractor.

@ingalls Does this supersede https://github.com/openaddresses/openaddresses/issues/132? 

Another thing to consider is the wording of the license (vague):

> The G-NAF and Administrative Boundaries datasets will be published under an open data licence at no cost to end users on data.gov.au in February 2016.

Anyone know anybody in the Commonwealth government they could ask about specific licensing?

**Comment by CloCkWeRX** [comment]
OpenStreetMap asked and received explicit permission - see wiki.openstreetmap.org/wiki/Attribution/data.gov.au_explicit_permission

Its likely to be licenced under CC-BY-3.0-AU or better, given AusGOAL (see https://wiki.creativecommons.org/wiki/Government_use_of_Creative_Commons#Australia  )

**Comment by CloCkWeRX** [comment]
> Does this supersede #132?
I think that multiple address sources simply add to the value. The specific sources listed in that ticket are likely more available at a different refresh rate; this is probably going to be updated quarterly. 

AFAIK There was discussion for "GNAF Live" incremental updates somewhere; but that's a lot of effort for small changes / probably wouldn't be opened up just yet.

GNAF is basically assembled from a giant ETL; and as houses get knocked down/new addresses made it can take some time to catch up - its fed from smaller government sources at the state/local level.

**Comment by wboykinm** [comment]
:+1:

**Comment by sbma44** [comment]
Checked in on this -- as of 2/22, they're still working on the release: https://blog.data.gov.au/news-media/blog/update-open-g-naf-and-administrative-boundaries-datasets

**Comment by maxious** [comment]
Checked in again today and it is now available! https://data.gov.au/dataset/geocoded-national-address-file-g-naf

**Comment by iandees** [comment]
This schema is pretty darn complicated. Does anyone have time to look through the docs and join the tables together into something we can more easily use?

**Comment by sbma44** [comment]
I'm going to try to block out some time today. @ingalls turned up this repo, which might provide some helpful guidance: https://github.com/minus34/gnaf-loader

**Comment by minus34** [comment]
iandees - what Maxious said :-)  [gnaf-loader](https://github.com/minus34/gnaf-loader) flattens the tables into a ready-to-use schema of 9 tables

**Comment by sbma44** [comment]
I haven't had a chance to dig in here beyond reading some docs, but would point folks toward Appendix A/page 33 of the documentation: https://www.scribd.com/doc/301507363/G-NAF-Product-Description

This table shows the joins necessary to produce a product compatible with other addressing standards. I think it's probably a good starting point for extracting the fields OA needs.

Unfortunately, I don't see a great way to process this using the normal conform process given the size of the data and the complexity of the joins. Unless someone else has a better idea I think periodically running `gnaf-loader` to produce a custom CSV may be the way to go. idk, @migurski do you have any thoughts about arbitrary bash in `machine`? :P

**Comment by tomhughes** [comment]
This probably doesn't matter for openaddresses but it should be noted that although the headline license is CC-BY-SA there are addition restrictions that mean it isn't technically open according to most definitions, namely:

* No use for generating addresses for the sending of mail unless you have verified them against a second source
* End users must only use the data in ways that are consistent with the Australian Privacy Principles issued under the Privacy Act 1988

The second one is clearly a "field of use" restriction that makes it technically non-open. I'm not sure how to categorise the first one...

**Comment by wboykinm** [comment]
@tomhughes The first one is a pretty standard "Do Not Call/Mail" list verification requirement - it's for vendors making contact regardless of data source, so the legal burden/liability is on that end user (the vendor). This _already_ applies to any use of openaddresses in the direct mail context where such national laws are in place.

**Comment by sbma44** [comment]
PR here: https://github.com/openaddresses/openaddresses/pull/1588

waiting on tests/fiddling with errors. `gnaf-loader` is excellent, made this easy. Alas, I don't see a way to fully automate the loading, but I've included the script necessary to create the CSV.

**Comment by slibby** [comment]
Closed via https://github.com/openaddresses/openaddresses/pull/1588
