### ISSUE TITLE
Isn't it a problem that HERE North America LLC holds a copyright over the zip code data in the New York statewide addresses

### ISSUE THREAD

**Issue by dthgeek** [openaddresses/openaddresses#1473]
The [source](http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=921) for us/ny/statewide states that "In the Address Points–SAM file, the ZipCode and ZipName attribute data is copyrighted by HERE North America LLC 2013 and licensed to the New York State Office of Information Technology Services. Please refer to the Metadata for more information." and the metadata for  Address Points - SAM - Statewide (http://gis.ny.gov/gisdata/metadata/SAM.address_points_SAM.xml) says "Use_Constraints: ZipCode/ZipName data copyrighted by HERE North America LLC © 2013 and licensed to the New York State Office of Information Technology Services". So doesn't that mean the address data can't be used by openaddresses.io?

**Comment by slibby** [comment]
On my reading that means that the ZipCode attribute should be removed from the scraping effort, but the address points themselves are not restricted.

**Comment by dthgeek** [comment]
Thank you for responding and sorry about the delay. 
Was the ZipeCode attribute from HERE removed and replaced using TIGER data? Also why is the rest of the data from New York Sate it unrestricted?

**Comment by iandees** [comment]
We removed the postcode from the output. Thanks for pointing this out.
