### ISSUE TITLE
Unit types in addition to unit numbers

### ISSUE THREAD

**Issue by stephenkhess** [openaddresses/openaddresses#1499]
With the inclusion of the `unit` field to conforms, is the expectation that unit types can be included when available?  For example, `/us/pa/lancaster.json` has the fields `UNITTYPE` and `UNITNUM`.  `UNITTYPE` has the possible values:

* UNIT
* APT
* LOT
* SUITE
* BLDG

Other sources combine type and number into a single field, so the data may already be "Apt 3" or "BLDG B".  It may be useful to convey to users what type of unit the address is.  Thoughts?

**Comment by stephenkhess** [comment]
Cleared this up with Ian Dees, closing.

**Comment by iandees** [comment]
For the record, the resolution here is that we do want to have unit type be part of the `unit` column, so when required concatenate the type and id fields if they're split apart.
