### ISSUE TITLE
Canada/New Brunswick doesn't have complete fields

### ISSUE THREAD

**Issue by riordan** [openaddresses/openaddresses#1507]
Bit of an epistemological question:

We have province-wide data for [New Brunswick](https://github.com/openaddresses/openaddresses/blob/7358ca0629bee0308d056f141d1adcc54b476abf/sources/ca/nb.json) (yay!), but it doesn't have things like the complete street name.

The field `STREET_NAM` is the name of the street, but doesn't have the type. Meanwhile the fields like `ST_TYPE_CD` and `STREET_DIR` necessary for constructing that full address, are numeric values from other tables (foreign keys). These keys are available in the CSV variant of the same file, but broken apart into several different CSVs.

What do we do?

**Comment by iandees** [comment]
Step 1: Bash them over the head with their normalization. :smile: 
Step 2: Download the files and do some work on your own machine to build the CSV as you want it.
Step 3: Add code or description for how you made the file to https://github.com/openaddresses/openaddresses/tree/master/scripts
Step 4: Send me the CSV/Shapefile/etc. and we can get it hosted on S3 (or you can create a separate Github repo to hold it?)

**Comment by slibby** [comment]
`d_ST_TYPE_` works for street name (type) in the interim, but you're right that street_dir is not sufficient in the SHP

**Comment by ingalls** [comment]
@iandees @slibby @riordan Being a native New Brunswicker I know several people that work at Service NB (The agency that produces the file). Before we go the route of custom scripts I'm going to send a quick note pointing to this ticket and see what their thoughts are.

Service NB has been absolutely incredible in the past at working with me at improving/taking suggestions about their data offerings.

**Comment by slibby** [comment]
sounds good :+1: plus really happy to know the term `New Brunswicker` now

**Comment by berniejconnors** [comment]
@iandees is correct.  You really need to download the CSV files and use all of the code tables to de-normalize the data to get a complete street address.

In the Street_types code table there is a "DISPLAY_BEFORE" column that indicates if the street type should be displayed before the street name (1) or after the street name (2).
![street_types](https://cloud.githubusercontent.com/assets/13241302/12851719/c37fe2fc-cc01-11e5-88ca-595ea09c43f8.JPG)

@slibby - I'm not sure what you mean that street_dir is not sufficient in the SHP.  In New Brunswick street_dir is used rarely, Only 0.9% of records.

@ingalls - Thanks for reaching out-  I am always happy to help but I don't monitor conversations at openaddress.

**Comment by ingalls** [comment]
@berniejconnors thanks for weighing in here! Do you mind asking to have this data included in the shapefile? I think it would make our job (and likely other data consumers) much easier when it comes to processing the data.

**Comment by trescube** [comment]
Has anyone heard back about this?  If not, I'll cobble together the data from the CSV sources.

**Comment by berniejconnors** [comment]
I'll follow-up with a co-worker on the status of the script we use to package the address data for download.

**Comment by ingalls** [comment]
@berniejconnors thanks a ton!

**Comment by ingalls** [comment]
This was fixed ages ago thanks to @berniejconnors
