### ISSUE TITLE
Support Constants for County/State/Region/Etc.

### ISSUE THREAD

**Issue by slibby** [openaddresses/openaddresses#1515]
It would be good if we could support adding a value in the `conform` that lets you specify a static City, State, Region, etc, when one is not available in the source. Especially for City data, they generally include number, name, even postcode, but rarely include City Name or State Name or County. 

What if in a `conform`, if any value is "_abcdef_" or "_abcdef_" or "CONSTANT:abcdef" -- then that value gets applied to every row? I think this would improve the completeness of many datasets, though it also involves a lot of re-work on existing sources. Would apply to many of the county datasets too.

**Comment by migurski** [comment]
Could be an [attribute function](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#attribute-functions), perhaps? 

```
"state": {"function": "constant", "value": "TX"}
```
