### ISSUE TITLE
Add address data from the City of Vienna

### ISSUE THREAD

**Issue by blutz3** [openaddresses/openaddresses#1517]
Hello,

the addresses of the City of Vienna are available as Open Data as csv-file, here you find the metadata: https://www.data.gv.at/katalog/dataset/1d5c2411-9719-4c8f-b99d-57a5f4a4ae41 and here the file: http://www.wien.gv.at/wohnen/baupolizei/csv/gebadr.csv 

The licence is CC BY 3.0 AT 

Please could you add the addresses to openaddresses.io.

Kind regards from Vienna
Brigitte Lutz

Ing. Brigitte Lutz, MSc
City of Vienna - Chief Executive Office
Executive Group for Organisation, Safety and Security
Process Managament & Information and Communication Technology

Rathausstraße 8
A-1010 Vienna
Telephone +43 1 4000 75023
Fax  +43 1 4000 99 75023
E-Mail: brigitte.lutz@wien.gv.at  
www: www.wien.gv.at
www: open wien.gv.at
twitter:@BrigitteLutz

**Comment by slibby** [comment]
Is there information about what projection the address coordinates are in? And which field is correct to use?

![image](https://cloud.githubusercontent.com/assets/1691225/12238685/86fa46b0-b842-11e5-840a-899d0cf0cc1d.png)

**Comment by tyrasd** [comment]
I'd assume that `GEB_X/Y` stands for the building (*Gebäude*) while `ZUG_X/Y` would be the entrance (*Zugang*). Coordinate system is very likely `EPSG:31256`. The top-right coordinate of the screenshot would then be at http://osm.org/go/0JrJCtk1W?m= which looks reasonable.

**Comment by slibby** [comment]
Closed by https://github.com/openaddresses/openaddresses/issues/1521
