### ISSUE TITLE
us/tn/shelby 

### ISSUE THREAD

**Issue by slibby** [openaddresses/openaddresses#1527]
Shelby County Data: https://services6.arcgis.com/FStub7HlCSCdqoXK/arcgis/rest/services/OpenData/FeatureServer/0

website: http://opendata.arcgis.com/datasets/1a8c342a997f4be09fa1c67d9f700ee0_0

**Comment by slibby** [comment]
Service changed or security changed - not currently available.

**Comment by trescube** [comment]
Found the data at http://opendata.arcgis.com/datasets/ab59956e886f403e8f427c2d675af4c3_0/data
