### ISSUE TITLE
Allegheny county, PA

### ISSUE THREAD

**Issue by iandees** [openaddresses/openaddresses#1537]
We already have a shapefile source, but here's an ESRI source to use (that might be more up to date):

http://geodata.alleghenycounty.us/arcgis/rest/services/OPENDATA/Addresses/MapServer/0

**Comment by trescube** [comment]
Can this be closed since it was fixed in https://github.com/openaddresses/openaddresses/commit/f800c4533b0281fa73a6a97cf73a7866564aa45a ?
