### ISSUE TITLE
Mixup in column values for various western US states

### ISSUE THREAD

**Issue by eruci** [openaddresses/openaddresses#1551]
eg, yuma.csv in Arizona
LON,LAT,NUMBER,STREET,UNIT,CITY,DISTRICT,REGION,POSTCODE,ID
-114.4425414,32.6561177,11189,East 39th Lane,,YUMA,,,,
-114.4194517,32.6810469,10302,South Del Rey Drive,,YUMA,,,,

STREET=11189
UNIT=East 39th Lane

Same problem on many csv files in California, Oregon, Washington

**Comment by migurski** [comment]
The UNIT column was added fairly recently, so you’re probably looking at a run that was generated some time ago.

**Comment by eruci** [comment]
Yep. I closed the issue soon after noticing that.
