### ISSUE TITLE
Possible source of UK open address data

### ISSUE THREAD

**Issue by wknowles** [openaddresses/openaddresses#1554]
A possible source of data for the UK could be [Open Addresses UK](https://alpha.openaddressesuk.org/). There is a [data download page](https://alpha.openaddressesuk.org/developers/apis-and-data) along with an API (in alpha). 

Coverage appears to be of the entire  UK.

The project is now on hibernation and is possibly incomplete but might be useful.

I have checked previous issues and can see no mention of this, but apologies if duplicated.

**Comment by iandees** [comment]
Thanks for the pointer. Last I checked, the OpenAddresses UK project doesn't associate any geographic coordinates with the collected addresses, so it won't be very useful for this project.

**Comment by wknowles** [comment]
D'oh! Sorry about that!
