### ISSUE TITLE
chicago southland

### ISSUE THREAD

**Issue by ansis** [openaddresses/openaddresses#156]
https://data.illinois.gov/Municipality/SSMMA-Addresses/96g3-9rcf

This might already be covered

**Comment by geobrando** [comment]
Data are coincident with existing data from [Chicago](https://github.com/openaddresses/openaddresses/blob/ea93bbc2b758008b83308621fd1a84e446505d66/sources/us/il/city_of_chicago.json) and [Cook County](https://github.com/openaddresses/openaddresses/blob/ea93bbc2b758008b83308621fd1a84e446505d66/sources/us/il/cook.json). Might be worth adding, but only avaiable as a csv with spatial reference system that doesn't have an EPSG code so [Machine](https://github.com/openaddresses/machine) is currently not able to process it.
