### ISSUE TITLE
Support for several language versions of addresses

### ISSUE THREAD

**Issue by vesameskanen** [openaddresses/openaddresses#1573]
Are there any plans for how to handle different language versions of addresses in an optimal way? Currently I could not find any recommendations or guidelines about this.  I noticed that  sometimes the same data has been linked with multiple conform objects (‘be/wa/brussels-fr’ and ‘be/wa/brussels-nl’).

From the application perspective, it would be best if language versions are somehow bind together. In other words, a single multi-language address is better than several copies of the same address in multiple languages. For example, a geocoding application can then return a single matched address in the preferred language instead of several translations of the same address (‘Albert’ matches both Albertinkatu and Albertsgatan in Helsinki, Finland).

All feedback and thoughts on this topic would be greatly appreciated.

**Comment by migurski** [comment]
Hi @vesameskanen, great question. Our output format is designed to be fairly simple, but we do include an `ID` column that can be used to indicate identical points. In the Belgium example, matching IDs would show how the address points correspond between data sets.

**Comment by vesameskanen** [comment]
Hello @migurski - thanks for the quick reply. ID matching indeed seems to provide a way to combine addresses. Anyway, it seems to me that a new official processing tag (or maybe  an attribute tag for multi-language files), which specifies the ISO 639-1 language code, would be very useful here. That would allow systematic handling of languages; properties of addresses with an identical id could then simply be mapped as 'street.fr', 'street.en' using the language code. What do you think about this idea?

**Comment by migurski** [comment]
That’s a great point about language code. What other examples exist for this? Cyprus, I imagine?

**Comment by vesameskanen** [comment]
https://en.wikipedia.org/wiki/List_of_multilingual_countries_and_regions

**Comment by vesameskanen** [comment]
Hi again @migurski - can we somehow contribute in this issue?  It seems to me that all that is required is one new **optional ** tag in conform object, 'language' stating the ISO 639-1 code. This extension would be fully backward compatible, and seems to provide quite standard universal information about the data content. I cannot see any disadvantages.

I guess this is purely a documentation issue; I can edit the CONTRIBUTING.md and make a pull request if that helps. Just let me know if you find this appropriate.

**Comment by migurski** [comment]
Yes, a pull request would be appropriate, thanks. Where do you think the value should end up, though? In the output CSV?

**Comment by vesameskanen** [comment]
I reconsidered what's the best place, and maybe the tag belongs to the coverage object. In other words, the value would be present in the metadata only. This approach seems to fit some existing data sources nicely (e.g. Helsinki and Brussels).  A pull request is already under work here.

**Comment by vesameskanen** [comment]
This issue is addressed by https://github.com/openaddresses/openaddresses/pull/1613
