### ISSUE TITLE
New users cannot sign in with github

### ISSUE THREAD

**Issue by jidanni** [openaddresses/openaddresses#1575]
New users cannot "sign in with github". One is simply redirected to what URI-decodes as:

http://openaddresses.io/login/index.html#error=invalid_credentials&error_message=Redirect URL "http://openaddresses.io/login/index.html" must match "http://openaddresses.io/contribute.html". Register your app credentials by visiting https//auth-server.herokuapp.com&state={"client_id":"4b8d48289d4d2d36833d","network":"github","display":"popup","callback":"_hellojs_mllrkfx","state":"","redirect_uri":"http://openaddresses.io/login/index.html","scope":"basic","oauth":{"version":2,"auth":"https://github.com/login/oauth/authorize","grant":"https://github.com/login/oauth/access_token","response_type":"code"},"oauth_proxy":"https://auth-server.herokuapp.com/proxy"}

**Comment by migurski** [comment]
Hello @jidanni, I'm sorry you are experiencing this error! Can I help you accomplish your goal in some other way? The login system that you're experiencing an error with is something we've been moving away from in favor of direct Github interactions, and the problem you're seeing is a great nudge for us to completely switch away.

**Comment by jidanni** [comment]
Well imagine if nobody could login to Facebook.
I'd say fix this first lest people doubt your site is "for real".

**Comment by migurski** [comment]
We’ve gone ahead and removed the login feature for now, as of https://github.com/openaddresses/openaddresses.io/pull/63. The _Submit a Dataset_ button now links to the contribution guide which will do for the time being, but we will need to improve that ASAP (https://github.com/openaddresses/openaddresses.io/issues/64).
