### ISSUE TITLE
"Download the collection .csv" link wording scary

### ISSUE THREAD

**Issue by jidanni** [openaddresses/openaddresses#1576]
On https://openaddresses.io/ one sees the button "Download the collection .csv" which in my mind means "Click this button to start downloading a .CSV file containing perhaps all the addresses in the world right to your browser!"

So users fear clicking it lest one giant file come sloshing down the line.

So please reword it.

**Comment by migurski** [comment]
Do you have a suggestion? What you describe is pretty much what happens.

**Comment by iandees** [comment]
In https://github.com/openaddresses/openaddresses.io/pull/63 I changed the button text to `View download options` because the link takes you to results.openaddresses.io, not to a CSV download directly.

**Comment by migurski** [comment]
@jidanni, is that a sufficient change? Looks like:

<img width="969" alt="screen shot 2016-02-28 at 9 12 27 am" src="https://cloud.githubusercontent.com/assets/58730/13380557/65783c52-ddfb-11e5-83cc-33b4a6a0eb53.png">

**Comment by jidanni** [comment]
Yes!

**Comment by migurski** [comment]
Great, thanks for your suggestions Dan!
