### ISSUE TITLE
Mention if individual users are welcome to submit their individual addresses

### ISSUE THREAD

**Issue by jidanni** [openaddresses/openaddresses#1577]
On
https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md
please answer the new FAQ: "I am just a simple person who wants to put my house into this openaddresses thing. Here's my address and my coordinates. Where is the online form where I can type them in and hit Submit. I can't even tell if you accept entries from the little guy with just his own address."

**Comment by migurski** [comment]
We don’t actually accept such entries! Your best bet for a single address is OpenStreetMap. OA’s project focus is on authoritative (typically government) sources. We’re thinking about what it might look like to accept corrections, and how our upstream sources might want to hear about those.

**Comment by iandees** [comment]
Some context on this request: OpenAddressesUK had/has a form on their page that accepted addresses and addresses and locations from users. Because of the name similarity there might be some overlap there.

**Comment by iandees** [comment]
(I don't know if that's the case with @jidanni here. I don't mean to put words in your mouth!)

**Comment by jidanni** [comment]
All I am saying is "Mention if individual users are welcome to submit their individual addresses",
best right there on https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md
which is where users land after clicking the link below "Help contribute. Grow OpenAddresses by contributing data from any place in the world." on the Homepage.

Just mention what you mention above in this bug report, but put it there on CONTRIBUTING.md, so new users will know within seconds of clicking around the site, Thanks.

**Comment by jidanni** [comment]
I.e. the answer is "No". Make sure they can find this answer easily. And yes, tell why like you do above too.

**Comment by migurski** [comment]
Thanks Dan!
