### ISSUE TITLE
Add Australia

### ISSUE THREAD

**Issue by lxbarth** [openaddresses/openaddresses#1608]
http://www.theregister.co.uk/2016/03/02/every_australian_address_yes_yours_and_even_yours_just_became_open_data/

**Comment by lxbarth** [comment]
Late to the party! 

https://github.com/openaddresses/openaddresses/pull/1588

**Comment by migurski** [comment]
It’s already available at http://results.openaddresses.io !

**Comment by lxbarth** [comment]
Nice! Kinda assumed full aus coverage?

**Comment by lxbarth** [comment]
![screen shot 2016-03-12 at 3 11 53 pm](https://cloud.githubusercontent.com/assets/98233/13725030/c86b89e0-e864-11e5-8315-6f59f55ee991.png)

**Comment by migurski** [comment]
Yes, we believe so. Zip collections + rendered maps catch up in time.

**Comment by lxbarth** [comment]
Got it! So cool.
