### ISSUE TITLE
us-fl-brevard

### ISSUE THREAD

**Issue by b-may** [openaddresses/openaddresses#1617]
Property Appraiser changed their website and no longer provides address.zip for download at new data download location of: https://www.bcpao.us/PublicData.aspx

Will contact them and respond with their response.

**Comment by b-may** [comment]
I called the Property Appraiser office and they said they no longer distribute the data. You have to get it from the source which is the county E911 / Address Assignment department. I emailed the GIS contact there and waiting on response.

**Comment by trescube** [comment]
Have you heard back yet?

**Comment by b-may** [comment]
No, just sent another request. If they don't respond in a couple days, I'll dig further.

**Comment by trescube** [comment]
Still nothing?

**Comment by b-may** [comment]
Found a phone number, called and left a message. The county GIS has a new ArcGIS Server online as well but didn't see the address points.

`http://gis.brevardcounty.us/gissrv/rest/services`

**Comment by trescube** [comment]
At least it has parcels, which is better than the current situation where the zip file is no longer hosted.  I'll get the source switched to ArcGIS parcels.

**Comment by b-may** [comment]
Finally got a copy of the address points. It was provided by dropbox link, so I put a copy here `https://www.mapwise.com/data/brevard_updateadd1.zip`

For future reference, the contact is:

Tim Witt
E911 GIS Analyst
Brevard County (FL) E9-1-1 Administration
TEL: (321) 690-6846

According to the county public records request instructions, you can make an anonymous request for the data by phone to the person who maintains the data. You should not have to fill out a form, contact the Coordinator, etc. No charge for the data. 

> Brevard County Board of County Commissioners Public Records Requests
Welcome to the Brevard County Board of County Commissioners Public Records Request page. Under Florida law, you are not required to submit a public records request in writing or identify yourself. You may make a verbal request for public records by calling the Public Records Request Coordinator at (321) 633-2071, or by emailing your request to Brittany.Ray@brevardcounty.us. **To make an anonymous public records request, please call or visit the County department from which you wish to request records**, during normal hours of business, so arrangements can be made to pick up records and pay any fees due.

**Comment by trescube** [comment]
Excellent, thanks!  I'll get a source for it shortly.
