### ISSUE TITLE
Saskatoon

### ISSUE THREAD

**Issue by ansis** [openaddresses/openaddresses#162]
http://opendata-saskatoon.cloudapp.net/DataBrowser/SaskatoonOpenDataCatalogueBeta/ParcelAddress#param=NOFILTER--DataView--Results

The csv download looks like it is broken/missing coordinates, but the kml version has them.

license: http://www.saskatoon.ca/DEPARTMENTS/Corporate%20Services/Corporate%20Information%20Services/OpenData/Pages/TermsofService.aspx

**Comment by slibby** [comment]
I downloaded the KML, converted it and added it back to dropbox: https://www.dropbox.com/s/vvk3u7o58r5b5bo/Saskatoon_Parcel_Addresses.zip?dl=1

**Comment by justinelliotmeyers** [comment]
currently pulling from their open data portal: http://results.openaddresses.io/sources/ca/sk/saskatoon
