### ISSUE TITLE
us-fl proposal to replace loveland data with mapwise data

### ISSUE THREAD

**Issue by b-may** [openaddresses/openaddresses#1633]
I realize this isn't a Pelias issues forum, but... I am proposing to replace the loveland version of Florida address data with data from MapWise. 

I've implemented Pelias address search into our web-based mapping app and have been researching geocoding problems. Our app just covers Florida, so I'm focusing exclusively on Florida. Two of the biggest problems traces back to the loveland address data. 

1) The loveland data does not include zip codes. This seriously confuses the geocoder when a zip code is included in an address search. Basically, zip codes cannot be used at all for searching, and that really confuses people!

2) The loveland data covers all of Florida, except Miami-Dade. The Pelias data importer is using the loveland data first, and ignoring the many counties of address point data available.

I have statewide parcel data sourced from Florida Department of Revenue (FDOR) and many counties. I've created a new Florida address file that includes zip codes, pin numbers and address types (single family residential, commercial, etc). In addition, unit numbers are separated out for several counties.

This version does not include counties where address point data is included in OA. The reasoning is the data would be redundant and the parcel centroid version of address data is not as accurate and complete as the address points data produced by counties.

There's a few counties with address point data "on-deck" to be added to OA, and I plan to update this version to remove those as they come on line in OA.

Another difference between the two data sets is this only includes parcel centroids that have an address number. I figured OA prefers actual addresses, but I can include all parcel centroids if that is preferred.

The data is available here: https://www.mapwise.com/data/florida_mapwise.zip

Thanks for your consideration.

**Comment by iandees** [comment]
Where did the mapwise data come from? What's its license?

**Comment by ingalls** [comment]
Just my 2c, I've always been an advocate of multiple overlapping sources. Unless the sources are identical I see no issues in having both. (Provided the mapwise license is acceptable as @iandees points out)

**Comment by b-may** [comment]
MapWise is my company. License is public domain. Some of the counties are sourced from FDOR and some directly from counties. Most GIS data in Florida public domain, unless explicitly exempted by FL Statutes - parcel data is not exempted. 

The loveland version is all FDOR. Each county is required to send their data to FDOR each year in a standardized format. The FDOR format provides the house number, name and unit in one field (number + predir + name + type + sdir + unit). The county versions usually break that out, so its easy and less error prone to provide number and unit as a separate field. The original data source is always going to lead back to the county property appraiser - just different ways of presenting the data to OA.

The problem I am trying to solve with my version is adding additional fields like zip codes so its useful to Pelias, but it should be useful to others as well. 

I'm also not providing overlap with counties that have point addresses in OA already, because from what I've seen so far, point addresses are the best source for addresses. For example, a retail shopping plaza will usually be just one or a few polygons with their own site address, but there may be 30 addresses in the plaza that are represented in the point address version provided by the county. One data set is meant for taxing real property and the other is meant for locating all entities with an address.

**Comment by iandees** [comment]
I appreciate your company releasing this data, and especially your interest in having it appear here.

When MapWise pulled this data together, how did you collect it? Did you reach out to individual counties and request data manually? I'm interested in trying to get as close to the source of the data as  possible. In addition to the MapWise dataset that you're offering, I would also like to see us (OpenAddresses) have some way of automatically pulling in data directly from the Florida counties themselves.

**Comment by b-may** [comment]
Glad to help out. I'm on the open source software and data bandwagon. I'm also a heavy contributor to OSM in Florida.

One of the main things we provide to our customers is access to standardized parcel data updated on a regular basis. Owner and sales info is updated monthly when we can. So, the first option is always finding the appraisers and counties that provide free downloads of the parcel shapefiles and/or taxroll data. We only pay for data when absolutely necessary and not too expensive. I'm really cheap. I'm not going to pay $150 for data for a county with 15,000 people in it. But I will pay $70 for Broward County with 1.5 million people. 

Some counties let you pay online and others you have to fill out their paper request form and mail it in with a check. All of the counties I have to pay for deliver via dropbox, etc or deliver to my ftp site. 

So, for the smaller counties that charge more than I'm willing to pay, we turn to using FDOR data, which is free and downloadable. In many cases, the smallest counties are charging the most money. Seen this issue in Georgia, too.

If you are interested in the FDOR version of data its here: ftp://sdrftp03.dor.state.fl.us/
You will find parcel shapefiles for each county with pin. And taxroll files for each county in CSV format with 150+ fields, including site address, site city and zip code.

For the point addresses, I've found a few additions to add to OA that are downloadable that I created Issues for. I can do some outreach to larger counties to try to find more data and see if they are willing to make it available for download. 

As you've probably seen, usually governments are either providing downloads or not, and its a big hairy deal to start providing downloads with regularly updated data. But governments in general do seem to become more open with data as time goes by. Some of the smaller ones who can't afford to deal with hosting data may be open to the idea of posting their data somewhere for free to an open data portal like OA. Of course then there's the esri "open data" stuff - governments are in love with esri. I could go on...

**Comment by b-may** [comment]
Is there anything I can do to help with the process of getting this data accepted to OA? I'm fine if you don't want to replace the loveland data. I'm very curious to see if this data will improve Pelias geocoding results in Florida since this version has zip codes and doesn't overlap with counties where there is already point address data in OA.

**Comment by sbma44** [comment]
@b-may the most helpful thing to nudge this along would be a pull request. Let me know if that's a possibility or if there's a way I can help.
