### ISSUE TITLE
New Hampshire

### ISSUE THREAD

**Issue by ingalls** [openaddresses/openaddresses#164]
http://www.granit.sr.unh.edu/data/downloadfreedata/downloaddata.html
granit@unh.edu 
(603) 862-1792

**Comment by ingalls** [comment]
Stale - no response. Someone else is welcome to take this on.

**Comment by slibby** [comment]
Re-contacted 8/24/15

**Comment by slibby** [comment]
No response - seems like we need to find someone at UNH with some connections there.

**Comment by slibby** [comment]
Found a statewide layer and added it - this can be closed.
