### ISSUE TITLE
us-tn data

### ISSUE THREAD

**Issue by tmcdon89** [openaddresses/openaddresses#1700]
I'm new to the project so I'm not entirely sure this is how to approach the subject but there isn't very much information available in us-tn

The following sites have a wide variety of maps and information available that may be useful for acquiring us-tn info. I'm guessing these would be related to Raster-based as they are not downloadable.
http://tnmap.maps.arcgis.com/home/
http://tnmap.tn.gov/assessment/

**Comment by ingalls** [comment]
Hey this looks promising. Give me a little bit to see if I can find a way to get at the raw data.

**Comment by iandees** [comment]
I *think* the last time I looked at TNMap they didn't have any addresses. Definitely worth looking at again.

**Comment by ingalls** [comment]
@iandees They definitely have addresses, but they also are the first government agency who actually knows how to configure an ESRI server.

**Comment by ingalls** [comment]
`Address:	MAIN ST 335` bit of a strange format though!

**Comment by iandees** [comment]
Yea, I think what I ran into was that even after finding their token granting endpoint the layer wasn't statewide at all and the formatting was very odd. It looks like coverage has improved a bit, but the address seems to be pretty wacky still.

**Comment by tmcdon89** [comment]
I noticed the addresses were in a strange format, but I also have pretty much zero experience with GIS data so I didn't know if that was an issue or not.

**Comment by iandees** [comment]
Sometimes when they have a GeocodeServer the description gives some more information about what to look for. In this case, the [GeocodeServer](http://tnmap.tn.gov/arcgis/rest/services/LOCATORS/COMPLETE/GeocodeServer) points to something called [TIPS](https://www.tn.gov/finance/article/tips). I wonder if we can ask them for the data in a more convenient format.

**Comment by iandees** [comment]
Check out [this sweet PDF](https://www.tn.gov/assets/entities/finance/oir/attachments/TIPS_Modeling_Specifications.pdf) that talks about addressing standards in TIPS. Lots of good diagrams there.

**Comment by tmcdon89** [comment]
Not sure if this helps, but I know they keep some info (like city boundaries) in a downloadable format at: http://tn.tnmap.opendata.arcgis.com/

**Comment by ingalls** [comment]
@iandees managed to get a very hacky script together that is going to grab it all. This will definitely be something we need to cache I'm afraid.

**Comment by aaronpdennis** [comment]
It looks like TIPS is a conglomerate of TN counties that are managing their own address points. [This layer seems to be tracking TIPS coverage](http://tnmap.tn.gov/arcgis/rest/services/TRANSPORTATION/TIPS_ECD_TRACKING/MapServer/0). The attribute table has columns that seem to be email addresses and contacts for each TN county, probably for a GIS manager.

[TIPS-coverage.xlsx](https://github.com/openaddresses/openaddresses/files/285091/TIPS-coverage.xlsx)

**Comment by ingalls** [comment]
More of: http://geojson.io/#id=gist:anonymous/38caff9eeb62ea430c62df645a6c3d12&map=18/35.03232/-89.61323 to come

**Comment by tmcdon89** [comment]
Exciting to see it come to fruition so quickly.

**Comment by ingalls** [comment]
Closing for now in favour of #1702
