### ISSUE TITLE
au-countrywide quarterly update needs reprocessing

### ISSUE THREAD

**Issue by andrewharvey** [openaddresses/openaddresses#1701]
As per https://github.com/openaddresses/openaddresses/blob/master/sources/au/countrywide.json the source must be regenerated now that there is a May release of http://data.gov.au/dataset/geocoded-national-address-file-g-naf

`http://s3.amazonaws.com/data.openaddresses.io/cache/au.zip` still shows `Last-Modified: Sat, 05 Mar 2016`

**Comment by ingalls** [comment]
cc/ @sbma44 did you have a script you used for this?

**Comment by andrewharvey** [comment]
@ingalls I believe [this is the script](https://github.com/openaddresses/openaddresses/blob/master/scripts/au/gnaf.sh). I've made [pull request](https://github.com/openaddresses/openaddresses/pull/1703) which makes some changes to this script for the May16 release and some other fixes.

I've run the updated script which produced the [updated au.zip file](https://www.alantgeo.com.au/share/au.zip).

**Comment by simonpoole** [comment]
While on this topic, I note that 
* OA claims that the data does not require attribution (it is licenced under a modified CC-by 4.0 licence)
* OA claims that it is freely shareable data, which it however, due to the above mentioned modification, isn't
In summary I'm not quite sure what this dataset is doing in OA except to one up other players.

**Comment by iandees** [comment]
@simonpoole that would be a great topic for a different ticket.

**Comment by andrewharvey** [comment]
>OA claims that the data does not require attribution (it is licenced under a modified CC-by 4.0 licence that clearly requires attribution)

Within https://github.com/openaddresses/openaddresses/blob/master/sources/au/countrywide.json license.attribution is true, where does OA claim it doesn't require attribution?

>OA claims that it is freely shareable data, which it however, due to the above mentioned modification, isn't.

The license.url contains the CC BY 4.0 license modified with a restriction on use for sending physical mail. The license doesn't prevent people sharing and using the data for other purposes does it?

**Comment by simonpoole** [comment]
From licence.txt in the OQ -zip archive:

au/countrywide
Website: http://data.gov.au/dataset/geocoded-national-address-file-g-naf
License: https://data.gov.au/dataset/geocoded-national-address-file-g-naf/resource/09f74802-08b1-4214-a6ea-3591b2753d30
Required attribution: None

The modification to CC 4.0 needs to be passed on downstream.

**Comment by migurski** [comment]
I think it needs an Attrubution Name set in the source to know what to include in that file; probably not the best choice to let it stringify Python's None there. I'll fix it in the machine code.

**Comment by andrewharvey** [comment]
It appears the May16 update has been processed in https://github.com/openaddresses/openaddresses/commit/aa225e648223eb5c7784f794c55ebb9bdba77cb8

**Comment by ingalls** [comment]
👍 Thanks a ton for staying on top of this @andrewharvey! If we miss processing the next update give us another poke and we'll be sure to update it! With the new Docket setup that @migurski worked on it should make this a breeze.

**Comment by andrewharvey** [comment]
@ingalls Looks like it needs updating again for the August release

**Comment by migurski** [comment]
Thanks @andrewharvey, it took no time at all since they’re keeping the data formats consistent.

**Comment by andrewharvey** [comment]
@migurski Just a ping that the GNAF Nov 16 update has been released and OA will need another update like https://github.com/openaddresses/openaddresses/pull/1915

**Comment by migurski** [comment]
Thanks @andrewharvey! Opened up #2157.

**Comment by andrewharvey** [comment]
@migurski GNAF Feb 17 is out http://data.gov.au/dataset/geocoded-national-address-file-g-naf/resource/99b44dff-4e84-4cb7-9cbf-a68d3ebf964a. Will need another update like #2157. Thanks!

**Comment by migurski** [comment]
Thanks Andrew!

**Comment by andrewharvey** [comment]
@migurski May17 update is out!

https://data.gov.au/dataset/geocoded-national-address-file-g-naf/resource/99b44dff-4e84-4cb7-9cbf-a68d3ebf964a

**Comment by migurski** [comment]
Thank you, Andrew!
