### ISSUE TITLE
us-ga-wilcox not correct

### ISSUE THREAD

**Issue by charlesminshew** [openaddresses/openaddresses#1705]
The Wilcox County, Georgia file is actually Bacon County, Georgia.

**Comment by trescube** [comment]
This appears to be true as there are no differences between `http://data.openaddresses.io/cache/us-ga-bacon_county.csv` and `http://data.openaddresses.io/cache/us-ga-wilcox_county.csv`.  Wilcox County, GA looks like it's behind a paywall.
