### ISSUE TITLE
Jamaica

### ISSUE THREAD

**Issue by milovanderlinden** [openaddresses/openaddresses#1707]
I will be mapping addresses in Jamaica two 2 weeks from now. We will be using OSM to store the data. I would like to know if there are any steps I need to take to make sure that it will later be possible to export the Jamaica dataset to openaddresses without infringing the license. Of course me and the team of local mappers will be the copyright owners and we would like to grant openaddresses the right to create a dataset for Jamaica.

Any advice?

Kind regards,

Milo

**Comment by sbma44** [comment]
Milo, I don't think there should be any issue as long as you can be certain that the data you export from OSM will only include information that you have a right to relicense.

Incidentally, thanks for thinking of OpenAddresses! I'm very excited to have data from Jamaica in the project.

**Comment by milovanderlinden** [comment]
Hello Tom,

Thank you for the response. As I will be operating with
http://caribbeanopeninstitute.org/, I will ask the mappers to add a tag to
all addresses they create called address:source=caribbean_cc0 which should
grant us with the possibility to also distribute the addresses to
openaddresses.io. It is kind of ironic, I have a banner on my openstreetmap
page stating that all my additions are public domain; and now I have to
make sure that I do not get "locked-in" by the OpenStreetMap license ;-)

2016-06-02 0:19 GMT+02:00 Tom Lee <notifications@github.com>:

> Milo, I don't think there should be any issue as long as you can be
> certain that the data you export from OSM will only include information
> that you have a right to relicense.
>
> Incidentally, thanks for thinking of OpenAddresses! I'm very excited to
> have data from Jamaica in the project.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openaddresses/openaddresses/issues/1707#issuecomment-223142301>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAGeNueGJYVz0YUKfAGpg2iXWfETWG4Mks5qHgVkgaJpZM4Ir6cp>
> .
>



-- 
[image: http://www.dogodigi.net] <http://www.dogodigi.net>
*Milo van der Linden*
web: dogodigi <http://www.dogodigi.net>
tel: +31-6-16598808

**Comment by migurski** [comment]
The US National Park Service has a similar dual-license process, and I think it’s a great adaptation to the OSM community’s decision to use a share-alike license. If possible, can you use one of the OSM filtering services to get this data out of OSM before it’s modified by anyone? I assume you’re using mapping tools that will be directly writing to the OSM database?

**Comment by slibby** [comment]
Hi @milovanderlinden just checking in to see: how did the address mapping project go in Jamaica? It would be great to see some addresses there, I have looked in the past and there's not much out there!

**Comment by justinelliotmeyers** [comment]
closing as per http://results.openaddresses.io/sources/jm/countrywide
