### ISSUE TITLE
Charleston SC

### ISSUE THREAD

**Issue by dmfenton** [openaddresses/openaddresses#1708]
Leaving this here so I can grab it later or so someone else can add

http://data.charleston-sc.opendata.arcgis.com/datasets/771aa25be25d4141a8ec6d74bdc1be8f_0
http://gis.charleston-sc.gov/arcgis/rest/services/External/OData_Central/MapServer/0

**Comment by slibby** [comment]
https://github.com/openaddresses/openaddresses/pull/1732
