### ISSUE TITLE
Iceland

### ISSUE THREAD

**Issue by ingalls** [openaddresses/openaddresses#171]
http://www.lmi.is/en/stafraen-gogn/

**Comment by sbma44** [comment]
@kelvinabrokwa got referred to this by @DKAdresser on Twitter -- it had slipped off the radar. Mind hunting this down?

**Comment by kelvinabrokwa** [comment]
I'm on it!

**Comment by slibby** [comment]
This dataset has been added and I believe the can be closed: https://github.com/openaddresses/openaddresses/blob/master/sources/is/countrywide.json
