### ISSUE TITLE
Itasca County, Minnesota

### ISSUE THREAD

**Issue by turtles2** [openaddresses/openaddresses#1718]
You can get parcels from [here](https://gisdata.mn.gov/dataset/us-mn-co-itasca-plan-parcels) if need be can I reach out and try for address data. But from my understanding address data can be extracted from this? 

[shp_plan_parcels.zip](https://github.com/openaddresses/openaddresses/files/310471/shp_plan_parcels.zip)

**Comment by slibby** [comment]
It looks like this layer contains Owner Addresses but not Parcel Address, so it won't work for contribution here (yet). If you wouldn't mind reaching out, either a postal address layer or a parcel layer with the parcel addresses themselves (not PIN + Owner Address) would be sufficient.

**Comment by turtles2** [comment]
Are you sure? As there is line ADDR_10001 that has Physical Address of the Parcel then TAX_DIST_NAME that has Name of Township or Municipality. But if these can't work I will reach out.

**Comment by trescube** [comment]
`ADDR_10001` looks pretty legit as the parcel address.  I see quite a few that have different values from the `ADDR1`/`ADDR2` fields (with some `ADDR2`'s in different states), though I don't 100% trust the `TAX_DIST_NAME` field for city as it doesn't match up reliably with google maps.  I'll get a source together.
