### ISSUE TITLE
ca-on-peel

### ISSUE THREAD

**Issue by kevin-peel** [openaddresses/openaddresses#1740]
Region of Peel has posted address points in CSV and Shapefile format at this location: http://opendata.peelregion.ca/data-categories/regional-geography/address-points.aspx

Covers the cities of Mississauga and Brampton and the Town of Caledon - areas to the west of Toronto.

**Comment by migurski** [comment]
Thanks @kevin-peel! Do you happen to know if the directions are prefixed or suffixed? E.g. is it `302 S Queen St.` or `302 Queen St. S` ?

**Comment by kevin-peel** [comment]
Suffixed `Queen St. S`

In cases where it is prefixed it is a part of the STREETNAME column, eg `South Millway`

**Comment by iandees** [comment]
Kevin, is your name really Kevin Peel or are you just a Kevin from Peel? :)

**Comment by ingalls** [comment]
This is awesome! I have a pending FOIA request with the County of Peel, love seeing them respond with open data!

**Comment by kevin-peel** [comment]
@iandees - Kevin from Peel. ;)  I maintain most of the data on our open data portal.

Thanks for the quick response to the release!

**Comment by migurski** [comment]
Welcome Kevin!
