### ISSUE TITLE
Indianapolis is lacking physical data

### ISSUE THREAD

**Issue by moore3071** [openaddresses/openaddresses#1743]
Physical addresses are not available for the Marion County, Indianapolis data. I'll update this if I find a resource with latitude, longitude, and physical addresses.

**Comment by trescube** [comment]
For some reason, not a single one of the 152,017 entries in `/us/in/marion.csv` has a house number or street.  The only reason I can see for it is that the data source specifies the fields as `STNUM` and `FULL_STNAME` whereas the conform specifies `stnum` and `full_stname` (just a case difference).  I didn't think they mattered but I'll update the source to see if that fixes things.

**Comment by migurski** [comment]
👍
