### ISSUE TITLE
Upload Clackamas, OR data to s3

### ISSUE THREAD

**Issue by trescube** [openaddresses/openaddresses#1746]
Until #1745 is supported, the following data can be imported but most be hosted on OA's s3 bucket:  

http://cmap.clackamas.us/dataportal/index.jsp

I'll create the source once the file is in place on s3.

**Comment by trescube** [comment]
I'd include the actual file but it's well over the 10MB github limit.  The desired file is listed under "Tax Lots".

**Comment by ingalls** [comment]
Sorry for taking so long with these, just noticed these now, feel free to cc me with @ingalls and I'll try to get them up the same day!

`http://data.openaddresses.io/cache/us-or-clackamas.zip`

**Comment by trescube** [comment]
Fixed in #1768
