### ISSUE TITLE
Iqualuit, Nunavut

### ISSUE THREAD

**Issue by ansis** [openaddresses/openaddresses#175]
http://www.city.iqaluit.nu.ca/i18n/english/Buildings-map-November2010-36X48.pdf

A pdf with no license, but there is probably a shapefile behind it. Possible contacts:
http://www.city.iqaluit.nu.ca/i18n/english/lands.html

**Comment by justinelliotmeyers** [comment]
emailed: admin@city.iqaluit.nu.ca

If dont hear back, will close out

**Comment by justinelliotmeyers** [comment]
@ingalls they replied on 11/19/18 - havent heard back. Would be a nice little addition. If I dont hear back by Friday, is the best way to FOIA Canada data through Muckrock? Thanks!!

**Comment by justinelliotmeyers** [comment]
Good morning,

 

I am sorry but I don’t know the answer. I will look into it and let you know what I find out.

 

Sincerely,

 

 

Amanda Wells

Lands Administrator

City of Iqaluit

P.O. Box 460

Iqaluit, NU

X0A 0H0

Phone: 867-979-5663 (Please note my new phone number)

Fax: 867-979-6383

Email: a.wells@city.iqaluit.nu.ca

**Comment by iandees** [comment]
I would say that it's a no. We can't relicense/redistribute. It might be worth explaining the project and asking if they'd offer a more permissive license for a subset of the data?

**Comment by justinelliotmeyers** [comment]
got it - I'll respond and see what they say. Thanks for looking it over!

**Comment by justinelliotmeyers** [comment]
Hi Justin,

We will have to look into this request, I will advise once I have clarification,

Thank you,

Jennifer

 

Jennifer Jarvis

City Planner and Development Officer

City of Iqaluit

P.O. Box 460, Iqaluit, Nunavut, X0A 0H0

 (867) 979-5661

j.jarvis@city.iqaluit.nu.ca

www.city.iqaluit.nu.ca

**Comment by ingalls** [comment]
Closing as stale
