### ISSUE TITLE
Correct Data for California

### ISSUE THREAD

**Issue by xtgMike** [openaddresses/openaddresses#1755]
Hi -

I am a Property Tax Agent and depend on exact locations of property addresses. I have a number of checks to verify an address is reasonable.  I use Mapquest and Google to check addresses and resolve any ambiguities.

In any event, I started with open address as my base and have corrected any errors in the data while adding any missing parcels.  I would like to give back and send my data set with APN, Street, Zipcode, Latitude, and Longitude.  By the way, I found my data city names do not correlate with the zipcode for the different counties we service.

What should I do to send the corrected data?

Mike

**Comment by iandees** [comment]
Hi Mike! Thanks for contacting us.

I'm curious to hear about what sort of discrepancies you're seeing. If you want to post your data somewhere (like Dropbox maybe?) and include a link here, that'd be really interesting.

Having said that, we don't actually apply any changes to the data we download from sources. If there's something wrong with our data, the best we can do right now is find the contact info for the source that has the problems and pass them along, hoping that they will make changes on their end.

Also, keep in mind that the data we distribute today is address points, not parcels. We're working on processing parcels (and some of our sources are indeed parcel centroids), but some of the discrepancies might come from that distinction.

**Comment by xtgMike** [comment]
Hi Ian,

I did some sanity checking on the data for each county.  As I have over 
4 Million records, I do not know which ones have been corrected.

Essentially, I have the most northern, southern, eastern, and western 
point for each county.  I compare these coordinates with the Geo data 
provided.  If a property is outside these coordinates, then the data is 
corrupt.

By the way, before I loaded the geo data, I cleaned up all the duplicate 
entries (and there are quite a few).

The other reasonable check is looking for two residential homes (not 
condos) that have the same geo location.  Obviously two homes (different 
street addresses) cannot have the same geo point.

As I have more records for counties than the open source data, I had to 
find the geocode for those homes not listed.

Here is a list of the 12 counties I am processing.  I have not finished 
all the counties and chipping away at them one by one.

Alameda
Contra Costa
Los Angeles
Orange
Placer
Riverside
Sacramento
San Bernardino
San Diego
San Joaquin
San Mateo
Santa Clara

**Comment by migurski** [comment]
@xtgMike, that sounds super interesting. We were thinking about a similar thing a while back, when we noticed a few flipped lat/lon sources: https://github.com/openaddresses/machine/issues/318. I’m happy that you went ahead and did this!

Do you happen to be able to map your changes back to original rows?

**Comment by xtgMike** [comment]
Unfortunately no.  I made the changes directly into our database and 
have geocoded data from a few places to get all the data for a county.  
I can give you the points for the counties I have done so far.

M

**Comment by migurski** [comment]
I bet we could turn that into some kind of diff as an experiment, especially if we know the timestamp of the files you downloaded.

**Comment by xtgMike** [comment]
The data came from the county file - although a few counties needed to 
add a city file as well.  Let me know what you want to do.

M
