### ISSUE TITLE
Upload Osceola, FL data to s3

### ISSUE THREAD

**Issue by trescube** [openaddresses/openaddresses#1757]
Until https://github.com/openaddresses/machine/issues/325 is supported, please upload the attached file to s3.  
[osceola.fl.zip](https://github.com/openaddresses/openaddresses/files/327881/osceola.fl.zip)

Needed for #1619

**Comment by ingalls** [comment]
Uploaded: `http://data.openaddresses.io/cache/us-fl-osceola.zip`
