### ISSUE TITLE
Belgium

### ISSUE THREAD

**Issue by ingalls** [openaddresses/openaddresses#179]
http://data.belgium.be/

**Comment by ingalls** [comment]
This got us the flanders dataset

**Comment by katossky** [comment]
There is also a data set for Wallonie, to arrive soon. Maybe you can have an early access by mailing to icar@spw.wallonie.be. I can assist for the French if needed.

The documentation is [here](http://geoportail.wallonie.be/georeferentiel/icar) (albeit in French) and the soon soon-to-come data will be available [here](http://geoportail.wallonie.be/catalogue/2998bccd-dae4-49fb-b6a5-867e6c37680f.html). But [the licence](http://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CGU.pdf) does not seem open-data friendly at all (my translation):

> The user ... can not distribute the data to a third party ; can not publish the data on the Internet via a web service ; can publish it as an static image.

**Comment by nvkelso** [comment]
Is this a generic open data license that they use, or something draft for
the draft dataset that they are taking public comment on?

**Comment by katossky** [comment]
It's difficult for me to understand. The licence is spread across 3 documents:

- 1 general "access" licence
- 1 specific "access" licence, restricting application of the previous one
- 1 "user" licence (the one that I mention in my previous comment)

**Comment by katossky** [comment]
I sent a mail to ask for more information, with copy to OpenAddress.

**Comment by sergiyprotsiv** [comment]
@katossky, I have preliminary data here: https://github.com/openaddresses/openaddresses/pull/2768
Let me know if there are any news on the license.

**Comment by katossky** [comment]
I am in discussion with them. They ask who is behind OpenAdresses. I do not know what to answer.

Since the licence authorizes a special agreement with the data producer SPW, I guess they want to know with who they are going to agree anything. Fore sure they can't sign anything with a Github account :)

Please help!

**Comment by iandees** [comment]
I could probably sign something. What are their terms?

**Comment by katossky** [comment]
They don't have terms yet. They ask "Who are we talking with?".

**Comment by katossky** [comment]
That's what I was gonna say, but I am afraid they would freak out :)

Do you read French? You're the one behind openaddresses@gmail.com, right? I always copy e-mails to that address.

**Comment by katossky** [comment]
I replied, with copy to @ingalls and @iandees, in both French and English. I'll keep you updated.

**Comment by iandees** [comment]
🤔  I don't have access to that Gmail address. I think @lxbarth or @ingalls created it? I have a catch-all for email on the openaddresses.io domain, so I'll change the contact link on the website to point to hello@openaddresses.io or something.

**Comment by lxbarth** [comment]
Not mine.

**Comment by msirenko** [comment]
@mb

Dear Sir Barkeshli,
 
As an aswer to your questions concerning addresses in Belgium, I hereby send you some information about the project BeStAddress.
 
The official deadline for BeStAddress to be in force is 1 January 2018. However, keeping in mind the current developments it will be difficult to maintain this deadline (or at least not for the full scope of the project). At the moment, the Address Committee is looking at different option to make sure that the deadline will be respected.
 
![image](https://cloud.githubusercontent.com/assets/7937582/26692014/09ed9260-46b4-11e7-9b14-894648f63084.png)


The goal of BeStAddress is to have one authentic source for all the Belgian addresses and to have a unification of referring to addresses and the linking of address data to it.  This database will be fed by those of the Belgian Regions (Flanders, Wallonia and Brussels). It is also there that the updates of the data will be done. The consumer will only have to request the data at one central point and will get the response there as well (see figure). With the current development in mind this will probably be a SOAP web service. It will be open data.
 
On the demand of a few partners it will also be foreseen that the users can perform a full download. Different working groups are looking into this to define how this will be done and with what frequency.

Summary:
- Timing: January 2018 (official deadline, might be difficult to reach)
- Open Source: yes
- Content:  one authentic source for all the Belgian addresses and to have a unification of referring to addresses and the linking of address data to it
- Sources: Databases Belgian Regions
- Update: continues updating
 
If the need for this data is urgent, it is best to contact the government of the regions to get their data.
Flanders (Flemish Region) already had an open data address databank, called CRAB.
You can download it here : https://download.agiv.be/Producten/Detail?id=447
Also the region of Brussels Capital had open data addresses, called Urbis-Adm.
You can download it here : http://urbisdownload-v2.gis.irisnet.be/nl/download/
 
Kind regards,
Vriendelijke groeten,
Tine VAN CAUTEREN
Attaché
Commerciële Directie
 
Nationaal Geografisch Instituut
Abdij Ter Kameren 13
1000 Brussel
Tel +32(0)2 629 82 91
E-mail tine.van.cauteren@ngi.be
Website : www.ngi.be – www.geo.be
logo_geobe

What follow-up

**Comment by katossky** [comment]
On my side, the responsible for ICAR data replied that we have to address our request to the Belgian Transport minister directly: http://diantonio.wallonie.be.
