### ISSUE TITLE
us-fl-duval

### ISSUE THREAD

**Issue by b-may** [openaddresses/openaddresses#1797]
Duval County FL just brought online a new ArcGIS server with address points.

`http://maps.coj.net/coj/rest/services/DuvalMaps/duvalProperty_2012/MapServer/34`

**Comment by trescube** [comment]
I'm having trouble opening the data in QGIS right now, it appears to stall about halfway thru, and I can't tell for certain what the fields are without seeing the source data.  I'll keep an eye on it.

**Comment by b-may** [comment]
I scraped 1000 records into shapefile format with all of the fields included - you can download the sample here:

`https://www.mapwise.com/data/address_points_duval_test.zip`

**Comment by trescube** [comment]
Thanks!  I'll check it out in a few minutes.
