### ISSUE TITLE
Update us/ma/statewide to use statewide address points instead of parcels

### ISSUE THREAD

**Issue by iandees** [openaddresses/openaddresses#1831]
New layer is here: http://gisprpxy.itd.state.ma.us/arcgisserver/rest/services/AGOL/MassGIS_Master_Address_Points/MapServer/0

**Comment by iandees** [comment]
If someone takes this, I'd love to see a step-by-step guide written about how to update an existing source with a new URL.

**Comment by trescube** [comment]
I can do that

**Comment by trescube** [comment]
It might be a few days.

**Comment by erictheise** [comment]
I've been looking for a way in to OA and would be glad to take this on but frankly I don't know enough to tell whether this is straightforward or has some hidden complexity.

**Comment by trescube** [comment]
Eric, you appear to have deleted your comment but if you're still watching it would be great to work with you on updating this data source.  It would be a great introduction to contributing to OA.

**Comment by trescube** [comment]
Great, sounds good!

**Comment by slibby** [comment]
closed via https://github.com/openaddresses/openaddresses/pull/1832

**Comment by erictheise** [comment]
I was still thinking about @iandees' ask, which was to contribute a step-by-step write up, presumably to https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md. I started in on a blog post which, when finished, I'd strip back to something less chatty.

The thing is, the bulk of it is about coaxing data out of the ESRI server and that's not really specific to a change in data source. Maybe I should let it go. Thoughts?

**Comment by iandees** [comment]
@erictheise I'd be curious to see your write-up including how you ended up coaxing data out of ESRI. I have my methods of doing it (as do others that contribute here) and I want to see if your methods are similar.

The eventual goal for me is to build a web app that let's people submit their own data (including an ESRI endpoint), see a sample of the source data, build the conform/mapping information, and preview the output result. Documenting the manual process is good first step towards making it automated.

**Comment by erictheise** [comment]
Okay, @iandees, I'll finish up my post in the next couple of days and see how if the info could be shoehorned into CONTRIBUTING.md. Will let you know. Maybe reopen the issue?
