### ISSUE TITLE
Include points interpolated from TIGER edges?

### ISSUE THREAD

**Issue by iandees** [openaddresses/openaddresses#1853]
What do y'all think about adding code to `machine` that would create interpolated points from linear address range features? A primary example of this would be the TIGER address ranges attached to their road "edges", but there are plenty of other sources we've run past that only distribute road centerlines with address ranges attached to them.

Is the increased coverage with lower accuracy acceptable? If we include TIGER, we would surely end up with duplicate address points: who should do the de-duplication? Would including a de-duplication step in OA's build system be a pre-requisite for this to be useful?

**Comment by migurski** [comment]
This makes me a bit uncomfortable. I’d feel better including ranges as a first-class object in some form, rather than generating fake points.

**Comment by missinglink** [comment]
ref: https://github.com/pelias/pelias/wiki/Interpolation:-existing-standards

**Comment by justinelliotmeyers** [comment]
@iandees can I close this or leave this open? Thanks!

**Comment by iandees** [comment]
Let's close it for now.
