### ISSUE TITLE
MN Counties 

### ISSUE THREAD

**Issue by turtles2** [openaddresses/openaddresses#1854]
This is a spreadsheet of all MN Counties and contact info for them. The ones in red did not respond after repeated attempts. The ones are yellow are paid most prices are listed. 
[Minnesota Counties  .xlsx](https://github.com/openaddresses/openaddresses/files/372576/Minnesota.Counties.xlsx)

Updated 
[Minnesota Counties.xlsx](https://github.com/openaddresses/openaddresses/files/374010/Minnesota.Counties.xlsx)

**Comment by iandees** [comment]
This is awesome, thanks for doing this work!

Have you seen our [OpenAddresses US County Status Doc](https://docs.google.com/spreadsheets/d/1HFm0YbFDC5YKkHKFt89EKdhpyaCCIo_CiDFjBNq4PoI/edit?usp=sharing)? It would be really helpful if you could integrate the information you found for this spreadsheet into the Minnesota rows in ours.

**Comment by turtles2** [comment]
I can do that but since most of this data is about if the sources are paid how can I add that? It dose not seem your sheet has those columns? I have the price's in my sheet and think it would be a shame to lose them.

**Comment by trescube** [comment]
I managed to track down ArcGIS servers for Chippewa, Cook, Norman, Pennington, Red Lake, Todd, and Waseca counties.  PRs have been generated/merged for all but Cook, I'm still working out the regex to extract the `unit` field on that one.

**Comment by turtles2** [comment]
Cool I will update as my only way of getting data was to email said county.
I haven't checked the JSON recently so I will check then add what I have to
the master and mine.

**Comment by trescube** [comment]
I just managed to get ahold of Hubbard County, too.

**Comment by trescube** [comment]
And [Kittson County ](https://github.com/openaddresses/openaddresses/pull/1863)

**Comment by trescube** [comment]
And [Olmsted County](https://github.com/openaddresses/openaddresses/pull/1864)

**Comment by trescube** [comment]
That's it, everything else is behind geomoose, mapserv, or beacon-schneider.

**Comment by migurski** [comment]
👏 👏 👏

**Comment by turtles2** [comment]
@trescube How are you getting this data? I have been reaching out to the County Assessors and finding they either have no idea about access to there data-sets or want money for it. 

It seems allot of counties use Beacon are they tight lipped about access to data?

**Comment by trescube** [comment]
I find their interactive map, open up Javascript console in Chrome, look for ArcGIS-formatted network traffic, then poke around on those servers.  

There are quite a number of Beacon servers in that area of the country but I was unable to get an the data underneath.

**Comment by justinelliotmeyers** [comment]
@turtles2 can i close this? any new resources? Thanks!!

**Comment by justinelliotmeyers** [comment]
Thanks! If you find any resources in the future, please share!!
