### ISSUE TITLE
Johnson County KS File

### ISSUE THREAD

**Issue by jsteibprinttime** [openaddresses/openaddresses#1891]
The file for Johnson County KS USA shows no data when downloaded. However there is sample data when that option is clicked on.

**Comment by trescube** [comment]
The county has put the parcel and address point data behind a login form.  It's still possible to get the data but it's a little trickier.  I'll see what I can do.

**Comment by justinelliotmeyers** [comment]
http://aims.jocogov.org/

**Comment by ingalls** [comment]
Closing paid source tickets
