### ISSUE TITLE
Oklahoma City, OK

### ISSUE THREAD

**Issue by tlpinney** [openaddresses/openaddresses#192]
Possible Contact Info: http://www.okc.gov/info_tech/index.html

Current map and address look up page which is not compatible with the downloader.
http://gis.okc.gov/website/okcmap/viewer.htm
http://www.okc.gov/info_tech/gis/StreetIndex/Forms/StreetAddressIntro.aspx

**Comment by geobrando** [comment]
Looks like OKC now has an open data portal.  Unfortunately, address data is the only GIS data that lacks a download button and is only visible in-browser or on a map.  Don't recognize the platform and couldn't figure out a way to extract it.  Sent an email to inquire about the data.  If that doesn't work, might have to try the option they provide of submitting an open records request.

https://data.okc.gov/Portal/desktop/page/maps

**Comment by slibby** [comment]
@geobrando did you ever hear back from OKC? This same area is covered by the data from https://github.com/openaddresses/openaddresses/blob/master/sources/us/ok/acog-counties.json but there are definitely slight differences when I compare both datasets on a map.

**Comment by geobrando** [comment]
@slibby I did not.  Just sent a follow up email. Thanks.

**Comment by geobrando** [comment]
Received a response that I would need to make a public records request for that data., and was given a link. I will see what that entails.

**Comment by geobrando** [comment]
http://www.okc.gov/clerk/OpenRecordsRequest/Forms/SubmitOpenRecordsRequest.aspx

**Comment by ingalls** [comment]
Closing as stale - Feel free to open a new issue if someone is actively going after these.

**Comment by trescube** [comment]
This looks like the data:  https://gis.okc.gov/arcgis/rest/services/Accela/AGIS_PPLS_DEV/MapServer/0

**Comment by trescube** [comment]
Perusing the data, this looks like it's all of Oklahoma County, OK (which includes Oklahoma City)
