### ISSUE TITLE
Encoding/Mojibake issues in some files

### ISSUE THREAD

**Issue by thatdatabaseguy** [openaddresses/openaddresses#1921]
There are a few files I saw in going through some of the OpenAddresses data that had encoding issues. The main example that's coming to mind at the moment is [city_of_wesel](https://github.com/openaddresses/openaddresses/blob/master/sources/de/nw/city_of_wesel.json) in Germany but there were others.

Possibly of interest for the machine repo, there's this a Python library that's super useful for fixing common encoding issues: https://github.com/LuminosoInsight/python-ftfy. It's in PyPI, works on Python 2/3, etc. Here's a quick example using a street name from the Wesel file:

```python
import ftfy

assert ftfy.fix_encoding(u"Aachener StraÃe") == u"Aachener Straße"
```

**Comment by iandees** [comment]
In this case, it looks like the `conform` object for that source specifies an incorrect encoding. I'll try pushing a fix for that.

**Comment by iandees** [comment]
@thatdatabaseguy thanks for finding this stuff. If you find another encoding problem please let us know with a new issue or reopen this one.

**Comment by thatdatabaseguy** [comment]
Oh cool, thanks. Didn't see the encoding param.
