### ISSUE TITLE
Add addresses in Mendocino county, CA

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1941]
Status:
- [x] **Research sources** and propose best source (and it's data license)
- [x] **Review proposed source**
- [x] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
emailed the county about their gis data here: http://www.co.mendocino.ca.us/econdev/gis/index.htm
Nothing available for download.  hopefully hear back from them soon.

**Comment by justinelliotmeyers** [comment]
emailed assesor:
Susan M. Ranochak
Mendocino County Assessor-County Clerk-Recorder
501 Low Gap Rd., Room 1020
Ukiah, CA 95482
707-234-6800 (Assessor)

**Comment by justinelliotmeyers** [comment]
![mendicino_ca](https://cloud.githubusercontent.com/assets/5324316/20099636/7d76aede-a587-11e6-8886-9a10149504ff.jpg)

found this - not sure if we can use it!?

**Comment by iandees** [comment]
@justinelliotmeyers where did you find it?

**Comment by justinelliotmeyers** [comment]
http://mapport.com/mendocino-county-parcel-viewer/

I downloaded it - will take a little work to grab the data out of it, but not too much.  I don't know what the TOU would be... thoughts?

**Comment by nvkelso** [comment]
No: Against terms: http://mapport.com/terms/

We'll need to get from county.

**Comment by justinelliotmeyers** [comment]
okay - I e-mailed them.  Hopefully hear from them soon.

**Comment by ingalls** [comment]
Just a reminder that all counties in CA have to provide this data to the public at-cost of the records. http://geospatial-solutions.com/california-supreme-court-rules-that-orange-county-must-provide-gis-data-to-the-public-for-a-nominal-fee-under-the-public-records-act/

**Comment by nvkelso** [comment]
Sharing the common wealth of the Golden State.

**Comment by justinelliotmeyers** [comment]
@nvkelso **currently working on address point dataset - will be ready in a few months ($30 for a cd/ dvd).  they do have parcels available now for $30 on cd/dvd.  I called (707) 234-6000 and asked to speak to someone with regard to gis data and that is what they told me.  So I am going to assign this to you.  The person I spoke to was named Leif Farr; very nice and helpful.

**Comment by nvkelso** [comment]
I'll ask for the parcels now.

**Comment by nvkelso** [comment]
Make check out $30. Payable to Mendocino County. Memo for `Parcel GIS Shapefile`.

```
Attention: Leif Farr
Information Services
501 Low Gap Road
Room 1440
Ukiah, CA 
95482
```

Update: Address points are more than 50% done, but only worked on between other gigs.

**Comment by nvkelso** [comment]
Check sent via snail mail. It's only a few hours north of SF where I am so maybe a CD this week?

**Comment by nvkelso** [comment]
I've received the DVD! Now for getting it onto S3...

**Comment by migurski** [comment]
I was unable to read the DVD using my old laptop. Maybe another CD drive would do it?

**Comment by nvkelso** [comment]
Doh! I'll try with new drive I ordered. Else will request replacement disc from county.

**Comment by nvkelso** [comment]
Data is ready for PR here:

- https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/nvkelso/d84a43/mendocino_california_Parcels_10_15_U.zip

Use `SITUS_*` fields – and like all parcel datasets, the rural areas don't have have street numbers but the urban areas do.

<img width="651" alt="screen shot 2016-12-13 at 12 57 19" src="https://cloud.githubusercontent.com/assets/853051/21159076/9d26b8fa-c134-11e6-9495-b8444b32b819.png">

![screen shot 2016-12-13 at 12 55 12](https://cloud.githubusercontent.com/assets/853051/21159077/9d3e1bd0-c134-11e6-98c9-cb20f81a0537.png)

**Comment by nvkelso** [comment]
Turns out there's a reason we stopped using DVD drives, but if you need a disk read, send it my way ;)
