### ISSUE TITLE
Add addresses in Trinity county, CA

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1942]
Status:

- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by davidchiles** [comment]
Isn't this already added?
https://github.com/openaddresses/openaddresses/blob/master/sources/us/ca/trinity.json

**Comment by iandees** [comment]
Yep!

**Comment by nvkelso** [comment]
Verified on map, sorry for the noise!
