### ISSUE TITLE
Add addresses in Grants Pass, OR

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1943]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
Parcels: http://gis2.co.josephine.or.us/arcgis/rest/services/JOCO_TaxLots/MapServer/0

![joco_taxlots](https://cloud.githubusercontent.com/assets/5324316/20138264/6becf03a-a64d-11e6-9a76-1db55a942212.jpg)

house number - ST_NO
street name base - ST_NAME
street name suffix - SITUS_SUFF

DISCLAIMER: Any GIS Map image and/or data that may be provided by Josephine County resources is intended for general visual reference and informational purposes only.  The accuracy of Geo positional/location information is not intended to be relied upon for any critical measurements nor guaranteed in any way.  Much of the data in these maps is dynamic and is updated at various intervals. At times, data depicted in a map one day may change and/or be updated the next day.  Due diligence on the part of the recipient is necessary to confirm its fitness for use in all cases.

**Comment by nvkelso** [comment]
"Due diligence on the part of the recipient is necessary", roger that ;)

**Comment by iandees** [comment]
We've already got this data here: https://github.com/openaddresses/openaddresses/blob/master/sources/us/or/josephine.json

**Comment by nvkelso** [comment]
@iandees But I still don’t see any dots showing up on the map around Grants Pass? Why?

<img width="698" alt="screen shot 2016-11-09 at 09 13 03" src="https://cloud.githubusercontent.com/assets/853051/20147400/c2145368-a65c-11e6-9588-dab737acad9a.png">

**Comment by iandees** [comment]
The data for Grants Pass is in our output (http://s3.amazonaws.com/data.openaddresses.io/runs/124045/us/or/josephine.zip), so I'm not sure why it's missing from the dotmap…

**Comment by nvkelso** [comment]
Dots in that CSV do match general pattern compared to parcels Justin found:

<img width="418" alt="screen shot 2016-11-09 at 09 31 54" src="https://cloud.githubusercontent.com/assets/853051/20148012/723a8116-a65f-11e6-98fa-0303060feef4.png">

**Comment by nvkelso** [comment]
Sorry for the wild goose chase, @justinelliotmeyers :(

Tracking missing dots from map in #2123.

**Comment by justinelliotmeyers** [comment]
No problemo - Just let me know if you need me to look into anything tonight.  Thanks
