### ISSUE TITLE
Add addresses in Kennewick/Richland, WA

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1944]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
emailed Benton County, WA (gis@co.benton.wa.us )

**Comment by justinelliotmeyers** [comment]
@iandees 
Franklin County, WA Parcels here: http://franklingis.org/franklingis/data/fe697be8_e7aa_11e5_a549_22000bb3a3a1/parcels

situs - has address stacked in field.

![franklin_co_us](https://cloud.githubusercontent.com/assets/5324316/20138685/b398bb38-a64f-11e6-8346-c8c8c7005b1c.jpg)


 Before proceeding, please read and accept the following terms and conditions governing the usage of the services provided on this site.

Regarding map content, data sets, and depictions thereof:
All information depicted herein is provided as-is, with no warranty, expressed or implied. No guarantee of information usability, accuracy or suitability is inferred, implied, or expressed. Neither Franklin County Regional Information System (FRIS), nor any member agency, shall be liable for any error or errors within, or implied by, the provided information, or for any loss, direct or indirect, immediate or subsequent, related to the use of this information or any information derived from this information. The information presented in this web map portal is subject to change without notice and does not represent a commitment on the part of Franklin County in the future.

Regarding Assessor's and/or Treasurer's data and associated reports or forms:
The information provided by Franklin County is provided 'as is' and for reference only. The user expressly agrees that the use of Franklin County's web site is at the user's sole risk. Franklin County does not warrant that the service will be uninterrupted or error free. Any information published on this server could contain technical inaccuracies or typographical errors. Changes may be made periodically to the tax laws, administrative rules, tax releases and similar materials; these changes may or may not be incorporated in any new materials on the web site. You should always use the original recorded documents for legal transactions.

All presentations are Copyright 2015, FRIS, All Rights Reserved.

**Comment by nvkelso** [comment]
License is fine.

**Comment by trescube** [comment]
I think we already have [points](https://github.com/openaddresses/openaddresses/blob/master/sources/us/wa/franklin.json) for Franklin County, WA.

**Comment by iandees** [comment]
Yep, closing this in preference to the address points data.

**Comment by justinelliotmeyers** [comment]
**We dont have data for Benton County (SW side of the river) - should this issue stay open?  Or should we create a new issue for Benton County, WA?  Thanks @iandees and @trescube

**Comment by iandees** [comment]
Looks like we have Benton here: https://github.com/openaddresses/openaddresses/blob/master/sources/us/or/benton.json

**Comment by justinelliotmeyers** [comment]
![kennewick](https://cloud.githubusercontent.com/assets/5324316/20144415/93d5ab92-a66a-11e6-9240-4469446460c0.png)

okay - I was going off of the visual from the map.  Kennewick seems empty on the site.  I'll have to dl WA tonight and see whats going on.  Thanks @iandees

**Comment by iandees** [comment]
Ah, I linked to Benton county, OR and you pointed to Benton county, WA.

Let's make a new ticket for Benton, WA.

**Comment by justinelliotmeyers** [comment]
*****They just responded - (Benton, WA).  @nvkelso can we agree to this license: http://benton.municipalcms.com/pView.aspx?id=725&catid=45

**Comment by iandees** [comment]
I think we would be OK with the exception of this one clause:

>  I will not use said records for commercial purposes and understand that it is my affirmative duty to prevent others from using said records for commercial purposes.

We can't guarantee that people will not use this data for commercial purposes.

**Comment by justinelliotmeyers** [comment]
**Attached are address points for Benton County. Please contact the individual cities for their address data.
 
Thanks,
Anthony Von Moos
GIS Technician
www.BentonCountyGIS.org

I'll ask what the TOU/ Copyright is.  otherwise we have the address points.

**Comment by justinelliotmeyers** [comment]
So when I asked for the data, I guess I agreed to the terms here: The requestor below hereby acknowledges receipt of information from the Benton County Geographic Information Systems Department (“GIS”). The requestor understands that Benton County makes no representation as to the accuracy or fitness of the information for a particular purpose, including, but not limited to, aerial photography, maps, data files, cartographic and/or physical data. The requestor further understands that the GIS information is the product of Benton County, created solely for its own use and no other purpose, commercial or otherwise. By agreeing below, the requestor agrees to hold harmless, including the cost of defending, Benton County and its agents or employees from any and all claims arising either directly or indirectly from the use of these photographs, maps or data files.

Looks like we cannot use the data.  Maybe we could write and ask if they can lift the " I will not use said records for commercial purposes and understand that it is my affirmative duty to prevent others from using said records for commercial purposes." for our specific project.  Thoughts?

**Comment by nvkelso** [comment]
That’s a confusing license.

5)       I agree to protect and hold harmless, including the cost of
defending, the agency and its agents and employees from which I have
obtained said records from any and all claims arising either directly or
indirectly from the commercial use of said records.

6)       I further agree that if the requested information is provided, I
will not sell the records or disseminate the data contained therein to
third parties.

One way of reading 5 and 6 is just applying to personally identifiable
information mentioned in section 1. Can you write them and ask if it’s just
that, or something more expansive?

**Comment by nvkelso** [comment]
I’m not bothered by that general click-through.

"product of Benton County, created solely for its own use and no other
purpose, commercial or otherwise.”

I read that to mean “hey, you could use this for commercial purposes, but
we didn’t make it for that use”.

**Comment by justinelliotmeyers** [comment]
I'm following up now and trying to find a good point of contact as per asking about the legal terminology.  The person who sent the data is just their GIS Tech.  So I will figure this out asap.  Thanks @nvkelso

**Comment by justinelliotmeyers** [comment]
Please contact Clark Posey (Clark.Posey@co.benton.wa.us )in the Planning department for more information on this data.

I emailed him asking for a call with regard to the Copyright and TOU - anything specific I should ask, or should I just ask if we can use it for the project and have that written in an official e-mail?

Thanks

**Comment by nvkelso** [comment]
Yep, sounds good. Washington State counties seems pretty good on the open
data spectrum.

**Comment by justinelliotmeyers** [comment]
We are getting the data!!!  and license for points will work out for what we are doing.  Stay tuned!!

**Comment by justinelliotmeyers** [comment]
Hi Justin,
 
The file Anthony sent you yesterday contains our rural address points. I double-checked on which disclaimer he had you sign and it is our generic disclaimer. The reference to commercial purposes has been in there a long time, but should be revisited. According to our Prosecuting Attorney’s Office the only restriction on utilizing our data for commercial purposes would be on lists of individuals (addresses with names, etc.), so the address point data is not a concern.
 
We can provide address point data for the cities of West Richland, Prosser and Benton City because we maintain that data. I will CC Anthony so he knows to send that data your way.
 
As far as the other two cities in our county, you might wish to contact Dan Welch from the City of Richland at DWelch@CI.RICHLAND.WA.US and for the City of Kennewick contact Aaron Lowe at aaron.lowe@ci.kennewick.wa.us.
 
I hope this helps.
 
Regards,
Mary
 
Mary M. Phillips, MS, GISP
GIS Manager
Benton County

**Comment by justinelliotmeyers** [comment]
emailing DWelch@CI.RICHLAND.WA.US and aaron.lowe@ci.kennewick.wa.us now

**Comment by justinelliotmeyers** [comment]
@nvkelso and @iandees  Benton County data is here:https://www.dropbox.com/s/qre4vtptg668cwg/AddressPoints.zip?dl=0 

The e-mail above is the license/ wording (is what Anthony Von Moos GIS Technician www.BentonCountyGIS.org ).  I reached out to the two cities that they do not have in this file.  Hopefully I hear from them soon.

Let me know if there is anything else you need from me.  After those two people respond, we can close this massive issue!?!

**Comment by justinelliotmeyers** [comment]
@nvkelso and @iandees City of Kennewick address points are here: http://gis.kennewick.opendata.arcgis.com/datasets/627b54ef549f47bd97b04481c45009e6_92

**Hi Justin,
 
Our address data is available for download as a shapefile here:  http://gis.kennewick.opendata.arcgis.com/datasets/627b54ef549f47bd97b04481c45009e6_92
 
There is currently a problem with the site that is causing as shift in the data, but it is only about 4 feet, so should be fine for your purposes.
 
 
Aaron Lowe
City of Kennewick
Software Support Supervisor
O: 509.585.4343  |  F: 509.585.4445
aaron.lowe@ci.kennewick.wa.us

**Comment by justinelliotmeyers** [comment]
Just Called Dan Welch (Welch, Dan	IT Applications Developer/Integrator	Assistant City Manager	(509) 942-7748 ) and he said he would send data!!!!  Lot of damn work for this tri city area!!!  As soon as I receive the data I will upload to dropbox and we can close the issue.  Thanks everyone for your patience with this one.

**Comment by nvkelso** [comment]
Awesome, thanks for the followups :)

**Comment by justinelliotmeyers** [comment]
Had to formally request Richlands data through public records request (*although I called and talked with gis data guy...).  Anyway - should be coming soon.  Cheers!
![screenshot_20161110-185610](https://cloud.githubusercontent.com/assets/5324316/20201654/aac596fa-a787-11e6-88a9-bcdb59210e00.png)

**Comment by justinelliotmeyers** [comment]
Richland, WA data here: https://www.dropbox.com/s/o4cx0sjdnqj20ju/CoRAddressPoly.zip?dl=0

I understand there are fees associated with receiving copies of records based on the City’s fee structure and the quantities of records I’ve requested. I understand that fees are based on the costs directly related to the City’s actual cost of copying public records. I further understand that fees are calculated after the records have been located and gathered and that I must pay for copies of records prior to receipt.
I Accept:	Yes
I understand by Washington State law, RCW 42.56.520, the agency has five (5) business days from the date my request is received in the office to respond to my request. This may or may not include the delivery of my requested information, or when the records are available to inspect or copy.
I Accept:	Yes
I understand that Washington State law, RCW 42.56.070(9), prohibits the use of lists of individuals for commercial purposes. "Commercial purposes" means that the person requesting the record intends that the list will be used to communicate with the individuals named in the record for the purpose of facilitating profit-expecting activity. I am certifying that the lists of individuals obtained through this request for public records will not be used for commercial purposes.
I Accept:	Yes

So this is the final part to this tickets puzzle.  Once uploaded we can close the ticket.  Thanks!!

**Comment by justinelliotmeyers** [comment]
Two counties, and two cities data were found and obtained/ uplloaded to dropbox.  I believe we can close this issue.  Thanks @iandees !  Just added pr to start being more consistent.
