### ISSUE TITLE
Add addresses in Olympia, WA

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1945]
Status:
- [x] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by slibby** [comment]
services Directory: http://agol.co.thurston.wa.us/arcgis/rest/services/Thurston?f=pjson

**Comment by justinelliotmeyers** [comment]
Restrictions on use does not look positive (http://www.geodata.org/disclaimer.htm ) I emailed them (09/27/2016) to see if we can have written approval.

**Comment by justinelliotmeyers** [comment]
follow-up email sent 11/14/2016

**Comment by justinelliotmeyers** [comment]
**Phone call with Tami Faulkner (360)754-4594 - they have the data and can sell it to us and we can use in OA - but we have to make sure they are not liable if anyone uses the datas and there are errors in it that cause them harm!?  But one interesting part of this call is that she mentioned the state of Washinton is in the process of creating a state wide address point dataset; and it will be open data.  I am going to close this tocket and say we wait for the free data (which this county will be in)

**Comment by iandees** [comment]
How much did they want for the data?

**Comment by justinelliotmeyers** [comment]
They didn't include a price - i was more concerned with the license/ TOU.  I can find out tomorrow if that is okay?

**Comment by iandees** [comment]
The license is fine. It sounds like the standard "indemnification" that most of our sources have.

**Comment by nvkelso** [comment]
I’ve asked them for purchase details via email.

**Comment by nvkelso** [comment]
Let's leave this open until January 2017. At that time state-wide data will land in https://github.com/openaddresses/openaddresses/issues/2141, or we'll pay the $200 for this place.

**Comment by nvkelso** [comment]
I received the following response (below). 

It would be cheaper ($150 versus $200) to buy their general Oct. 2016 (quarterly) CD rather than having them pull a nightly for us. They do take credit cards. But let's still wait until January 2017 to see if statewide data for Washington materializes.

```
There are two options to purchase our parcels layer:
 
Our Parcel Layer is available for purchase for $200 + tax. The Parcel layer is 
as pulled when you place your order. Therefore, the data is as current as the 
night before.
 
The second option is to purchase our Base Data Disc which includes the layers 
you requested and many others (approx 23 layers total). The Base Data Disc is 
available for $150 +tax. The Base Data Disc’s layers are pulled quarterly so the 
data is current as of October 1st, 2016.
 
Layers Included in the Base Data Disc are:
Parcels; City & Urban Growth Area Boundaries; Road Centerlines; Railroad & 
Utilities; Water Bodies & Streams; 10 Foot Contour Interval; Public Land Survey 
System; County Zoning; Census Tracts (2010); School Locations & School 
Districts; Fire Stations & Fire Districts; Zipcode Boundaries; Political Boundaries; 
Government Lands; Parks & Trails; Watersheds & Basins; Shoreline Master Plan
 
If you would like to place an order I will need your contact, billing and shipping 
information. For payment your options are to pay with a credit card over the 
phone, can send you a billing invoice, or you can pay in person at our office. Your 
delivery options are that you can pick it up at our office (Building 4 by the 
Courthouse Complex- I can send you directions if needed), burn the data to a 
disc and mail it to you ($1 shipping fee), or you can download the data directly 
to your computer using SendThisFile (which I can send you instructions for if 
you haven't used it before).
 
Please note that there is a convenience fee of 2.35% added to the bill of any 
order paid with a credit card. The convenience fee does not apply to orders 
paid with cash or a check.
 
Please let me know if you have any questions, need anything clarified, or 
would like to place an order.
 
 
Thanks,
Elizabeth Donovan
GIS Analyst II
Thurston GeoData Center
(360) 754-4594 Main Line
(360) 867-2054 Direct Line
Public Office Hours: Monday–Friday 9:00 – 1:00
```

**Comment by nvkelso** [comment]
The statewide Washington data has landed, but it's a bit messy. I'll order this now so we have a cleaner option.

**Comment by nvkelso** [comment]
Parcel data received via FTP for Thurston county, Washington state (Olympia, WA) and posted here using S3 uploader:

* https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/nvkelso/cd363b/parcels_thurston_county_washington_state.zip

Note that we are **not** allowed to publish owner names and owner contact addresses, so we need to use the **`situs`** address and other fields (e.g.: don't use `address1` or `address2`).

The projection was unreadable when I opened in QGIS, but reading the PRJ file manually I set it to `NAD_1983_StatePlane_Washington_South_FIPS_4602_Feet` in QGIS via the projection search tool and everything lined up as expected.

![screen shot 2016-12-06 at 13 15 25](https://cloud.githubusercontent.com/assets/853051/20944012/b7ce593e-bbb6-11e6-96b9-2d9457360c2b.png)

<img width="609" alt="screen shot 2016-12-06 at 13 14 25" src="https://cloud.githubusercontent.com/assets/853051/20944013/b7ecd7a6-bbb6-11e6-9731-3bcee4a076ce.png">
