### ISSUE TITLE
Add addresses in Klamath Falls, OR

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1946]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
Klamath County, Oregon Parcels: http://services.arcgis.com/H6Mh1bySxR4oHx6x/arcgis/rest/services/KC_Taxlots/FeatureServer/0

![klamath_or](https://cloud.githubusercontent.com/assets/5324316/20138969/95ad66bc-a651-11e6-9f62-17543b0c5035.jpg)


SITUS_ADDRESS - address - seems to be empty for quite a few however?

**Comment by nvkelso** [comment]
Normal for federal land, and there is a lot of it here.

**Comment by trescube** [comment]
We already have [this data](https://github.com/openaddresses/openaddresses/blob/master/sources/us/or/klamath.json).

**Comment by iandees** [comment]
I was wondering why the Esri links were all purple in my browser already 😄 .

**Comment by nvkelso** [comment]
Hmm, this data is also missing from the dot map.

**Comment by nvkelso** [comment]
Why does http://s3.amazonaws.com/data.openaddresses.io/runs/124045/us/or/klamath.zip fail for me?

**Comment by iandees** [comment]
Where did you get that URL from?

**Comment by nvkelso** [comment]
I guessed it from the Medford URL pattern. Where are the real URL endpoints documented?

**Comment by iandees** [comment]
Look at https://results.openaddresses.io, click "Show Remaining" and search for `us/or/klamath`. It'll give you the most recent successful cache. In this case, the most recent cache is at http://s3.amazonaws.com/data.openaddresses.io/runs/119498/us/or/klamath.zip.

**Comment by nvkelso** [comment]
It's definitely there:

<img width="725" alt="screen shot 2016-11-09 at 09 51 20" src="https://cloud.githubusercontent.com/assets/853051/20148567/1f13bc98-a662-11e6-80ee-fca888664351.png">

**Comment by nvkelso** [comment]
@justinelliotmeyers best practice to verify the data is actually missing from @iandees link above. If it is not missing, then add comment in the issue saying it's a map visualization issue not a data source issue.

**Comment by nvkelso** [comment]
Will likely made redundant with https://github.com/openaddresses/openaddresses/issues/2148.
