### ISSUE TITLE
Add addresses in Tacoma, WA

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1947]
Status:
- [x] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by iandees** [comment]
Here's a layer: http://wspdsmap.ci.tacoma.wa.us/arcgis/rest/services/AddressLookup/MapServer/0?f=json

(Browsing via HTML is disabled on this server)

**Comment by justinelliotmeyers** [comment]
Their cities gis webpage is here: http://www.cityoftacoma.org/government/city_departments/community_and_economic_development/geographic_information_systems__gis_/ I sent an e-mail to the person requesting the data (09/27/2016).

**Comment by justinelliotmeyers** [comment]
Follow-Up email sent 11/14/2016 requesting data

**Comment by nvkelso** [comment]
@iandees Is the link you noted in https://github.com/openaddresses/openaddresses/issues/1947#issuecomment-247419711 good enough to proceed with a PR or should @justinelliotmeyers keep following the research thread?

**Comment by nvkelso** [comment]
Statewide data may land in https://github.com/openaddresses/openaddresses/issues/2141.

**Comment by justinelliotmeyers** [comment]
After emailing Nancy (. Nancy Grabinski-Young at ngrabins@cityoftacoma.org or (253) 591-5394 ) several times since September 27th... I followed up with her boss today.  She called me and asked 50 questions!?!  They are going to clip the data to the city proper and send it to us.  I told her if I don't receive it by Friday I was going to call and follow up.  So we should receive something in the next few days.

**Comment by nvkelso** [comment]
What’s in the unclipped data? The more addresses the better, unless it’s
something they can’t give us.

**Comment by justinelliotmeyers** [comment]
long story - after they clip it and ship it I will ask the guy if we can receive the full dataset.  It was not my idea to clip it - I would never say such a thing - but that is what she was willing to do, so I said yes please...  Stay tuned amigos!! haha

**Comment by justinelliotmeyers** [comment]
Just followed up with an e-mail... hopefully we get this today!?  stay tuned

**Comment by justinelliotmeyers** [comment]
https://www.dropbox.com/sh/jtzicj9d0hsyrs7/AADfsHr3m1ArHqi3NGRQaw5Pa?dl=0

Received the data!!!!!!!!!!!!!!!!!!! Will follow-up and see what was actually clipped and why, but this is a start - hopefully the new state-wide parcel layer (https://github.com/openaddresses/openaddresses/issues/2185 ) surrounds this and makes it a complete area, or Pierce County data ( https://github.com/openaddresses/openaddresses/issues/2174 )
