### ISSUE TITLE
Add addresses in Yakima, WA

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1949]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
https://gis.yakimawa.gov/arcgis101/rest/services/Assessor/AssessorParcels/MapServer/0

data is updated nightly
