### ISSUE TITLE
Add addresses in Bend, OR

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1950]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by davidchiles** [comment]
Data for Deschutes County, Oregon appears to be split up in two locations. The [Taxlots](http://data.deschutes.org/datasets/28019431cced49849cb4b1793b075bf1_2) contains the geometry and the [Mailing Addresses Table](http://data.deschutes.org/datasets/b4876b2c240946db893a6956daf20302_4) contains the address.

>This table has a one to one relationship with taxlots.

**Comment by nvkelso** [comment]
Will likely made redundant with https://github.com/openaddresses/openaddresses/issues/2148.

**Comment by iandees** [comment]
Closed by https://github.com/openaddresses/openaddresses/pull/2064
