### ISSUE TITLE
Add addresses in Roseburg, OR

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1951]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by nvkelso** [comment]
Douglas county isn't included in state-wide Oregon data in #2148, this issue is still relevant.

**Comment by justinelliotmeyers** [comment]
Ricky Hoffman	City Planner	541-863-3171	rjhoffma@co.douglas.or.us

he is sending form to sign tomorrow

**Comment by justinelliotmeyers** [comment]
Justin,
 
I have attached the data request form to this email. Fill it out and I will get you as much of the information that I can. The fee for the dataset is $20. (We can take a check in the mail or a payment over the phone). Thanks
 
Respectfully,
 
 
 
Richard J. Hoffman
Planner III and GIS Specialist
Douglas County Planning Department
1036 S.E. Douglas Avenue
Douglas County Courthouse - Justice Building - Room 106
Roseburg, OR   97470
[DCGISDataRequest.pdf](https://github.com/openaddresses/openaddresses/files/730272/DCGISDataRequest.pdf)

**Comment by nvkelso** [comment]
Payment and form sent via snail mail.

**Comment by nvkelso** [comment]
Received at a via FTP today – looks like 55,000 addresses! Data table looks clean.

This fills one of the last big gaps in Oregon along the I-5 corridor around Roseburg :)

- https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/nvkelso/f56dce/douglas-co-oregon-address-points.zip

<img width="813" alt="screen shot 2017-03-10 at 15 28 44" src="https://cloud.githubusercontent.com/assets/853051/23817254/8da4b75e-05a6-11e7-87fe-055ba3da4763.png">

<img width="1425" alt="screen shot 2017-03-10 at 15 27 55" src="https://cloud.githubusercontent.com/assets/853051/23817255/8db7b7be-05a6-11e7-8072-a6e1a048edfd.png">
