### ISSUE TITLE
Add addresses in Salem, OR

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1952]
Status:

- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by nvkelso** [comment]
Seems like the Marion County datasource might not have included Salem proper? @justinelliotmeyers can you take a look, please?

**Comment by justinelliotmeyers** [comment]
@nvkelso http://gis.co.marion.or.us/gisdownload/disclaimer.aspx

do those terms look okay? if so, they have parcels on next page after accept - dl'ing now to see if addresses are in there

**Comment by justinelliotmeyers** [comment]
Phone call w Marion County gis - if we want to cover all of Salem (*5 county service area she believed) we need to contact salem. Salem is responsible for the address points. Marions data is for Taxlots.

**Comment by justinelliotmeyers** [comment]
Beth Tanner
GIS Analyst 1

Email:
BTanner@co.marion.or.us

Phone:
(503) 576-7134

**Comment by justinelliotmeyers** [comment]
Since this is for Marion - I believe we can leave closed; Salem covers more than Marion county and has ticket: https://github.com/openaddresses/openaddresses/issues/1954

All we need to do is strike out terms in agreement and see if they give us the green light.

**Comment by nvkelso** [comment]
Related: https://github.com/openaddresses/openaddresses/issues/2494
