### ISSUE TITLE
Add addresses in Tillamook, OR

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1953]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
emailed gis@co.tillamook.or.us  on 11/8/2016

**Comment by justinelliotmeyers** [comment]
Hi Justin,
The county 911 system is the originator of address points.  I’ve cc’d the 911 director and LCOG.  You should contact them to get data for your program.
 
Wendy Schink
GIS Analyst
Tillamook County
201 Laurel Ave.
Tillamook, OR 97141
503-842-3400

**Comment by justinelliotmeyers** [comment]
followed up with 	
kmassie@lcog.org,
dkettner@tillamook911.com

**Comment by nvkelso** [comment]
Will likely made redundant with https://github.com/openaddresses/openaddresses/issues/2148.

**Comment by nvkelso** [comment]
Ooops, Justin says Tillamook isn't included in the state-wide dataset. This issue is still relevant.

**Comment by nvkelso** [comment]
@justinelliotmeyers Can you ping Tillamook County again, please?

**Comment by justinelliotmeyers** [comment]
yessir

**Comment by justinelliotmeyers** [comment]
called and left a voicemail - (http://www.co.tillamook.or.us/gov/gis/contact.htm)
GIS Page here: http://www.co.tillamook.or.us/gov/gis/dataaccess.htm
license for usage: http://www.co.tillamook.or.us/gov/gis/Documents/TCGIS_DATA_LICENSE_v1.5.pdf
prices here: http://www.co.tillamook.or.us/gov/gis/Prices.htm

**Comment by nvkelso** [comment]
What's not to love about ` $ 0.05 per polygon, or $ 0.10 per arc whichever is appropriate, plus preparation and media costs.` I'll hazard 50,000 records is >$1,000 cost.

**Comment by justinelliotmeyers** [comment]
wendy called back and told me to reach out to lcog e911 for addresses:
http://www.lcog.org/585/Regional-Land-Information-Database-RLID
Keith Massie  
Geographic Information Systems & Data Services
Title: Regional Address Coordinator
Phone: 541-682-4652 

calling now

**Comment by justinelliotmeyers** [comment]
and here she is:
From: GeodatabaseServer@lcog.org [mailto:GeodatabaseServer@lcog.org] 
Sent: Monday, February 20, 2017 10:05 PM
Subject: GIS Data Available from LCOG
 
A new GIS data deliverable is now available for download.

ftp://ftp.lcog.org//lcog/Outgoing/TillamookECD/Tillamook_Deliverable_2017_02_20.zip
Datasets (ordered by most recent change date)

Dataset Name
Last Change Date
Road_Centerline
2017-02-08 12:04:49
Streets
2017-02-08 12:04:49
Address
2017-02-08 10:09:20
Address_Point
2017-02-08 10:09:20
Alternate_Name
None
City
None
EMS
None
EMS_ARA
None
ESN
None
Fire
None
Fire_ARA
None
Police
None
Police_ARA
None

**Comment by justinelliotmeyers** [comment]
Mr. Massie also wished us luck with our project ;)

**Comment by nvkelso** [comment]
All's well that ends well :)
