### ISSUE TITLE
Add addresses in Twin Falls, ID

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1955]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
contacted planning and zoning: pandz@co.twin-falls.id.us 11/7/2016

**Comment by justinelliotmeyers** [comment]
contacted assesor: tfcassessor@co.twin-falls.id.us 11/7/2016

**Comment by justinelliotmeyers** [comment]
planning and zoning response: Justin,
Our office does not have address data, You may want to contact SIRCOMM (Southern Idaho Regional Communications Center) in Jerome County.  I think they may have that.  
Sorry I couldn't help.
Paula

called JOHN MOORE
SIRCOMM DIRECTOR
(208) 324-1344
john@sircomm.com

they have no gis or address data.

**Comment by justinelliotmeyers** [comment]
may be able to scrape data from these? 
https://tax.idaho.gov/gis/parcelmaps.cfm

**Comment by nvkelso** [comment]
@iandees what do we usually do with parcel polygons? There's good state-wide parcel data via that portal.

Looks like each parcel has a Site Address (eg: `Site Address: 1208 HIGHLAND LANE`), but parcels centroids are a bit sad / confusing when overlayed on their road network. 

<img width="1223" alt="screen shot 2016-11-07 at 10 11 40" src="https://cloud.githubusercontent.com/assets/853051/20069803/e755962c-a4d2-11e6-9d9e-799461459666.png">

**Comment by iandees** [comment]
Most of the data on http://data.idahoparcels.us/ is stuck in a Google Earth server that isn't easily scrape-able.

**Comment by nvkelso** [comment]
@justinelliotmeyers you want to try to scrape just this chunk of Idaho from that Google Earth server?

**Comment by nvkelso** [comment]
Still a hole.

**Comment by justinelliotmeyers** [comment]
Steve Root
GIS Technician
Twin Falls County, ID
Assessor Dept.
(208) 736-4156

he is emailing me terms/ pricing

*Robin Wilson from city will follow-up with her boss on Thursday to see if city can give us their data
208-736-2274

**Comment by justinelliotmeyers** [comment]
county has 42k parcels - he told me they don't maintain address in data, but lady from city said county does... so yeah...!?!

**Comment by justinelliotmeyers** [comment]
I’ve attached the procedure and options related to our GIS data. As far as addresses, properties with homes/building have addresses. Those such as farm ground, State/Federal Lands do not. I would estimate that 90 % of our parcels have addresses. If you have further questions, feel free to contact me. Have a great day.
 
Steve Root
GIS Technician
Twin Falls County, ID
Assessor Dept.
(208) 736-4156

[GIS Disclaimer (Revised 09-06-2016).pdf](https://github.com/openaddresses/openaddresses/files/732636/GIS.Disclaimer.Revised.09-06-2016.pdf)
[GIS Procedure & Options.pdf](https://github.com/openaddresses/openaddresses/files/732641/GIS.Procedure.Options.pdf)

**Comment by nvkelso** [comment]
Looks like $350 fee, but their license agreement prohibits redistribution unless we get written permission (in addition to signing their generic form).

**Comment by migurski** [comment]
I would be interested to see whether our case for the benefits of open data outweighs the case for distribution fees. $350 is not a ton, maybe they’d be happy to have someone like OA redistribute?

**Comment by nvkelso** [comment]
That sounds like a multi-month discussion that can happen in parallel to
paying the fee and getting the data?

**Comment by ingalls** [comment]
Closing paid source tickets
