### ISSUE TITLE
Add addresses in Coos Bay, OR

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1956]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
map here: http://coosmap.co.coos.or.us/cooscountymap/ but dont think we can get at the data...

**Comment by justinelliotmeyers** [comment]
emailed:
Laurie Burke,
Cadastral Cartographer
Team Leader

541-396-7906
lburke@co.coos.or.us

**Comment by iandees** [comment]
Yea, that map system is not familiar to me.

**Comment by nvkelso** [comment]
Will likely made redundant with https://github.com/openaddresses/openaddresses/issues/2148.

**Comment by nvkelso** [comment]
Yes, Coos is included in #2148, closing this one.
