### ISSUE TITLE
Add addresses in Elko, NV

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1958]
Status:

- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by iandees** [comment]
Here's an ESRI endpoint: http://gis.elkocountynv.net:1402/arcgis/rest/services/Basemap/AddressPoints/MapServer/0?f=json

**Comment by nvkelso** [comment]
West Wendover, NV is included in Elko County, but Wendover UT is in a different state.
