### ISSUE TITLE
Add addresses in Flagstaff, AZ

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1959]
Status:
- [x] **Research sources** and propose best source (and it's data license)
- [x] **Review proposed source**
- [x] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
Found Data here: http://data.flagstaff.opendata.arcgis.com/datasets/2fb5c93fdef94c59a79e12a06b35e796_0 - unsure of license.  So I reached out to them here: http://www.flagstaff.az.gov/directory.aspx?EID=782 and asked for the most current data and an official letter for approval.  Sent 09/27/2016

**Comment by justinelliotmeyers** [comment]
@iandees data is here: http://data.flagstaff.opendata.arcgis.com/datasets/2fb5c93fdef94c59a79e12a06b35e796_0

Was told to "use the data" for the project.  I do not see anything about a license - so maybe just note that.

Margaret Neff <MNeff@flagstaffaz.gov>
to me 
Please go ahead! It’s open data!

**Comment by nvkelso** [comment]
Related: https://github.com/openaddresses/openaddresses/issues/2209 for the county area around Flagstaff.
