### ISSUE TITLE
Add addresses in Wendover, NV

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1960]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
map here: http://gis.elkocountynv.net:1402/elkogisweb.html
address points here: http://gis.elkocountynv.net:1402/arcgis/rest/services/Basemap/AddressPoints/MapServer/0?f=json

@migurski  - can you make magic happen!?!?  Thanks!

**Comment by iandees** [comment]
We already have the [Elko, NV data source](https://github.com/openaddresses/openaddresses/blob/master/sources/us/nv/elko.json).

But the title of this ticket is for Wendover, NV, which I think is actually a tiny little town in Utah. Is that what you had in mind, @nvkelso?

**Comment by justinelliotmeyers** [comment]
**Good thing you noticed this!  Utah has Statewide Parcels... *I think!?!  Tooele County is here: ftp://ftp.agrc.utah.gov/UtahSGID_Vector/UTM12_NAD83/CADASTRE/UnpackagedData/Parcels_Tooele/Parcels_Tooele_shp.zip 
![tooele_county](https://cloud.githubusercontent.com/assets/5324316/20103113/a4ae7bee-a596-11e6-92d9-501a7bf6828e.jpg)

**8372/27930 have a null value for the address

Parent DIR has other counties parcel datasets if we are missing anything else in Utah - or I can do a statewide check later if you think it is of any value?  Let me know.  Thanks!  Parent DIR here: ftp://ftp.agrc.utah.gov/UtahSGID_Vector/UTM12_NAD83/CADASTRE/UnpackagedData/

**Comment by nvkelso** [comment]
Agree it's covered elsewhere.

Panning around the Utah map on openaddresses.io I'm not seeing any other large gaps. So let's move onto other states.
