### ISSUE TITLE
Add addresses in Page, AZ

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1961]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
emailed Robin Crowther
Planning and Zoning Director
Phone: (928) 645-4210
Fax: (928) 645-4250
rcrowther@cityofpage.org

**Comment by justinelliotmeyers** [comment]
they do not have the data; told me to reach out to Coconino County - which has data here: http://data-coconinocounty.opendata.arcgis.com/datasets/76ca136c49db437aa624ab8f05d493bd_0

**Comment by justinelliotmeyers** [comment]
it isnt in that dataset
called them and they have it, will call me back; they dont know why it isn't in the dataset, but will get back to me.

**Comment by justinelliotmeyers** [comment]
its in there, i was looking at wrong field...

**Comment by justinelliotmeyers** [comment]
use about resource or here: https://utility.arcgis.com/usrsvcs/servers/76ca136c49db437aa624ab8f05d493bd/rest/services/OpenData/CoconinoCountyOpenData/FeatureServer/0

**Comment by nvkelso** [comment]
I see the data on the map now, closing.

<img width="416" alt="screen shot 2017-07-25 at 20 35 51" src="https://user-images.githubusercontent.com/853051/28603440-e6e42546-7178-11e7-9ccb-caeedf11ff48.png">
