### ISSUE TITLE
Add addresses in Winnemucca, NV

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1962]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
contacts listed:http://winnemuccacity.org/Contacts.cfm

emailed: 
D. Stephen West .... City Manager/Engineer ............. wmcadsw@winnemuccacity.org
Roger Sutton ............ Public Works Supervisor ........ wmcards@winnemuccacity.org

**Comment by justinelliotmeyers** [comment]
Justin,
We have no GIS department but we have a City utility master map that is maintained by the Humboldt County Assessor's office on ARCGIS. The locations of our utility facilities shown on the map have not been surveyed, however.
Steve

**Comment by justinelliotmeyers** [comment]
so that leads us back to here: https://github.com/openaddresses/openaddresses/issues/2449

**Comment by nvkelso** [comment]
K, let's close this one.
