### ISSUE TITLE
Add addresses in Roswell, NM

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1963]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
http://chavesnm.mygisonline.com/?pin=

**Comment by nvkelso** [comment]
A Sidwell joint.

**Comment by justinelliotmeyers** [comment]
KILLING AND UPDATING NEW ISSUE! https://github.com/openaddresses/openaddresses/issues/5014
