### ISSUE TITLE
Add addresses in Santa Fe, NM

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1964]
Status:
- [x] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by slibby** [comment]
potential: http://services3.arcgis.com/OrtlXpzQGtgBGqsz/ArcGIS/rest/services/Proposed_Zoning/FeatureServer/0

**Comment by justinelliotmeyers** [comment]
SIgned up on their cities official request page (http://crm.santafenm.gov/constituent/) sent official request through this portal as well as e-mailing their gis department (09/27/2016)

**Comment by justinelliotmeyers** [comment]
following up today:
lisa martinez
land use director
5059556617

**Comment by justinelliotmeyers** [comment]
literally bounced around all week - called about ten times...  *new contact - http://www.santafenm.gov/staff_directory/detail/323
LEONARD PADILLA

GIS Project Coordinator
Information Technology and Telecommunications
GIS - Geographical Information Systems
(505) 955-6616

**Comment by justinelliotmeyers** [comment]
**Leonard Padilla - Super helpful - sending the data and terms.  Also sending me the person who is the head of the statewide user group - then if we need anyone elses contact information in the state, we will have it.  We may even be able to obtain a statewide address dataset.  will copy entire email once he sends the data and upload data.

**Comment by justinelliotmeyers** [comment]
https://www.dropbox.com/sh/s07nzmqv49pwlgh/AACEpl49RLO5RHKsvQh73TRGa?dl=0

**Comment by justinelliotmeyers** [comment]
I had to call him back and remind him to send the data...  Thats how my week is going to end!?!  As per the terms - he said no restrictions - but there is a disclaimer attached.  Let me know if anyone has questions.  Thanks!

**Comment by iandees** [comment]
This is great, @justinelliotmeyers! The disclaimer looks like a standard limitation of liability and the address points data looks pretty useful to me.
