### ISSUE TITLE
Add addresses in Mobile, AL

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1966]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
tons of data here: http://maps.cityofmobile.org/GIS/gisdata_download.aspx but no parcels or addresses.  Emailed: gis@cityofmobile.org 11/7/2016

**Comment by justinelliotmeyers** [comment]
http://maps.cityofmobile.org/arcgis/rest/services/AddressPnt_MS/MapServer/0
