### ISSUE TITLE
Add addresses in Auburn, AL

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1967]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
@iandees you think this will work?  http://gis.auburnalabama.org/public/rest/services/Main/COABasemap/MapServer/2

It says "There are no markers for the address point location, although the label text that displays is the approximate location of the address point" for every address point layer in their Mapserver...  or should we try to use the parcels themselves?
