### ISSUE TITLE
Add addresses in Birmingham, AL

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1968]
Status:
- [x] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
Sent e-mail requesting data (09/27/2016)

**Comment by justinelliotmeyers** [comment]
We have data for Jackson County - can close this issue

**Comment by iandees** [comment]
I don't see it in the Alabama folder: https://github.com/openaddresses/openaddresses/tree/master/sources/us/al

**Comment by justinelliotmeyers** [comment]
**Sorry, I'm a idiot - if it in Jefferson County.  https://github.com/openaddresses/openaddresses/commit/fb890d04cd8efca86dd02d70b63fd4c957f72619

**Comment by justinelliotmeyers** [comment]
Birmingham is in Jefferson County.

**Comment by iandees** [comment]
Wahoo!
