### ISSUE TITLE
Add addresses in Augusta, GA

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1969]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by davidchiles** [comment]
Source: http://gismap.augustaga.gov/arcgis/rest/services/Map_LayersJS/MapServer/73

**Comment by justinelliotmeyers** [comment]
@davidchiles thanks for the source!  looks good amigo!  
![augusta_ga_address_points_11_3_2016](https://cloud.githubusercontent.com/assets/5324316/19991148/94db23ce-a209-11e6-94d0-6ff7d0956a7f.jpg)
