### ISSUE TITLE
Add addresses in Athens, GA

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1971]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by iandees** [comment]
Athens uses [a system from Beacon Schneider](https://qpublic.schneidercorp.com/Application.aspx?AppID=630&LayerID=11199&PageTypeID=1) that sits on top of Esri services. So far I don't think anyone has figured out how to get to the juicy data below the Beacon Schneider shell.

**Comment by nvkelso** [comment]
@justinelliotmeyers Want to take a crack at scraping this data?

**Comment by justinelliotmeyers** [comment]
I have tried to crack the code for the beacon jive... just like the geocortex...  Let me see if I can come up with something else.

**Comment by nvkelso** [comment]
Still a hole.
