### ISSUE TITLE
Add addresses in Spartanburg, SC

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1972]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
there is data here:http://www.spartanburgcounty.org/185/Geographic-Information-Systems

but I think is in tiles or some fancy locked up version of an interactive rest service I haven't seen

**Comment by nvkelso** [comment]
@justinelliotmeyers Can you contact someone there asking for the raw data, please?

**Comment by justinelliotmeyers** [comment]
sent email:rbrown@spartanburgcounty.org
04/11/2017

**Comment by justinelliotmeyers** [comment]
County Parcels:https://services7.arcgis.com/deoj2Y8l1tBr7P5X/ArcGIS/rest/services/LauderdaleService/FeatureServer/4

**Comment by trescube** [comment]
I found Spartansburg parcels here last week:  http://arcgis4.roktech.net/arcgis/rest/services/Spartanburg/ROKMAPS/MapServer/10

Fixed in #2823

**Comment by justinelliotmeyers** [comment]
Do you think the county layer would be better than the resource you found @trescube ? should we change the name of the issue to Lauderdale County ? Thanks!

**Comment by trescube** [comment]
Isn't Lauderdale County in Mississippi?

**Comment by trescube** [comment]
I'm not sure how the issue changed from Spartanburg, SC to Lauderdale County, MS.

**Comment by justinelliotmeyers** [comment]
oops - I was working on https://github.com/openaddresses/openaddresses/issues/2023#event-1034640936

**Comment by trescube** [comment]
K, I'm going to close this issue then!

**Comment by justinelliotmeyers** [comment]
thanks! sorry!
