### ISSUE TITLE
Add addresses in Kitty Hawk, NC (outer banks)

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1974]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by iandees** [comment]
Part of Dare County, NC.

They use Geoserver: http://gis.darecountync.gov/

**Comment by nvkelso** [comment]
Still a hole.

**Comment by justinelliotmeyers** [comment]
geoserver here: http://gig.darecountync.gov/geoserver

but dont think they have addresses/ parcels

have pins and lots however

**Comment by justinelliotmeyers** [comment]
e-mailed Ryan Taylor (http://www.darenc.org/public/gis.asp )

**Comment by nvkelso** [comment]
There’s a SHP download option there, but it’s fairly janky data – only
house numbers (no street name or city), and looks to be CAD derived instead
of GIS. Also incomplete. We should reach out to them and see if they have
better data around (there’s a “original_fid” on the lot address records,
this looks to be derived data and maybe the original is better).

**Comment by justinelliotmeyers** [comment]
e-mail sent (CCed @trescube @nvkelso @mapbox)

**Comment by nvkelso** [comment]
@justinelliotmeyers can you  pick this one back up, please?

**Comment by nvkelso** [comment]
I see data here now, closing.

<img width="576" alt="screen shot 2017-07-25 at 20 27 58" src="https://user-images.githubusercontent.com/853051/28603229-cda82f74-7177-11e7-8f6c-e7657a59ebb5.png">
