### ISSUE TITLE
Add addresses in Winston-Salem, NC

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1975]
Status:
- [x] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
Parcel data and other gis data here: http://www.cityofws.org/departments/planning/gis/gis-data-sets-for-download.  License and restrictions look prohibitive.  I have e-mailed them to see if they would consider being part of the project and send us official data and written permission. E-mailed 09/27/2016

**Comment by justinelliotmeyers** [comment]
[WS_GIS data request, release, disclaimer and fees.pdf](https://github.com/openaddresses/openaddresses/files/564369/WS_GIS.data.request.release.disclaimer.and.fees.pdf)

Licensing looks restrictive - even if we purchased, would not be able to use (* No use for resale or commercial purposes*)

**Comment by justinelliotmeyers** [comment]
calling Forsyth County to see if they will give us data instead of city

**Comment by justinelliotmeyers** [comment]
Dave Toren
GIS Programmer
MapForsyth
Forsyth County

(336) 703-2329

said shouldn't be a problem to share data, but has to speak with Matthew Hamby, the City / County Addressing Coordinator.  If I do not hear from him tomorrow, he told me to call back and we will get it figured out.

**Comment by justinelliotmeyers** [comment]
We have received the data!! 189k records!! NAD_1983_StatePlane_North_Carolina_FIPS_3200_Feet

https://www.dropbox.com/s/ie1eo9k8gsk4l58/FCAddresses_1.zip?dl=0

**Comment by iandees** [comment]
Uploaded the data here:
https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/iandees/eb1e8e/FCAddresses_1.zip
