### ISSUE TITLE
Add addresses in Knoxville, TN

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1976]
Status:
- [x] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
Emailed both metro planning commission (http://www.knoxmpc.org/aboutmpc/contact.htm ) and cities gis dept (http://www.kgis.org/KGISMaps/Map.htm) 09/27/2016 - requesting data and permission

**Comment by justinelliotmeyers** [comment]
Keith Stump <kstump@kgis.org> replied this morning: 
Dear Justin,
 Thank you for your inquiry, but unfortunately we do not offer an open data option for  address data at this time. Best wishes on your project.
 Keith G. Stump,  GISP
 Executive Director / GIO
______________________
Knoxville, Knox County, KUB GIS (KGIS)
606 Main St, Suite 150
Knoxville, TN 37902
865.215.2641
www.kgis.org

I asked him if the city would consider changing its mind as numerous other cities around the world have open data at this time.  I also asked who I may speak to as per their city changing the policy.

**Comment by justinelliotmeyers** [comment]
I also reached out to the mayor's office to see if they would consider creating an open data portal: https://www.facebook.com/MayorBurchett/

**Comment by justinelliotmeyers** [comment]
Sent final follow-up to Mr. Gustin to see if we can get the data

Jon Gustin
Manager, E-Government Services
Knox County GIS Coordinator
Knox County Office of Information Technology
400 Main Street, L-114
Knoxville, TN 37902
Office: 865.215.4227
Cell: 865-254-0600

**Comment by justinelliotmeyers** [comment]
Knox County, Knoxville, and the utility board will not share the data at this time - I tried to explain open data would benefit everyone, but Mr. Gustin was not hearing it and there was a long silence on the phone with him.  Festive.

**Comment by justinelliotmeyers** [comment]
no data
