### ISSUE TITLE
Add addresses in York, PA

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1977]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by davidchiles** [comment]
I'm a bit unfamiliar with ESRI services so I don't know where to go from here.

This has the geometry: http://gis.york-county.org/yorkclient/proxy.ashx?http://pc61198svmh/ArcGIS/rest/services/York/ParcelPoly/MapServer/0/

This has the address string: http://gis.york-county.org/yorkclient/proxy.ashx?http://pc61198svmh/ArcGIS/rest/services/York/ParcelPoly/MapServer/1/

How can I combine them to use in a single json source for York County?

**Comment by justinelliotmeyers** [comment]
the above map server seems to be dead.  I emailed info@yorkcountypa.gov asking for the data (11/8/2016).
