### ISSUE TITLE
Add addresses in suburbs around Philadelphia, PA

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1979]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by davidchiles** [comment]
Looks like the two counties missing are Delaware and Montgomery Counties. 

This is as close as I can get to the data on Montgomery County: http://propertyrecords.montcopa.org/pt/arcgismaps/arcgismapadvanced.aspx

And I'm not sure what's going on in Delaware County: http://www.co.delaware.pa.us/planning/mapping/GISDataLayers.html

**Comment by justinelliotmeyers** [comment]
Deleware Co update - DelmutoJ@co.delaware.pa.us - There is a regional NG911 group that will be addressing this data so it’s possible it will happen sooner than later but no guarantee. 
I’ll keep you posted if anything changes.
-Julie

**Comment by justinelliotmeyers** [comment]
Montgomery reply:
Hi Justin,
 
You will need to speak with our IT Department. We do not have address points in shapefile as of this time, but it is something we are working towards. However, our address data is available through our IT Data Sales: http://www.montcopa.org/439/Data-Sales

Costs here: http://www.montcopa.org/DocumentCenter/View/2498

**Comment by nvkelso** [comment]
Well, $20k / year fee isn’t great.

But can you ask them if we have rights after that to use commercially and
to redistribute, please?

**Comment by nvkelso** [comment]
Still a hole.

**Comment by justinelliotmeyers** [comment]
followed up with Deleware Co update - DelmutoJ@co.delaware.pa.us

**Comment by justinelliotmeyers** [comment]
emailed boahelp@montcopa.org asking about TOU after purchase

**Comment by justinelliotmeyers** [comment]
no data
