### ISSUE TITLE
Add addresses in Durham, NC

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1980]
Status:
- [x] **Research sources** and propose best source (and it's data license)
- [x] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
wrote and requested data and permission (https://durhamnc.gov/1227/GIS-Services )09/27/2016.  I believe data can be downloaded from here: https://opendurham.nc.gov/explore/?q=address&sort=modified (**there are three different datasets (with different amounts of records)).  It appears all three have a ODBL license - not sure if we can have that for this project?  http://opendatacommons.org/licenses/odbl/

**Comment by justinelliotmeyers** [comment]
Email and data received - **No Mention of copyright - I e-mailed and asked as well as voicemail.  Will call again today.

Hi Justin,
 
Per your request I have placed the latest shapefile of the county-wide address points on our FTP site for you to download. Please follow the login credentials below to access this site:
 
Web browser entry: -
Username: -
Password: -
 
Please copy the contents of the folder to your hard drive or local network as soon as you can and let me know when you have successfully done so, so that I can remove the folder to free up the space in our ftp site for future customers.
 
If you have any problem downloading the data or using the file, please let me know.
 
Regards,
 
 
Jing N Huang
GIS Analyst II
Technology Solutions - GIS, City of Durham
101 City Hall Plaza, 4th Floor, Ste 4142
Durham, NC 27701-3329
 
P 919 560-4122, ext 33244
F 919 560-4808
 
Jing.Huang@durhamnc.gov
http://www.durhamnc.gov/departments/gis/

**Comment by justinelliotmeyers** [comment]
uploading data to dropbox and will update link

**Comment by justinelliotmeyers** [comment]
https://www.dropbox.com/sh/4pwm2iyb25tlbk1/AABLnuePkbhdURtA-zruuzA-a?dl=0

***I need to get a copyright response before I can say use this data

**Comment by justinelliotmeyers** [comment]
Called Mr. Huang for past three days and left voicemails and e-mails.  No response.  Called the GIS Manager ( Marcus Bryant) and he was not in office either.  Left him a voice mail.  I will continue to follow-up until I understand what metadata/ terms/ copyright on shapefile is.

**Comment by justinelliotmeyers** [comment]
Marcus Bryant called me back - its open - use for whatever you want!  He told me we cannot receive in writing and told me to follow their terms here: http://opendurham.nc.gov/terms/terms-of-use/

**Comment by nvkelso** [comment]
@iandees A curious set of mixed messages in the src data license (local gov't says use it for anything, but it's technically released under an ODbL). 

What's OpenAddresses approach to ODbL sources? Are there other ODbL datasets included already?

**Comment by nvkelso** [comment]
Looks like there are a handful of other ODbL datasets included:

- https://github.com/openaddresses/openaddresses/search?utf8=%E2%9C%93&q=odbl

**Comment by iandees** [comment]
Yep, we have a couple ODbL sources. They should only be included in the share-alike output of OpenAddresses.

It does appear that the Durham folks are confused about what ODbL means, or maybe the dataset they gave via FTP is different than the one on the opendurham portal?

**Comment by justinelliotmeyers** [comment]
I think the open data concept is new to some people. When I spoke with Mr. Bryant - he said that this is a new concept to the people there and they put the cart before the horse; literally called the open data movement and the direction of all things tech the Wild West!  But I asked him about the terms of use and he said there were none.  I pointed out that their site has two different sets of terms and they conflict.  He said the new open data portals terms are the most current and to use those as the terms; as they have yet to update anything on their sites end.  I believe the data I received from Mr. Huang is the most current dataset - but if we want to use points from the open portal instead that is up to who does the import (*then the actual license is right there - as Nate noticed it is ODBL for all three address points datasets) http://opendurham.nc.gov/explore/?sort=modified&q=address then click information.  Sorry, its a bit long winded, but just want to make sure we know terms and source of data.

**Comment by migurski** [comment]
As long as we mark the right "attribution required" and "share-alike" flags in the OA source information, the data will be handled appropriately in our system.

**Comment by justinelliotmeyers** [comment]
@nvkelso can we close this issue?  Thanks!

**Comment by iandees** [comment]
I can still add the data here. I'll close it with the pull request in a minute.
