### ISSUE TITLE
Add addresses in Sault Sainte Marie, MI

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1983]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
calling: 

1118 East Easterday Avenue, Sault Ste. Marie, Michigan 49783
Phone: (906) 635-1581
Fax: (906) 635 9582
Email: agency@eup-planning.org

**Comment by justinelliotmeyers** [comment]
http://www.saultcity.com/gis
engineering dept (gis)
has a fee:$250 
leo miller (joe)
906-632-5732

he is OOO and will be back tomorrow.

**Comment by justinelliotmeyers** [comment]
@nvkelso can you follow-up on this?

**Comment by nvkelso** [comment]
Email sent.

**Comment by justinelliotmeyers** [comment]
thank you!

**Comment by nvkelso** [comment]
Sadly they don't allow commercial / redistribution even after the $250 fee is paid (plus another $300 for address points). No plans to open up the data. (This from further emails with Joe Miller.)

```
If you are interested in purchasing our parcel dataset we would send you an invoice for $250 dollars  for the base set and $300 dollars if you need additional information such as address points or zoning included.    Normally I send our purchasers a dropbox link so that they can download the dataset once it is confirmed that we have received payment.    If you are interested I would need your billing address so that we can send you an invoice to get the process started.  
 ```

and

```
Unfortunately to answer your question, we do have a restriction on distribution and commercial use on our parcel dataset.
```

**Comment by justinelliotmeyers** [comment]
no data
