### ISSUE TITLE
Add addresses in Kokomo, IN

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1984]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
They list addresses as a dataset they have; http://www.cityofkokomo.org/departments/engineering_and_traffic/geographic_information_system_(gis).php

**Comment by justinelliotmeyers** [comment]
http://foster2.cityofkokomo.org/Address.kml
http://foster2.cityofkokomo.org/AddressPoint.kml
http://foster2.cityofkokomo.org/AddressPoint.kmz

**Comment by trescube** [comment]
There are no street names that I could find.  There are house numbers, though (I think).

**Comment by justinelliotmeyers** [comment]
coming in an e-mail now amigo ;)

**Comment by justinelliotmeyers** [comment]
https://www.dropbox.com/s/v241xwltc0udpgj/AddressPoints.zip?dl=0

**Comment by justinelliotmeyers** [comment]
Thanks:
Jesse h Johnson
System Project Designer
for City of Kokomo Engineering Dept.
765-456-7411
765-456-7400

**Comment by nvkelso** [comment]
I see this data on the map now, closing.

<img width="528" alt="screen shot 2017-07-25 at 20 37 17" src="https://user-images.githubusercontent.com/853051/28603465-18469588-7179-11e7-829c-9845b0daaecd.png">
