### ISSUE TITLE
Add addresses in Lansing, MI

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1985]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by nvkelso** [comment]
Michigan data is hard / expensive.

**Comment by nvkelso** [comment]
This is looking like a bigger hole now.

**Comment by justinelliotmeyers** [comment]
Just called. They have the data, but can't share. They don't know why they can't share but they have the data.

**Comment by justinelliotmeyers** [comment]
Sharon, the assessor, is out until tomorrow. She may be more help than the person I spoke with

**Comment by justinelliotmeyers** [comment]
Emailed Ingham County: http://ingham-equalization.rsgis.msu.edu/

**Comment by justinelliotmeyers** [comment]
Clinton County pricing: https://www.clinton-county.org/DocumentCenter/View/776
they have an interactive map here:https://app.fetchgis.com/clinton but it's locked up in the fetch gis.

**Comment by justinelliotmeyers** [comment]
will call sharon today to follow-up

**Comment by nvkelso** [comment]
@justinelliotmeyers can you confirm these prices (and that they include full GIS shapefile  /GeoDB data of parcel polygons &/or address points), please?

**Parcel Layer per County**
- `$5,000` (in-county)
- `$5,600` (out-county)

They seem prohibitively expensive, but this is the state of expensive GIS data...

**Comment by justinelliotmeyers** [comment]
called:
Name: Erin Wyrick 
Title: GIS Coordinator 
Phone: 989 224-5119 
Email: gis@clinton-county.org

left a voicemail

**Comment by justinelliotmeyers** [comment]
Erin called back:
they have an address point dataset, but it is new, and they never released it. I asked, and they may, but she has to ask her superiors. Fingers crossed!

otherwise parcel data is $5600 - 32-36k parcels

**Comment by justinelliotmeyers** [comment]
if it were purchased, it is considered ours and we can use/ resell I was told...

**Comment by justinelliotmeyers** [comment]
sent follow-up email to Erin

**Comment by justinelliotmeyers** [comment]
email follow-up sent to assessor@lansingmi.gov

**Comment by justinelliotmeyers** [comment]
voicemail...
Please contact Sam Quon in Information Technology. Ph:  517-483-4310
 
Sharon Frischman, MMAO
City Assessor
Direct 517 483 4136

**Comment by justinelliotmeyers** [comment]
Justin,
 
The parcel layer cost is $5600.  We are not selling the point data at this time.  The parcel layer does not have lat/long, but does have house number and street name…
 
Thanks,
Erin Wyrick
GIS Coordinator
Clinton County
100 East State Street G200
St. Johns, MI  48879 (USA)
Phone: (989) 224-5119 Fax (989) 224-5102
E-mail to: GIS@clinton-county.org

**Comment by justinelliotmeyers** [comment]
I asked if I file a FOIA for the address points if she thought we would receive them. and she said go for it. So I plan on jumping through that hoop today ;)

**Comment by justinelliotmeyers** [comment]
@ingalls as per the issue with Ingham, I have been poking around the county. Found this page: https://lansingmi.gov/1490/Street-Conditions

Which lands you here: 
https://services1.arcgis.com/pNPbgWy7hpfFGWoZ/ArcGIS/rest/services

There are several parcel datasets. Pulling some in to see quality/ coverage. Stay tuned!!

**Comment by justinelliotmeyers** [comment]
1)Lets close https://github.com/openaddresses/openaddresses/issues/4918
2)Lets use the full Ingham county dataset here: https://services1.arcgis.com/pNPbgWy7hpfFGWoZ/ArcGIS/rest/services/Tax_Parcel/FeatureServer/0

**Comment by justinelliotmeyers** [comment]
![lansing](https://user-images.githubusercontent.com/5324316/79456791-1d93e680-7fbd-11ea-9f05-89ac9b8d191d.png)
