### ISSUE TITLE
Add addresses in Kalamzoo, MI

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1986]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by nvkelso** [comment]
Michigan data is hard / expensive.

**Comment by justinelliotmeyers** [comment]
I think this may exist somewhere else in the issues?

**Comment by justinelliotmeyers** [comment]
https://github.com/openaddresses/openaddresses/issues/2378

**Comment by nvkelso** [comment]
Agree, closing this one in favor of #2378.
