### ISSUE TITLE
Add addresses in suburbs north of NYC (White Plains), NY

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1987]
Status:

- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by slibby** [comment]
Covered by NY Statewide, right?

Anyways, there is a service for Westchester County: http://giswww.westchestergov.com/arcgis/rest/services/MappingWestchesterCounty_AdditionalLayers/MapServer/78

**Comment by nvkelso** [comment]
How does the statewide source get infested? I don't see address dots on the map, is there an import error?

**Comment by pblack-trulia** [comment]
westchester parcel shapefile with address http://giswww.westchestergov.com/download/wcparcels.zip

**Comment by slibby** [comment]
@nvkelso looks like the "statewide" is missing Westchester and other areas. no idea of the why/background but then it's worth a dedicated src.

**Comment by trescube** [comment]
Westchester added in https://github.com/openaddresses/openaddresses/pull/2043

**Comment by nvkelso** [comment]
@trescube nice! ready to close? What's the convention around here? Are builds continuous, when will the map update?

**Comment by iandees** [comment]
Builds are continuous: the "hooked" build step on #2043 will have information about caching/transformation status. The screenshot that @trescube added there came from data downloaded from the hooked build step.

After a source is merged, a single download run for all sources is performed at least once a week, followed by a dot-map build that is run roughly once a week. You can see when these runs happen in the #machine channel on Slack. @migurski please correct me if these time gradients are wrong.

**Comment by nvkelso** [comment]
:+1:
