### ISSUE TITLE
Add addresses in Flint, MI

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1988]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
emailed Planner II- Kevin Schronce, kschronce@cityofflint.com 11/4/2016

**Comment by justinelliotmeyers** [comment]
http://services3.arcgis.com/blE8NdGZSd9Sfngv/arcgis/rest/services/genParcels/FeatureServer/0

but a token is required?

**Comment by migurski** [comment]
Is there a web view of these? We have dealt with tokens before like this: https://github.com/openaddresses/openaddresses/pull/2079

**Comment by justinelliotmeyers** [comment]
Not sure where I found this last night, but this has their parcels: http://flint.maps.arcgis.com/apps/webappviewer/index.html?id=6b818d399713408f92dc897d80e283bd

**You are going to have to exaplin how you do this magic.

**Comment by dexterslu** [comment]
Here's the entirety of Genesee County's parcels, about 190k records: 
http://services2.arcgis.com/5ckbIY7K9TUKoseK/ArcGIS/rest/services/Parcels/FeatureServer/0
