### ISSUE TITLE
Add addresses in suburbs east of NYC on Long Island (Hempstead), NY

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1990]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by slibby** [comment]
The missing section is Nassau County.

They have a GIS Server but REST Services directory access is blocked. I was able to find one working Map Service here: https://gis.nassaucountyny.gov/arcgis/rest/services/Akanda/MapServer/

**Comment by iandees** [comment]
Looks like address info is available via a secondary, non-Esri endpoint here: https://lrv.nassaucountyny.gov/map/getparcellist.php?gpl=03%20209%2000040

**Comment by justinelliotmeyers** [comment]
this is one of the last three/ four counties that will be updated by the state wide address data here: http://gisservices.dhses.ny.gov/arcgis/rest/services/SAM_Address_Points/MapServer/1

**Comment by justinelliotmeyers** [comment]
@iandees although there is no data currently, can we close this issue or should we wait until the data is uploaded?  Thanks!

**Comment by iandees** [comment]
Let's keep it open for now.

**Comment by nvkelso** [comment]
Still a hole.

**Comment by nvkelso** [comment]
Closed by NY state update: https://github.com/openaddresses/openaddresses/pull/3204#event-1163036812.
