### ISSUE TITLE
Add addresses in Cape Gerardeau, MO

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1993]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
maps/ gone girl interactive map (*arcgis powered here) http://www.cityofcapegirardeau.org/CityHall-PLANNING/Geographic-Information-Systems-Maps.aspx

**Comment by justinelliotmeyers** [comment]
Boom! Found her: http://arcgis.cityofcapegirardeau.org:6080/arcgis/rest/services/Parcels_Only/MapServer/0
