### ISSUE TITLE
Add addresses in Lafeyette, IN

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1994]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
Parent County Addresses: http://gis2.tippecanoe.in.gov/arcgis/rest/services/AddressPoints/MapServer
