### ISSUE TITLE
Add addresses in St. Charles, MO

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1996]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by slibby** [comment]
Open REST Service: http://gis.sccmo.org/scc_gis/rest/services/open_data/AddressPoints/MapServer/0/

**Comment by nvkelso** [comment]
This isn't showing up on the dot map :\ 

@trescube can you investigate why your PR is having problems, please?

**Comment by nvkelso** [comment]
Continuing the investigation in https://github.com/openaddresses/openaddresses/issues/2406.
