### ISSUE TITLE
Add addresses in Amarillo, TX

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2001]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by nvkelso** [comment]
Still missing after statewide Texas data via https://github.com/openaddresses/openaddresses/issues/2179.

**Comment by justinelliotmeyers** [comment]
https://services6.arcgis.com/Vdk8uHgdgYx8ZqS6/ArcGIS/rest/services/AddressPointsArcGISOnline/FeatureServer

**Comment by justinelliotmeyers** [comment]
parent page: https://amarillo.maps.arcgis.com/home/index.html

**Comment by nvkelso** [comment]
Looks great!
