### ISSUE TITLE
Add addresses in Wichita, Kansas

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2002]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by nvkelso** [comment]
This is looking like a bigger hole now.

**Comment by justinelliotmeyers** [comment]
Is this closed now? or does https://github.com/openaddresses/openaddresses/pull/2423 resolve this? Thanks!

**Comment by nvkelso** [comment]
Yes: Looks like #2423 will resolve this, once it's merged.
