### ISSUE TITLE
Add addresses in Minot, ND

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2003]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
Ward County Parcels: http://54.213.14.253/arcgis/rest/services/Parcels/WCParcels/FeatureServer/0

**Comment by justinelliotmeyers** [comment]
The source I found above is different than what we have for parcels now (*I believe)

@nvkelso in our current OA data, we have covergae for Minot, ND in the us/nd/ward data - so maybe this can be closed as per existing coverage:http://results.openaddresses.io/sources/us/nd/ward
dense part is Minot
![ward](https://cloud.githubusercontent.com/assets/5324316/23507891/1b2d3b5e-ff1d-11e6-9ad2-61c530c29823.jpg)

**Comment by nvkelso** [comment]
Oh, we do have coverage already! Downgraded to priority 4, but since it seems different still marking it ready for PR.

**Comment by nvkelso** [comment]
I see data here now, closing.

<img width="490" alt="screen shot 2017-07-25 at 20 38 07" src="https://user-images.githubusercontent.com/853051/28603477-3c43a1ce-7179-11e7-9415-24915d3656bd.png">
