### ISSUE TITLE
Add addresses in Tulsa, OK

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2005]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
Tulsa data here: http://maps.cityoftulsa.org/gis/rest/services/Base/tca_parcel/MapServer/0
