### ISSUE TITLE
Add addresses in Salina, Kansas

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2006]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
maps here: http://www.salina-ks.gov/content/18394/18540/20881/default.aspx

but terms popup right away; not sure if it's okay that we use the data:
eventually leads you to http://70.167.136.51/arcgis/rest/services/ArcGIS_Online/MapServer/13

**Comment by iandees** [comment]
The terms look like a standard indemnity clause followed by a "don't sell this data". I think we're OK.

**Comment by justinelliotmeyers** [comment]
Thanks for looking that over ;)
