### ISSUE TITLE
Add addresses in Garland, TX

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2007]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by nvkelso** [comment]
Still missing after statewide Texas data via https://github.com/openaddresses/openaddresses/issues/2179.

**Comment by justinelliotmeyers** [comment]
https://services2.arcgis.com/g3rbttPStUJTjAz2/ArcGIS/rest/services/Base_Map/FeatureServer/1
