### ISSUE TITLE
Add addresses in Longview, TX

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2009]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by nvkelso** [comment]
Still missing after statewide Texas data via https://github.com/openaddresses/openaddresses/issues/2179.

Oddly the rural areas around there do have coverage now?

<img width="733" alt="screen shot 2016-12-13 at 14 33 22" src="https://cloud.githubusercontent.com/assets/853051/21162221/291a71d8-c141-11e6-828b-f6c7f464e14e.png">

**Comment by justinelliotmeyers** [comment]
open data portal! http://data-longviewtexas.opendata.arcgis.com/

Data here: https://cloud.longviewtexas.gov/arcgis/rest/services/OpenData/OpenData/MapServer/13

**Comment by nvkelso** [comment]
@justinelliotmeyers nice find! thanks for adjusting the labels, I've also removed you from assignee so it's clear someone else can pick up the issue to create the Pull Request now :)
