### ISSUE TITLE
Add addresses in Waco, TX

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2012]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
parcels: http://gis.ci.waco.tx.us/arcgis/rest/services/Parcels/MapServer/0
