### ISSUE TITLE
Add addresses in Nacogdoches, TX

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2018]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
http://co.nacogdoches.tx.us/maps/public_geodata_downloads/datasets/AddressPointsSHP.zip
Shapefile (File Size:1.34Mbs, Last Updated:11/04/2016)
Disclaimer:
By using this webpage you are confirming that you understand that all of the GIS data and resources avalable through this web-page are for informational purposes and may not have been prepared for or be suitable for legal, engineering, or surveying purposes. They do not represent an on-the-ground survey and represent only the approximate relative location of property boundaries. These datasets and resources are provided by the Nacogdoches County GIS & 911 Addressing Coordinator with the information available in the Nacogdoches County GIS & 911 Addressing databases. However, they are provided without guarantee of accuracy of data. They are not intended to imply property ownership. They are not intended to imply legal or contractual obligations in any respect; they are not an express or implied warranty.
