### ISSUE TITLE
Add addresses in Beaumont, TX

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2019]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
address: https://311webservreq.cityofbeaumont.com/map/rest/services/CRW/FeatureServer/0
parcel: https://311webservreq.cityofbeaumont.com/map/rest/services/CRW/MapServer/6

**Comment by justinelliotmeyers** [comment]
Disclaimer:

This web page is a public resource of general information. The City of Beaumont makes no warranty, representation, or guarantee as to the content, sequence, accuracy, timeliness, or completeness of any of the spatial data or database information provided herein. The City of Beaumont shall assume no liability for any errors, omissions, or inaccuracies in the information provided regardless of how caused; or any decision made, action taken, or not taken by any person relying on any information or data furnished within. These maps are not the official City of Beaumont maps. For official City maps, contact the City Clerk for a Public Information Request.

The City of Beaumont shall not be responsible for any decisions based up the use of this data. While this information is made available to the public, it was created for internal use, and while we make every attempt to keep it updated, we make no claim as to its accuracy or completeness. This data is not designed to be used as a primary tool in permitting, citing, or in other decisions based solely on this information.

Any problems with the data on this site, please email our GIS Coordinator.
