### ISSUE TITLE
Add addresses in Cody, WY

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2020]
Status:
- [x] **Research sources** and propose best source (and it's data license)
  - [x] City of Cody
  - [x] Surrounding county
- [x] **Review proposed source**
- [x] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by slibby** [comment]
Park County, WY has an old, old MapServer app available here: http://maps.greenwoodmap.com/park//
County Assessor contact: PMeyer@parkcounty.us

**Comment by justinelliotmeyers** [comment]
emailed: support@cityofcody.com 11/7/2016
also asked them on their facebook wall: https://www.facebook.com/cityofcody

**Comment by justinelliotmeyers** [comment]
https://www.dropbox.com/s/9uufp2oin9x8i0c/recodygisdatarequest01990.zip?dl=0
![cody_wy](https://cloud.githubusercontent.com/assets/5324316/20066368/52a5b310-a4df-11e6-933c-a3b77a50062a.jpg)

HOUSE_NUMB - house number
STREET_NAM - street name
Data from:
SCOTT KITCHEN | SYSTEM ADMINISTRATOR
(307) 527-3466 | skitchen@cityofcody.com
cityofcody-wy.gov | IT Support
1338 Rumsey Ave, Cody, WY 82414-3713

**Comment by nvkelso** [comment]
Looks like the Dropbox link is for Cody alone, and the MapServer link has similar data model but for entire county. 

@iandees What's order of operations? Add both?

**Comment by iandees** [comment]
@nvkelso we don't have a way to extract data from old mapservers like that. It's a good indication that the data would be retrievable by talking to them, though.

**Comment by nvkelso** [comment]
@justinelliotmeyers Can you also track down the county data, please?

**Comment by justinelliotmeyers** [comment]
e-mailed
Park County Assessor: Pat Meyer (PMeyer@parkcounty.us)
Park County Courthouse
1002 Sheridan Ave. Cody, WY 82414
Cody: (307) 527-8650, Powell: (307) 754-8650
Toll Free: 1 (800) 786-2844 ext 8650
Fax: (307) 527-8649

**Comment by nvkelso** [comment]
I think the city portion is ready for a PR, but the county part is outstanding.

**Comment by justinelliotmeyers** [comment]
I'll call the county tomorrow and see if we can get this wrapped up.

**Comment by justinelliotmeyers** [comment]
** @iandees you think you can grab this: http://utility.arcgis.com/usrsvcs/servers/ce42c8fc53844590a94d26124c0e39e2/rest/services/ets/ParcelsSecure/MapServer/0 ?

**Comment by justinelliotmeyers** [comment]
called and left a voicemail for:
Park County	GIS Coordinator	
Joy Gonion	
(307) 527-8658	
JGonion@parkcounty.us

**Comment by justinelliotmeyers** [comment]
@nvkelso  $150 for file (for Park County) (either address points or parcels) we just have to e-mail Joy (JGonion@parkcounty.us)

**Comment by nvkelso** [comment]
I've emailed her.

**Comment by nvkelso** [comment]
Filled out their PDF form and paid via credit card (address points only). Data files should be emailed to me soon.

**Comment by nvkelso** [comment]
Received the data, here's the column preview (only a generic street address column):

<img width="324" alt="screen shot 2016-11-29 at 09 06 32" src="https://cloud.githubusercontent.com/assets/853051/20720298/7aa4e544-b613-11e6-90de-9d23fd8133f7.png">

**Comment by nvkelso** [comment]
Uploaded using OpenAddresses.io S3 uploader:

- https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/nvkelso/5a5bf6/ParkCountyADDRESS_POINTS_point.zip
