### ISSUE TITLE
Add addresses in Alexandria, LA

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2021]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
http://www.rapc.info/GIS/GIS.aspx
emailed jamie@rapc.info

**Comment by justinelliotmeyers** [comment]
Justin,
 
Are you working with any specific government entity in the parish?   That’s about the only way I’m going to be able to give it out.   It is considered public record, technically.   So we do make that available online to view and we do offer assistance in office should you need anything.   Also, we don’t house parcels here.   You’ll want to get in touch with the Rapides Parish Tax Assessor @ www.rapidesassessor.org
 
Thanks,
 
 
Jamie Wallace
Rapides Area Planning Commission
GIS Administrator/Parish Mapping
Office: 318-487-5401 EXT-28
Fax:     318-487-5406
jamie@rapc.info
http://www.rapc.info

**Comment by justinelliotmeyers** [comment]
called Jamie - cannot give out shapefile data. They have a map you can view and that is all they will do at this point.

Will reach out to assessor's office.

**Comment by justinelliotmeyers** [comment]
found the data in the online mapserver here: http://gis.rapc.info/gis/rest/services/portal_rapc/Addresses/MapServer/0

**Comment by nvkelso** [comment]
"It is considered public record, technically." Sigh.
