### ISSUE TITLE
Add addresses in Lauderdale County, MS

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2023]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
email sent:
Hugh Smith
311 27th Ave
Meridian, MS 39301
601-485-1920 Fax 601-485-1864
hughsmith@meridianms.org

**Comment by justinelliotmeyers** [comment]
emailed hughsmith@meridianms.org
04/11/2017

**Comment by justinelliotmeyers** [comment]
Lauderdale GIS County Parcels:https://services7.arcgis.com/deoj2Y8l1tBr7P5X/ArcGIS/rest/services/LauderdaleService/FeatureServer/4

From here:http://tscmaps.com/cnty/lauderdale-ms/
