### ISSUE TITLE
Add addresses in Hattiesburg, MS

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2025]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by nvkelso** [comment]
Still a hole

**Comment by justinelliotmeyers** [comment]
http://www.hattiesburg.org/index.cfm/contact-us
requested data through their city contact us webpage

**Comment by justinelliotmeyers** [comment]
they are sending the data now

**Comment by justinelliotmeyers** [comment]
Justin,
I’ve attached a .zip file that has the address points and parcel data for the city. If you need anything else, don’t hesitate to ask.
 
Thanks,
Grant Hobgood

**Comment by justinelliotmeyers** [comment]
https://www.dropbox.com/sh/5q5wbvd1jxsuc9v/AABawshhK1rXFzNdKqnerFtEa?dl=0
