### ISSUE TITLE
Add addresses in Colorado Springs, CO

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2026]
Status:
- [x] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by slibby** [comment]
service: http://gis.coloradosprings.gov/arcgis/rest/services/springsview/SpringsView_AllLayers/MapServer/120 ?

**Comment by justinelliotmeyers** [comment]
sent out several e-mails and asked on social media (facebook/ twitter) for gis/ planning department contact info and asked about open data.  Will need to follow-up asap.

**Comment by justinelliotmeyers** [comment]
followed up with planning department who told me to contact IT, who sent me to colorado computer support, who sent me back to the planning department.  I finally received someones contact info who may assist.  
matt bingman
mbingman@springsgov.com
719-385-5602
called and left a voicemail - will follow-up tomorrow if I do not hear from him tonight

**Comment by justinelliotmeyers** [comment]
Matt called me today (10/4/2016 4 pm CST) and said they have the data.  He cannot just give it to me because it is from their police department - He literally had to take a polygraph test to access it (no idea why - thought i would just make mention of it!?!) - He is reaching out to the head of IT to see if it is something we can access and will get back to me in the next day or two.

**Comment by slibby** [comment]
Wow, please thank him for his diligence!

**Comment by justinelliotmeyers** [comment]
10/13/2016 called Matt backand left a voicemail - emphasizing we only need lat/ long/ st name and house/ bldg number.

**Comment by justinelliotmeyers** [comment]
10/14/2016 called Matt again and left voicemail

**Comment by justinelliotmeyers** [comment]
I think we can close this because we have the data for all of El Paso County, CO.

**Comment by justinelliotmeyers** [comment]
El Paso link here: https://www.dropbox.com/sh/nnux4dwcxlivva2/AAC2_0oXKeDS-_kOQNDtedY8a?dl=0

**Comment by iandees** [comment]
I used our upload thing to put this on S3 here: https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/iandees/b43a21/JM EPC Lat Long Location Data.zip
