### ISSUE TITLE
Add addresses in Shreveport, LA

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2027]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
no data here: https://services3.arcgis.com/cEsSI6IR59h5UGE4/ArcGIS/rest/services

**Comment by justinelliotmeyers** [comment]
officially requested data from Caddo Parish here: http://la-caddoparish.civicplus.com/FormCenter/Online-Forms-2/Public-Works-GIS-Map-Request-Form-38

**Comment by nvkelso** [comment]
I asked them again via the same form.

**Comment by justinelliotmeyers** [comment]
I sent another formal request; I will call on Wednesday if I do not receive a response.

**Comment by justinelliotmeyers** [comment]
12/21/2016 after calling several times today... finally got through to the only office that handles gis - was told they would pull the data, but no idea if that will happen.  I believe the person in charge is:
Leon Gafford  
Public Works GIS 
Title: GIS Analyst
Phone: (318) 226-6934

Hopefully I can resolve all of this today.

**Comment by justinelliotmeyers** [comment]
what a journey...
gis > assesors > third party company > sales person...

$2000 for all of Caddo Parish (about 140 k parcels).  about 100k in Shreveport alone (which if we don't want all data, it is $.40 per parcel with $100 minimum.  

I sent a formal e-mail about the project to make sure the terms of the data allow redistribution. Stay tuned @nvkelso 

The point of contact I was working with is here:
Brad Merrick
501-801-0174
bmerrick@datascoutpro.com
