### ISSUE TITLE
Add addresses in Lafayett, LA

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2030]
Status:

- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by davidchiles** [comment]
ArcGIS REST Services Directory: http://lcgmaps.lafayettela.gov/arcgis/rest/services

**Comment by iandees** [comment]
Here's an address layer: http://lcgmaps.lafayettela.gov/arcgis/rest/services/BaseLayerServices/LCG_Address_Points/MapServer/0

**Comment by slibby** [comment]
closed via #2050
