### ISSUE TITLE
Add addresses in Barrow, Alaska

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2031]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
e-mailed:
Mari Moore, Deputy Assessor
Email: mari.moore@north-slope.org
Phone Number: (907) 852-0355
Fax Number: (907) 852-4091

**Comment by justinelliotmeyers** [comment]
filed out form they just sent:

Good morning Justin,
Could you please fill out the request form and return it to Charmaine.
Thanks,
-Dan
 
Daniel (Dan) Heiner
North Slope Borough
GIS System Programmer
Planning & Community Services

**Comment by justinelliotmeyers** [comment]
Good afternoon Justin,
 
I’ve been assigned to fulfill your data request. Are you looking to get address points for the Barrow area only?
 
Charmaine Hingada
GIS Technician
 
NSB Planning & Community Services
PO Box 69 Barrow, AK 99723
907-852-0333 ext. 1153
Charmaine.Hingada@north-slope.org

**Comment by justinelliotmeyers** [comment]
I asked for all the data they had

**Comment by justinelliotmeyers** [comment]
You can get it sometime this afternoon. There will be a $10.00 fee, would you like to proceed?
 
Charmaine Hingada
GIS Technician
 
NSB Planning & Community Services
PO Box 69 Barrow, AK 99723
907-852-0333 ext. 1153
Charmaine.Hingada@north-slope.org

**Comment by justinelliotmeyers** [comment]
5449 records - check or cash (no cc)
you do not have to fill out a formal request, as I already did and she (Charmaine) is expecting someone else to contact her with moving forward on purchasing the data. Let me know if you have any other questions. Thanks!

**Comment by nvkelso** [comment]
I'll followup with Charmaine on payment details.

**Comment by nvkelso** [comment]
Emailed.

**Comment by justinelliotmeyers** [comment]
Thank you!
