### ISSUE TITLE
Add addresses in Hawaii (outside of Honolulu)

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2032]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
  - [x] Kauai County https://github.com/openaddresses/openaddresses/pull/2567
  - [x] Maui County
  - [ ] Hawaii County https://github.com/openaddresses/openaddresses/pull/2565
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
**
http://hawaiistatewidegisopendataportal.histategis.opendata.arcgis.com/datasets/579b8dcb7a8e44c1af201e1b3cdf655f_25

http://files.hawaii.gov/dbedt/op/gis/data/alltmk.shp.zip

wrote them to see if they have addresses to link to parcel data or if they have a different address point dataset.

**Comment by justinelliotmeyers** [comment]
Hello,
 
I’m afraid that we don’t have address points for the parcels.  The City and County of Honolulu does have a site address table for their parcels, which can be found here:  ftp://gisftp.hicentral.com/Attribute_Tables/. For the other counties, you might try contacting their respective Real Property Tax Division offices.
 
Thanks,
 
Joan Delos Santos
_____________________________
 
Joan Delos Santos
Hawaii Statewide GIS Program
State of Hawaii, Office of Planning
235 S. Beretania St., 6th Floor
Honolulu, HI  96813
Phone (808) 587-2895

**Comment by justinelliotmeyers** [comment]
i replied to ask if anyone in her office knew of the data and for specific contacts if I were to have to reach out to individual tax offices.

**Comment by justinelliotmeyers** [comment]
Emailed the following on 11/3/2016:
Kauai County GIS Coordinator:
Garrett Johnson 
Department of Information Technology 
(808) 241-4492
gjohnson@kauai.gov
 
Maui County GIS Services Manager:
Bill Medeiros
Department of Management
(808) 270-7518
mauigis@maui.net
 
The County of Hawaii GIS Coordinator is out on leave.  While she is away, you can contact Sheila Cadaoas:
 
Sheila Cadaoas
Information Systems Program Manager
Department of Information Technology
County of Hawaii    808.932.2965
Sheila.Cadaoas@hawaiicounty.gov

**Comment by justinelliotmeyers** [comment]
Sent follow-up emails to all three contacts today.  Not really sure why they aren't responding...

**Comment by nvkelso** [comment]
It’s always beach-o’clock in Hawaii ;)

**Comment by justinelliotmeyers** [comment]
Maui County Parcels - http://hawaiistatewidegisopendataportal.histategis.opendata.arcgis.com/datasets/c61357edec2e4994ae3c179ba8d3088c_8

Maui County Addresses - http://www.co.maui.hi.us/DocumentCenter/Home/Index/125

**Comment by trescube** [comment]
Wow, they certainly don't make it easy.  Here's the ESRI server behind the scenes:  http://geodata.hawaii.gov/arcgis/rest/services/ParcelsZoning/MapServer/8

Unfortunately this service doesn't have address info.  The second link @justinelliotmeyers posted contains a TSV file that has all the address info but no lat/lng.  Fortunately there's a `TMK` field shared between the two data sources that seems to be fairly solid, though the TSV contains some padding in its version.  

Another good thing, that ESRI server also has parcels for some additional counties and cities in Hawaii.

**Comment by justinelliotmeyers** [comment]
yeah - there is a statewide parcel dataset and the TMK is the field we want.  I am trying to do 50 things right now, but I can get it in a shapefile and export it out with the joined table.  That sound okay @trescube  ?

**Comment by trescube** [comment]
Yep, sounds good!

**Comment by justinelliotmeyers** [comment]
**i always double check my work, and for some reason that table has duplicate TMK ids...  I'll have to see if there are duplicates with different addresses.  Give me a little bit, sorry

**Comment by justinelliotmeyers** [comment]
i hand checked a few and they all have same address - I did a join, added a frequency field at the end so you can see how many times the TMK id was in the table (*the table had a TMK length of 12 (+000) so i just kept the left 9 and did the join (probably TMI, but just wanted to share).  Joined table in shapefile is here: https://www.dropbox.com/s/ntajztsezsdgkd4/Parcels__Maui_County.zip?dl=0

![maui_parcels](https://cloud.githubusercontent.com/assets/5324316/20196388/85211d6c-a768-11e6-83c9-9f861eff2c30.jpg)

**Comment by trescube** [comment]
Downloaded and checked it out.  Looks good, I'll try to get a source together this evening.

**Comment by trescube** [comment]
@justinelliotmeyers Thanks for getting the data together!

**Comment by justinelliotmeyers** [comment]
I still need to follow-up with the other two counties.  Once I hear back from them I think we can close the issue if thats okay @trescube ?  Let me know, Thanks!
Justin

**Comment by trescube** [comment]
Yep, no problem!

**Comment by nvkelso** [comment]
@justinelliotmeyers Can you tickle the other 2 Hawaii counties again, please?

**Comment by justinelliotmeyers** [comment]
Sent follow-up to Kauai, Hawaii, and Honolulu counties. If I do not hear back by wednesday, I will follow-up

**Comment by justinelliotmeyers** [comment]
02/22/2017
E-mailed Kauai - http://www.kauai.gov/realproperty - rpassessment@kauai.gov
E-mailed Hawaii County - http://www.hawaiicounty.gov/real-property-tmk-maps - planning@co.hawaii.hi.us and cohrpt@co.hawaii.hi.us
Emailed Honolulu County -bfsrpmailbox@honolulu.gov  - filled out form: https://www.realpropertyhonolulu.com/help-resources/contact-us

**Comment by justinelliotmeyers** [comment]
Uploading soon:
Hi Justin,

Yes, we do have a TMK shapefile.  We also have corresponding dbase tables that may further assist you.  I will send over a link shortly.  Regarding an address point shapefile, you may want to further contact Planning Dept., as they maintain this dataset.  I have copied Mary Aken their Tax Maps and Records Supervisor.

Thanks,
Cheryl Chan
County of Hawaii
Real Property Tax Division

**Comment by justinelliotmeyers** [comment]
hawaii county (*i added join for @trescube ) - https://www.dropbox.com/sh/bl9du5wks42tepc/AAB1EZ0zPOIKFgSWDPsvlf5Ua?dl=0
![untitled](https://cloud.githubusercontent.com/assets/5324316/23245200/d20bac86-f958-11e6-8f21-70e16d7a6b92.jpg)

**Comment by nvkelso** [comment]
!!! Great work :)

**Comment by justinelliotmeyers** [comment]
I also asked Cheryl for a contact at Kauai County. Hopefully we finish the entire state soon!

**Comment by trescube** [comment]
Nice!  I got the data, the regexes aren't bad for splitting up the number and street, should have a PR together by this afternoon.

**Comment by trescube** [comment]
Getting a GDAL error:  `2017-02-23 16:36:11,445    ERROR: GDAL gave Failure 1: IllegalArgumentException: Invalid number of points in LinearRing found 3 - must be 0 or >= 4
`

**Comment by justinelliotmeyers** [comment]
Cheryl just sent me the contact information for the other County. I just emailed them and hopefully hear from them soon.

**Comment by justinelliotmeyers** [comment]
Kauai Parcels: http://geodata.hawaii.gov/arcgis/rest/services/KOHA/koha/MapServer/1
