### ISSUE TITLE
Add addresses in Valdez, Alaska

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2034]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
emailed: cfarmer@ci.valdez.ak.us

**Comment by justinelliotmeyers** [comment]
emailed entire staff ;)
Chris Farmer	Information Technology Director	Chris Farmer	(907) 834-3453
Vacant Position	Administrative Assistant		(907) 834-3453
Matthew Osburn	Desktop and Communications Manager	Matthew Osburn	(907) 834-3453
Lisa Martin	Information Technology Systems Manager	Lisa Martin	(907) 834-3453
Melody Francis	Information Technology Specialist	Melody Francis	(907) 834-3453

**Comment by nvkelso** [comment]
Whoa, cowboy.

**Comment by trescube** [comment]
That's probably literally everyone that lives in Valdez, AK.

**Comment by justinelliotmeyers** [comment]
Hi Justin,
 
No, I’m sorry my dept in Finance doesn’t have the GIS data.  Please contact AnnMarie Lain in Community Development as she is our Senior GIS/Planning Technician at 907-834-3450 or better method via email to alain@ci.valdez.ak.us and she can get back to you.  Generally you need to fill out a Public Records Request with what you need and it gets forwarded to appropriate dept to complete.  I have attached the form and this should be emailed to our Records Manager Shelley McMillen at smcmillen@ci.valdez.ak.us or faxed to 907-835-2992.  She can be reached by phone at 907-834-3457 if you have specific questions with the form.
 
Have a great day!
Tracy Studer
Accountant II
City of Valdez
PO Box 307/212 Chenega Ave
Valdez, AK  99686
Ph: 907-834-3455
Fax: 907-834-3403
tstuder@ci.valdez.ak.us

**Comment by justinelliotmeyers** [comment]
Spoke with AnnMarie on the phone - needs to get approval from superior before sending. Stay Tuned 'eh

**Comment by justinelliotmeyers** [comment]
emailed:
alain@ci.valdez.ak.us
