### ISSUE TITLE
Add addresses in Sitka, Alaska

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2035]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
have data here: http://www.asgdc.state.ak.us/#452 but no addresses. 
I emailed planning@cityofsitka.org
They have it locked in some interactive map: http://www.mainstreetmaps.com/ak/sitka/public.asp

**Comment by justinelliotmeyers** [comment]
Hi Justin,
 
Sorry about the late response. Updated address data can be found in the parcel file found here http://www.mainstreetmaps.com/AK/Sitka/downloads/AK_Sitka_Parcels.zip
 
Also, I’m attaching an address point file but it has not been updated.
 
Joshua Houston
CAD / GIS Tech.
City and Borough of Sitka
907.747.1858

**Comment by justinelliotmeyers** [comment]
his attachment here: https://www.dropbox.com/s/thukiyfa1vb27pk/addressPoints.zip?dl=0

**Comment by arch0345** [comment]
Resolved in #6334
