### ISSUE TITLE
Add addresses in Juneau, Alaska

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2036]
Status:
- [x] **Research sources** and propose best source (and it's data license)
- [x] **Review proposed source**
- [x] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
Juneau Parcel Data here: https://ftp.ci.juneau.ak.us/pub/CBJ_GIS_map_layers/juneau_alaska_gis_internet_parcel_layer.zip

house number and street name in the site_addrs field.
![juneau_parcels](https://cloud.githubusercontent.com/assets/5324316/19989439/dd22f650-a1fc-11e6-8cad-1ff1855f5bfd.jpg)


license not mentioned but maybe in overview here: http://epv.juneau.org/

**Comment by nvkelso** [comment]
I'm fine with that source.
