### ISSUE TITLE
Add addresses in Nome, Alaska

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2037]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
emailed: cweidler@nomealaska.org

Tom Moran, 
City Manager

Nome
AK,  99762
Get Directions

Phone: (907) 443-6600
Fax: (907) 443-5349

**Comment by justinelliotmeyers** [comment]
Good afternoon, Justin:
 
I am including City Clerk Bryant Hammond in this reply.  He may be able to assist you with your request.
 
Thank you.
 
Candace Weidler
Executive Assistant
City of Nome
Phone: 907.443.6600
FAX: 907.443.5349
www.nomealaska.org

**Comment by arch0345** [comment]
Resolved in #6340
