### ISSUE TITLE
Add addresses in Bethel, Alaska

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2038]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
pretty cool looking pdf maps ;)
http://www.cityofbethel.org/vertical/sites/%7B86032ACB-92B0-4505-919A-3F45B84FECD9%7D/uploads/City_of_Bethel_Address_Map.pdf

emailed them asking for data: tmeyer@cityofbethel.net

**Comment by justinelliotmeyers** [comment]
Hi Justin,
It's a goal to have this info someday, we're just not there yet.  Not other agency would have this.


Ted.

**Comment by arch0345** [comment]
Source was added in #6343, but this only includes house numbers
