### ISSUE TITLE
Gwinnett County, GA

### ISSUE THREAD

**Issue by slibby** [openaddresses/openaddresses#2060]
Gwinnett County is one of the largest counties (by population) with no OpenAddresses point data.

Their GIS site sells data for a nominal fee: https://www.gwinnettcounty.com/portal/gwinnett/Departments/InformationTechnologyServices/GeographicInformationSystems/GISDataandMapSales?portal:windowState=normal&portal:componentId=c7bbb381-c193-4cf0-89f0-7e893ecb2ab8&interactionstate=JBPNS_rO0ABXd5ABNzdHJ1dHMucG9ydGxldC5tb2RlAAAAAQAEdmlldwAVc3RydXRzLnBvcnRsZXQuYWN0aW9uAAAAAQAaL3ZpZXcvaW5kZXghcHJvZHVjdERldGFpbHMACXByb2R1Y3RJZAAAAAEACUdJU19TRVQtMwAHX19FT0ZfXw**&portal:type=action&portal:portletMode=view

Unclear if Address Points are available or only Cadastral data.

**Comment by iandees** [comment]
I was about to buy this data, but unfortunately the license agreement for this data says:

> 5.1 Licensee shall not disclose, publish, sell, assign, lease, sublicense, market, distribute, loan,
offer, or transfer the GIS Data, or any portion thereof, to third parties except as may be
specifically authorized in a written addendum to this Agreement

**Comment by nvkelso** [comment]
I nominate @justinelliotmeyers to hassle Gwinnett County, GA for a written addendum saying OpenAddresses is awesome.

**Comment by justinelliotmeyers** [comment]
I emailed sharon.stevenson@gwinnettcounty.com again.  first time it took her 5 days to reply... now we are on 13 days... so hopefully she replies soon.  Our initial phone conversation - they have the data but not 100% coverage of the county - that is one reason they are reluctant to share at this point.  I told her anything now would be helpful to us.  She said she would talk it over with the gis manager - hopefully I hear from her tomorrow - if I don't by noon I am calling again.

**Comment by justinelliotmeyers** [comment]
Called 11/14/2016 and left voicemail...

GIS Office Staff and Management
Sharon Stevenson, ITS Manager
770-822-8033

**Comment by justinelliotmeyers** [comment]
Called again today.  Spoke to Sharon - she said she will not look into this until the end of the month.  she said this is as fast as county government moves.  I asked for a different contact and she said there is not one.  She told me she needs to talk it over with the gis manager (*she is the gis manager...)???  So I called the e911 sherriff dispacth and left a voicemail to see if they have address data.

**Comment by justinelliotmeyers** [comment]
She actually replied to my e-mail...  after a festive phone call I am very surprised.  Can someone help me ( @nvkelso or @iandees  ) answer the following questions she asked: 

Mr. Meyers,
My apologies for the delayed response.  Our data sales policies do not have a clear option for providing data for Open Data sources, however I will contact our Law department and department director to  see if our special agreement may be used for this purpose.  Please answer the following questions to help us make a decision:
·        Will the data be resold or redistributed in its original form?
·        Are you or someone at OpenAddresses authorized to sign a License Agreement prior to receiving the data? 
·        Will the County be required to sign any agreements from OpenAddresses?
·        How is the share-alike license enforced?
 
 
Thanks,
Sharon Stevenson, GISP
LIS Manager
Gwinnett County GIS
75 Langley Drive
Lawrenceville, GA 30046
770-822-8033
sharon.stevenson@gwinnettcounty.com
GIS Data Browser

**Comment by nvkelso** [comment]
> · Will the data be resold or redistributed in its original form?

It will not be resold, but it will be redistributed in a transformed form. The data is normalized into a common data structure as it's imported into OpenAddresses, and that normalized data is redistributed.

> · Are you or someone at OpenAddresses authorized to sign a License Agreement prior to receiving the data? 

I believe @iandees is an officer of an OpenAddresses incorporated thing.

> · Will the County be required to sign any agreements from OpenAddresses?

We don't have a click thru agreement.

> · How is the share-alike license enforced?

OpenAddresses includes a disclaimer with the data but does not track downstream use of the data. If a downstream user is out of compliance, the downstream user would need to be contacted.

**Comment by justinelliotmeyers** [comment]
closing as we have: http://results.openaddresses.io/sources/us/ga/gwinnett
