### ISSUE TITLE
St. Charles County, MO new open data portal with addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2076]
http://gis.sccmo.opendata.arcgis.com/datasets/1cabc91810a54f29ba42637dfff92748_0

**Comment by justinelliotmeyers** [comment]
https://github.com/openaddresses/openaddresses/issues/1996

**Comment by nvkelso** [comment]
@justinelliotmeyers how is the data different than #1996? Should we replace the feed in #1996 with this feed instead?

**Comment by justinelliotmeyers** [comment]
@nvkelso I believe the https://github.com/openaddresses/openaddresses/issues/1996 REST service has more data in it, and it is more current (based on a quick dl of both datasetys and looking at them)
