### ISSUE TITLE
Bates County, MO address data

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2085]
**Lat, Long values need to be updated**
The e911 person told me they aren't 100% done with the dataset, but should be in a few weeks.  I asked for what they have now and sent this.
https://www.dropbox.com/sh/nd4i1i9qo20vaxi/AADaKhLurWIeO9qIoInNsejUa?dl=0

**Comment by justinelliotmeyers** [comment]
@slibby I assigned to you so you can show me what to do next whenever you have time.  Thanks.

**Comment by slibby** [comment]
1.  Download and extract the files, record the shapefile name and the fields for number, all street info, and zipcode, town and county if present.
2. Find another conform object from a recent PR that is relatively similar (shapefile): https://github.com/openaddresses/openaddresses/blob/ac003d8cc001752ad0b92aea9c28b3f79004a31b/sources/us/tx/brazoria.json
3. Copy that JSON to a text file and update the relevant fields:
```
{
	"coverage" : {
		"US Census" : {
			"geoid" : "29013",
			"name" : "Bates County",
			"state" : "Missouri"
		},
		"country" : "us",
		"state" : "mo",
		"county" : "Bates"
	},
	"website" : "http://www.batescounty.net/maps.php",
	"data" : "https://www.dropbox.com/sh/nd4i1i9qo20vaxi/AADaKhLurWIeO9qIoInNsejUa?dl=1",
	"type" : "http",
	"compression" : "zip",
	"conform" : {
		"type" : "shapefile",
		"file" : "Export_Output_2"
		"number" : "ADDNUM",
		"street" : ["PREDIR", "STNAME", "STFUFFIX"],
		"city" : "PSTLCOMM",
		"postcode" : "ZIPCODE"
	}
}
```
Note:
- dl=1 in Dropbox URL
- updated FIPS (simple Google Search)

4. Browse to correct location (https://github.com/openaddresses/openaddresses/sources/us/mo)
5. create new file called bates.json (our preferred format omits _county)
6. paste in JSON
7. Create Pull Request based on that file
8. hooked should run the CI for that Pull Request and validate that it can access that data.
9. check hooked results i.e. http://s3.amazonaws.com/data.openaddresses.io/runs/121546/output.txt
If it succeeds, then wait for a project collaborator to merge it.

**Comment by slibby** [comment]
also some people have been adding photos of the coverage for proof of quality (taken from your desktop GIS of choice).
![image](https://cloud.githubusercontent.com/assets/1691225/19664586/6084d60a-99fe-11e6-8a7e-779d82067223.png)

**Comment by slibby** [comment]
closed by https://github.com/openaddresses/openaddresses/pull/2086
