### ISSUE TITLE
duplicate entries in openaddr-collected-global.zip

### ISSUE THREAD

**Issue by missinglink** [openaddresses/openaddresses#2098]
@iandees I mentioned this to you once before and I thought it was resolved, but I still have the same issue today on a fresh download from `http://s3.amazonaws.com/data.openaddresses.io/openaddr-collected-global.zip` :(

I'm not sure exactly how this is possible.. but the `openaddr-collected-global.zip` file contains duplicate entries for the same file path:

```bash
$ unzip openaddr-collected-global.zip

....
  inflating: summary/de/berlin-summary.csv  
  inflating: summary/de/berlin-summary.vrt  

replace us/or/washington.vrt? [y]es, [n]o, [A]ll, [N]one, [r]ename: 
```

there is an `-o` flag for `unzip` which masks the issue, so I'm using that for now.

more info:

```bash
$ zipinfo -1 /data/oa/openaddr-collected-global.zip | sort | uniq -c | sort -nr | head
      2 us/or/washington.vrt
      2 us/or/washington.csv
      2 summary/us/or/washington-summary.vrt
      2 summary/us/or/washington-summary.csv
      1 za/wc/cape_town.vrt
```

```bash
$ unzip -l /data/oa/openaddr-collected-global.zip | grep "/or/washington-summary"
     2647  2016-10-29 12:37   summary/us/or/washington-summary.csv
      346  2016-10-29 12:37   summary/us/or/washington-summary.vrt
     2647  2016-10-29 13:07   summary/us/or/washington-summary.csv
      346  2016-10-29 13:07   summary/us/or/washington-summary.vrt
```

```bash
$ LC_ALL=C shasum /data/oa/openaddr-collected-global.zip 
72134fe4eb0f0e257472445d2e76593ddcaa5f10  /data/oa/openaddr-collected-global.zip
```

**Comment by trescube** [comment]
@missinglink Are you on a mac or linux?  Mac's native compression utilities have a weird issues with really large .zip files including, but not limited to, claims of duplicate entries.  I ran into this issue a few months ago and had to resort to [7zip](http://www.7-zip.org/7z.html) on OSX to handle it correctly.

**Comment by missinglink** [comment]
```bash
$ cat /etc/issue
Ubuntu 14.04.5 LTS \n \l

$ uname -a
Linux peter-johnson1 3.13.0-96-generic #143-Ubuntu SMP Mon Aug 29 20:15:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ unzip --help | head -1
UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.
```

**Comment by trescube** [comment]
Well I'm stumped then.

**Comment by missinglink** [comment]
I just had a read online and apparently it's totally valid for a zip file to have two entries with the same path when adding files using 'append' mode. There is no integrity check and so presumably the second file will override the first and that's the intended behavior (when using the `-o` flag).

I'm not sure how big an issue it is really, just a bit of a gotcha when scripting an OA download/update shell script.

**Comment by migurski** [comment]
Yeah that’s frustrating; I’ll investigate again to see why dupes might show up.

**Comment by missinglink** [comment]
This is still an issue, I just unzipped the global file on an AWS box and got the same warning about `washington` being a dupe ¯\_(ツ)_/¯

**Comment by missinglink** [comment]
You can confirm it with the following command:

```
$ unzip -Z1 openaddr-collected-global.zip | sort | uniq -d
summary/us/or/washington-summary.csv
summary/us/or/washington-summary.vrt
us/or/washington.csv
us/or/washington.vrt
```

`¯\_(ツ)_/¯`

**Comment by ingalls** [comment]
This should be resolved in the new batch service. If it isn't feel free to open an issue in the openaddresses/batch repo
