### ISSUE TITLE
Boone County, MO, and the city of Columbia, MO

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2102]
As per Boone County - 
https://www.showmeboone.com/GIS/
GIS Manager
Jason Warzinik, GISP
Boone County Govt. Ctr.
801 E. Walnut Street, Room 220
Columbia, MO 65201
Phone (573) 886-4325
E-mail jwarzinik@boonecountymo.org

purchase - license agreement - **No data for Columbia, MO
$150 - 
address data mentioned at top - https://www.showmeboone.com/GIS/metadatafiles/metadata.asp

I am requesting data now to obtain the license agreement to see if it will work for OA.
____________________________________________________________________________________________________
**But we can access Columbia data here: Which I believe is already in OA

http://gis.gocolumbiamo.com/arcgis/rest/services/View_Services/ADDRESS_LABELS/MapServer

**Comment by justinelliotmeyers** [comment]
looks like we already have data for Columbia - I will get the license agreement for the rest of the county now

**Comment by justinelliotmeyers** [comment]
follow-up sent to jwarzinik@boonecountymo.org on 11/14/2016

**Comment by justinelliotmeyers** [comment]
[AddressLayer_JustinM.pdf](https://github.com/openaddresses/openaddresses/files/589490/AddressLayer_JustinM.pdf)
[License Agreement(Justin).pdf](https://github.com/openaddresses/openaddresses/files/589491/License.Agreement.Justin.pdf)


@nvkelso can you look these over?  He just sent them this morning; not sure if their license agrees with the project.  Thanks!
Justin

**Comment by iandees** [comment]
It's a no-go due to the non-redistribution part of the agreement:

>  Transfer Prohibited, Written Consent Required. Licensee agrees not to distribute the GIS files, whether in present format or in any other further developed format, or transfer them to any person or entity of any type without the written consent of Licensor. The undersigned further agrees not to permit any person within its employ, or agent or contractor, or other person, to use, reuse or distribute the GIS files provided hereunder for any purpose except as authorized by this License Agreement without the written consent of Boone County, Missouri.

**Comment by justinelliotmeyers** [comment]
called to see if we can have a written agreement that allows us to use in the OA project.  was not in and I left a voicemail.

**Comment by nvkelso** [comment]
Still a hole.

**Comment by justinelliotmeyers** [comment]
e-mail sent:
Jason Warzinik, GISP, GIS Manager
Boone County
801 E. Walnut, Room 220
Columbia, MO 65201-4890
Phone: (573) 886-4325
Fax: (573) 886-4322
E-mail: jwarzinik@boonecountymo.org
www: www.showmeboone.com

**We may want to consider trying to get the whole state through a FOIA or not so formal request from Steve Lewis; thoughts anyone?
