### ISSUE TITLE
Grants Pass and Klamath Falls, Oregon missing from dot map

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2123]
Following up from https://github.com/openaddresses/openaddresses/issues/1943, turns out we _do_ have address points ([zip](http://s3.amazonaws.com/data.openaddresses.io/runs/124045/us/or/josephine.zip)) but the aren't showing up on the general dot map shown on openaddresses.io when they should.

**Comment by nvkelso** [comment]
Public dot map:

![dot map](https://cloud.githubusercontent.com/assets/853051/20147400/c2145368-a65c-11e6-9588-dab737acad9a.png)

OpenAddresses CSV:

![csv is fine](https://cloud.githubusercontent.com/assets/853051/20148012/723a8116-a65f-11e6-98fa-0303060feef4.png)

**Comment by nvkelso** [comment]
Same deal with Klamath in https://github.com/openaddresses/openaddresses/issues/1946.

**Comment by iandees** [comment]
I'm going to move this discussion over to the `machine` repo, where the dotmap code is:

https://github.com/openaddresses/machine/issues/434
