### ISSUE TITLE
Isanti County, MN

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2137]
Called and spoke to county assesor:
County Assessor
Michelle Moen
(763) 689-2752

She explained they do have parcel polygons where the address data can be extracted from. But there is a price attached: $0.20 Per parcel; plus $25.00 setup fee – this fee would result in an expensive dataset. The GIS Manager told me the same fee would apply to derive addresses. She mentioned that the e911 sheriff’s office was creating an address point dataset for e911 dispatch.

After a few calls back and forth with sheriff (Robert Shogren - 9-1-1 Coordinator/Dispatcher - Isanti County Sheriff’s Office - Office: 763-689-2141 ) He told me he would share the data once it is created, but right now it is just the centroids of the assesors parcels and he cannot redistribute that format.

I will follow-up in a month to see where he is at with the project.  I did mention that I would be willing to help in my spare time if he needed assistance.

**Comment by justinelliotmeyers** [comment]
Good Morning Justin!
A full export file of the counties parcels is $75.00.  Let me know if you have any further questions!
 
Thanks!
Kasey Gilly
Deputy Auditor/Treasurer Il
Isanti County Auditor-Treasurer Dept
555 18th Ave SW
Cambridge, MN  55008
763-689-1644

**Comment by justinelliotmeyers** [comment]
her supervisor is out of office until 12/2/2016 and will find out if we can use for OA.

**Comment by trescube** [comment]
Any update on this?

**Comment by justinelliotmeyers** [comment]
just sent a follow-up email to Kasey and Robert

**Comment by justinelliotmeyers** [comment]
Hi Justin,
It is $75.00 for the full export file.
 
Thanks!
Kasey Gilly
Deputy Auditor/Treasurer Il
Isanti County Auditor-Treasurer Dept
555 18th Ave SW
Cambridge, MN  55008
763-689-1644

so I am not sure next steps as per moving forward - seems like I am kinda getting three different answers from a few people - I say shoot for the $75 version!?!

**Comment by justinelliotmeyers** [comment]
Isanti County has made a decision on address points, don’t know what their decision is. Michelle Moen from the assessor’s office is part of that decision making process. Her email is michelle.moen@co.isanti.mn.us
 
Robert Shogren

**Comment by justinelliotmeyers** [comment]
just emailed kasey back and asked if check/ cc worked and file format

**Comment by justinelliotmeyers** [comment]
$75 data is only a table with no geo-data. Will not work. Sheriff wants me to speak to assessor (*who is out on maternity leave). I believe that the data is too expensive at this point in time.

**Comment by nvkelso** [comment]
Let's skip this one, for now.

**Comment by justinelliotmeyers** [comment]
http://gis.co.isanti.mn.us/arcgis/rest/services/Zoning/Feedlot_Map/MapServer/3

**Comment by justinelliotmeyers** [comment]
@trescube just found this today!

**Comment by ingalls** [comment]
Closed by: https://github.com/openaddresses/openaddresses/pull/4764
