### ISSUE TITLE
Steele County, MN

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2139]
City address points - http://www.co.steele.mn.us/arcgis/rest/services/Steele_LINK_public/MapServer/5
Rural address points - http://www.co.steele.mn.us/arcgis/rest/services/Steele_LINK_public/MapServer/6
![steele_co_mn_addr](https://cloud.githubusercontent.com/assets/5324316/20347279/474f8086-abce-11e6-9943-8d28e5ea2a3e.jpg)

**Comment by iandees** [comment]
Looks like we have these already: [rural](https://github.com/openaddresses/openaddresses/blob/master/sources/us/mn/steele_rural.json) and [city](https://github.com/openaddresses/openaddresses/blob/master/sources/us/mn/steele_urban.json).

**Comment by justinelliotmeyers** [comment]
@iandees sorry!?  I was just panning around the openaddresses.io map and noticed the data was not there?  For some reason they are not plotting on the map (search for owatonna mn in the map and you will see they do not appear to be there)?

**Comment by iandees** [comment]
No worries! Remember that the dot map on openaddresses.io is out of date because some step along the way of updating it is broken. We're working on fixing it in https://github.com/openaddresses/machine/issues/434. Until then, you should look at the map and list of files at https://results.openaddresses.io/

**Comment by justinelliotmeyers** [comment]
Thanks!  I wish it were interactive where i can zoom around and make sure I know what we have and dont have - no more response needed on this issue, thanks amigo!
