### ISSUE TITLE
Douglas County, California

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2146]

**Comment by iandees** [comment]
Do we already have this data?

**Comment by justinelliotmeyers** [comment]
This county is not real!? As per the US analysis, I was starting to close pockets on the west coast - starting with https://github.com/openaddresses/openaddresses/issues/2145 and panning up - thought I was still in California (*was in Oregon)... but the data that esri gave me was for Douglas Colorado...  so I jumped the gun on this one and just removed all comments and closed the ticket.  Sorry
