### ISSUE TITLE
Oregon State Address Points

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2148]
Justin,
 
Cy Smith, our Geospatial Information Officer, asked me to send our address points for your use.  I’ve uploaded them temporarily to Dropbox for your download:
 
https://www.dropbox.com/sh/2kkdfdsyq3x0z2u/AAA-SFU7ggJvF16swVekpKwHa?dl=0
 
The features are provided by jurisdiction and contained in a file geodatabase.
 
Please let me know when you have downloaded the necessary files so I can remove them.
 
Thank You,
 
-josh
 
=============================
Joshua Tanner, GISP, MGIST
GIS Analyst / Web Administrator
Geospatial Enterprise Office
635 Capitol St NE # 150
Salem, OR 97301
503-378-2781
gis.oregon.gov

![oregon_oa_statewide](https://cloud.githubusercontent.com/assets/5324316/20497866/cf7af5ac-aff8-11e6-9718-61925bc168d4.jpg)

**Comment by justinelliotmeyers** [comment]
Missing the following counties:
+ Lincoln
+ Tillamook
+ Columbia
+ Gilliam
+ Morrow
+ Union

**Comment by migurski** [comment]
Great. I can use this list to make a coverage footprint polygon, similar to [the one for NY State](https://github.com/openaddresses/openaddresses/blob/master/sources/us/ny/statewide.json#L3).

**Comment by justinelliotmeyers** [comment]
Just double checked based on his e-mail and that is the complete list

**Comment by justinelliotmeyers** [comment]
Also, creating a new dropbox link in case they remove the one listed above; will paste in new comment once finished uploading

**Comment by migurski** [comment]
Justin, are you able to use https://results.openaddresses.io/upload-cache? It’d be better than Dropbox for this purpose since it allows project members to save files in our own S3 buckets.

**Comment by justinelliotmeyers** [comment]
@migurski Error logging in: you need to be a member of the OpenAddresses Github organization. ?

I did create a new download link: https://www.dropbox.com/sh/hjc5e1mljkxendo/AAAZE7QT3wy1ZTU8NX3i__Xla?dl=0

**Comment by migurski** [comment]
I’ll upload it, and meanwhile try to find out why you can't log in. You are a member of the organization, so you should be able to authenticate like @iandees and myself.

**Comment by justinelliotmeyers** [comment]
yeah - sorry, I tried three times and I can't get it off the Log In page (*same error message)

**Comment by migurski** [comment]
Use this: https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/migurski/d5add2/oregon_state_addresses.zip

**Comment by justinelliotmeyers** [comment]
Thanks @migurski !!
