### ISSUE TITLE
Travis County, TX

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2158]
The data can be downloaded here: https://data.austintexas.gov/Geodata/Address-Points/bpa2-q2tj

although this is on the cities open data portal, it covers the county.  If we are missing anything in the region, we can look at the surrounding counties (here: http://regional-data.capcog.opendata.arcgis.com/datasets?q=property&sort_by=relevance ) or I was told individual cities there : sunset valley, lakeway, roundrock, cedar park - all maintain their own address data.  So its all over the place...  Tonight I'll download all of Texas and do some analysis against US TIGER Places and see where we are missing data.  If anyone has questions/ concerns let me know.  Thanks

**Comment by iandees** [comment]
The Austin, TX data can be found in this source here:
https://github.com/openaddresses/openaddresses/blob/4061df1d4af774d8c8fb0402d6353f47285384d0/sources/us/tx/city_of_austin.json

**Comment by justinelliotmeyers** [comment]
@iandees I was looking for data for all of Travis County, TX as per http://davidchiles.org/2016/11/21/Progress-on-OpenAddresses.html saying we are missing Travis County - and after several phone calls - that is where they told me the data was.  I opened, panned around, and the county seems full (even overlaps to the county to the north of it).  I have to do some analysis tonight to see what cities we have data for and what ones are missing.  I usually trust the interactive map right on OA - but sometimes things don't plot.  not trying to make more work where we don't need it - just trying to make sure we account for major metros/ big counties.

**Comment by iandees** [comment]
(The interactive map on openaddresses.io is still out of date)

**Comment by justinelliotmeyers** [comment]
I'm going to close this issue; after looking into our sources and looking at the data, we have a top-notch dataset for Travis county/ Austin (*although it is in the city of Austin's open data portal, has coverage for the majority of Travis County).  I created the issue ticket because of the article here: http://davidchiles.org/2016/11/21/Progress-on-OpenAddresses.html but should have looked at the data first.  I believe we have coverage for Travis County based on the data here: https://github.com/openaddresses/openaddresses/blob/4061df1d4af774d8c8fb0402d6353f47285384d0/sources/us/tx/city_of_austin.json
