### ISSUE TITLE
Data sources from OK

### ISSUE THREAD

**Issue by tlpinney** [openaddresses/openaddresses#216]
Choctaw County, OK 
http://choctaw.oklahoma.usassessor.com/

Seminole County, OK
http://seminole.oklahoma.usassessor.com/Shared/base/AA/Error.php?errorCode=-4

![image](https://cloud.githubusercontent.com/assets/152429/2923127/c20bcb88-d70d-11e3-9a14-0c82076b5a60.png)

Beckham County, OK
http://beckham.okcountyassessors.org/

Custer County, OK
http://custer.okcountyassessors.org/

Grady County, OK
http://grady.okcountyassessors.org/

Mayes County, OK
http://mayes.okcountyassessors.org/

Jefferson County, OK
http://jefferson.okcountyassessors.org/

Love County, OK
http://love.okcountyassessors.org/

**Comment by ingalls** [comment]
Closing as stale - Feel free to open a new issue if someone is actively going after these.
