### ISSUE TITLE
Richland County, ND Parcel data

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2168]
![richland_nd_parcels](https://cloud.githubusercontent.com/assets/5324316/20710902/c8c244a0-b60a-11e6-95e5-778cc1b978a6.jpg)

https://c39gisserver.co.richland.nd.us/arcgis/rest/services/Cadastre/Parcel_Layer/MapServer/0

**Comment by trescube** [comment]
I'm having a really hard time with this source, it gives a lot of `ReadTimeoutError`'s on the 3rd batch.  I've had no luck with [pyesridump](https://github.com/openaddresses/pyesridump) either.
