### ISSUE TITLE
us-fl-st_johns

### ISSUE THREAD

**Issue by b-may** [openaddresses/openaddresses#2170]
St Johns County address points shapefile is here: http://www.gis.bocc.co.st-johns.fl.us/GISDataDepot/download.aspx?layer=/GISDataDepot/Library/Address_Site.zip

public domain (any public data in FL unless specifically exempted)

**Comment by nvkelso** [comment]
Nice find!

This is near Jacksonville in north Florida. From Wikipedia: `St. Johns County is a county of the U.S. state of Florida. As of the 2010 United States Census, the county's population was 190,039. The county seat and largest incorporated city is St. Augustine.`

**Comment by trescube** [comment]
OA machine is throwing an exception trying to unzip the file:  https://s3.amazonaws.com/data.openaddresses.io/runs/133288/output.txt

I can download/unzip on both linux and mac without a problem.

**Comment by migurski** [comment]
Strange. I tried running the source through Python locally, and it was fine. Then re-ran the pull request and the same error came up.
