### ISSUE TITLE
Pierce County, WA Parcel Data

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2174]
![pierce_co_wa](https://cloud.githubusercontent.com/assets/5324316/20728886/cde23588-b64d-11e6-9e28-e270b145faaf.jpg)

TERMS OF USE here: http://yakima.co.pierce.wa.us/GeoDataExpress/PierceCountyGISDataTermsofUse.pdf

@nvkelso can you look over the terms above to make sure the data is okay to use?  I believe it is, just want another set of eyes to check it out before a PR is created.  Thanks!

the address field is: Site_Address; physical location address of the property. Site address may be different than the mailing address. When a site address contains "XXX" it means the house number is unverified.

ArcGIS open data portal site: http://gisdata.piercecowa.opendata.arcgis.com/datasets/0bddcec060764ce8a6b6c07a60af170c_0

Rest: https://services2.arcgis.com/1UvBaQ5y1ubjUPmd/arcgis/rest/services/Tax_Parcels/FeatureServer/0

**Comment by nvkelso** [comment]
Terms look fine to me.

**Comment by justinelliotmeyers** [comment]
Thank you sir!  Although not in these terms, I think every city/ county (in WA ) is concerned with lists of people's names being used for commercial purposes.  When I tell them we want nothing to do with it, there are a lot more easy going...

**Comment by justinelliotmeyers** [comment]
**as per the county creating the actual address point layer from Linda Gerrell - 2537984923

no timeline, fighting to get it in 2017 budget - and once it is created, cannot say whether or not it will be open data

**Comment by trescube** [comment]
Only `Site_Address` is valid, the `City_State` and `Zipcode` fields are for mailing address.  Rather than not skipping house number or using `0`, the source adds `XXX`, eg - `XXX KEY PENINSULA HWY N`.
