### ISSUE TITLE
Convert source JSON validity check to jsonschema

### ISSUE THREAD

**Issue by iandees** [openaddresses/openaddresses#2175]
We should convert the checks that are done in [this node program](https://github.com/openaddresses/openaddresses/blob/master/test/sources.js) to use a jsonschema.

**Comment by migurski** [comment]
I was not familiar with JSON Schema; it’s described at http://json-schema.org. I think this is a good idea, if there’s good tools in Node and in Python!

**Comment by trescube** [comment]
I have a schema ~90% built for this locally that I'll hopefully be wrapping up this week.  The performance is far better than the node tests.  Using [ajv](https://www.npmjs.com/package/ajv) for validation, all 1788 sources can be checked in < 2 seconds vs 20 seconds for the node tests.  

There's also an off-by-one error in sources.js tests.  It processes all the but last source.

**Comment by trescube** [comment]
Fixed in #2253
