### ISSUE TITLE
Kharkiv Ukraine

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2176]
http://cdr.citynet.kharkov.ua/arcgis/rest/services/gis_ort_stat_general/MapServer/1

I tried to quick pull some down and verify - looks like points plot, but didn't want to come in WGS84 - just a fyi

**Comment by nvkelso** [comment]
The projection is pulkovo-1942-gauss-kruger-7n, aka [EPSG:28467](http://spatialreference.org/ref/epsg/pulkovo-1942-gauss-kruger-7n/), via [metadata](http://cdr.citynet.kharkov.ua/arcgis/rest/services/gis_ort_stat_general/MapServer) on the level up on that endpoint.

**Comment by trescube** [comment]
I set `"srs": "EPSG:28467"` in the conform object but that doesn't appear to work in geojson-typed sources.

**Comment by trescube** [comment]
This was fixed in #2217 and #2541
