### ISSUE TITLE
Add prefix functions support for letter suffix house number

### ISSUE THREAD

**Issue by trescube** [openaddresses/openaddresses#2177]
The functions `prefix_number` and `prefix_street` should support an optional letter suffix as part of the house number.  For example, Berks County, PA has addresses like `70A RIEGEL LN` which the `prefix-*` functions don't support now (the `regexp` it was [using before](https://github.com/openaddresses/openaddresses/blob/614bfe07844f6698307f1d8312fb8a72e4d8a603/sources/us/pa/berks.json) didn't account for an optional letter so there was no regression with the switch).  This is quite common in the US so risk is low for misinterpretation.

**Comment by migurski** [comment]
Point of order: this should probably go in `openaddresses/machine` since it’ll be addressed there.

**Comment by trescube** [comment]
Oh, whoops!  My bad, I'll move it.

**Comment by trescube** [comment]
Moved to openaddresses/machine#465
