### ISSUE TITLE
Texas OA Data

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2179]
![texas_oa_yeeeehawwww](https://cloud.githubusercontent.com/assets/5324316/20774587/f810ac68-b724-11e6-9f0b-baf46cae0461.jpg)

After filing an official PIA, this is what I was sent.  Cheers!

Mr. Meyers,
 
The information responsive to your request can be downloaded via the following link:  https://geo-comm.sharefile.com/d-s72fbc0849fe49de9.  The Road Centerline and Site Structure Address Points (SSAP) layers include the fields responsive to your request.  SSAP includes fields for latitude and longitude, however, pursuant to the CSEC NG9-1-1 GIS Data Standard, latitude and longitude are currently optional fields so not all SSAP may have x/y information.  Please let me know if you need further assistance.
 
Thank you.
 
Patrick Tyler
Public Information Coordinator
Commission on State Emergency Communications (CSEC)

**Comment by iandees** [comment]
Wahoo! This is great, thanks for chasing this, @justinelliotmeyers.

I uploaded the data here: http://data.openaddresses.io.s3.amazonaws.com/cache/us/tx/20161129_CSEC_SSAP_RCL.zip

**Comment by justinelliotmeyers** [comment]
**They plan on having complete coverage by February 2017 - I will put in my calendar to do another formal PIA request so we can fill in the missing counties.
