### ISSUE TITLE
Canadian County, OK

### ISSUE THREAD

**Issue by tlpinney** [openaddresses/openaddresses#218]
Source:
http://www.canadiancounty.org/index.aspx?nid=908

**Comment by slibby** [comment]
Can be closed, this is covered by https://github.com/openaddresses/openaddresses/blob/master/sources/us/ok/acog-counties.json

**Comment by ingalls** [comment]
Hey I don't see any data here so closing is :+1: just wanted to post a reminder that we definitely want overlapping data if it is from different providers.

**Comment by geobrando** [comment]
agreed @ingalls.  Definitely closed because there was no data available.
