### ISSUE TITLE
2016 Washington State parcels (polygons)

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2185]
http://geoservices.wa.gov/arcgis/rest/services/Parcels/ECY_Washington_State_Parcel_Database_2016/MapServer/0

**Comment by iandees** [comment]
The data in here is going to be rather difficult to pull out. The situs address is all merged together into one line with various formats that won't be easily regex'ed out:
- `930 GOLDEN CREST DR WENATCHEE, WA 98801` (no comma after the street name)
- `648 13TH ST` (no city,state,zip)
- `504 S ZINSER,KENNEWICK,WA,USA` (includes country)
- `9213 77TH ST SW UNIT C` (note the subaddress `UNIT C` is present in the situs address line even though there's a subaddress field in the data source)

I think I'd rather see us use this state source to try and find individual municipality address sources and/or give feedback to the state GIS organization that's putting this data together.

**Comment by migurski** [comment]
Any chance these are owner addresses rather than SITUS?

**Comment by iandees** [comment]
I checked on [a map](http://www.arcgis.com/home/webmap/viewer.html?url=http%3A%2F%2Fgeoservices.wa.gov%2Farcgis%2Frest%2Fservices%2FParcels%2FECY_Washington_State_Parcel_Database_2016%2FMapServer&source=sd) and it looks like the situs addresses do correspond with street names in the cases I checked.

**Comment by nvkelso** [comment]
Related: It looks like the **2015** version (versus this 2016 data) was used in this recent PR: https://github.com/openaddresses/openaddresses/pull/2133. 

@iandees: what's the backstory on that? Should we make a new PR for this issue for the 2016 data?

**Comment by iandees** [comment]
I don't think 2016 existed there when I created that PR.

**Comment by nvkelso** [comment]
Can you check to see if the coverage is better in 2016 version, please?

**Comment by arch0345** [comment]
Resolved in #6223
