### ISSUE TITLE
Remove El Paso county from Texas footprint map

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2186]
Picking up from https://github.com/openaddresses/openaddresses/pull/2180#event-879484747...

Looks like El Paso county didn't get knifed out of the revised Texas footprint, but should be.

![remove these counties](https://cloud.githubusercontent.com/assets/853051/20819113/44d21ea2-b7e7-11e6-8ee2-be1ad7f8733b.gif)

![texas county names](http://www.digital-topo-maps.com/county-map/texas-county-map.gif)

**Comment by migurski** [comment]
Oops, thanks!
