### ISSUE TITLE
McKinley County, NM

### ISSUE THREAD

**Issue by tlpinney** [openaddresses/openaddresses#219]
Contact:
http://www.co.mckinley.nm.us/assessor.htm

**Comment by ingalls** [comment]
Closing as stale - Feel free to open a new issue if someone is actively going after these.

**Comment by justinelliotmeyers** [comment]
<img width="1176" height="732" alt="Image" src="https://github.com/user-attachments/assets/06c5f043-6fbd-431b-9c87-7a9acc74abac" />

https://gis.gallupnm.us/server/rest/services/City_of_Gallup_Roads_and_Addresses_GIS1/FeatureServer/4

**Comment by iandees** [comment]
Thanks Justin! I added that.
