### ISSUE TITLE
Kenton County, KY Parcels

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2196]
![kenton_ky](https://cloud.githubusercontent.com/assets/5324316/20937770/6168f072-bbb6-11e6-8dba-882c238cf507.jpg)

http://kcgis.kcor.org/arcgis/rest/services/KentonPVAMap/MapServer/6

**Comment by nvkelso** [comment]
This is suburbs of Cincinnati on the south side of the river.

**Comment by justinelliotmeyers** [comment]
It looks like the entire county to me?

![kenton_ky_zoomed_out](https://cloud.githubusercontent.com/assets/5324316/20941848/6a791146-bbc6-11e6-836a-71efe355e2b4.jpg)
