### ISSUE TITLE
Address Data for United States, Missouri, Kansas City

### ISSUE THREAD

**Issue by sbaugher** [openaddresses/openaddresses#2198]
Using MapZen (which uses OPenAddresses), I was unable to find several Kansas City, MO street addresses, for example:

5400 N Oak Trafficway, Kansas City, MO

Kansas City, MO seems to publish addresses with lat/lng in multiple formats with a public domain license:

https://data.kcmo.org/GIS/Geocoded-Kansas-City-Addresses/3639-4c86

I confirmed that the address above shows up in their dataset, but I'm not at all sure how to "submit" it to this project.

**Comment by trescube** [comment]
Oh, nice!  We have a source for Kansas City, MO but it appears to be broken.  We'll get this taken care.  Thanks for submitting the data!
