### ISSUE TITLE
Del Norte county, California

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2200]
Part of "finish California" sprint.

**Comment by nvkelso** [comment]
Related: 

- https://github.com/openaddresses/openaddresses/issues/2201
- https://github.com/openaddresses/openaddresses/issues/2202
- https://github.com/openaddresses/openaddresses/issues/2203
- https://github.com/openaddresses/openaddresses/issues/2204
- https://github.com/openaddresses/openaddresses/issues/2205
- https://github.com/openaddresses/openaddresses/issues/2206
- https://github.com/openaddresses/openaddresses/issues/2207

**Comment by nvkelso** [comment]
Download link:

- http://www.co.del-norte.ca.us/departments/information-technology/geographic-information-services-gis/Parcels.zip?attredirects=0&d=1

**Comment by nvkelso** [comment]
Hmm, looks like the file only has APN parcel numbers, the `situs_address` is empty for all records :(

Will require email / phone followup to find join table:

- http://www.co.del-norte.ca.us/departments/information-technology/geographic-information-services-gis

![screen shot 2016-12-06 at 21 16 14](https://cloud.githubusercontent.com/assets/853051/20955597/510f968e-bbf9-11e6-9caa-c7da4e2dd277.png)

<img width="633" alt="screen shot 2016-12-06 at 21 15 34" src="https://cloud.githubusercontent.com/assets/853051/20955598/514e08b0-bbf9-11e6-92b3-a0cc9331fd5e.png">

**Comment by nvkelso** [comment]
```
To obtain a legal description of a parcel, please consult your deed or contact the 
Del Norte County Assessor's Office at (707) 464-7200. For detailed, site specific 
information on flood zones or land use information please contact the Del Norte 
County Community Development Department at (707) 464-7254. 
```

They do have an Esri server for a map viewer:

- https://dnco.maps.arcgis.com/apps/MapTools/index.html?appid=b47cd7d681a34383951e7cfaf8cb8a34

@iandees any tricks to get the parcels out of there?

**Comment by davidchiles** [comment]
@nvkelso This endpoint looks promising https://services3.arcgis.com/IkUDY1vRIUWiVvcz/ArcGIS/rest/services/DN_Parcels/FeatureServer/0

This has 16,165 parcels. But maybe not all have an address?

```
SIT_ST_NUM
SIT_ST_NAM
```

**Comment by nvkelso** [comment]
Looks to be same data, still with empty situs fields :(

**Comment by nvkelso** [comment]
Called the number, got transferred around a couple times. They have a single GIS tech, left a voice message with her.

**Comment by trescube** [comment]
@davidchiles is right, the `SIT_ST_NUM` and `SIT_ST_NAM` fields are valid and full of good data.

**Comment by nvkelso** [comment]
Closed via https://github.com/openaddresses/openaddresses/issues/2559.
