### ISSUE TITLE
Siskiyou county, California

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2201]
Part of "finish California" sprint.

**Comment by nvkelso** [comment]
Nothing obvious:

- http://www.co.siskiyou.ca.us/content/assessor-division-parcel-maps
- http://www.co.siskiyou.ca.us

**Comment by nvkelso** [comment]
Possibly ([src](http://ice.ucdavis.edu/doc/parcel_data_contacts)):

```
Jeff Clausen
311 Fourth Street
Room 108
Yreka, CA 96097
530.842.8036
```

**Comment by justinelliotmeyers** [comment]
530-841-2100
planning dept has data

**Comment by justinelliotmeyers** [comment]
parcels here: https://www.co.siskiyou.ca.us/content/planning-division-gis-data-download

**Comment by justinelliotmeyers** [comment]
assessor has addresses $300

**Comment by justinelliotmeyers** [comment]
@ingalls not sure if this is something you guys could help with?

**Comment by justinelliotmeyers** [comment]
Britt Dveris

Senior Planner, Planning Division

hasnt heard back from GIS coordinator (said next week most likely), but believes will not share data because of accuracy issues. Migrating to enterprise gis later in year (*no timeline*) and hopefully will have data then. But no idea when. So getting address points from gis dept isnt happening. Calling assessor's office now.

**Comment by justinelliotmeyers** [comment]
Assessor's office called me back. Data is updated in June and released in July once a year. So essentially the data gets updated once a year and is sold. Can buy old data, but attributes would not join to APN to planning deprtments parcel layer is what I was told. This whole thing is very confusing, never heard of a county doing things like this. so planning dept told me to ask assessor and assessor told me to go back to ask the planning dept. PING PONG BALL TIME... So I reached back out to planning dept, and hopefully I can re-explain what we need without getting the run around.

**Comment by justinelliotmeyers** [comment]
here they are! https://www.dropbox.com/s/mt6jp62lecrcfdh/sisk.csv?dl=0
