### ISSUE TITLE
Modoc county, California

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2202]
Part of "finish California" sprint.

**Comment by nvkelso** [comment]
Possibly ([src](http://ice.ucdavis.edu/doc/parcel_data_contacts)):

```
Cheri Budmark, Assessor
204 South Court Street
Suite 106
Alturas, CA 96101
530.233.6218
assessor@co.modoc.ca.us
```

Looks to be ParcelQuest related.

**Comment by nvkelso** [comment]
Related:

- http://www.co.modoc.ca.us/departments/assessor/ownership-information (maps link to Parcel Quest)
- http://www.co.modoc.ca.us/departments/assessor
- http://www.co.modoc.ca.us/departments/information-technology

**Comment by nvkelso** [comment]
Since this is Parcel Quest related, it's probably a paid source, but let's confirm.

**Comment by justinelliotmeyers** [comment]
it is... I called parcelquest, ill see how much it is.

**Comment by justinelliotmeyers** [comment]
links back to parcelquest still - http://www.co.modoc.ca.us/departments/assessor

**Comment by justinelliotmeyers** [comment]
@nvkelso found this tonight!!!!!!!!!!!!!!!! https://gis2.cdfa.ca.gov/server/rest/services/Parcel_DM/MapServer/24/

there might be other CA counties - not 100% certain on source - but seems like it's coming from the state - Thoughts?

Cheers!!

**Comment by justinelliotmeyers** [comment]
![modoc](https://user-images.githubusercontent.com/5324316/49777638-54723200-fccf-11e8-8651-90884bb937ec.png)

**Comment by nvkelso** [comment]
Fantastic find!
