### ISSUE TITLE
Imperial county, California

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2207]
Part of "finish California" sprint.

**Comment by nvkelso** [comment]
Via ([src](http://ice.ucdavis.edu/doc/parcel_data_contacts)):

Looks like good data, just need to get it.

- Map viewer: https://www.geoviewer8.com/?username=icpublic&password=icpublic
- County "GIS" page: http://www.co.imperial.ca.us/Assessor/

```
For further assistance and for questions or concerns about your property 
assessment, please call: (442) 265-4949, The Assessor’s property tax 
assessment information line or send an email at: assessor@co.imperial.ca.us .
```

Old contact?

```
Laura Cervantes, Cadastral Map/GIS Supervisor
County Assessor Office
940 W. Main Street, Suite 115
El Centro, CA 92243
760.482.4247
lauracervantes@co.imperial.ca.us
```

<img width="1391" alt="screen shot 2016-12-06 at 21 46 40" src="https://cloud.githubusercontent.com/assets/853051/20956366/3d9f2ef2-bbfe-11e6-9876-949623f18098.png">

<img width="555" alt="screen shot 2016-12-06 at 21 50 33" src="https://cloud.githubusercontent.com/assets/853051/20956365/3d83f86c-bbfe-11e6-98f2-a8655cba03ef.png">

**Comment by nvkelso** [comment]
I've sent them an email.

**Comment by nvkelso** [comment]
From Justin's comment in https://github.com/openaddresses/openaddresses/issues/2515#issue-206580096...

emailed Imperial County - assessor@co.imperial.ca.us

http://www.co.imperial.ca.us/Assessor/FIRelease.html

data here: http://services.geoviewer8.com/arcgis/rest/login?redirect=http%3A//services.geoviewer8.com/arcgis/rest/services/ImperialCounty_Public/MapServer/

**Comment by nvkelso** [comment]
@justinelliotmeyers How do we get a login token for that Esri server?

**Comment by justinelliotmeyers** [comment]
no idea! I just e-mailed them (assessor@co.imperial.ca.us ) and asked for data/ token.

**Comment by justinelliotmeyers** [comment]
we can buy, and incorporate into the project - they accept check/ CC

Sure, my direct line is listed here below:
(442) 265-1311   
 
 
 
LAURA J CERVANTES, GISP
Cadastral Mapping / GIS Supervisor
Imperial County Assessor's Office
(442) 265-1311

**Comment by nvkelso** [comment]
I'll followup with her...

**Comment by nvkelso** [comment]
Email sent.

**Comment by justinelliotmeyers** [comment]
![screenshot_20170306-170653](https://cloud.githubusercontent.com/assets/5324316/23634360/d411db3e-0297-11e7-811e-19046bab899d.png)

**Comment by nvkelso** [comment]
That’s the same weird / custom GIS portal as before (view only) :\

**Comment by nvkelso** [comment]
My sister lives in this county, will be nice to get her on the map!

**Comment by justinelliotmeyers** [comment]
@nvkelso you know a lot of people in a lot of places amigo!!!

**Comment by justinelliotmeyers** [comment]
![imperial](https://user-images.githubusercontent.com/5324316/49778009-02321080-fcd1-11e8-86a0-3d7e6c403fb6.jpg)

I think this is one of the last three! @nvkelso same source from previous two tonight!

https://gis2.cdfa.ca.gov/server/rest/services/Parcel_DM/MapServer/12

**Comment by nvkelso** [comment]
100% at long last!

**Comment by migurski** [comment]
💯
