### ISSUE TITLE
Coconino County AZ

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2209]
![coconino_az](https://cloud.githubusercontent.com/assets/5324316/20968162/1750291a-bc51-11e6-8f54-f1d71a59ba88.jpg)

http://data.coconinocounty.opendata.arcgis.com/datasets/76ca136c49db437aa624ab8f05d493bd_0

rest: https://utility.arcgis.com/usrsvcs/servers/76ca136c49db437aa624ab8f05d493bd/rest/services/OpenData/CoconinoCountyOpenData/FeatureServer/0

**Comment by nvkelso** [comment]
(Does duplicate addresses in Flagstaff, but that's okay.)

**Comment by justinelliotmeyers** [comment]
fix broken link. new page:
https://datahub-coconinocounty.opendata.arcgis.com/datasets/b1765e3b217d4a43a0034ffe70230a39_0
https://services1.arcgis.com/Rlvx5g8pKeK13apH/arcgis/rest/services/County_Addresses/FeatureServer/0
