### ISSUE TITLE
La Paz County, AZ

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2211]
Justin,
 
We can provide you with a cd containing parcel information for La Paz County.  You would need to send us your written request together with a check in the amount of $300 payable to the La Paz County Assessor’s Office.  GIS data information is provided through our Community Development Department.  You can contact Nora Yackley at nyackley@co.la-paz.az.us for further information.  
 
Kimmy Olsen
Administrative Assistant
La Paz County Assessor's Office
Office Hours: M-TH 7am-6pm
1112 Joshua Ave., Suite 204
Parker, AZ 85344
Phone: 928-669-6165
Fax: 928-669-9740

**Comment by nvkelso** [comment]
Interstate 10 goes thru, seems worth while to buy.

**Comment by nvkelso** [comment]
Curious fact from the Wikipedia page: The formation of this country prompted Arizona to change the laws to make it harder to form new counties in the state.

**Comment by nvkelso** [comment]
I've emailed asking for payment details.
