### ISSUE TITLE
us/ga/forsyth

### ISSUE THREAD

**Issue by davidchiles** [openaddresses/openaddresses#2221]
http://gisp2.forsythco.com/arcgis/rest/services/TaxAssessor/CAMA_ParcelMap/MapServer/0

**Comment by davidchiles** [comment]
@trescube 😕 This is for Forsyth County. The pull request was for Douglas County.

**Comment by trescube** [comment]
D'OH!  Sorry about that.

**Comment by trescube** [comment]
Some might say that I had Georgia on my mind :rimshot:

**Comment by justinelliotmeyers** [comment]
https://geo-forsythcoga.opendata.arcgis.com/datasets/siteaddress
