### ISSUE TITLE
Cochise County, AZ

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2228]
![cochise_az_12082016](https://cloud.githubusercontent.com/assets/5324316/21022600/3848a2dc-bd4b-11e6-9cf5-a5dabcb26114.jpg)

Mr. Meyers,
 
I have created an export of Cochise County addresses as requested and uploaded it to the Cochise County ftp site.
 
As it states in the GIS Map Gallery, you’ll need to contact the Assessor’s office directly to obtain ownership and assessment information as they charge per record.
 
They can be reached at assessor@cochise.az.gov or by phone at 520-432-8650 if you require that data.
 
Thank you,
 
----------------------------------------------
Jodi McGrath
GIS Technician
Cochise County Information Technology
1415 Melody Lane, Building D
Bisbee, AZ 85603
520-432-8336 phone
520-432-8347 fax
 
Public Programs. . .Personal Service
www.cochise.az.gov

**Comment by justinelliotmeyers** [comment]
https://www.dropbox.com/sh/wqc35ksrhfvtc5i/AABow5r84CqhMniri0eHWJ5xa?dl=0

**Comment by iandees** [comment]
Uploaded to https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/iandees/c5c85c/CcGISData161208.zip

**Comment by justinelliotmeyers** [comment]
Thanks @iandees

**Comment by iandees** [comment]
That link I posted was for the .mdb, which we don't support, so I uploaded the accompanying CSV: https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/iandees/c5c85c/Dev_Address_V.csv.zip
