### ISSUE TITLE
Richland county, SC

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2229]
The suburbs around Columbia, SC are **Richland County**.

They charge $.50/ parcel - roughly 164k parcels. That is just for the geometry. Attributes can be purchased separately. That's more expensive than my petty cash jar, so filing this away for a lucrative day.

e-mailed them: GIS@rcgov.us - called - office is closed. will call first thing in morning.

They are also working on an address point dataset, but it's a ways off.

**Comment by nvkelso** [comment]
Still a hole

**Comment by justinelliotmeyers** [comment]
checked again, geoserver is locked up requesting password. Closing for now.
