### ISSUE TITLE
New Nation-wide Czech Address Data!!

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2238]
![cz_addr_12092016](https://cloud.githubusercontent.com/assets/5324316/21076941/f06f5320-bf07-11e6-9449-18b65caf0c8f.jpg)

Current data below is green.  Red is new data.  (I like mapping during the holidays... X-Mas colors...).
![cz_addr_12092016_compare_to_current](https://cloud.githubusercontent.com/assets/5324316/21076945/2954ca9e-bf08-11e6-9c92-1250a1880a74.jpg)

For the past week I have been working with our current Czech Address data.  Looks amazing!  I did notice a few issues with the data however.  
1)there is a shift compared to current data from http://services.cuzk.cz/ (Adresy )
2)the locations seem to be triplicated (essentially each address has three identical points)

I have done the following steps to create a new Czech Dataset:
1)Downloaded all 6,258 files here: http://services.cuzk.cz/gml/inspire/ad/epsg-4258/

2)Extract

3)convert all xml files to shapefile in FME (*UTF-8 using fanout method); **554782.xml errors out because the 2GB dbf limit - so this was manually converted in QGIS

4)merge files together in one feature class in ESRI

5)reproject to WGS84

6)add X Y

7)export out X, Y, and alternativ fields (alternativ has address information)

I need to know if I should do a spatial join to current administrative boundaries?  Please lt me know.

**Comment by justinelliotmeyers** [comment]
I believe I found a table (http://apl.czso.cz/irso4/home.jsp ) that links to their basic settlement units that tells us the number of addresses we should roughly have per location; not sure how current it is, but I believe they update it regularly.  Data is here: https://www.dropbox.com/sh/d0wwy2wksdejqiy/AACyUy7Eun-RLb69xhdBrX94a?dl=0

**Comment by justinelliotmeyers** [comment]
https://www.dropbox.com/s/fhopgbg4vkyoobr/czech_addresses_wgs84_12092016_MASTER.zip?dl=0

**Comment by trescube** [comment]
Sweet!  Is there a form of the data with the the address parts split out or is the single `alternativ` field reliably parseable with regexes?

**Comment by justinelliotmeyers** [comment]
From the RUIAN, the way the original import happened; possibly.  I downloaded this gis data from their open INSPIRE dataset.  It seems to be updated very frequently.  So I think either way, we should update it (with or without the data I created).  But the way I converted from their xmls through FME it put it in one field.  Google translate stops working once you get so far in the RUIAN XML download area, so I don't know if I would be grabbing all locations, fields, etc.  Let me know if you want me to dig any further into this.  But they update this all the time it seems like (current to the day on RUIAN).  we should try to stay just as frequent if possible.

**Comment by trescube** [comment]
I think it can make some sense of it.  Towards the end of the file the commas go away or there aren't as many comma-delimited fields but the general format w/postcode might be enough to go on.

**Comment by justinelliotmeyers** [comment]
Do you want me to run a nearest to the current data and add all those fields?

**Comment by trescube** [comment]
Sure, if you can, that would be helpful if it's not too much trouble

**Comment by justinelliotmeyers** [comment]
yes - i have two files; the current dataset w triplicates, and uniques i split out.  ill run  against my uniques, think it should be fine - essentially this will just be a check for you to split out fields - running now.  I'' upload asap when its done cranking (**pending esri doesn't error 99999)!?!

**Comment by justinelliotmeyers** [comment]
@trescube here is the near analysis done on my filtered unique data: https://www.dropbox.com/s/l5r6smxtxbprzpc/new_czech_near_existing_oa.zip?dl=0

let me know if you have any questions

thanks,
Justin

**Comment by trescube** [comment]
@justinelliotmeyers I checked out the latest data and the separate fields for number/street/city are fantastic!  I noticed a few issues though that I wasn't sure if they were just how Czech addresses were formatted.  First, `NUMBER` and `POSTCODE` values > 1000 are number-formatted with commas.  Second, `/`-delimited numbers like `249/20` have `NUMBER` value of 0.  Please advise!

**Comment by justinelliotmeyers** [comment]
If you are talking about the nearest values (from old data (our current OA)), it is because arc doesn't like numbers that are not numbers and it removes the values (either makes null, or makes them a zero).  but in the new data, everything came the way it is, so I would say everything is raw data - unless the way FME converted it changed something, but I don't think it would have.  I hope that makes sense.

**Comment by trescube** [comment]
I think that makes sense.  I'm currently trying to pull a PR together for the first one you sent and that's going reasonably well, the regexes are a little tricky though.  Anyway, do you know how `č.p. 360, 79862 Rozstání` should be parsed?  The lat/lon on google goes to:

Rozstání 360
798 62 Rozstání

but I'm not sure what the `č.p.` part means.

**Comment by justinelliotmeyers** [comment]
Perhaps this: https://cs.m.wikipedia.org/wiki/Číslo_popisné

**Comment by justinelliotmeyers** [comment]
Perhaps this: https://cs.m.wikipedia.org/wiki/Číslo_popisné ; I don't know how it should be parsed.  I just hope it is consistent.  I'm away from a PC right now but can look later to see.  I think Praha gas a good open website that may have addresses that we can double check against here: http://www.geoportalpraha.cz/cs/opendata#.WFWJzJ9MFnG but I can't see if any of the datasets are address points.

**Comment by justinelliotmeyers** [comment]
@trescube this seems to explain the Czech addresses pretty good: http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/czeEn.pdf

**Comment by trescube** [comment]
I worked thru the regexes with @thatdatabaseguy last week.  There are still some tweaks to be made but I'm actively working on them.
