### ISSUE TITLE
Campbell and Pendleton Counties, Kentucky

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2247]
Campbell:
![campbell_ky](https://cloud.githubusercontent.com/assets/5324316/21159867/c5db1522-c150-11e6-8987-2c428e284e06.jpg)
http://linkgis.org/arcgisweb/rest/services/addressPoints/MapServer/3
NUMADDR - house number and street name

Pendleton:
![pendleton_ky](https://cloud.githubusercontent.com/assets/5324316/21159876/d1925eb6-c150-11e6-9ceb-051d58db11df.jpg)
http://linkgis.org/arcgisweb/rest/services/addressPoints/MapServer/4
NUMBER_ - house number
STREET - street name

Source: http://www.pdskc.org/
Field with address information:

**Comment by migurski** [comment]
Merged both!
