### ISSUE TITLE
Jamaica Parcel data

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2256]
http://gaia.globejamaica.com/NLA_Flex/rest/services/Maps/LandBase_NLA/MapServer/37

Not sure if this will work or is of any value, but wanted to share

**Comment by trescube** [comment]
This might work, too:

http://gaia.globejamaica.com/NLA_Flex/rest/services/Maps/Parcel_Mobile/MapServer/0

It also looks like it has separated fields for street.  I can't get either to load in QGIS, though.

**Comment by lagoonowner** [comment]
Its advisable to label them

**Comment by trescube** [comment]
I'm currently scraping the source with pyesridump but it's taking _forever_.

**Comment by justinelliotmeyers** [comment]
Stephen,
Thanks for looking into this. About a week ago I had an online chat session with one of the technical people for their agency. It sounds like there's roughly 900,000 parcels they have for the country. I'm not sure all of them have addresses however, specifically in the rural parts. I looked at about 1000, and some of the addresses seem good, but a lot were empty or missing. Hopefully this gives us some good coverage in Jamaica mon :)

**Comment by trescube** [comment]
Okay, I pulled both sources down with pyesridump.  The first contains 92,173 addresses while the second contains 188,795.  Both seem rather light for an island of 3 million people, but it's a start.  I'll get a source together tonight or tomorrow.
