### ISSUE TITLE
Henrico County VA Address Points

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2258]
![henrico_co_va_addr_points_12162016](https://cloud.githubusercontent.com/assets/5324316/21278910/a4c8926c-c3ab-11e6-8af9-e8fc352f07c2.jpg)

http://gis.co.henrico.va.us/arcgis/rest/services/OpenData/MapServer/35

**Comment by trescube** [comment]
Fixed in #2259
