### ISSUE TITLE
Gatineau, QC, CA

### ISSUE THREAD

**Issue by james2432** [openaddresses/openaddresses#2262]
https://github.com/openaddresses/openaddresses/blob/master/sources/ca/qc/gatineau.json
Way back I notified you that the click through didnt work for gatineau, because you needed to accept the license terms. I've been processing Gatineau address data in the CSV format to add to osm and upload that month's file to dropbox. Would it be useful for me to give you a dropbox link to the latest file that I could update when I update the file in osm: 
https://www.dropbox.com/s/oddopnkftwsytju/ADRESSE_LATEST.7z?dl=1

**Comment by nvkelso** [comment]
Nice! I see what you mean about the license click-thru (and it's just CC-BY, sigh).

We generally do S3 uploads so I've done that step and it's here:

- https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/nvkelso/6e49cb/Gatineau_QC_CA_ADRESSE.zip

Looks like this data source has not been added to the map yet (though it was indexed):

<img width="1062" alt="screen shot 2016-12-19 at 10 38 25" src="https://cloud.githubusercontent.com/assets/853051/21324697/baa82ce0-c5d7-11e6-8583-8bcbc80f7176.png">

<img width="856" alt="screen shot 2016-12-19 at 10 38 46" src="https://cloud.githubusercontent.com/assets/853051/21324698/baaa6bfe-c5d7-11e6-9fbb-c827d09c4316.png">

![screen shot 2016-12-19 at 10 38 54](https://cloud.githubusercontent.com/assets/853051/21324696/ba8fb804-c5d7-11e6-95b6-affa5d01b4ff.png)

**Comment by james2432** [comment]
Yeah, the license page has to receive a "accept license" cookie before download proceeds, which is annoying. I update this data monthly(when they release a new file) older files can be found here: https://www.dropbox.com/sh/n8tpe1p45fvzmrk/AAB0YFAIjCpZfF8aZxUXf8uYa?dl=0

**Comment by james2432** [comment]
I just checked and the csv seems to work directly now with this link(didn't before): http://gatineau.ca/upload/donneesouvertes/ADRESSE.csv

**Comment by james2432** [comment]
Shapefile even works now: http://gatineau.ca/upload/donneesouvertes/ADRESSE.zip
