### ISSUE TITLE
Lincoln County, WY

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2286]
![lincoln_wy](https://cloud.githubusercontent.com/assets/5324316/21433565/5366e530-c83e-11e6-880a-e45d0f1d3388.jpg)

https://www.dropbox.com/s/2m0s7fqrv9u9jyh/LincolnCoWyRuralAddresses.zip?dl=0

**Comment by justinelliotmeyers** [comment]
Initial E-mail:
Justin,

Yes I did get your email.  I've just been unavailable to get back to you until now.  Yes, I think the county would be willing to share our data for this project.  How do you want the x,y?  Lat/long, Northing/Easting?  Let me know and I will start putting it together.  

Destry Dearden, GISP
IT/GIS Director
520 Topaz Suite 109
Kemmerer, WY 83101
(307)877-2102
dtdearden@lcwy.org
Website: www.lcwy.org

E-mail today:


Justin,

I was able to compile our Rural Addresses into a shapefile for you.  Take a look and see if it will work for you.  Thanks for contacting me.  Once you have published it to this project, can you please send me a link to the project with our data included?

Thanks!

**Comment by trescube** [comment]
Getting this error in the machine processing this souce:  `GDAL gave Failure 6: No translation for Mercator_Auxiliary_Sphere to PROJ.4 format is known.`

**Comment by iandees** [comment]
See also https://github.com/openaddresses/machine/issues/423.
