### ISSUE TITLE
Add Alabama statewide addresses

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2294]
We tried to add statewide addresses in Alabama via https://github.com/openaddresses/openaddresses/pull/1905, but the remote server wasn't reliable. 

Filing this away for a rainy day. Perhaps a call to them might fix it?

**Comment by trescube** [comment]
I managed to pull the data down with 3 runs of pyesridump but wasn't able to make heads or tails of when to use `ADD1` or `ADD2`.  The 2 fields seem to be blank, an address with unknown mailing address or situs, or just contain PO boxes.  Sometimes both fields were PO boxes!

**Comment by justinelliotmeyers** [comment]
pull not working. Killing.
