### ISSUE TITLE
UK Data - OpenAddressesUK.Org

### ISSUE THREAD

**Issue by garfbradaz** [openaddresses/openaddresses#2299]
Hey Guys,

I don't know if these guys are affiliated with you? But it would be good to have a combined dataset:

[Link](https://alpha.openaddressesuk.org/)

They seem to have JSON and CSV datasets.

**Comment by iandees** [comment]
openaddressesuk.org doesn't capture any location information with their addresses, so the dataset isn't particularly useful to us. For example, https://alpha.openaddressesuk.org/addresses/fVEYss.json only has a lat/lon for the postcode.
