### ISSUE TITLE
Document support for layer names in conform

### ISSUE THREAD

**Issue by migurski** [openaddresses/openaddresses#2305]
- [x] Wait for https://github.com/openaddresses/machine/pull/510 to be merged
- [x] Wait for changes to be released to all workers
- [x] Describe use of new `layer` conform attribute
- [ ] Update New Jersey statewide source, as noted in https://github.com/openaddresses/machine/issues/500#issuecomment-269878745

**Comment by iandees** [comment]
You read my mind. I was just thinking about how to explain this in the docs...

**Comment by migurski** [comment]
Want to take a crack at this one? I'm just about ready to merge and release.

 _…waits for CI tests after another Python 2 strings/bytes bug._

**Comment by migurski** [comment]
Released. Changes will be on all workers after [the current batch set](https://results.openaddresses.io/sets/141476/) is complete. Should be tomorrow sometime.
