### ISSUE TITLE
Nashville Tennessee source failing

### ISSUE THREAD

**Issue by davidchiles** [openaddresses/openaddresses#2324]
Looks like the URL changed to https://maps.nashville.gov/arcgis/rest/services/Cadastral/Parcels/MapServer/0
and there's also another layer at  https://maps.nashville.gov/arcgis/rest/services/Cadastral/Parcels/MapServer/1

The  address points endpoint might be better: https://maps.nashville.gov/arcgis/rest/services/Addressing/AddressPoints/MapServer/0

It has 280662 records

**Comment by nvkelso** [comment]
One or both of these?

- https://github.com/openaddresses/openaddresses/blob/master/sources/us/tn/city_of_nashville.json
- https://github.com/openaddresses/openaddresses/blob/master/sources/us/tn/nashville_davidson.json

**Comment by trescube** [comment]
I think the latter is for all of Davidson County.
