### ISSUE TITLE
Wrong projection data Belgium (Flanders and Brussels region)

### ISSUE THREAD

**Issue by Platzii** [openaddresses/openaddresses#2328]
Hi all

I've noticed that the OpenAddresses data in Belgium is not correct.

The coordinates from the OpenAddresses zips (results.openaddresses.io) differ slightly from the coordinates from the source (https://github.com/openaddresses/openaddresses/blob/master/sources/be/flanders.json). Possible due to a wrong projection/conversion used.

Here is a small visualisation of the problem:
![screen shot 2017-01-06 at 16 07 38](https://cloud.githubusercontent.com/assets/7767841/21722047/403c564a-d42b-11e6-9917-51ba3b45258a.png)
The green points are coming from the source data, the red are from the OpenAddresses csv.
This use-case is at Tennisstraat, Gentbrugge, Belgium (https://goo.gl/maps/rd64qcV1miq) but all data from Flanders and Brussels seems to be affected.

Can you please investigate this issue?

Kind regards
Simon

**Comment by iandees** [comment]
I wonder if this is happening because the conform includes a projection. After https://github.com/openaddresses/machine/issues/500 we override the source projection (if any) with the conform projection if it exists.

**Comment by Platzii** [comment]
Well, that explains it!
Projection used in the source is Belge Lambert 1972 (https://epsg.io/103300)

**Comment by Platzii** [comment]
Brussels data seems to be correct
Although the map on https://openaddresses.io/ shows the shifted coordinates

**Comment by Platzii** [comment]
Not fixed yet :/

<img width="1196" alt="screen shot 2017-01-07 at 15 05 07" src="https://cloud.githubusercontent.com/assets/7767841/21742235/bbcd6640-d4ea-11e6-9555-b8151a38832c.png">

**Comment by iandees** [comment]
The data from results.openaddresses.io is only updated weekly. If you are checking there, give it a few days.

**Comment by Platzii** [comment]
Yes, I know, but the last run was Saturday, Jan 07, 2017 according to the site.
So it should be fixed already?

**Comment by iandees** [comment]
The latest run has started but has not finished yet.
