### ISSUE TITLE
Monmouth County, NJ

### ISSUE THREAD

**Issue by geobrando** [openaddresses/openaddresses#234]
http://co.monmouth.nj.us/page.aspx?ID=3866

**Comment by slibby** [comment]
Parcel layer available via REST here: http://maps.co.monmouth.nj.us/maps/rest/services/PublicData/Parcels/MapServer/0

**Comment by justinelliotmeyers** [comment]
Thanks @slibby http://maps.co.monmouth.nj.us/maps/rest/services/PublicData/Parcels/MapServer/0 has the parcels with addresses in the PropertyLocation field.  +250k locations!!
![monmouth_nj](https://cloud.githubusercontent.com/assets/5324316/20100064/9ce6b668-a589-11e6-986d-6fae52ae55ee.jpg)

**Comment by iandees** [comment]
Thanks for finding such a great parcel dataset, but our statewide New Jersey address points dataset covers this area with better data. I don't think I'm going to add this for now.

**Comment by ingalls** [comment]
Hmm @iandees I think the more overlapping data sources we can get the better! If this has addresses I think we should definitely include it.

**Comment by iandees** [comment]
The reason I closed this is twofold:

1. There's an implicit assumption that smaller governmental units will have better data: that county data will be better than statewide data, for example. This dataset is the first that would not follow that assumption
2. There is only street address and number in a single line, and our current methodology (a regex) for splitting that apart is not very robust.

**Comment by ingalls** [comment]
@iandees Thanks for the explanation here, definitely still think overlap is super important but your argument is convincing. Closing out.

**Comment by iandees** [comment]
Yea, well you convinced me to add it so 😄

**Comment by ingalls** [comment]
Haha yeah I saw that soon after :P I'm all on board having it as well.
