### ISSUE TITLE
Philadelphia, PA

### ISSUE THREAD

**Issue by jamesmbentley** [openaddresses/openaddresses#235]
City of Philadelphia address data on Github. I only uploaded the csv, but we also have geojson and shapefile formats.
[Address Data](https://github.com/CityOfPhiladelphia/OIT-geodata/tree/master/Open%20Address%20Data)

**Comment by geobrando** [comment]
Hey @jamesmbentley.  This is great.  Adding this in #1233

A couple questions

1) Are you still planning to update this regularly?
2) Could you add postcode data?

Pinging you an another issue raised about Philadelphia addresses

**Comment by jamesmbentley** [comment]
The [repo](https://github.com/CityOfPhiladelphia/OIT-geodata/tree/master/Open%20Address%20Data) I created is an export of the table @rcheetham mentioned. I can look into scheduling the update process and also adding the zip code data.

**Comment by geobrando** [comment]
Thanks!

**Comment by jamesmbentley** [comment]
@geobrando @iandees the csv of Philadelphia's [address data](https://github.com/CityOfPhiladelphia/OIT-geodata/tree/master/Open%20Address%20Data) was updated this morning and the zipcode field was added. I'm still working on the automated update and pull request process. I'll update the readme later this afternoon.

**Comment by iandees** [comment]
@jamesmbentley As long as the URL stays consistent we'll keep downloading the updated version. You don't need to submit pull requests to us every time. Thanks for making it available!

**Comment by geobrando** [comment]
@iandees 
Was there a PR somewhere?  @jamesmbentley was just referencing this issue in his commit and then letting us know, as I asked if he could output postcode in the CSV that they host in their repo.  He's also working on a process to automate the updates from the source data.

Looks like he's doing a bit of filtering from the source data.  Wondering if a parcel id number if present, if that should also be included.

> DATA DEVELOPMENT: This data is created from the ULRS PARCEL_ADDRESS table that contains a row of every standardized address in the system and is linked to a parcel. Each row also contains coordinates in NAD_1983_StatePlane_Pennsylvania_South_FIPS_3702_Feet (2272). The uploaded data is exported from the table after a running a SQL query against the layer to make sure none of the following fields are NULL; street_number, street_name, street_type, x_coord, and y_coord.

**Comment by iandees** [comment]
There was not a PR to update the source file to include postcode. We chatted yesterday at JS.Geo and I didn't understand that he was adding new fields.

**Comment by geobrando** [comment]
Got it.  Postcode has now been added.
