### ISSUE TITLE
Saginaw County, MI Parcels/ Address Labels

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2359]
![saginaw_parcels](https://cloud.githubusercontent.com/assets/5324316/22063687/17605984-dd4e-11e6-8972-2786174bc6b2.jpg)

Not sure the best source to use;
Parcels - http://beta.sagagis.org:6080/arcgis/rest/services/MyServices/sagaframeless/MapServer/1
address labels (*seems to have the fields that would make sense for us) - http://beta.sagagis.org:6080/arcgis/rest/services/MyServices/Saga_General/MapServer/7

**Comment by nvkelso** [comment]
Closing in favor of earlier https://github.com/openaddresses/openaddresses/issues/1989.
