### ISSUE TITLE
Eaton County, MI Parcels

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2362]
*Unsure this will work*

http://ecgis.eatoncounty.org/ecgis/rest/services/Equalization/Parcels/Mapserver/0

**Comment by trescube** [comment]
They have directory access turned off, but I found address points here:  http://ecgis.eatoncounty.org/ecgis/rest/services/Addressing/SiteAddressPoints/MapServer/0?f=json
