### ISSUE TITLE
Midland, Michigan

### ISSUE THREAD

**Issue by tlpinney** [openaddresses/openaddresses#237]
http://gis6.midland-mi.org/ArcGIS/rest/services/Property/MapServer/1

**Comment by geobrando** [comment]
Property layer no longer available.

Address data available for a fee http://www.cityofmidlandmi.gov/647/Purchasing-GIS-Data

**Comment by iandees** [comment]
$1500 for address points or $3000 for parcels. I don't see any agreement that prevents us from distributing it after buying it, either.

**Comment by nvkelso** [comment]
@migurski This is a good example for the writeup for county that we could pay something that's not crazy expensive and have redistribution rights to.

Breakdown of paid sources seem to be in the:

- Less than 500 range ($20 and $200 are common)
- Up to $5,000 (this one is $1,500)
- More than $5,000 (I've seen $20,000)

**Comment by justinelliotmeyers** [comment]
shes locked up
