### ISSUE TITLE
Lenawee County, MI Addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2376]
We do have an address point dataset for most of Lenawee County (does not include the Cities of Adrian & Tecumseh, which have their own GIS departments).  We do charge for non-government data requests, the address point dataset is $400 (about 35,000 address points).  We must receive payment and a signed copy of our data dissemination agreement before any data can be sent out.
 
Note that this layer was originally a polygon centroid file, while a significant portion of it has be realigned to be a building centroid roughly a third of it is still parcel centroid based.
 
Depending on your usage a road centerline layer may work, we have one for $50 or one can be downloaded from the States geographic library (link below).
 
If you have any questions or comments please feel free to call or email.

http://www.mcgi.state.mi.us/mgdl/
 

Thank You

Dereck Wilt
GIS Technician
Lenawee County Equalization/GIS Division
301 N Main St
Old Courthouse 1st Floor
Adrian, MI  49221

Office: 517-264-4522
Direct: 517-264-4695
Fax: 517-264-4529

**Comment by justinelliotmeyers** [comment]
Please sign and return to:

Equalization Department /GIS Division
Data Dissemination Agreement for Geographic Information.

Dereck Wilt, GIS Technician
LENAWEE COUNTY, MICHIGAN
Equalization Department /GIS Division
301 N. Main St.
Old Courthouse 1st floor
Adrian, MI 49221
Phone: (517)264-4522 · Fax: (517)264-4529


We, the undersigned, hereby agree to the following conditions for receiving data from the Lenawee County Equalization Department/GIS Division:

1. The data provided by the Lenawee County Equalization Department/GIS Division will be used only for the project(s) specified below:
	
	Enter project name:


2. The Lenawee County Equalization Department/GIS Division will be properly cited as the source of the data.

3. All assumptions and sources of error shall be communicated to the recipient(s) of the data. These assumptions and sources of error shall be noted on any published map.

4. No manipulation of the existing data (excluding thematic mapping and map compositions) shall take place without written consent from the Lenawee County Equalization Department/GIS Division.

5. Data from the Lenawee County Equalization Department/GIS Division shall not be distributed to any third parties in their digital form or in any fashion which would be unreasonably simple to obtain the data there from, without written consent of the Lenawee County Equalization Department/GIS division and with a signed Data Dissemination Agreement from said party

6. Data from the Lenawee County Equalization Department/GIS Division shall not be placed onto any public or multi-agency internet or intranet application without the prior written consent of the Lenawee County Equalization Department/GIS Division.

LIST LAYERS REQUESTED:





														
Signature									Date


Print Name:								
Organization:								
Address:

**Comment by nvkelso** [comment]
Can you link to their **data dissemination agreement**, please?

**Comment by iandees** [comment]
We can't use that because of the no redistribution clauses.

**Comment by justinelliotmeyers** [comment]
I'm reaching out to both cities mentioned in the e-mail that have their own gis departments now

**Comment by justinelliotmeyers** [comment]
https://services6.arcgis.com/vseBlcrQsepHsjub/ArcGIS/rest/services/tecumseh_parcel/FeatureServer/0

**Comment by nvkelso** [comment]
Bummer on no redistribution :(

Might be good for Al to still include sources like this with `skip: true`
to provide more training data to libpostal machine learning?
