### ISSUE TITLE
Livingston County, MI

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2377]
Hi Justin,
 
The entire data set for all of Livingston County is $36,000  according to our Enhanced Access Fee Schedule.
At the time of purchase you would be required to sign a Non Disclosure form.
 
Let me know if you are interested.
 
Thanks

**Comment by justinelliotmeyers** [comment]
e-mailed to verify cost and requested non-disclosure form:
addressing@livgov.com

**Comment by nvkelso** [comment]
How many records in Livingston County?! That’s a pretty steep price tag :\

**Comment by justinelliotmeyers** [comment]
can we grab their buildings looks like there is an addr field (*not sure if it is tiles though): http://tiles4.arcgis.com/tiles/cL47lSDX9wW9Ylgx/arcgis/rest/services/Basemap/MapServer/7 @iandees ?

**Comment by justinelliotmeyers** [comment]
@nvkelso 
Hello Justin,
 
$36,000 is for just for the address points and the accompanying attribute table. We currently have 81,861 address points in GIS for the county.
 
Parcels are a separate dataset of 86,381 parcels. The cost is $1 per parcel.
 
A sample of our Nondisclosure Agreement can be found at the following link,
 
https://www.livgov.com/gis/Documents/NondisclosureSample.pdf
 
Feel free to contact me if you have any questions.
 
Thanks,
 
 
Sandon Lettieri
GIS Technician
Livingston County
SLettieri@livgov.com
P: (517) 540 - 8780
F: (517) 545 - 9608
