### ISSUE TITLE
City of Portage, MI (Kalamazoo County)

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2378]
Filled out formal FOIA requesting data today (01/19/2017)

- City of Portage (paid, cheap)
- City of Kalamazoo (???)
- County of Kalamazoo (paid, crazy expensive)

**Comment by nvkelso** [comment]
This would fill a big hole.

**Comment by justinelliotmeyers** [comment]
Portage, city of kalamazoo, and county all maintain individual datasets...
I filed official FOIA w Portage, they want $100 for the layer, do not know what TOU are.

Playing cat and mouse with county - may be able to get all in one shot with them.

Left voicemail with county coordinator ;
GIS (Geographic Information Systems)	(269) 383-8814
Chris Bessert, GIS Coordinator	

stay tuned

**Comment by justinelliotmeyers** [comment]
left Chris another voicemail this am

**Comment by justinelliotmeyers** [comment]
followed up after we spoke on the 27th... left another voicemail...

**Comment by justinelliotmeyers** [comment]
Hello Justin,
It was nice talking with you on the phone today. At this time, we are still working on the address point layer for Kalamazoo County and it is not available for sale.
 
The parcel data is available at a $0.50 per parcel cost, or a lump sum of $14,000 for the county excluding the City of Portage and City of Kalamazoo, who have their own parcels and separate pricing.
 
As discussed, we may move toward more open availability of GIS data in the future, but it depends on the willingness to do that by the local units that have the ownership of the data. It may take some time to get there.
 
You are welcome to connect with us again in 6 - 12 months if you like to get updated on the status of our data.
 
Thank you,
 
Lotta Jarnefelt
Director
Department of Planning and Community Development
Kalamazoo County
201 W Kalamazoo Ave
Kalamazoo MI 49007
Phone (269) 384-8115
Fax (269) 383-8920
Email LMJARN@kalcounty.com
