### ISSUE TITLE
Missing data for Peoria city, Ill.

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2408]
Related issue https://github.com/openaddresses/openaddresses/issues/473 seems to have only landed data outside the city?

**Comment by justinelliotmeyers** [comment]
http://www.centralilmaps.com/arcgis/rest/services/Citylink_Flex/MapServer/9

**Comment by trescube** [comment]
This appears to be all of Peoria county.

**Comment by nvkelso** [comment]
Related, across the river: 

- https://github.com/openaddresses/openaddresses/pull/2632
