### ISSUE TITLE
Missing data in Scranton, PA

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2409]

**Comment by iandees** [comment]
No obvious online map data available.

**Comment by justinelliotmeyers** [comment]
**new interactive map! http://www.scrantonpa.gov/

once you open it, it opens a arcis powered map - then boots you to log in.

**Comment by justinelliotmeyers** [comment]
e-mailed LACKAWANNA COUNTY IT

**Comment by justinelliotmeyers** [comment]
should be in here: http://www.safdn.org/gis/

I'm hoping

**Comment by nvkelso** [comment]
I'm not seeing addresses or parcels on those links?

**Comment by nvkelso** [comment]
Oh, the Wilkes-Barre source doesn't include Scranton though on closer inspection.

The other parcel theme in that MapServer is for a different area, too. So this one for Scranton is still MIA.

**Comment by nvkelso** [comment]
@justinelliotmeyers Can you followup on this one, please?

**Comment by justinelliotmeyers** [comment]
emailed both:
Jeff Mando
Chief Information Officer
Phone: 570-963-6450
Fax: 570-963-6705
E-mail: mandoj@lackawannacounty.org 

and 

Mike Brown
Deputy Director
Phone: 570-963-6743 x1469
Fax: 570-963-6705
E-mail: brownmi@lackawannacounty.org

**Comment by justinelliotmeyers** [comment]
Justin,
 
The county Department of Information Technology doesn’t handle these types of requests. Please direct your request to the county planning office, they manage GIS mapping. You can reach them directly by contacting their office at 570-963-6826
 
If you don’t get a response please don’t hesitate to get back in touch with me.
 
 
Best Regards,
 
Jeffrey Mando
Jeffrey Mando, CGCIO, ITILv3
Chief Information Officer (CIO)
Lackawanna County, Pa.
200 Adams Ave, Suite 314, Scranton PA. 18503
mandoj@lackawannacounty.org
Phone: (570) 963-6450

**Comment by justinelliotmeyers** [comment]
I called and left a voicemail

**Comment by justinelliotmeyers** [comment]
terms and prices for data: https://www.dropbox.com/sh/295qffrm90898pv/AADTwWAagZ6Y-I-2IUxnSIw3a?dl=0

**Comment by trescube** [comment]
Boo, can't redistribute w/o their consent.

**Comment by justinelliotmeyers** [comment]
after speaking to the guy on the phone, I thought he was just going to send shapefile data. then I saw two docs....

**Comment by nvkelso** [comment]
At least the cost is “only" $500 for the complete county parcel layer :\

**Comment by justinelliotmeyers** [comment]
I asked if we purchased if that could be amended. Fingers crossed...

**Comment by justinelliotmeyers** [comment]
he is sending address points - no license or terms ;) - stay tuned!

**Comment by justinelliotmeyers** [comment]
![lc](https://cloud.githubusercontent.com/assets/5324316/25199288/554ef13a-2518-11e7-9a9d-c5b61724463c.jpg)

Wow - what a journey this ticket has been through...

**Comment by justinelliotmeyers** [comment]
https://www.dropbox.com/sh/hjthjh2wozegvd2/AAA0O6QWLyMgGmMkDHf2NALBa?dl=0
