### ISSUE TITLE
Missing data in Edmonton, Canada

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2410]
Big city, no data. @justinelliotmeyers you want to take a look?

**Comment by justinelliotmeyers** [comment]
don't see on their open data portal. e-mailed them and tweeted to see if they have data. Will look to see if there is a REST somewhere.

**Comment by justinelliotmeyers** [comment]
also requested parcels: assessment@edmonton.ca

**Comment by justinelliotmeyers** [comment]
here she is! https://data.edmonton.ca/City-Administration/Property-Information-Data/dkk9-cj3x

**Comment by justinelliotmeyers** [comment]
![edmonton_addr](https://cloud.githubusercontent.com/assets/5324316/22250127/cddaede0-e213-11e6-91c8-f64382a83ab0.jpg)
