### ISSUE TITLE
Missing data in Winnipeg, Canada

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2411]
Big city, no data. @justinelliotmeyers you want to take a look?

**Comment by justinelliotmeyers** [comment]
https://data.winnipeg.ca/City-Planning/Addresses/cam2-ii3u

**Comment by justinelliotmeyers** [comment]
although we don't need parcels, here they are: https://data.winnipeg.ca/City-Planning/Survey-Parcel/emk4-cdaw

**Comment by justinelliotmeyers** [comment]
![winnipeg_ca](https://cloud.githubusercontent.com/assets/5324316/22254250/094599b2-e222-11e6-9d2d-aee2ce84c14a.jpg)

**Comment by trescube** [comment]
@justinelliotmeyers how did you get this into QGIS?  The CSV download has the lat/lon values in a concatenated field that the machine can't split apart.  The JSON download isn't GeoJSON.

**Comment by justinelliotmeyers** [comment]
I honestly don't remember. I may have just manually ripped apart the csv and made the geometry (lat long) fields work (maybe a sed with "(" and a few other things)

or I did it in arcmap and not qgis - but I really don't remember!? Do you need help with it?

**Comment by trescube** [comment]
Oh, nope, I can extract what I need, just didn't know if you were able to easily import it.

**Comment by justinelliotmeyers** [comment]
did we ever implement this?

**Comment by nvkelso** [comment]
Not yet, it's in the `ready for PR` backlog.

**Comment by nvkelso** [comment]
This data is on the map now, closing.

<img width="317" alt="screen shot 2017-07-25 at 20 42 26" src="https://user-images.githubusercontent.com/853051/28603557-d05fa074-7179-11e7-9281-e960e4f96536.png">
