### ISSUE TITLE
Missing data in Saskatoon, Canada

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2412]
Big city, no data. @justinelliotmeyers you want to take a look?

**Comment by justinelliotmeyers** [comment]
![sask](https://cloud.githubusercontent.com/assets/5324316/22257918/88a4eed2-e22d-11e6-91f3-ee0c4492c91e.png)

http://opendata-saskatoon.cloudapp.net/DataBrowser/SaskatoonOpenDataCatalogueBeta/ParcelAddress#param=NOFILTER--DataView--Results

KML FORMAT :(

**Comment by nvkelso** [comment]
KML opens fine into QGIS via OGR, so this will _probably_ work. If not, should be simple machine change to make to add support.

Will require some RegEx as all address components in single field.

<img width="1435" alt="screen shot 2017-01-24 at 09 09 44" src="https://cloud.githubusercontent.com/assets/853051/22258066/fc0e4526-e214-11e6-8c6e-16221e597647.png">

**Comment by trescube** [comment]
We appear to support KML by specifying `"type": "XML"` as in [this](https://github.com/openaddresses/openaddresses/blob/master/sources/de/nw/kreis_viersen.json).

**Comment by trescube** [comment]
They also have the option to download as CSV.

**Comment by trescube** [comment]
Well, turns out the CSV file doesn't contain any lat/lon info.

**Comment by trescube** [comment]
Ended up using KML output with type=xml in the source.
