### ISSUE TITLE
Cyprus Address Data

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2421]
http://eservices.dls.moi.gov.cy/arcgis/rest/services/INSPIRE/AD_Addresses/MapServer/0

**Comment by sergiyprotsiv** [comment]
This one has a very messy pattern of relationships to different tables, perhaps this is the official INSPIRE way to structure the data relationally (if so, this could be useful in the future if more countries published  their data using the underlying INSPIRE schema, and not just a single table).

**Comment by justinelliotmeyers** [comment]
I wasn't sure if this was going to work or not; they have cadastral data, but I don't know if that would help or even be useful?

**Comment by justinelliotmeyers** [comment]
no actual address data
