### ISSUE TITLE
Sweden National Addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2422]
http://www.lantmateriet.se/sv/Kartor-och-geografisk-information/Geodatatjanster/Tjanster-enligt-Inspire1/#faq:Adress-Nedladdning-Inspire

**Comment by sergiyprotsiv** [comment]
I checked with Lantmäteriet a few years back to get the address data for my research. The price they quoted was on the order of 100 000 EUR for the whole country, maybe this changed.
Asked them a few weeks ago regarding their plans to open the data up and they said they have no funding to do so yet.
OA covers about 15% of population at the moment (of which only Stockholm is an official open data release, I think).

**Comment by justinelliotmeyers** [comment]
thanks a lot of $ - I know a lot of nations in the EU are opening their data under the INSPIRE initiative - surprised they don't have the AD Theme open for Sweden...

**Comment by msirenko** [comment]
Confirmed that it's in the 100K Euro range, double that if you want to make data available to your customers

**Comment by boxed** [comment]
This is no longer the case! The full vector database of all buildings, roads, etc with addresses is now published under a CC attribution license: https://www.lantmateriet.se/sv/Kartor-och-geografisk-information/Kartor/oppna-data/anvandarvillkor/

**Comment by justinelliotmeyers** [comment]
thanks @boxed !!!!!!!!!!!

**Comment by boxed** [comment]
Heh, glad someone else is excited! I tried looking into what to do but I am pretty out of my waters here.  To get the data you register some account then access an FTP (not SFTP!) with the files. That's it from what I can tell. Note that you have to have a fairly weak password as their site rejects big complex ones with an incorrect error message :P

**Comment by justinelliotmeyers** [comment]
I am registered - let me try to log in and see if it is there

**Comment by sergiyprotsiv** [comment]
My understanding is that the sources that have been opened are basically the same as last year (though they will open historical orthophotos soon).
There are no addresses I was able to find - the maximum is the names of road segments in Vägkartan.
The addresses seem to be the most protected datasource. I have access to the complete cadastre and the detailed building dataset via the university I work at, but even that has no addresses :/
Would be awesome if i'm wrong though!

**Comment by nvkelso** [comment]
Costs $100,000 to get password for open data (from https://github.com/sergiyprotsiv Slack update)
