### ISSUE TITLE
Uruguay

### ISSUE THREAD

**Issue by astoff** [openaddresses/openaddresses#2424]
Uruguay's _Dirección Nacional de Catastro_ has parcel data for the whole country, apparently without addresses... It might be worth checking with them if one can get the addresses somewhere.

http://catastro.mef.gub.uy/12360/10/areas/geocatastro.html

**Comment by justinelliotmeyers** [comment]
I can email later today. Alguien habla español?

**Comment by thatdatabaseguy** [comment]
Yo lo hablo, pero not super familiar with talking to GIS departments even in English :-).

There's a contact list here for what looks like their main office in Montevideo: http://catastro.mef.gub.uy/innovaportal/file/6634/10/tel_montevideo_30mayo2016.pdf. I'd guess the best bet's probably their IT department: computos@catastro.gub.uy. They also probably speak English if there's a standard script/template already written.

It looks like the data sets are split up by region (called a "department" in Uruguay, yay ambiguity) outside of Montevideo. The regional contact list is here: http://catastro.mef.gub.uy/innovaportal/file/6634/10/tel_oficinas_del_interior.pdf, but the Montevideo office might be able to handle everything.

**Comment by justinelliotmeyers** [comment]
e-mailed computos@catastro.gub.uy

**Comment by justinelliotmeyers** [comment]
I believe I asked them several months ago (*could have been BA, Argentina...!?), but I don't think they have the information, only polys. We will find out! Hopefully Montevideo can support everything, if not then we can go down the list. Thanks @astoff and @thatdatabaseguy !

**Comment by astoff** [comment]
https://github.com/openaddresses/openaddresses/pull/2918 fixes this.
