### ISSUE TITLE
Vernon, BC, Canada

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2441]
https://www.vernon.ca/government-services/maps-gis/open-data-deep > Cadastral Data >	vernon_civic_address_points.zip	Jan 13, 2017 5:07 PM

![vernon_update](https://cloud.githubusercontent.com/assets/5324316/22370812/636e102c-e461-11e6-8449-15572d8d3d89.jpg)

Red = New
Black = Existing

**Comment by trescube** [comment]
New source contains an additional 144 entries.
