### ISSUE TITLE
Columbia Shuswap Regional District, BC, CA

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2443]
![csrd updates](https://cloud.githubusercontent.com/assets/5324316/22371209/d884b2a6-e463-11e6-8a4e-ae462d2da3a1.jpg)
**Must Agree to license terms before download* - can someone review before we green light this for OA?
http://www.csrd.bc.ca/services/maps > Cadastral and Property Information

**Comment by iandees** [comment]
The license seems ok. It looks like a standard indemnity with a little extra bit about them owning the derivative data.
