### ISSUE TITLE
Churchill County, Nevada

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2447]
![churchill](https://cloud.githubusercontent.com/assets/5324316/22442898/eb3f2abc-e70a-11e6-9d08-72e534b176d0.jpg)

http://www.churchillcounty.org/index.aspx?NID=213 (*Parcels with APN and Site Address LINK)

**Comment by nvkelso** [comment]
Interstate 80 passes thru there, and Fallon is a US Census designated micropolitan area.
