### ISSUE TITLE
Eureka County, Nevada Parcels

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2448]
http://services7.arcgis.com/npQRqzUHX9auAwvE/arcgis/rest/services/parcels/FeatureServer/0

Source: http://www.co.eureka.nv.us/assessor/assessor.htm

**Comment by nvkelso** [comment]
There are less than 2,000 people in Eureka county, but I-80 passes thru.

**Comment by trescube** [comment]
This data is all over the place, there's no reliable address field.  Both `SITEADDRES` and `PLOCNM` appear to be the best field, but well over half the values contain surveying information rather than an address.

**Comment by trescube** [comment]
On revisiting, I think some sense can be made through judicious use of `PLOC_`, `PLOCDR`, and regexes on `PLOCNM`.

**Comment by trescube** [comment]
Now the source requires a token.

**Comment by arch0345** [comment]
Resolved in #3301
