### ISSUE TITLE
Humboldt County, Nevada Parcels

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2449]
http://humboldtnv.mygisonline.com/

http://landernv.mygisonline.com/arcgis/rest/services/NV_Lander/LanderNVcache/MapServer

can anyone grab these?

**Comment by nvkelso** [comment]
Looks to be a http://www.sidwellco.com gig.

**Comment by justinelliotmeyers** [comment]
https://nyenv.mygisonline.com/arcgis/rest/services/NV_Nye/NyeNVcache/MapServer

**Comment by justinelliotmeyers** [comment]
Sidwell does 11 counties from what their sales guy told me. I had a call with him - sending e-mail and requesting a quote. Of course every county has a different TOU/ copyright - so this should be a wild ride... Only in Nevada!!!!!

**Comment by justinelliotmeyers** [comment]
https://whitepinenv.mygisonline.com/

**Comment by trescube** [comment]
This one (White Pine) needs authorization token.

**Comment by justinelliotmeyers** [comment]
Hi Justin,
 
Currently our address point data is not available and there is a charge for our parcel data. It is $200 for just the shapefile and then $500 for the shapefile with associated data (such as ownership and land use). If you are interested I can either send it via email or mail it on a cd.
 
Regards,
 
Stephen Barrow
GIS Technician
Humboldt County
775-623-6318

**Comment by justinelliotmeyers** [comment]
No it does not (have situs address field in $200 version). The only potentially useful information that version has is parcel number and acreage. There are about 17,600 records and we actually do not have a copyright on the data. We request that you do not sell the information and must state that the data is for assessment purposes only and no warranties expressed or implied are granted. Our address points were in the process of being created when I started here a few months ago so I am not completely sure of when they might be completed. If you do not need the data immediately and are mainly looking for addresses I could let you know when that is available. I am not sure what the price will be for that but can let you know as soon as I find out. Yes, a check is the best option and once we receive that I can send you the data.  
 
Hope this helps!
 
Stephen Barrow
GIS Technician
Humboldt County
775-623-6318

**Comment by justinelliotmeyers** [comment]
hopefully he lets me know about the address points soon
