### ISSUE TITLE
Baldwin County, GA

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2453]
Source: http://mgrcmaps.org/baldwincounty/parcelviewer/
http://www.mgrcmaps.org/arcgis/rest/services/BaldwinCounty/BaldwinCountyParcelViewer/MapServer/4

**Comment by trescube** [comment]
The source doesn't appear to contain any addresses.

**Comment by trescube** [comment]
Removing "ready for PR" since there's nothing to process.

**Comment by nvkelso** [comment]
Oops! @trescube I do see data (around 900 parcels in the 2013 layer), though?

<img width="1432" alt="screen shot 2017-02-22 at 21 22 18" src="https://cloud.githubusercontent.com/assets/853051/23245935/2147a318-f945-11e6-9f4b-2ca127dc6989.png">
