### ISSUE TITLE
Banks County, GA

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2454]
Locked up in third party software... http://www.qpublic.net/ga/banks/search.html

Source: http://co.banks.ga.us/dept-gis-mapping.html
Fees: http://co.banks.ga.us/buy_13_1368410367.pdf

$1200

**Comment by nvkelso** [comment]
@justinelliotmeyers can you get the terms, please?

**Comment by justinelliotmeyers** [comment]
hold please... :)

**Comment by justinelliotmeyers** [comment]
**Addresses in data are bad. they would be incorrect.  
70% complete with new address layer - working on it for a few years
In 4-5 months I was told to check back; **September
