### ISSUE TITLE
Barrow County, GA

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2456]
http://www.barrowga.org/departments/tax-assessor.aspx
31,317 real property parcels,1,670 personal property accounts, and inspects 1,617 mobile homes
tpalmer@barrowga.org

**Comment by justinelliotmeyers** [comment]
Our county offers both GIS parcel & WinGAP data for all the parcels within Barrow County.
To receive both files we charge $150.00.
 
Let me know if you have any more questions or want to purchase it
 
Thanks,
 
Terah Palmer
GIS/ Conservation Use Specialist
Barrow County
Tax Assessorss Office
30 N. Broad St.
Winder, GA 30680
(770)307-3108 ext. 3811
Fax: (770)307-3405

**Comment by justinelliotmeyers** [comment]
I e-mailed and asked what the terms of use are

**Comment by justinelliotmeyers** [comment]
To proceed with the purchase of data we will need a check made to Barrow County and request for the data. Once the check is received I will put the data on our ftp site for you to pull from.
We do not have any terms or anything to sign.
 
Thank you,
 
Terah Palmer
GIS/ Conservation Use Specialist
Barrow County
Tax Assessors Office
30 N. Broad St.
Winder, GA 30680
(770)307-3108 ext. 3811
Fax: (770)307-3405

**Comment by nvkelso** [comment]
Exurbs between Atlanta and Athens, a good find!

**Comment by nvkelso** [comment]
Sent check via snail mail.

**Comment by nvkelso** [comment]
I received access to FTP site today via email, but that is a _hot mess_ of GB of files of linked tables. I think I see an Esri GeoDB format blob of data in there (that I can't open in QGIS). I've asked for a shapefile version back at that email.

**Comment by nvkelso** [comment]
Got a SHP version, but it only has APN parcel identifiers. The support staff said we need to join with the WinGAP data tables (that I also downloaded). They are serious DB geeky. 

<img width="773" alt="screen shot 2017-03-13 at 13 30 50" src="https://cloud.githubusercontent.com/assets/853051/23874083/a511a1fc-07f1-11e7-9792-55b1a92e3d5d.png">

<img width="977" alt="screen shot 2017-03-13 at 13 31 24" src="https://cloud.githubusercontent.com/assets/853051/23874082/a4e80bbc-07f1-11e7-8214-e231da5e1be2.png">

**Comment by nvkelso** [comment]
I joined the data in this one:

- https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/nvkelso/54cc50/BARROW_PARCELS_WITH_ADDR.zip

Here's the raw data if I made a mistake / we want to revise this in the future (e.g. also **add mobile home addresses**, which apparently a 2nd join one needs to make and really!?).

- https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/nvkelso/4302a7/BARROW_PARCELS_AND_WINGAP.zip

For the one I joined, the SHP export causes all sorts of short field funk. Here are the ones that are interesting for address construction (only street number and street name):

<img width="612" alt="screen shot 2017-03-13 at 17 12 14" src="https://cloud.githubusercontent.com/assets/853051/23880434/e2411494-0810-11e7-9402-c52dd5be7f7a.png">

Beware of 2 things: NULL street addresses, and `0` value street addresses. I know, right?! I'm guessing the `0` values would mess up the street address interpolation code if left in, I think NULLs are automatically removed already in machine?

Yellow in the maps below are the NULL and `0` values.

<img width="859" alt="screen shot 2017-03-13 at 17 17 54" src="https://cloud.githubusercontent.com/assets/853051/23880461/097f3568-0811-11e7-8066-fca9d7b91c7e.png">

<img width="898" alt="screen shot 2017-03-13 at 17 07 55" src="https://cloud.githubusercontent.com/assets/853051/23880436/e259165c-0810-11e7-945f-504ccf0b1c34.png">

<img width="965" alt="screen shot 2017-03-13 at 17 07 41" src="https://cloud.githubusercontent.com/assets/853051/23880435/e258cf4e-0810-11e7-9548-5a474300b0ab.png">
