### ISSUE TITLE
Alma, Georgia

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2458]
http://www.sgrcmaps.com/arcgis/rest/services/Alma/PropertyInformation/MapServer/0

**Comment by nvkelso** [comment]
Looks like this is from another regional gov't like Detroit with the following county coverage (many but not all have "property" endpoints, e.g.: parcels), and current OpenAddress.io coverage:

* Alma
* BenHill
* Berrien
* Blackshear
* Brantley
* Brooks
* Coffee
* Cook
* DPH
* Fitzgerald
* Irwin
* LiveOak
* Nashville
* Region
* Tifton
* Utilities
* valor
* vpd
* VSU

<img width="848" alt="region_of_georgia" src="https://cloud.githubusercontent.com/assets/853051/22475129/d5f33922-e792-11e6-930e-b0bf0c222097.png">

<img width="846" alt="oa_coverage_georgia" src="https://cloud.githubusercontent.com/assets/853051/22475128/d5d380b4-e792-11e6-9e42-ce26b61d5584.png">
