### ISSUE TITLE
Cook County, GA

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2461]
**We already have this source, but seems stale - maybe we should see if this is valuable?**

Parcels and Addresses
http://www.sgrcmaps.com/arcgis/rest/services/Cook/CookParcels/MapServer

**Comment by trescube** [comment]
Here's some analysis.  

# Original static source

The original source is static and hosted by OA.  It has 11,318 entries, of which 6,629 have non-zero house number and non-zero-length house number and street.  The original source has to use regexes for house number and street.  Of those 6,629 entries, there are some with obviously invalid street names, like:

* -83.3787498,31.0283441,6840,E COUNTY LINE & 6900 RD,,,,ga,,,0f122bbd3e27cc50
* -83.3029372,31.0324168,11,BLOCK B LOT,,,,ga,,,42cbadd7f7be6c47

# New ESRI source

The ESRI source has 8,319 entries, of which 8,292 have non-zero house number and non-zero-length house number and street.  I couldn't find any obvious invalid street names.  

# Conclusion

I'm calling this an improvement.
