### ISSUE TITLE
Bryan County, GA

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2462]
http://bryangis.bryan-county.org/arcgis/rest/services/PropertyDetails/MapServer/0

**Comment by trescube** [comment]
Address points!  http://bryangis.bryan-county.org/arcgis/rest/services/AddressPoints/MapServer/0

**Comment by justinelliotmeyers** [comment]
i believe there are only 485 - vs parcels (*maybe that was a different county though...). Did a lot of research in GA this am...

**Comment by justinelliotmeyers** [comment]
I think I went in every dir and the parcel one seemed promising - thats why I added the addresses, said pull PR, then changed link and removed PR.  Sorry for the confusion.

**Comment by trescube** [comment]
I saw the 485 count but running the source to see if that's just the arbitrary limit they placed on query size.  There are 30k+ people in the county so I'll switch to parcels if address points is lacking.

**Comment by justinelliotmeyers** [comment]
Thanks boss!

**Comment by trescube** [comment]
Yep, really only 485.  Darn it.
