### ISSUE TITLE
Update municipality_of_helsingborg.json

### ISSUE THREAD

**Issue by bennyjonsson** [openaddresses/openaddresses#2469]
Helsingborgs open-data including addresses can be found at
* http://kartor.helsingborg.se/oppnageodata/baskarta.php (Updated every week)

**Comment by trescube** [comment]
Thanks for this!  We already pull data from an [ESRI source](http://geodata.helsingborg.se/arcgis/rest/services/Trafik/Skolskjuts_160914/MapServer/37) for [Helsingborgs](https://github.com/openaddresses/openaddresses/blob/master/sources/se/municipality_of_helsingborg.json), so I think the zip file is a dump from this source.
