### ISSUE TITLE
Salem, OR

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2494]
found this today; looks like it covers the other side of the Willamette River

![salem_or](https://cloud.githubusercontent.com/assets/5324316/22736963/ffb55d34-edce-11e6-91f8-bcb9d0642281.jpg)

https://services.arcgis.com/kIA6yS9KDGqZL7U3/arcgis/rest/services/Primary_Address/FeatureServer/0

**Comment by iandees** [comment]
Where'd you find this?

**Comment by justinelliotmeyers** [comment]
http://opendata.arcgis.com/datasets/salem::primary-address-1?geometry=-127.378%2C44.245%2C-118.683%2C45.606

**Comment by justinelliotmeyers** [comment]
is there something wrong with it @iandees ?

**Comment by iandees** [comment]
Nope! Just curious so we can find licensing and website information.

**Comment by justinelliotmeyers** [comment]
as per that (lic. TOU) - in the whole ordeal with the old license - they were going to send the data, we just needed to cross out the terms that didn't align with our project and submit - so we could, in theory, get the whole 3-4-5 county area if we would do that!? Do I have the authority to do that, or should someone else review and do that? I spent a lot of time on that one, and then it somewhat just died in a matter of minutes...
