### ISSUE TITLE
Marietta, Georgia Parcels!

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2495]
![marietta](https://cloud.githubusercontent.com/assets/5324316/22737294/7ef4f644-edd0-11e6-83a0-8f8c5405f0d4.jpg)

https://secure.mariettaga.gov/arcgis/rest/services/AGOL_OpenData/MapServer/0

**Comment by trescube** [comment]
I think these might even be the address points:  https://secure.mariettaga.gov/arcgis/rest/services/MyMarietta/MapServer/1

**Comment by trescube** [comment]
Went with parcels, there are 3x as many records as the other layer.

**Comment by justinelliotmeyers** [comment]
the open data portal didn't list addresses - so I only had the option to go with parcels :( *I always try to find addresses before I opt for parcels
