### ISSUE TITLE
Atlanta Parcels (Fulton and Dekalb Counties)

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2496]
no us/ga/dekalb in downloads, so I believe we are missing Dekalb; hopefully this fills in that hole ;)

http://gis.atlantaga.gov/dpcd/rest/services/Land/ParcelLayer/MapServer/0

**Comment by trescube** [comment]
Address points:  http://gis.atlantaga.gov/dpcd/rest/services/Land/AddressPointsE911/MapServer/0

**Comment by justinelliotmeyers** [comment]
do they cover Dekalb?

**Comment by trescube** [comment]
Good question, I'll investigate.

**Comment by trescube** [comment]
They appear to have disabled querying for feature count.

**Comment by trescube** [comment]
pyesridump manages to get the data so we'll probably have to cache it on s3.

**Comment by trescube** [comment]
@justinelliotmeyers Yep, the points cover both Fulton and DeKalb counties.  Looking into count differences now.

**Comment by justinelliotmeyers** [comment]
awesome - hopefully it fills a big gap in greater ATL and GA!

**Comment by trescube** [comment]
194,702 points
167,960 parcels
