### ISSUE TITLE
Nevada 11 counties from sidwell

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2502]
followed up with Russ; he never returned my e-mail from 9 days ago...
http://www.sidwellco.com/team/russ-donovan/

**Comment by justinelliotmeyers** [comment]
[Copy of digital data pricing 2 2017.xlsx](https://github.com/openaddresses/openaddresses/files/788432/Copy.of.digital.data.pricing.2.2017.xlsx)

**Comment by nvkelso** [comment]
Hahaha: Paying per address record gets expensive! @migurski for planning / proposal writing background.

Total is $390,000!? _($369,863.19 + $21,000 processing fees)_


Counties | Parcel Count | Price per Parcel | Processing Price | Fee |  | tax roll | M/S account |  Address Points  
------------ | ------------ | ------------ | ------------ | ------------ | -- | -------- | ------------ | ------------
Adair MO  | 13,754 |  $0.20  |  $2,750.80  |  $300  |  | X |  | 
Bond IL  | 8,146 |  $0.25  |  $2,036.50  |  $300  |  |  |  | 
Bottineau ND  | 17,322 |  $0.30  |  $5,196.60  |  $300  |  | X | X | X
Buchanan IL | 20,295 |  $0.15  |  $3,044.25  |  $300  |  |  |  | 
Burke ND  | 7,276 |  $0.35  |  $2,546.60  |  $300  |  | X | X | 
Cavalier ND  | 12,083 |  $0.30  |  $3,624.90  |  $300  |  | X | X | 
Chaves NM  | 36,565 |  $0.12  |  $4,387.80  |  $300  |  | X |  | 
Cherokee KS  | 16,057 |  $0.15  |  $2,408.55  |  $300  |  | X |  | 
Clark IL  | 14,109 |  $0.20  |  $2,821.80  |  $300  |  | X | X | 
Clayton IA  | 28,509 |  $0.12  |  $3,421.08  |  $300  |  |  |  | 
Clinton IL  | 25,659 |  $0.12  |  $3,079.08  |  $300  |  | X |  | 
Crawford IL  | 16,600 |  $0.15  |  $2,490.00  |  $300  |  | X | X | 
Crawford IA  | 23,661 |  $0.15  |  $3,549.15  |  $300  |  | X | X | 
Delaware IN  | 59,519 |  $0.10  |  $5,951.90  |  $300  |  |  |  | 
Dewitt IL  | 11,176 |  $0.20  |  $2,235.20  |  $300  |  | X |  | 
Dickinson KS  | 13,883 |  $0.20  |  $2,776.60  |  $300  |  |  |  | 
Divide ND  | 7,848 |  $0.35  |  $2,746.80  |  $300  |  | X | X | 
Douglas IL  | 15,051 |  $0.15  |  $2,257.65  |  $300  |  |  | X | 
Eddy ND  | 5,020 |  $0.35  |  $1,757.00  |  $300  |  | X | X | 
Eddy NM  | 51,267 |  $0.10  |  $5,126.70  |  $300  |  | X |  | X
Edwards IL  | 8,067 |  $0.25  |  $2,016.75  |  $300  |  |  |  | 
Ford IL  | 10,356 |  $0.20  |  $2,071.20  |  $300  |  | X | X | 
Forsyth GA  | 78,184 |  $0.10  |  $7,818.40  |  $300  |  |  |  | 
Foster ND  | 3,017 |  $0.40  |  $1,206.80  |  $300  |  | X | X | 
Fountain IN  | 14,738 |  $0.20  |  $2,947.60  |  $300  |  | X |  | 
Franklin IL  | 30,643 |  $0.12  |  $3,677.16  |  $300  |  | X |  | 
Fremont IA  | 16,094 |  $0.15  |  $2,414.10  |  $300  |  |  |  | 
Fulton IL  | 11,134 |  $0.20  |  $2,226.80  |  $300  |  |  |  | 
Fulton GA  | 332,735 |  $0.10  |  $33,273.50  |  $300  |  |  |  | 
Greenville IL  | 10,555 |  $0.20  |  $2,111.00  |  $300  |  |  |  | 
Hamilton IL  | 10,195 |  $0.20  |  $2,039.00  |  $300  |  | X |  | 
Henderson IL  | 7,892 |  $0.25  |  $1,973.00  |  $300  |  |  |  | 
Humboldt IA  | 17,174 |  $0.15  |  $2,576.10  |  $300  |  |  |  | 
Ida IA  | 11,573 |  $0.20  |  $2,314.60  |  $300  |  | X | X | no address points
Jasper IA  | 29,914 |  $0.12  |  $3,589.68  |  $300  |  |  |  | 
Jefferson IA  | 17,837 |  $0.15  |  $2,675.55  |  $300  |  | X | X | 
Jefferson IL  | 29,293 |  $0.12  |  $3,515.16  |  $300  |  | X | X | 
Jewell KS  | 7,393 |  $0.25  |  $1,848.25  |  $300  |  |  |  | 
Jones IA  | 22,125 |  $0.15  |  $3,318.75  |  $300  |  |  |  | 
Kane IL | 182,976 |  $0.25  |  $45,744.00  |  $300  |  | X |  | price set by Kane
Kidder ND | 5,915 |  $0.35  |  $2,070.25  |  $300  |  | X | X | 
Lake IN | 243,156 |  $0.10  |  $24,315.60  |  $300  |  | X |  | X
Lee IA  | 30,194 |  $0.12  |  $3,623.28  |  $300  |  |  |  | 
Lee IL  | 28,796 |  $0.12  |  $3,455.52  |  $300  |  | X |  | X
Madison IA  | 17,672 |  $0.15  |  $2,650.80  |  $300  |  | X |  | 
McLean IL  | 69,771 |  $0.10  |  $6,977.10  |  $300  |  | X |  | 
Mitchell IA  | 11,503 |  $0.20  |  $2,300.60  |  $300  |  |  |  | 
Monona IA  | 23,967 |  $0.15  |  $3,595.05  |  $300  |  | X | X | 
Monroe IA  | 15,698 |  $0.15  |  $2,354.70  |  $300  |  |  |  | 
Mountrail ND  | 14,972 |  $0.30  |  $4,491.60  |  $300  |  | X | X | 
Mercer IL  | 11,861 |  $0.20  |  $2,372.20  |  $300  |  |  |  | 
Nicollet MN  | 15,229 |  $0.15  |  $2,284.35  |  $300  |  |  |  | 
Peoria IL  | 87,463 |  $0.10  |  $8,746.30  |  $300  |  |  |  | 
Pershing NV  | 12,054 |  $0.25  |  $3,013.50  |  $300  |  | X | X | 
Pope IL  | 7,467 |  $0.25  |  $1,866.75  |  $300  |  |  | X | 
Pulaski AR | 177,851 |  $0.10  |  $17,785.10  |  $300  |  | X |  | X
Rolette ND  | 4,848 |  $0.40  |  $1,939.20  |  $300  |  | X | X | 
St. Clair IL  | 152,462 |  $0.10  |  $15,246.20  |  $300  |  |  |  | 
Sedgwick KS  | 219,462 |  $0.10  |  $21,946.20  |  $300  |  |  |  | 
Terry TX  | 8,857 |  $0.25  |  $2,214.25  |  $300  |  | X | X | 
Torrance NM  | 30,884 |  $0.12  |  $3,706.08  |  $300  |  | X |  | X
Tuscaloosa AL  | 101,248 |  $0.10  |  $10,124.80  |  $300  |  | X |  | 
Ward ND  | 20,396 |  $0.30  |  $6,118.80  |  $300  |  |  | X | 
Washington IA  | 39,440 |  $0.12  |  $4,732.80  |  $300  |  | X |  | 
Washington IL  | 19,713 |  $0.15  |  $2,956.95  |  $300  |  | X | X | 
Wayne IL | 20,121 |  $0.15  |  $3,018.15  |  $300  |  |  | X | 
Wells ND  | 8,419 |  $0.35  |  $2,946.65  |  $300  |  |  | X | 
Webster IA  | 33,135 |  $0.12  |  $3,976.20  |  $300  |  | X |  | 
White IL | 20,595 |  $0.15  |  $3,089.25  |  $300  |  | X | X | 
Worth IA  | 11,893 |  $0.20  |  $2,378.60  |  $300  |  | X |  | 
 |  |  |  $369,863.19  |  $21,000  |  |  |  |

**Comment by nvkelso** [comment]
The ones that stick out at me as interesting are:

- Chaves NM
- Delaware IN
- Eddy NM
- Forsyth GA
- Franklin IL
- **Fulton GA** – this is a decent sized place, do we already have it covered?
- Kane IL
- **Lake IN** – another big place!
- McLean IL
- **Peoria IL** – wow!
- Pulaski AR
- St. Clair IL
- Sedgwick KS
- **Tuscaloosa AL**
