### ISSUE TITLE
Stearns County, MN Address Points

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2504]
1)is this for all parcels? No, this is from our address point layer, and only has property addresses for parcels with addressable structures.  There may be some instances where a parcel has multiple addresses if a secondary structure is also addressed on that parcel.  Also for some areas in the county, for certain platted areas, addresses were pre-assigned to the lot before the houses were built.  So there are some addresses that do not have a structure yet.  For corner lots in these areas there may be 2 addresses (one off of each street).  Only one of those would be the official address once the driveway access is established.  Is there any metadata?  There is not current metadata on this layer.

2)what are the terms of use for this dataset?  unlimited

3)how often is this updated? New addresses are added as requested.  We are looking at adding it to our FTP site for public access starting Q2.  Once that happens it will be available for download quarterly.

Thank you,
Dan

Daniel J. Schmitz
Senior GIS Specialist
Stearns County Auditor/Treasurer's Office
705 Courthouse Square
St. Cloud, MN 56303
(320) 654-4689
daniel.schmitz@co.stearns.mn.us

**Comment by justinelliotmeyers** [comment]
[Address_Points_Lat_Long.xlsx](https://github.com/openaddresses/openaddresses/files/761875/Address_Points_Lat_Long.xlsx)

**Comment by iandees** [comment]
Converted to CSV and uploaded to S3: https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/iandees/2433c6/Address_Points_Lat_Long.csv.zip

**Comment by nvkelso** [comment]
This is north-west of Minneapolis–St-Paul, with big city for the county being St. Cloud.

**Comment by trescube** [comment]
@iandees That export has `^M`s which caused issues with the machine.  I re-exported and uploaded to cache at https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/trescube/d09cac/Address_Points_Lat_Long.csv.zip

**Comment by trescube** [comment]
Hmm... other errors now

**Comment by trescube** [comment]
Fixed in #2522
