### ISSUE TITLE
Warren County, Ohio Issues?

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2510]
I downloaded the 	us_midwest.zip 706MB

and noticed Warren County Ohio is missing.

Found data here: http://www.co.warren.oh.us/warrengis/Downloads.aspx *license looks okay when clicking through terms to accept

But I believe we already have the data: http://results.openaddresses.io/sources/us/oh/warren - looks like an error for some reason

**Comment by nvkelso** [comment]
Suburbs north of Cincinnati.

**Comment by trescube** [comment]
w00t!  The GDB includes address points!

**Comment by trescube** [comment]
Oh, the current source is failing because they've managed to turn off programmatic access somehow to the machine.  pyesridump gets it, though.
