### ISSUE TITLE
Monroe County, Ohio Issues/ New Source

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2511]
http://results.openaddresses.io/sources/us/oh/monroe

I downloaded what we have and it looks stale. After finding new parcel data: https://geo.oit.ohio.gov/arcgis/rest/services/parcels/monroeparcels/MapServer/0

There seems to be more parcels with addresses. *The address points we do have are shifted and off in some cases. 

![monroe_oh](https://cloud.githubusercontent.com/assets/5324316/22783733/19d9764c-ee9b-11e6-9778-87beee54fc8d.jpg)

**Comment by nvkelso** [comment]
Rural area south of Wheeling WV, in Ohio.

**Comment by trescube** [comment]
This data is pretty unreliable.  There are only 7988 records that are prefixed with a house number whereas the existing source has 8313 records, all with a house number.  The parcels layer street names are often w/o a type as well:

- 51677 MAIN
- 42890 WEST UNION
- 209 ROY

I recommend that we stick with what we have.
