### ISSUE TITLE
Imperial County, California Data Request

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2515]
emailed Imperial County - assessor@co.imperial.ca.us

http://www.co.imperial.ca.us/Assessor/FIRelease.html

data here: http://services.geoviewer8.com/arcgis/rest/login?redirect=http%3A//services.geoviewer8.com/arcgis/rest/services/ImperialCounty_Public/MapServer/

**Comment by nvkelso** [comment]
This is a dup of https://github.com/openaddresses/openaddresses/issues/2207.

**Comment by justinelliotmeyers** [comment]
Sorry!? Wasn't in download for counties and in us west
