### ISSUE TITLE
Tel Aviv, Israel Addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2523]
I believe these are addresses (spot checked one street and they have numbers and what appear to be names ;)

![tel_aviv](https://cloud.githubusercontent.com/assets/5324316/22928710/d1af15a4-f285-11e6-91c7-5830b04fa25a.jpg)

https://gisn.tel-aviv.gov.il/arcgis/rest/services/IView2MapEngWM/MapServer/1

**Comment by nvkelso** [comment]
Dude, nice find!
