### ISSUE TITLE
Cumberland County, NC Parcels/ Addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2531]
![cumberland_nc](https://cloud.githubusercontent.com/assets/5324316/23021407/cc3fc9ca-f419-11e6-8bfe-6da6f1a98b56.jpg)

Parcels: http://gis.co.cumberland.nc.us/arcgis_public/rest/services/TaxParcelViewer/Parcels_2017/MapServer/0

Addresses (*not sure if values will work for these): http://gis.co.cumberland.nc.us/arcgis_public/rest/services/TaxParcelViewer/Addresses/MapServer/0

**Comment by trescube** [comment]
The addresses look good, the field name are just a bit cryptic.
