### ISSUE TITLE
Pickens County, SC Address Points

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2532]
![pickens_sc](https://cloud.githubusercontent.com/assets/5324316/23021649/03ff1aea-f41b-11e6-967a-705c996a2db0.jpg)

https://services1.arcgis.com/59960rq18IxUcAVI/arcgis/rest/services/Pickens_Open_data/FeatureServer/0

source:http://opendata.arcgis.com/datasets/pickenscosc::address-points

**Comment by trescube** [comment]
This was taken care of in #2527 and #2529

**Comment by justinelliotmeyers** [comment]
sorry; never saw it in the downloads section; thought i checked before I created the issue.

**Comment by trescube** [comment]
Oh, no problem, thanks for double checking!
