### ISSUE TITLE
Wright County, Iowa

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2595]
I have received your request.  I have attached a GIS data request contract for your review.  Should you still want the information, please fill out the request contract and return to me. 
 
If you have any questions, please give me a call.
 
 
Shari Plagge, ICA
Wright County Assessor
115 N. Main
PO Box 428
Clarion, IA  50525
(515) 532-3737 office
(515) 532-3501 fax
splagge@co.wright.ia.us

**Comment by justinelliotmeyers** [comment]
https://www.dropbox.com/s/f3tj9trqtb1usx1/Data%20request%20contract.doc?dl=0

**Comment by justinelliotmeyers** [comment]
I emailed and asked if there was a newer version of the agreement (since this one is from 2006). I also asked if data can be redistributed; response below:

Justin,
 
Our Board adopted this policy in 2006.  Generally the cost today is for the time spend to gather the information and the cost of the media (since GIS requests are usually too large for us to send via email they are put on a USB flash drive).  You can use the data to make your own product to distribute in your own format. 
 
 
Shari Plagge, ICA
Wright County Assessor
115 N. Main
PO Box 428
Clarion, IA  50525
(515) 532-3737 office
(515) 532-3501 fax
splagge@co.wright.ia.us

**Comment by iandees** [comment]
Can't use it:

> Unauthorized Use.  The User shall not sell, loan, rent, assign, distribute or otherwise transfer the Product in any digital form or format, (including, but not limited to, networks, timesharing, or multiple CPU arrangements).

**Comment by justinelliotmeyers** [comment]
I saw that and is why I asked about a newer version of the license and if it can be redistributed; "You can use the data to make your own product to distribute in your own format."

how should we handle situations like this when license that needs to be signed says no, but the phone calls/ emails say go ahead!?

**Comment by iandees** [comment]
Ideally they would send over a new agreement with the restrictive parts removed so we could sign it. Another idea is that we could strike out those parts of the agreement and ask them to to counter-sign the updated version, but they might not have the authority to do that...

**Comment by justinelliotmeyers** [comment]
just got off the phone with her;
we can derive data and incorporate into OA and host that for free like we have been.
we cannot buy, copy, and sell.

we can only sign license as is - no striking out terms/ altering/ etc.

So I'm not sure where this leaves us.

Her contact info is here:
Shari Plagge, ICA
Wright County Assessor
115 N. Main
PO Box 428
Clarion, IA  50525
(515) 532-3737 office
(515) 532-3501 fax
splagge@co.wright.ia.us

**Comment by nvkelso** [comment]
We can try what Ian suggests (and I think Ian would be the one to initiate
that since he has legal OA authority), and if she signs it good, else we’re
SOL.

**Comment by justinelliotmeyers** [comment]
no data
