### ISSUE TITLE
California State Data

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2596]
In contact with a few people as per a state-wide address dataset. No returned e-mails since 2/3/2017... But I did find this; perhaps a state-wide parcel dataset for residential areas?

http://services.gis.ca.gov/arcgis/rest/services/Boundaries/Parcels_Residential/MapServer/0

**Comment by justinelliotmeyers** [comment]
Just got off the phone with john - he cannot share data as per license agreement. He does have a UCD dataset of parcels with only APN field. Although this will not help us, I asked for it anyway ;)

He said several counties in the state are under agreement w third party vendor http://www.parcelquest.com/

**Comment by nvkelso** [comment]
Most the remaining small counties in California are locked up in Parcel
Quest, sadly.

**Comment by justinelliotmeyers** [comment]
no state wide initiative (according to John) for a pacel/ address dataset.

**Comment by nvkelso** [comment]
We have almost all of the data in California anyhow.

For completeness on the 1/2 dozen missing counties it might be interesting
to get a list of addresses from the county in question, and then run them
thru Mapzen search to geocode them using the Tiger information. I suspect a
lot of address point data we get from counties start off life that way, and
then is moved onto buildings in a cleanup step. Right now this isn’t
priority.

**Comment by jalessio** [comment]
@justinelliotmeyers I'm not sure if this data different than the what you linked to on services.gis.ca.gov so just throwing this into the mix. I've come across this statewide parcel boundary dataset before. Unfortunately, it only only contains the geometries and the parcel ID:

https://egis3.lacounty.gov/dataportal/2015/09/11/california-statewide-parcel-boundaries/

That page points to a ~3.1 GB zip file:
http://egis3.lacounty.gov/dataportal/wp-content/uploads/ShapefilePackages/Parcels_CA_2014.zip

@nvkelso I never thought about reverse geocoding to attach known address points to parcels... that's an interesting idea.

**Comment by iandees** [comment]
(Note that OpenAddresses is looking for primary sourced data, so I wouldn't want us to ingest generated data like geocoded address lists)

**Comment by jalessio** [comment]
@iandees yes, I veered the discussion off course there... didn't mean to imply that was suitable for ingestion into openaddresses, but instead as a potential use of openaddresses' sourced data.

**Comment by iandees** [comment]
No worries. I didn't mean to halt conversation.

**Comment by ingalls** [comment]
Stale
