### ISSUE TITLE
Lee County, GA data issue

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2598]
several times when I try to import tables into arcgis, they error out on the STREET field. typically I just change the length of the field to 500 and don't care. I'm getting ready to fill in suburb voids for ATL and brought in the state. I found this in the STREET field for Lee

"Atkinson_out.csv Berrien_out.csv Brantley_out.csv Camden_out.csv Charlton_out.csv clean.sh Colquitt_out.csv Cook_out.csv Glynn_out.csv Lanier_out.csv Lee_out.csv Mitchell_out.csv node_modules package.json README.md run.sh test.sh Turner_out.csv util "

I've seen stuff like this before in other tables, not sure how it's happening - just wanted to bring to groups attention.

Thanks,
Justin

**Comment by nvkelso** [comment]
@justinelliotmeyers Can you clarify which OpenAddress data file you're seeing the `Atkinson_out.csv ...` content, please?

**Comment by justinelliotmeyers** [comment]
Sorry!

https://s3.amazonaws.com/data.openaddresses.io/runs/162051/us/ga/lee.zip

**Comment by migurski** [comment]
I peeked in the log, and it looks like our data source has these values. It was cached in late 2015, clearly we need a new one: https://s3.amazonaws.com/data.openaddresses.io/runs/162051/output.txt

**Comment by justinelliotmeyers** [comment]
![lee_ga](https://user-images.githubusercontent.com/5324316/48422789-6216b500-e72d-11e8-973d-7cca92cb1e8f.png)


STAY TUNED!

**Comment by ingalls** [comment]
Tracking fix: https://github.com/openaddresses/openaddresses/pull/4256
