### ISSUE TITLE
Dekalb County, GA

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2599]
http://maps.dekalbcountyga.gov/arcgis/rest/services/TaxParcels/MapServer/2

**Comment by iandees** [comment]
There's address points at:
http://maps.dekalbcountyga.gov/arcgis/rest/services/TaxParcels/MapServer/2

**Comment by justinelliotmeyers** [comment]
thats the same link; did you mean something different!?

**Comment by iandees** [comment]
Nope... I think I got the Polk's mixed up when I was checking your existing URL.

**Comment by nvkelso** [comment]
Fixed in https://github.com/openaddresses/openaddresses/pull/2625.
