### ISSUE TITLE
Coweta County, GA 

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2608]
E-mailed 02/28/2017 7:00 a.m. EST

Clint Richmond
GIS Analyst, Information Technology  
22 E Broad Street, Suite 252
Newnan, GA 30263 
crichmond@coweta.ga.us 
678-854-0029 

website:http://www.coweta.ga.us/index.aspx?page=685

**Comment by justinelliotmeyers** [comment]
Justin,
 
We can provide this data for free since it has to do with a governmental project or database; however we do need you to fill out our annual data exchange agreement.  Please sign, scan, and return. 
 
Then I can put this data together for you.
 
Thanks,
 
Adam Ray
GIS Technician, Information Technology
Coweta County Board of Commissioners
22 East Broad Street, Suite 250
Newnan, GA 30263
aray@coweta.ga.us
http://www.coweta.ga.us
(770)254-3716 x8213
[CowetaCountyDataExchangeAgreement v080516.pdf](https://github.com/openaddresses/openaddresses/files/807189/CowetaCountyDataExchangeAgreement.v080516.pdf)

**Comment by justinelliotmeyers** [comment]
not sure how to handle this!?

**Comment by justinelliotmeyers** [comment]
@iandees or @nvkelso thoughts? Thanks!

**Comment by nvkelso** [comment]
I think @iandees needs to do the honors with signature.

**Comment by msirenko** [comment]
Looks like Coweta has an ESRI server: http://gis.coweta.ga.us/arcgis/rest/services/Parcels/MapServer/0

Is this usable for our purposes?

**Comment by nvkelso** [comment]
@msirenko Yes, looks like it! Here's a preview:

- http://www.arcgis.com/home/webmap/viewer.html?url=http%3A%2F%2Fgis.coweta.ga.us%2Farcgis%2Frest%2Fservices%2FParcels%2FMapServer&source=sd

<img width="847" alt="screen shot 2017-06-13 at 16 05 07" src="https://user-images.githubusercontent.com/853051/27108462-23731f00-5052-11e7-80f1-d6cb6f1b4118.png">

**Comment by migurski** [comment]
Lovely render; surprising to see something look so nice out of an automated tool.

**Comment by trescube** [comment]
Points are here:  http://gis.coweta.ga.us/arcgis/rest/services/AddressPoints/MapServer/0
