### ISSUE TITLE
Cobb County, GA Parcels

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2609]
http://www.cobbgis.org:81/arcgislb1/rest/services/tax/cobbparcelsmap_wgs/MapServer/3

**Comment by nvkelso** [comment]
Looks like there is a "House Numbers" source there, too:

- http://www.cobbgis.org:81/arcgislb1/rest/services/tax/cobbparcelsmap_wgs/MapServer/0

**Comment by nvkelso** [comment]
Fills big hole in Atlanta area!

<img width="549" alt="screen shot 2017-02-28 at 09 12 47" src="https://cloud.githubusercontent.com/assets/853051/23416056/2694938a-fd96-11e6-8bbc-c7c998f96130.png">

**Comment by nvkelso** [comment]
Some PR fixed this.
