### ISSUE TITLE
Haralson County, GA

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2613]
e-mailed county 02/28/2017 7:20 am EST

Sherri R. Mobley, Tax Commissioner - Office Hours Monday - Friday 8:00 AM - 4:30 PM

Office address:
4276 Georgia Highway 120
Buchanan, GA  30113

Mailing address:
PO Box 330
Buchanan, GA 30113

Phone: (770) 646-2020
Fax: (770) 646-8677
Email: taxcomm@haralsoncountyga.gov

**Comment by justinelliotmeyers** [comment]
I have forwarded your email to the Haralson County Tax Assessor’s Office.  Our office is for collection only. 
 
 
Thanks,
Sherri R. Mobley
Haralson County Tax Commissioner
P O Box 330
Buchanan, Georgia  30113
770-646-2020
770-646-8677 fax
taxcomm@haralsoncountyga.gov

**Comment by nvkelso** [comment]
Far exurbs of Atlanta, pretty small county.

**Comment by justinelliotmeyers** [comment]
Hi Justin,

Hubert asked me to contact you about our GIS data.  We have copy rights & a cost for our data.

    $1,500.00 for the GIS parcel shape file on CD and copy to be signed.

The parcel shape we have, but no current data for address points.


Eve

770-646-2022

**Comment by nvkelso** [comment]
Doh! Let's skip this for now.

**Comment by justinelliotmeyers** [comment]
no data
