### ISSUE TITLE
Henry County, GA

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2614]
emailed 02/28/2017 7:26 EST
schitwood@co.henry.ga.us
140 Henry Pkwy
McDonough, GA 30253
Tel: (770) 288-6278
Fax: (770) 288-7550 

website: http://www.co.henry.ga.us/gis/

**Comment by justinelliotmeyers** [comment]
sabrina sent a download link for the parcels: https://www.dropbox.com/l/scl/AADWmk-W8-oEfpEEWWjeGYjOvS6MzkpQ5jQ

**Comment by iandees** [comment]
Can you download and post to S3? It's only shared with you.

**Comment by justinelliotmeyers** [comment]
i just saw that - my S3 uploader has never worked ;) I am downloading now and will upload to dropbox - give me five minutos amigo!

**Comment by justinelliotmeyers** [comment]
https://www.dropbox.com/sh/uasfwkzc4wi9xhz/AAAXbaejkLDSqGyKm0_7rrILa?dl=0

**Comment by nvkelso** [comment]
Uploaded to: 

- https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/nvkelso/fbd853/Henry-county-GA-parcels.zip
