### ISSUE TITLE
Polk County, GA

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2617]
emailed 02/28/2017 7:30 am EST
taxoffice@polkga.org

Polk County Tax Commissioner - Kathy Cole
144 West Avenue
Suite A
Cedartown, Georgia 30125
Phone: (770) 749-2125
Fax: (770) 749-2149

316 N. Piedmont Avenue
Rockmart, Georgia 30153
Phone: (770) 684-3185
Fax: (770) 684-2575

Site:http://www.polkgeorgia.org/CountyDepartments/TaxCommissioner/tabid/66212/Default.aspx

**Comment by nvkelso** [comment]
Exurbs of Atlanta that fills a hole.

**Comment by justinelliotmeyers** [comment]
no data
