### ISSUE TITLE
Chattooga County, Georgia

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2618]
emailed 7:40 am EST
 
Joy Cooper Hampton, Tax Commissioner
Chattooga County, Georgia
Email: joyhtaxcommissioner@gmail.com

Office Hours:
Monday through Friday, 8:30 a.m. – 5:00 p.m. CLOSED MOST MAJOR HOLIDAYS.

Phone: 706.857.0703

Fax: 706.857.0748

Mailing Address: 
P.O. Box 517
Summerville, GA 30747-0517

Physical Address:
Courthouse Annex, 120 Cox Street
Summerville, GA 30747

site:https://www.chattoogacountygatax.com/#/contact

**Comment by nvkelso** [comment]
Almost too far from Atlanta to be considered an exurb, pretty small place.

**Comment by justinelliotmeyers** [comment]
sent follow-up email

**Comment by justinelliotmeyers** [comment]
no data
