### ISSUE TITLE
Floyd County, GA

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2619]
data is here: https://gis01.romega.us/arcgis/rest/services

but I cannot get past 
Error: Services Directory has been disabled

Source: http://gis.romega.us

Maybe @trescube or @iandees can work their magic on this!?

**Comment by iandees** [comment]
There's parcels here: https://gis01.romega.us/arcgis/rest/services/Parcels/MapServer/0?f=json

I can't tell if the address-related fields there are situs or mailing, though.

**Comment by arch0345** [comment]
Resolved in #4578
