### ISSUE TITLE
Haines Borough, Alaska

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2634]
http://services3.arcgis.com/pMlUMMROURtJLUZt/ArcGIS/rest/services/hainesborough_parcels07312015/FeatureServer/0

![haines_borough](https://cloud.githubusercontent.com/assets/5324316/23507020/177ada24-ff19-11e6-8976-c9d50dfa344f.jpg)

**Comment by trescube** [comment]
Contains no addresses.  There's an address field but it's for owner details, not physical address.

**Comment by justinelliotmeyers** [comment]
dang. I saw the ADDRESS1 and ADDRESS2 fields and thought it would have something
I'll e-mail them and see
Sorry about that

**Comment by trescube** [comment]
No problem, good to explore.

**Comment by justinelliotmeyers** [comment]
received a call - they should be sending the data soon.

**Comment by justinelliotmeyers** [comment]
received a fgdb - erroring out. emailed back and asked for shapefile from:
Holly Smith
Borough Planner
Haines Borough
103 Third Avenue S.
PO Box 1209
Haines, AK 99827
www.hainesalaska.gov
hsmith@haines.ak.us
Phone: (907) 766-2231 ext. 23
Fax: (907) 766-2716

**Comment by justinelliotmeyers** [comment]
holly is going to send data this week!

**Comment by justinelliotmeyers** [comment]
https://www.dropbox.com/s/0m0gtlnoablvt72/HainesAddress42017.zip?dl=0

**Comment by justinelliotmeyers** [comment]
updated ready for pr although it is still in shapefile format.
