### ISSUE TITLE
São Paulo, Brazil

### ISSUE THREAD

**Issue by lxbarth** [openaddresses/openaddresses#266]
From @vgeorge on [OSM/talk-br](https://lists.openstreetmap.org/pipermail/talk-br/2014-July/008556.html):

> The Geolog dataset is a polygon shapefile where each element has name and address number ranges on both sides of the street. We would need to transform this to OpenAddresses data model and give attribution at the project page.
> 
> The file is available here:
> 
> http://www.prefeitura.sp.gov.br/cidade/secretarias/upload/desenvolvimento_urbano/dados_estatisticos/arquivos/20131203_geolog.zip
> 
> On the wiki:
> 
> https://wiki.openstreetmap.org/wiki/Geolog_PMSP_Import
> 
> Right now I'm focused in importing water streams data to OSM, but I can have a look later on how to add Geolog to OpenAddresses.

**Comment by tiagofassoni** [comment]
I talked to some people at the São Paulo city hall, the license question can be resolved.

Is there going to be support to address interpolation?

Thanks!

**Comment by justinelliotmeyers** [comment]
@lxbarth I am going to close this out as we have a nation wide dataset including São Paulo, Brazil (https://openaddresses.io/dotmap.html#9.57/-23.6446/-46.5818 ) Thanks!
