### ISSUE TITLE
Add data in Branson MO

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#2661]
Currently a hole in the map.

- ftp://msdis.missouri.edu/pub/Cadastral/MO_2009_Taney_County_Parcel_Polygons_shp.zip
- metadata: ftp://msdis.missouri.edu/pub/metadata_gos/MO_2009_Taney_County_Parcel_Polygons_shp.xml

Found on a Missouri data depot:

- http://www.msdis.missouri.edu/data/datalist.html#list

**Comment by trescube** [comment]
The first doesn't contain any address info.  Did you see that elsewhere?

**Comment by nvkelso** [comment]
Doh! I also don’t see address info, but there is a parcel identifier. I’ve
sent email to patsya@co.taney.mo.us (listed in the metadata) to ask for the
address components.

**Comment by nvkelso** [comment]
Got an email back, linking to:

https://beacon.schneidercorp.com/Application.aspx?AppID=26&LayerID=155&PageTypeID=2&PageID=277

But I don't see a download button there. Asking for clarification via email.

**Comment by nvkelso** [comment]
County says they don't have the data. Will look into getting the data from the Schneider link, or looking into a FOIA.

**Comment by trescube** [comment]
There are quite a number of counties behind Schneider in that area of the country and that state specifically.  Being able to scrape it would be quite a boon.

**Comment by nvkelso** [comment]
So oddly enough Schneider claims Branson is **not** a customer, even though they have data on that website!?

Bottom line for the other Schneider counties in MO: $1000 gets one parcels with addresses (that's $1000 per county). Terms of use vary and would need to be confirmed per county, list below:

- Audrain
- Callaway
- Cass
- City of Wildwood
- Greene
- Jasper
- Pettis
- Pike
- Platte
- Taney

$1000 is at the far limit of my petty cash allowance. So maybe one of these is interesting, but not all of them.

**Comment by justinelliotmeyers** [comment]
no data
