### ISSUE TITLE
Coffey, Kansas

### ISSUE THREAD

**Issue by chdean** [openaddresses/openaddresses#2662]
Address points shapefile provided by the county GIS department:

https://drive.google.com/file/d/0B_e3BsntC0LUZ2FNTGJfV0Jmcms/view?usp=sharing

**Comment by iandees** [comment]
Thanks! Can you provide more information about how you got this data, if we have permission to share it/redistribute it?

**Comment by chdean** [comment]
Cara Mays, the county's GIS specialist, sent it after I explained that OpenAddresses would redistribute. Their agreement only prohibits commercial use.
[GIS Open Records Request (EMAIL).pdf](https://github.com/openaddresses/openaddresses/files/829349/GIS.Open.Records.Request.EMAIL.pdf)

GIS Department	
Coffey County Courthouse	
110 S 6th St, Room 202 
Burlington, KS 66839

Telephone: 620-364-8426 or 800-947-5351	

Fax: 620-364-8428

**Comment by iandees** [comment]
Gotcha, thanks. For the record, the agreement prevents collecting a list of names for the purpose of sales. It doesn't necessarily prevent commercial use.

**Comment by chdean** [comment]
Ah, I see that now rereading it. Thanks.

I'm happy to do the PR, but I don't think I have access to upload to the S3 bucket.

**Comment by iandees** [comment]
Here ya go: https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/iandees/903d8a/CF_OpenAddresses.zip

**Comment by chdean** [comment]
#2664

**Comment by iandees** [comment]
I'm going to keep this open until the pull request closes it.

**Comment by nvkelso** [comment]
For those following along at home, a rural area between Kansas City and Wichita.
