### ISSUE TITLE
Ogle County, Illinois

### ISSUE THREAD

**Issue by chdean** [openaddresses/openaddresses#2675]
Available at $.25/record for 23,400 address points ($5850). Their license normally does not allow redistribution, but they said they might be able to make an exception for our purposes if we submit a request.

http://oglecounty.org/departments/gis-department/digital-data/

Ogle County GIS
Ogle County Courthouse
105 S. 5th Street; Suite 202
Oregon, IL 61061
Phone: (815) 732-1153
Hours: 7 a.m. – 4:30 p.m.
e-mail:  gis @ oglecounty.org

**Comment by nvkelso** [comment]
Exurbs of Chicago.

**Comment by nvkelso** [comment]
That's past my petty cash limit, so marking this for a raining money day.

**Comment by justinelliotmeyers** [comment]
no data
