### ISSUE TITLE
Dakota County, MN   us_mn_dakota

### ISSUE THREAD

**Issue by fawcett** [openaddresses/openaddresses#268]
Address points for Dakota County, MN

The address file is at:  http://gis.co.dakota.mn.us/WebsiteGISData/propertyinfo/fgdb/PROPERTYINFO_Addresses.zip

The page describing all available datasets and their terms of use are found at:  http://www.co.dakota.mn.us/HomeProperty/MappingServices/GISData/Pages/default.aspx

Note:  Data is in Dakota County Coordinate SRS:  http://www.co.dakota.mn.us/HomeProperty/MappingServices/GISData/Documents/DakotaCountyMNCoordinatesFeet1.zip

It appears as though the only restrictions on use is that if you redistribute their data, you include their disclaimer and metadata.

**Comment by justinelliotmeyers** [comment]
@fawcett I am going to close out this issue as we currently have a source that is being updated every week by DC. you can see the updates: http://results.openaddresses.io/sources/us/mn/dakota
Cheers!

**Comment by fawcett** [comment]
Cool. My goal was just to help make sure that OpenAddresses was pointed at a good source for Dakota's data. There are individuals at Dakota, and the org itself are doing progressive things with their data. Thanks!
