### ISSUE TITLE
Harrison, MO

### ISSUE THREAD

**Issue by ltuff** [openaddresses/openaddresses#2686]
County Assessor Lily Craig charges $200 for the record. 

Contact Lila Craig, City Assessor harco@grm.net

**Comment by nvkelso** [comment]
For GIS shapefile Data?

**Comment by ltuff** [comment]
Yes, that is correct and can not be used for resale. For future reference, unless otherwise noted, it is for GIS shapefile or CSV data.

**Comment by nvkelso** [comment]
8,000 pop small sized county

**Comment by justinelliotmeyers** [comment]
no data
