### ISSUE TITLE
Colorado State Wide Parcels/ Addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2690]
https://data.colorado.gov/Local-Aggregation/2016-Colorado-Parcels-Layer-Public-/izys-vycy
https://gisftp02.state.co.us/#/c.StateLevelAgencies/GOV/OIT/CSO/GIS/CY2016/Parcels/

**Comment by justinelliotmeyers** [comment]
this may also help: https://data.colorado.gov/Transportation/Colorado-Address-Layer-Public-/n7je-akky

**Comment by nvkelso** [comment]
I found this from a different angle searching for precinct shapefiles:

- https://gisftp02.state.co.us/#/c.StateLevelAgencies/GOV/OIT/CSO/GIS/CY2016/Parcels/

Counties that are special here not already included in OpenAddresses look to include:

- **Morgan**	9.79 mb
- **Ouray**	2.59 mb
