### ISSUE TITLE
New York State address data - asking for advice on how to post this.. 

### ISSUE THREAD

**Issue by nygeog** [openaddresses/openaddresses#281]
The web url is https://gis.ny.gov/gisdata/inventories/details.cfm?DSID=921

I have it in CSV and shp and could format it to match the geojson. 

Thanks
Danny

**Comment by slibby** [comment]
I think this issue can be closed as the data has been successfully integrated here: https://github.com/openaddresses/openaddresses/blob/master/sources/us/ny/statewide.json
