### ISSUE TITLE
Cornwall, UK

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2856]
https://map.cornwall.gov.uk/arcgis/rest/services/inspire/inspire_landbuildings/MapServer/1 (has address field)

or addresses here: https://map.cornwall.gov.uk/arcgis/rest/services/property/MapServer/1

**Comment by nvkelso** [comment]
The about page makes it sound like all the content is OS and crown
copyright, so no-go.
