### ISSUE TITLE
Santa Rosa County, FL

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2859]
http://arcgis4.roktech.net/arcgis/rest/services/santarosa/GoMaps4_0/MapServer/2

**Comment by trescube** [comment]
Too slow!  I was on a tear on http://arcgis4.roktech.net/arcgis/rest/services/ at the end of last week and imported what I could find.  Santa Rosa was taken care of in #2824 .

**Comment by justinelliotmeyers** [comment]
haha - looking for airports for my coworker and found: https://en.wikipedia.org/wiki/Naval_Outlying_Field_Spencer

checked their gis for S and G and found it!

**Comment by justinelliotmeyers** [comment]
i recall finding the roktech at starbucks before I left for CR... lots of little gems in there
