### ISSUE TITLE
Barbados Address Points

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2871]
email sent:  contact@townplanning.gov.bb
http://www.townplanning.gov.bb

**Comment by brianjd** [comment]
@justinelliotmeyers Did you ever receive a response?

**Comment by justinelliotmeyers** [comment]
no, I just e-mailed them again. Some countries agencies are really bad at e-mail responses, but it could have went in their junk folder. A call might be best if this doesn't work.

**Comment by brianjd** [comment]
@justinelliotmeyers I'm curious, did they actually respond?

**Comment by justinelliotmeyers** [comment]
No. If any agencies respond, I put it in the tickets. Caribbean nations rarely do. I believe the best way to contact them is in person or by phone.
