### ISSUE TITLE
Additional Arkansas Statewide source

### ISSUE THREAD

**Issue by slibby** [openaddresses/openaddresses#2872]
http://gis.arkansas.gov/arcgis/rest/services/FEATURESERVICES/Planning_Cadastre/MapServer/0

Source: http://gis.arkansas.gov/2017/04/18/parcel-update-62-counties/

**Comment by trescube** [comment]
Points here:  http://gis.arkansas.gov/arcgis/rest/services/FEATURESERVICES/Location/MapServer/14

Pulling down now to check out counts and quality.

**Comment by trescube** [comment]
Description says it includes: "City of Harrision, City of Hope, City of Jonesboro, City of Paragould, City of Cabot, City of Pine Bluff, Baxter, Benton, Bradley, Calhoun, Carroll, Chicot, Clark, Cleburne, Cleveland, Columbia, Crawford, Cross, Dallas, Desha, Drew, Faulkner, Grant, Greene, Hot Spring, Howard, Izard, Jefferson, Johnson, Lafayette, Lawrence, Lee, Lincoln, Little River, Logan, Madison, Marion, Miller, Mississippi, Monroe, Montgomery, Nevada, Newton, Perry, Pike, Poinsett, Polk, Pope, Prairie, Pulaski, Ouachita, Randolph, Saline, Scott, Searcy, Sebastian, Sevier, Sharp, Stone, Union, Van Buren, Washington, White, Woodruff, Yell "

Which is 58 of the 114 counties + a smattering of cities.

**Comment by trescube** [comment]
The parcels layer contains 44 counties and only overlaps a bit with the points source.  Good data in both.

**Comment by trescube** [comment]
Well, upon revisiting, I had apparently been comparing Missouri county names with Arkansas county names.

**Comment by trescube** [comment]
According to the [site](http://gis.arkansas.gov/?product=situs-address-points) we're currently pulling the SHP file from, it hasn't been updated since 2016-08-02.  That bears out in the record counts, too, with 1,446,586 from the SHP file and 1,448,324 from ESRI.

**Comment by justinelliotmeyers** [comment]
@slibby @trescube closing if that is okay - currently have two other resources for state addresses/ parcels. Now I'm going county by county.

Let me know, Thanks!
