### ISSUE TITLE
Scotland Address Data Request Sent

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2878]
http://www.onescotlandgazetteer.org.uk/

https://www.spatialdata.gov.scot/geonetwork/srv/eng/catalog.search#/metadata/250ea276-48e2-4189-8a89-fcc4ca92d652

https://data.gov.uk/dataset/one-scotland-gazetteer

**Comment by justinelliotmeyers** [comment]
HI Justin, 

Are you familiar with the dataset?
What is your intended use for the data?

The One Scotland Gazetteer dataset is actually licenced under the One Scotland Mapping Agreement. 

For non-members, an Ordnance Survey contractor’s licence is required: https://www.ordnancesurvey.co.uk/business-and-government/licensing/partners/

Regards,

Ron

-------------------------- 
Ron Wilkinson 
One Scotland Gazetteer Custodian | Improvement Service 
iHub, Quarrywood Court, Livingston, EH54 6AX | How to find us
www.onescotlandgazetteer.org.uk
‘The Improvement Service is a UK Living Wage Employer’.

**Comment by justinelliotmeyers** [comment]
Hi Justin, 

Address data in the UK is complicated by intellectual property rights; specifically local government, Royal Mail, and Ordnance Survey. 

In short, there is not an open dataset of all UK addresses available. 

You are right in saying that address data is included in INSPIRE (annex 1) – however, being INSPIRE compliant does not mean that the data must be open and available free of charge. 

Happy to discuss further – if you send me your contact phone number. There’s many nuances of address data in the UK which surprise a lot people!

Regards,

Ron

-------------------------- 
Ron Wilkinson 
One Scotland Gazetteer Custodian | Improvement Service 
iHub, Quarrywood Court, Livingston, EH54 6AX | How to find us
www.onescotlandgazetteer.org.uk

**Comment by nvkelso** [comment]
Face palm:

"You are right in saying that address data is included in INSPIRE (annex 1)
– however, being INSPIRE compliant does not mean that the data must be open
and available free of charge.”

Well, it was worth asking :)

**Comment by justinelliotmeyers** [comment]
no data
