### ISSUE TITLE
East Feliciana Parish, LA Parcels

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2881]
http://services1.arcgis.com/fe3XWHMASK948q2c/ArcGIS/rest/services/EastFelParcels/FeatureServer/0

**Comment by nvkelso** [comment]
North of Baton Rouge. 

<img width="938" alt="screen shot 2017-04-20 at 16 32 20" src="https://cloud.githubusercontent.com/assets/853051/25256621/01eac09e-25e7-11e7-80a6-02bac871ad96.png">
