### ISSUE TITLE
Cherokee County, SC Address Points

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2884]
Assessor told me to reach out to e911:
911 Addressing is located at:
110 Railroad Avenue
Gaffney, SC 29340
Phone: 864.902.2250
Fax: 864.902.1100
Lori Kidd, Coordinator  
Email: lori.kidd@cherokeecountysc.com

called and left  a voicemail

**Comment by justinelliotmeyers** [comment]
just spoke on the phone - she said no sharing. I asked why not. She said you have to sign disclaimer. Coming soon...

**Comment by justinelliotmeyers** [comment]
Justin,
Our data IS public record from our website.  However, it is not downloadable. 
Based on the conversation we just had, I’d like to point out a few points:
NG911 is still in the future for South Carolina.  Our state is not NG911 ready.
I work FOR 911 and they have full use of the address points.  I provide them with EACH layer they use to dispatch emergency service personnel.  The ‘taxpayers’ that you mentioned are not suffering because we may or not release our data to your website.
Following the link that you provided, I ascertained that all data that is placed on your site and is made downloadable from your site which will make you or supervisor’s ability to sign our disclaimer impossible.  Maybe I was too quick to make that assumption without sending to you.
I have attached a copy of the disclaimer for your review.
 
Thanks,
 
 
Lori Kidd
Cherokee County
Addressing/Mapping
110 Railroad Ave
Gaffney  SC  29340
864-902-2250

she said we could not sign this... but I am no lawyer!? https://www.dropbox.com/s/ra04oicguos78nn/disclaimer.doc?dl=0

Can someone review this @nvkelso @iandees

**Comment by iandees** [comment]
She is correct. We can't distribute data from them "WITHOUT THE PRIOR EXPRESS WRITTEN APPROVAL OF CHEROKEE COUNTY". It sounds like she's not going to give us that 😄 .

**Comment by nvkelso** [comment]
@justinelliotmeyers I changed the label to `bad-license` as I've been using `prohibitive` for things that cost more than $300.

**Comment by justinelliotmeyers** [comment]
sorry! Thanks for taking care of that ;)

**Comment by iandees** [comment]
When we get a Beacon Schneider scraper running we can just get their data from https://qpublic.schneidercorp.com/Application.aspx?App=CherokeeCountySC&Layer=Parcels&PageType=Map

The license on that page says nothing about redistribution limitations.

**Comment by justinelliotmeyers** [comment]
I <3 @iandees !!!!!!!!!!!!!!!

**Comment by nvkelso** [comment]
Re-opening issue if that's the case.

**Comment by justinelliotmeyers** [comment]
killing if we cant get data - thoughts @ian @nvkelso

**Comment by iandees** [comment]
Yep, go ahead.

**Comment by justinelliotmeyers** [comment]
no data. good bye!
