### ISSUE TITLE
US-VA-Charlottesville

### ISSUE THREAD

**Issue by ingalls** [openaddresses/openaddresses#291]
http://www.charlottesville.org/gis/zip_download/parcel_area.zip

Does not contain address information

**Comment by slibby** [comment]
REST service for parcels here: http://gisweb.charlottesville.org/arcgis/rest/services/Layers/MapServer/1

**Comment by nvkelso** [comment]
I see data on the dotmap for this area.

But the data download for address **points** is here:

- http://widget.charlottesville.org/gis/zip_download/parcel_point.zip

<img width="722" alt="screen shot 2016-12-13 at 22 40 21" src="https://cloud.githubusercontent.com/assets/853051/21172178/3cb607f4-c185-11e6-8d58-f272e27560bd.png">
