### ISSUE TITLE
Uruguay Nation-wide Addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2917]
![uy_oa_yeeeeehawwww_sample](https://cloud.githubusercontent.com/assets/5324316/25396706/971a65fa-29b3-11e7-91b4-d05774861410.jpg)
![uy_oa_yeeeeehawwww](https://cloud.githubusercontent.com/assets/5324316/25396707/972d1614-29b3-11e7-9fa0-452648407c48.jpg)

After talking it over with @iandees we will add the data - I see no mention of any terms (Source: http://correo.com.uy/ ) - so we need to maintain that in the metadata if possible.

Dropbox link coming soon ;)

**Comment by justinelliotmeyers** [comment]
https://www.dropbox.com/sh/1xwe680o04lgmu2/AADh6MhcQeS3LtAXuQGwyjxfa?dl=0

**Comment by justinelliotmeyers** [comment]
I am downloading one other dataset that may have different results - I will upload that as well

**Comment by nvkelso** [comment]
Awesome!!!

**Comment by migurski** [comment]
Looks like it has a meaningful projection; I included a couple sample rows below. This might be the right conform:

```JSON
{ "street": "nombre", "number": "numero", "postcode": "cp" }
```

Data is now at https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/migurski/387f46/uy_num_puertas_2014.zip

```
id: Integer (9.0)
cp: Integer (9.0)
idcalle: Integer (9.0)
nombre: String (254.0)
numero: Integer (9.0)
letra: String (254.0)
nombre_inm: String (254.0)
forma_de_o: Integer (9.0)
forma: String (254.0)

OGRFeature(uy_num_puertas_2014):0
  id (Integer) = 679622
  cp (Integer) = 40098
  idcalle (Integer) = 16465
  nombre (String) = A VILLA INDART
  numero (Integer) = 2006
  letra (String) = (null)
  nombre_inm (String) = (null)
  forma_de_o (Integer) = (null)
  forma (String) = (null)
  POINT (684244.22 6532092.5)

OGRFeature(uy_num_puertas_2014):1
  id (Integer) = 529278
  cp (Integer) = 12810
  idcalle (Integer) = 10414
  nombre (String) = BURDEOS
  numero (Integer) = 2736
  letra (String) = (null)
  nombre_inm (String) = (null)
  forma_de_o (Integer) = (null)
  forma (String) = (null)
  POINT (566573.54 6139948.2)

OGRFeature(uy_num_puertas_2014):2
  id (Integer) = 529275
  cp (Integer) = 12810
  idcalle (Integer) = 10414
  nombre (String) = BURDEOS
  numero (Integer) = 2520
  letra (String) = (null)
  nombre_inm (String) = (null)
  forma_de_o (Integer) = (null)
  forma (String) = (null)
  POINT (566454.56 6139899.68)
```

**Comment by justinelliotmeyers** [comment]
Thanks @migurski !!
The other dataset I am trying to grab has less attributes, and in spot checking I believe they are the exact same datasets - just named different.

**Comment by astoff** [comment]
That's funny -- I had just found a possibly different countrywide source at http://sit.mvotma.gub.uy/arcgis/rest/services/Herramientas/Busquedas/MapServer/9

It is sparse in Montevideo but seems good elsewhere. Also, some street names are in the form "Surname, Given name". That's something to watch out, whatever source is eventually used.

**Comment by trescube** [comment]
D'oh!  Sorry @migurski I didn't see that you had uploaded to the cache already.
