### ISSUE TITLE
Davidson County, TN Parcels

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2920]

**Comment by justinelliotmeyers** [comment]
https://gis1imcloud1.amec.com/arcgis/rest/services/7622_DavidsonCounty/Property/MapServer/2

**may be some other goodies in the parent dirs

**Comment by nvkelso** [comment]
Looks like we have city core in OA now, but the area south of city / in city? is missing. Does this fill that in?

**Comment by justinelliotmeyers** [comment]
downloading all TN to see ;) - It wasn't in the downloads section, so I figured add it since I saw it.

**Comment by justinelliotmeyers** [comment]
our current data is missing a lot of locations in this area -86.685179  36.054487

my pyres download is'nt working (wants new python coding) right now so I cannot download the data above - but it will fill in a lot of missing locations

**Comment by justinelliotmeyers** [comment]
dead link
