### ISSUE TITLE
matosinhos, portugal addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2925]
http://web2.cm-matosinhos.pt/arcgis/rest/services/Limite_Planos/MapServer/3

**Comment by nvkelso** [comment]
North of Porto, a big city in Portugal.

**Comment by astoff** [comment]
There is a list of GIS departments of various Portuguese regions at http://wiki.openstreetmap.org/wiki/WikiProject_Portugal/Lista_de_Fontes

**Comment by sergiyprotsiv** [comment]
Great find @justinelliotmeyers ! I was always assuming that Numeros de Policia refers to police stations. It should be possible to get many Portuguese sources then. E.g. the Lisbon map that @astoff mentions takes data from https://gis.cm-lisboa.pt/arcgis/rest/services/MapaBase_ETRS89/MapServer/3 ;)

**Comment by justinelliotmeyers** [comment]
the lisboa stuff might be tricky - thats why i didnt create a ticket for it yet - not sure what sources to use: https://gis.cm-lisboa.pt/arcgis/rest/services/Arcgis_Online/Lx_MapaBase/MapServer

0, 1, or 2 !!??

**Comment by astoff** [comment]
"Número de polícia" is ideed a fascinating notion. [This document](https://www.ctt.pt/contentAsset/raw-data/250ad2ec-6d75-448c-bee4-3a9dcc050815/ficheiro/Manual_de_Enderecamento.pdf?byInode=true) from the postal service confirms that this is just the building number. For the record, the term for unit would be "alojamento". And "morada" is of course the street name.

Note that these Lisbon layers have a lot of parenthetical remarks mixed with the addresses. They would need to be stripped out.

**Comment by justinelliotmeyers** [comment]
@astoff sometimes they come as:
Punto Kilométrico 
Número de Policía 
Portal de Policía

**Comment by astoff** [comment]
https://github.com/openaddresses/openaddresses/pull/2936 closes this.
