### ISSUE TITLE
Slovenia Addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2926]
![slov](https://cloud.githubusercontent.com/assets/5324316/25448039/4113dd30-2a85-11e7-8500-cac1a666174a.png)

**Comment by justinelliotmeyers** [comment]
can @nvkelso or @iandees look at the terms?
http://egp.gu.gov.si/egp/

right under blue box (where it says Splošni pogoji uporabe geodetskih podatkov )

I think it is fine, but want another set of eyes on it

**Comment by iandees** [comment]
It looks like a CC-BY license, which is fine.

**Comment by justinelliotmeyers** [comment]
downloading a few supplemental datasets to hopefully add in street names as these only contain number/ apartment. they should join based on a street id field. stay tuned

**Comment by nvkelso** [comment]
Wow!

**Comment by justinelliotmeyers** [comment]
if you want you guys can sign up and dl directly!

**Comment by justinelliotmeyers** [comment]
there is a whole bunch of other goodies in there ;) admins, settlements, etc

**Comment by migurski** [comment]
😮 

That’s a whole country.

**Comment by justinelliotmeyers** [comment]
yeah - we aren't messing around here... this is a serious global dataset!!!!!!!!!

**Comment by sbma44** [comment]
awesome! [this was rumored to be coming](https://github.com/openaddresses/openaddresses/issues/1107) but it's amazing to see it actually happened

**Comment by justinelliotmeyers** [comment]
here is the formatting: http://www.e-prostor.gov.si/fileadmin/struktura/sifrant_rpe_enot.htm

**Comment by justinelliotmeyers** [comment]
uploading raw gis data to dropbox

**Comment by justinelliotmeyers** [comment]
https://www.dropbox.com/sh/8pred67i3zycstl/AABhJOfrXRyqHi0s8J0ZbJWVa?dl=0

**Comment by stefanb** [comment]
The dataset contains plenty of other information, should some of that be included as well (besides minimal mandatory street name and numbers)?
Eg city names, post codes (with names), commune & region names...

Some smaller places don't have street system, so the city name + house number is normally used instead. Is it ok to repeat the city name in both fields (street and city) in such cases?

There are 500000+ addresses, is it ok to have them all in a single csv or should it be split into smaller chunks (eg regionally)? "Address counts per source" chart on  http://results.openaddresses.io/dashboard tops at 200000 addresses, but there seem to be larger sources mentioned in the Lost sources section.

**Comment by sergiyprotsiv** [comment]
@stefanb Thanks for looking into this! The relevant fields are in the "Attribute Tags" section of the contributing manual (https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md). So, I'd say at least house, street, city, postcode are necessary. If available, municipalities/communes should be under the "district" field, and statistical region under "region".

Best to keep the whole source as a single file. The Mexico import contained 30M addresses in one file and the import went smoothly.

On street names my feeling is that it should be kept empty, but maybe there was a similar precedent already? @migurski and @thatdatabaseguy, do you have suggestions on this?

**Comment by thatdatabaseguy** [comment]
@stefanb @sergiyprotsiv I think that's fine. OSM has the notion of "[addr:place](http://wiki.openstreetmap.org/wiki/Key:addr:place)", which handles this, but IIRC in most countries in the region, the place is basically used as a street name. We currently import Slovakia, Poland, Austria, etc. which would probably list the city in the street field for smaller villages. If we're changing that for Slovenia we'd want to do the same for other sources, so think I'd prefer to list the city as "street".

**Comment by stefanb** [comment]
Tnx, all clear now. I expect to have a pull request with scripts and source definition JSON ready in the next few days.

**Comment by justinelliotmeyers** [comment]
thanks @stefanb !!!!!!!!!!!
