### ISSUE TITLE
Trinidad Tobago National Address Improvement Project

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2937]
The national address improvement project is developing a point layer for all the addresses. Unfortunately this will not available for distribution to the public until the completion of the project. The completion is due at the end of 2018.

Mr. Carmichael Ellis, GISP
Address Management Systems Officer at TTPOST

**Comment by justinelliotmeyers** [comment]
Whatever you think is best; do you have a point of contact there? I was sent a nation-wide parcel dataset, but it doesn't have addresses, and unsure of source.

**Comment by brianjd** [comment]
I did make a contact while I was down there in the Lands & Surveys department.  At the time I was advised there were some internal struggles in regards to completing the project.  I will follow-up with them and track in #4195.  Are you able to share the parcel dataset?
