### ISSUE TITLE
Elbert County, Colorado

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2938]
email sent:assessor@elbertcounty-co.gov

**Comment by justinelliotmeyers** [comment]
john hanson voicemail
Elbert County Sheriff's Office 
751 Ute Ave 
P.O. Box 486 
Kiowa, Colorado 80117 
303-621-2027

**Comment by justinelliotmeyers** [comment]
Let me know if you would like bye some Data
 
Bart Chambers
 
G I S Specialist
OIL & GAS
NATURAL RESOURCES
AGRICULTURAL
Assessor's Office
(303) 621-3103

files here: https://www.dropbox.com/sh/e1g4lj85nzpqio9/AAD26o-njHoOqYVAqqsmX2G6a?dl=0

**Comment by nvkelso** [comment]
The cost of $500 is at top-end of "cheap", but the terms are prohibitive.

**Comment by nvkelso** [comment]
South-east of Denver, looks fairly exurban / rural.

**Comment by justinelliotmeyers** [comment]
the Douglas County e911 dispatch maintains Elbert and Douglas addresses. He cannot give out Elberts data as he is not the owner.

**Comment by justinelliotmeyers** [comment]
no data
