### ISSUE TITLE
Guernsey Address Points!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2957]
![mystery](https://cloud.githubusercontent.com/assets/5324316/25583277/1952d548-2e5f-11e7-80b8-f3ad80dd1bb9.png)

https://gps.digimap.gg/arcgis/rest/services/AddressPointLabels/MapServer/0

**Comment by iandees** [comment]
Some fun history!

https://en.wikipedia.org/wiki/Bailiwick_of_Guernsey

**Comment by trescube** [comment]
Before I submit a source and get sued into oblivion by the Royal Mail, do we have permission to add this?

**Comment by justinelliotmeyers** [comment]
I didnt see any TOU popup in the interactive map

**Comment by justinelliotmeyers** [comment]
I looked before I submitted the ticket

**Comment by trescube** [comment]
Sweet!  I'll add it.

**Comment by justinelliotmeyers** [comment]
**Jersey may be in a different DIR, but I didn't see it** Unless if Jersey is in the Guernsey stuff
