### ISSUE TITLE
Faroe Islands!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2959]
![fo](https://cloud.githubusercontent.com/assets/5324316/25586810/102ad85c-2e6f-11e7-9f40-15b4d7e5a147.jpg)

http://gis.us.fo/arcgis/rest/services/adressur/adressa/MapServer/0

**Comment by nvkelso** [comment]
Last week it was southern most addresses, now you’re going for northern
most ;)
