### ISSUE TITLE
Greenland Addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2960]
http://www.nunagis.gl
GIS@asiaq.gl
--------------------- 
Ministry of Finance 
Section of National Planning
Box 1037
3900 Nuuk
 
Updated 26.02.2015

**Comment by justinelliotmeyers** [comment]
Dear Justin

 

Have you being answered for you question?

 

Otherwise, you should check our GIS platform en.nunagis.gl (which we experience some technical difficulties at this time). In this GIS platform, you choose a city/town and you activate this layer with housenumber or bulding number (B-nr) in the layer “placename + boarder” (remember to zoom in sufficiently in order to enable to housenumber layer).

 

If the English version of GIS platform (en.nunagis.gl) does not work, try the Danish version by entering dk.nunagis.gl > choose the town > activate the housenumber layer in the “Stednavne + grænser” – layer (remember to zoom in). Unfortunately there is no streetname yet, so you only see the housenumber (and or the entire address).

 

Inussiarnersumik / Med venlig hilsen

Asiaq

Ludvig Petersen

Tlf 348825

**Comment by justinelliotmeyers** [comment]
I emailed back and asked for the points. Stay tuned!

**Comment by justinelliotmeyers** [comment]
There are no  address point in the system yet. The only shapefile you may acquire, is the layer with building and building number, and those layers are not free.
 
May I ask why you are trying to find address points? What is the occasion?
 
Inussiarnersumik / Med venlig hilsen
Asiaq
Ludvig Petersen
Tlf 348825

**Comment by justinelliotmeyers** [comment]
Hi Justin
 
In Greenland we do only have a complete address theme (road names and house numbers) in one town; the city of Nuuk. But the road geometry, the road names, the building geometry and house numbers are not connected (georeferenced).
 
In general, the buildings in Greenland have a building number e.g. B-234 (not a house number as commonly known) that is only unique for each town or settlement, meaning that one building number can occur in several locations (towns and settlements). Many locations in Greenland, typically the settlements, do not have any roads, and therefore no road names. The traffic infrastructure consists of paths and trails without any names.
 
We have a project ongoing, that will give each building number a unique ID consisting of the location number and georeferenced to the building geometry, and georeferencing the road geometry with road names and house numbers, for those locations that have roads, road names and house numbers.
 
So, for the moment, we can only offer you the buildings and the building numbers for all the locations of Greenland, and for the city of Nuuk, we can also offer you buildings and house numbers.
 
We can deliver these information for DKK 5.000,-.
 
 
Inuulluaqqusillunga/
Venlig hilsen/
Kind regards
 
Jens Gottlieb
Cartographer
Head of Section
Maps & Geodata

**Comment by nvkelso** [comment]
That’s $730.09 US Dollar at today’s exchange rate. A little steep but not
crazy expensive.

Can you clarify with him that we'd have redistribution rights and what sort
of attribution requirements (if any), please?

**Comment by justinelliotmeyers** [comment]
e-mailed Ludvig and Jens to check on TOU and attribution.

**Comment by justinelliotmeyers** [comment]
I just sent a follow-up email to the May 15th e-mail. Hopefully we hear from them soon.

**Comment by justinelliotmeyers** [comment]
Sent follow-up e-mail

**Comment by justinelliotmeyers** [comment]
An exciting project!
 
At this moment, the requested data is not available. However Greenland is running a project so Greenlandic address’ will be georeferenced and hopefully available for free. Expected conclusion of the project is during 2018.
 
Inussiarnersumik / Med venlig hilsen
Asiaq
Ludvig Petersen
Tlf +299 348815

My Response below:
Thanks for the information! For the current data you do have, do you know the total amount, coverage, and have any metadata? I would like to document it so when we check back in the future, we know what to expect. Is the current data available for purchase if it is not free?

Thanks!
Justin

**Comment by justinelliotmeyers** [comment]
At this monent, we cannot even provide metadata. All addresses have not being transformed to electronic data yet. We do guess that there are about 35.000 valid addresses in 17 towns and 58 communities in Greenland.
 
Inussiarnersumik / Med venlig hilsen
Asiaq
Ludvig Petersen
Tlf +299 348815

**Comment by justinelliotmeyers** [comment]
the price for the building geometry and the building number for all the locations of Greenland is DKK 5.000,-
 
You can incorporate the data into your project as long as you refer to Asiaq, Greenland Survey.
 
As I wrote in the mail we do only have house numbers for the city of Nuuk, but building numbers for the towns and settlements for all the locations of Greenland.
 
I do not have the numbers of how many addresses that exist in the dataset. The data is not in a database but in CAD files for each location.
 
Regards
Jens

**Comment by justinelliotmeyers** [comment]
I asked if there was a shapefile/ csv/ other geospatial format besides CAD

**Comment by justinelliotmeyers** [comment]
We can deliver in MapInfo and shape file formats.
 
/Jens

**Comment by justinelliotmeyers** [comment]
About $786
https://www.google.com/search?q=dkk+to+dollars&oq=DKK+to+doll&aqs=chrome.0.0j69i57j0l4.2695j0j7&sourceid=chrome&ie=UTF-8

**Comment by nvkelso** [comment]
Rad! Do they deliver via download link or DVD? (Since they are so far away download link is better.)

**Comment by justinelliotmeyers** [comment]
I just emailed Jens and asked him for the order form, and the delivery method. I'm going to be off grid for the next couple days, so my internet, email might not work the greatest. As soon as I hear back from him, I will update you. Thanks!

**Comment by justinelliotmeyers** [comment]
Justin

 

We do not have an order form, but you can send me your request for the exact data sets you would like to buy, and send me your contact information:

Full name, address and phone number.

 

Then we will put your data on our FTP server, and send you an invoice.

 

/Jens
