### ISSUE TITLE
Wallonia Addresses?

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2961]
We are missing all of Wallonia Correct?
Found this - may be something to dive into?

**Comment by sergiyprotsiv** [comment]
@justinelliotmeyers, we've added a source on Wallonia a few weeks back (https://github.com/openaddresses/openaddresses/pull/2768), but their terms are unclear, so it was not merged

**Comment by justinelliotmeyers** [comment]
will need to dedicate time to research license - closing to clear out backlog
