### ISSUE TITLE
Miaoli County Taiwan Addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2962]
http://ja.miaoli.gov.tw/arcgis/rest/services/Miaoli/miaoliDpDynamic_B/MapServer/1

**Comment by sergiyprotsiv** [comment]
@justinelliotmeyers, I've added about half counties in Taiwan (https://github.com/openaddresses/openaddresses/pulls?utf8=✓&q=is%3Apr%20author%3Asergiyprotsiv%20), but if you find others (or a good source for Taichung), would be great!

**Comment by trescube** [comment]
Was fixed in #2910
