### ISSUE TITLE
Alberta Addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2966]
https://amdsp.ca/index.html
**please review license before we implement or decide if we cannot**
![ab](https://cloud.githubusercontent.com/assets/5324316/25637229/49d92818-2f52-11e7-9f3b-e5023b5e5d18.jpg)

Little over 265k records

**Comment by justinelliotmeyers** [comment]
Justin,

The City of Red Deer’s Address nodes, points of interest, and road centreline are now available to the public through the Alberta Municipal Data Sharing Partnership website.

Please visit amdsp.ca and select ‘Download AMDSP data’.  

If you have any issues, feel free to give me a call.

Leigh-Ann Martin | GIS Supervisor
IT Services
The City of Red

**Comment by justinelliotmeyers** [comment]
I called her to find out more about this project

**Comment by iandees** [comment]
License looks ok. They **require attribution**:

> Acknowledge the source of the Information by including any attribution statement specified by the Information Provider(s) and, where possible, provide a link to this licence.
If the Information Provider does not provide a specific attribution statement, or if you are using Information from several Information Providers and multiple attributions are not practical for your product or application, you must use the following attribution statement:
Contains information licensed under the Open Government Licence – 
Alberta Municipal Data Sharing Partnership (AMDSP)

and we can redistribute:

> You are free to: Copy, modify, publish, translate, adapt, distribute or otherwise use the Information in any medium, mode or format for any lawful purpose

**Comment by justinelliotmeyers** [comment]
![tb2](https://cloud.githubusercontent.com/assets/5324316/25637420/e5b8af88-2f52-11e7-8e23-6ce994fefe2d.jpg)


Take Off 'Eh!!!!!!!!!!!!!!!

**Comment by nvkelso** [comment]
Here's what we have now, this will be a huge improvement! :)

<img width="608" alt="screen shot 2017-05-02 at 15 17 57" src="https://cloud.githubusercontent.com/assets/853051/25641725/965ccbac-2f4a-11e7-91b3-2bba30c87a69.png">

**Comment by trescube** [comment]
I'm going to cache this on s3 since name/email is required for them to send a custom download link.
