### ISSUE TITLE
Main site broken

### ISSUE THREAD

**Issue by jharpster** [openaddresses/openaddresses#2967]
Looks like the main site is broken.

![image](https://cloud.githubusercontent.com/assets/224853/25638575/bdd59860-2f3d-11e7-817a-67ed57746ed1.png)

**Comment by iandees** [comment]
Looks like GitHub changed their GH Pages IP load balancer IP addresses so our Cloudflare setup was pointing to the wrong place.

I fixed that and it seems to work for me now.

**Comment by iandees** [comment]
Thanks for spotting this, by the way.

**Comment by jharpster** [comment]
Sure. Figured it was something small.
