### ISSUE TITLE
Sudbury, ON, CA

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2973]
Good Morning Justin,
I'm passing your request along to the Coordinator of our GIS Department, she will be able to answer your question,
- Dave

Krista Carre <Krista.Carre@greatersudbury.ca>
cc:	Kris Longston <Kris.Longston@greatersudbury.ca>

**Comment by justinelliotmeyers** [comment]
they sent the data! Will upload to dropbox. can @iandees or @nvkelso please review these before we use? 

Disclaimer: The information attached is provided “as is” and while the City of Greater Sudbury provides this information in good faith, the City does not warrant, convenant or guarantee, in an expressed or implied form, arising by law or otherwise, the completeness, effectiveness, accuracy and/or fitness or the information for any particular use.  The City does not assume responsibility nor accept any liability arising from any use of the information.

The City of Greater Sudbury shall not be liable in respect of any claim, demands and/or action, irrespective of the nature of the claim, demand and/or action alleging any loss, injury or damages, direct or indirect, which may result from the use of the City of Greater Sudbury information.  The City of Greater Sudbury shall not be liable in any way for loss of profits or contracts, or any other consequential direct or indirect loss of any kind resulting from the use of the City of Greater Sudbury information.

The user of the City’s information shall indemnify and save harmless the City of Greater Sudbury from and against any claims, demand, action, costs (including without limitations, legal fees, disbursements and administrative costs), losses, injuries, expenses, damages, fines, orders, and/or recoveries suffered by , made, brought and/or recovered against the City of Greater Sudbury, irrespective of the nature of the cause of the claims, demands, actions, alleged losses, costs, expenses, damages and/or injuries (including injuries resulting in death), including without limitations claims, demands, actions, costs, expenses, damages and/or injuries arising out of the City’s negligence, gross negligence, errors and omissions and/or willful misconduct, as pertaining to the provision and/or use of the City of Greater Sudbury information.

**Comment by justinelliotmeyers** [comment]
![sud](https://cloud.githubusercontent.com/assets/5324316/25823632/af6553a2-340a-11e7-8404-be08fdb4edf6.jpg)

**Comment by justinelliotmeyers** [comment]
https://www.dropbox.com/s/n6bj7h6cz9risrj/Address_Points_May_8_2017.zip?dl=0

**Comment by iandees** [comment]
License looks good to me.

**Comment by justinelliotmeyers** [comment]
Thanks @iandees

**Comment by justinelliotmeyers** [comment]
yes, this is the raw data - do you want me to ask them for all fields if they have a different attribute table/ dataset?

**Comment by trescube** [comment]
Not yet, I'll take a crack at it, the regexes shouldn't be that bad, just weird formatting.

**Comment by justinelliotmeyers** [comment]
@trescube they just changed this to open data I think!!!!!!!  http://opendata.greatersudbury.ca/datasets/address-points-layer

**Comment by trescube** [comment]
Sweet!  I'll add to my to-do list for this afternoon.
