### ISSUE TITLE
Download links for gzip format

### ISSUE THREAD

**Issue by moshe** [openaddresses/openaddresses#2974]
Hi,
I wonder if by any chance you can supply the dumps with gzip format rather than zip format?
My main reason for asking it is that gzip can be streamed very easily so I won't need to download and decompress the entire file in order to read it.

**Comment by migurski** [comment]
Can you say more about how you're using OA data? I selected zip format because it’s possible to get random access to a file contained in an archive, which I don’t believe is supported by `.tar.gz` files. When I’ve needed to skip complete downloads, I use HTTP Range headers to pick out selected parts of the remote zip files without downloading the entire thing ([sample code here](https://github.com/openaddresses/claypigeonfs/blob/master/Claypigeon/remote.py)).

**Comment by moshe** [comment]
Hi @migurski,
I'm the writer of [elasticsearch_loader](https://github.com/moshe/elasticsearch_loader) my next feature is able to read datasources from yml file and load them into elasticsearch.
I came across this repo while searching for use cases for streamable datasources.
zip is not feats to my use case because it also a container format (one zip file can hold several files) and I can't pipe it into another command; for example:
`curl -X GET https://example.com/file.gz | zcat | elasticsearch_loader -` 
which streams the entire file line by line to my code without the need to save the whole file in disc / hold it into memory.

From what I understand you cannot stream zip file from the beginning to its end can zip stores the metadata in the end of the file, so its more complicated then gzip file. [link](http://stackoverflow.com/questions/7132514/bash-how-to-unzip-a-piped-zip-file-from-wget-qo)

regarding your code, I cannot find where your code is handling the fact that the remote is a zip file.

**Comment by migurski** [comment]
I see — in the case of OpenAddresses, there are in fact multiple files in each archive, typically a large CSV some smaller metadata files. I’m not sure it will be possible to accommodate your sample usage, because there aren’t many single-file archives in OA.

**Comment by ingalls** [comment]
Data downloaded via the https://batch.openaddresses.io/data service can now be streamed. The default format is a line delimited list of GeoJSON Features
