### ISSUE TITLE
Pockets of missing data in Sao Paulo, Brazil

### ISSUE THREAD

**Issue by oini** [openaddresses/openaddresses#2996]
On close investigation, few pockets of residential establishments seem to have missing address data in Sao Paulo, Brazil. 

<img width="956" alt="screen shot 2017-05-16 at 12 26 42 am" src="https://cloud.githubusercontent.com/assets/1933377/26074166/6afb6b06-39ce-11e7-8a43-db3cc19188f6.png">

_The image above shows few missing pockets in Sao Paulo_

<img width="1046" alt="screen shot 2017-05-16 at 12 22 24 am" src="https://cloud.githubusercontent.com/assets/1933377/26074071/2b7f9024-39ce-11e7-8e66-33845a81bb1d.png">

_Example of a missing pocket in the heart of the city_

<img width="1174" alt="screen shot 2017-05-17 at 2 08 55 pm" src="https://cloud.githubusercontent.com/assets/1933377/26145653/d637274c-3b0a-11e7-8f7c-6f67a16c5617.png">

_Sao Paulo on the slippy map_

cc @migurski @ingalls @msirenko

**Comment by astoff** [comment]
Those pockets are missing in the original dataset. If you look at it, you will see that the addresses are all there, but a sizable fraction doesn't have lat/lon fields.

I'm afraid we'll need to wait until the 2020 census data comes out.

**Comment by plentz** [comment]
we probably can close this one in favor of https://github.com/openaddresses/openaddresses/issues/7251

**Comment by iandees** [comment]
Sure, sounds good. Thanks for making the new issue.
