### ISSUE TITLE
Germany, OpenData License

### ISSUE THREAD

**Issue by it4workflow** [openaddresses/openaddresses#3008]
As @sergiyprotsiv mentioned in #2483 

> No specific license, but is is under the "open data" section of the official geoportal.

This isn't correct: there is a specific license ([Data licence Germany – attribution – version 2.0](https://www.govdata.de/dl-de/by-2-0)) for the most parts of OpenData in Germany (and specifically for Thüringen, see [Landesprogramm_oGD_V1_0.pdf](http://www.geoportal-th.de/Portals/0/Downloads/IKG-GIZ/download/Landesprogramm_oGD_V1_0.pdf) on page 35) , therefore we couldn't import it into OpenStreetMap, because it's incompatible with the OdBL

So, where is

> (2) The user must ensure that the source note contains the following information:
> 
> * the name of the provider,
> * the annotation "Data licence Germany – attribution – Version 2.0" or "dl-de/by-2-0" referring to the  licence text available at www.govdata.de/dl-de/by-2-0, and
> * a reference to the dataset (URI).

mentioned?

**Comment by it4workflow** [comment]
Just an example of a tool for checking the streetnames and housenumbers with OpenData from Thüringen and the mention of it: [regio-osm](http://regio-osm.de/hausnummerauswertung/auswertung_anzeigen?job_ids=47147&ausgabefarbig=true&linktyp=osmkartevoll&unterdrueckfertigestrassen=nein&unterdrueckspalten=nein&land=Bundesrepublik+Deutschland&stadt=Schleusegrund) (top right corner)

**Comment by sergiyprotsiv** [comment]
Closed by https://github.com/openaddresses/openaddresses/pull/3024
