### ISSUE TITLE
Possibly disable Lithuania countrywide source

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#3015]
Reported in https://github.com/openaddresses/openaddresses/commit/63a94bb0d3a3e6a088aefb7d45798b8e11527b44, let's confirm the license terms for the nationwide Lithuania address source. 

If it's not good terms, let's keep it indexed (don't delete the file) but disable it's export (add property key value to JSON) in the bulk runs.

Related: We do include data from the [capital](https://github.com/openaddresses/openaddresses/issues/2390) in a different JSON source – and that data appears to be fine.

**Comment by nvkelso** [comment]
Looks like @sergiyprotsiv added it in https://github.com/openaddresses/openaddresses/commit/63a94bb0d3a3e6a088aefb7d45798b8e11527b44.

**Comment by tomass** [comment]
Capital (Vilnius) source is fine. Vilnius municipality provides weekly updated data source in fully open manner.
Country source is not fine, country wide data is NOT open and additionally given source is from other government department using a copy of original data. Url was probably taken out from internal sources of that other department website, as that other department does not give the address url as "open data".
