### ISSUE TITLE
Summit County, Colorado

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3016]
Just spoke to Rich on the phone - data should be on a rest service by end of month! Stay tuned - he said he would follow-up once data is ready

http://www.co.summit.co.us/251/GIS

**Comment by justinelliotmeyers** [comment]
https://gis.summitcountyco.gov/arcgis/rest/services/AGO_Open_Data/Parcel/MapServer/0

**not live yet

**Comment by justinelliotmeyers** [comment]
Rich sent me the shapefile data: here are the TOU - can @nvkelso or @iandees review?

https://www.dropbox.com/s/rwwubf41lhgc15z/2017-03%20GIS%20Data%20and%20DATA%20License%20Fee%20Schedule%20%28002%29.pdf?dl=0

**Comment by iandees** [comment]
This looks OK. I don't see anything limiting our redistribution rights, there's only a disclaimer for indemnification.

**Comment by justinelliotmeyers** [comment]
Thanks! Should I just upload the data or wait until their service goes live in a few weeks or so?

**Comment by iandees** [comment]
My vote would be to wait for the service.

**Comment by justinelliotmeyers** [comment]
me too - just wanted to check.  Thanks!!

**Comment by nvkelso** [comment]
Can you also upload now to Dropbox and post link here so we have the data in case their upload never completes, please?

**Comment by justinelliotmeyers** [comment]
uploading now. I think this is where BBB is! **NSFW fyi**

**Comment by justinelliotmeyers** [comment]
https://www.dropbox.com/s/u8wg0vlv5bmwedg/SummitCOAddressPts.zip?dl=0

**Comment by justinelliotmeyers** [comment]
![summit](https://cloud.githubusercontent.com/assets/5324316/26690880/02663e74-46c9-11e7-83b4-3e87501e2705.jpg)

**Comment by justinelliotmeyers** [comment]
https://services6.arcgis.com/dmNYNuTJZDtkcRJq/arcgis/rest/services/Address_Points/FeatureServer/0

**Comment by justinelliotmeyers** [comment]
source:https://hub.arcgis.com/datasets/SummitCountyCO::address-points
