### ISSUE TITLE
Sullivan County, NY Issue

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3017]
new links perhaps? https://services7.arcgis.com/bx3OlIPqiDclwaja/ArcGIS/rest/services

current source is erroring out: http://results.openaddresses.io/sources/us/ny/sullivan

**Comment by trescube** [comment]
Looks like it's now at https://services7.arcgis.com/bx3OlIPqiDclwaja/ArcGIS/rest/services/SCGISO_911_Data_Update/FeatureServer/0
