### ISSUE TITLE
Typo in fr/alpes_maritimes dataset

### ISSUE THREAD

**Issue by kei42** [openaddresses/openaddresses#3022]
Hello,

First thanks for your great work ! 

I have an issue with the dataset I downloaded here: http://results.openaddresses.io/sources/fr/alpes_maritimes

There is a typo in an address: 
all the addresses like this:
chemin de peidesalle
should be like this: 
chemin de peidessalle

There should be 2 s's.

You can find it on openstreetmap: 
https://www.openstreetmap.org/search?query=230%20Chemin%20De%20Peidessalle#map=19/43.64001/7.02979

When searching on https://openaddresses.io/ map search engine I can also find the correct address, but it is not on the dataset.

Should I parse it and submit the correct address ?

Thanks for your help !

**Comment by trescube** [comment]
Looking thru the data provided by the French government that OpenAddresses sources, I see that there are two possible fields for street name: `nom_voie` and `nom_afnor`.  Here is the header row and a sample with the street name you mentioned:

```id;nom_voie;id_fantoir;numero;rep;code_insee;code_post;alias;nom_ld;nom_afnor;libelle_acheminement;x;y;lon;lat;nom_commune
ADRNIVX_0000000261692859;chemin de peidesalle;0242;152;B;06152;06560;"";"";CHEMIN DE PEIDESSALLE;VALBONNE;1025240.3;6290288.8;7.03113256592113;43.6369108193955;Valbonne
```

I don't know French well enough to say for certain, but it appears that `nom_afnor` is more accurate than `nom_voie` in this instance.  The [metadata document](https://adresse.data.gouv.fr/pdf/description-contenu.pdf) says that `nom_afnor` means (translated) ["Name standardized according to postal standard"](https://translate.google.com/#fr/en/Nom%20normalis%C3%A9%20selon%20la%20norme%20postale).  It also says that `nom_voie` means (again, translated): ["Track name in lowercase
Accented with alternative names
potential"](https://translate.google.com/#fr/en/Nom%20de%20la%20voie%20en%20minuscules%0Aaccentu%C3%A9es%20avec%20les%20noms%20alternatifs%0A%C3%A9ventuels).  In light of this information, I think we can safely switch to `nom_afnor` if you think this is the correct course of action.  Please advise.

**Comment by kei42** [comment]
Hello,
Sorry to respond this late.
Indeed the nom_afnor is the normalized name use by the postal services. I think we should use this one. 
But I think the nom_voie is not the correct one (it should be the same as nom_afnor in lower case but with accents if there are any). 
Could you tell me the contact email address so I can send them a notice to change the nom_voie.

Thanks.

**Comment by trescube** [comment]
OA pulls the data from https://adresse.data.gouv.fr/ which is run by the French goverment.  We don't have a relationship with them directly, but this is the contact email address on the site is   adresse@data.gouv.fr

**Comment by kei42** [comment]
Thanks I'll contact them.

**Comment by thatdatabaseguy** [comment]
Wait, looking at the data file now, it contains many incorrect normalized names like "RUE DE L EGLISE" instead of "rue de l'église".

Elisions and accents are not super easy to add back in once they've been removed. The elisions alone affect > 18k addresses in exchange for fixing one spelling mistake (or maybe a handful). I think it's better to contact the government and ask them to correct that mistake than to use normalizations in place of data.

**Comment by trescube** [comment]
So this should be switched back and we'll just lose the `SS` but retain the elisions and accents?

**Comment by thatdatabaseguy** [comment]
Yeah, spot checked a few cases and it looks like nom_voie is as close to the real street name as is possible from this file. nom_afnor is sort of like using a USPS address validation response.

**Comment by trescube** [comment]
K, sorry @kei42, we'll have to switch it back for more accurate data in the vast majority of cases.  Hopefully an email to the addressing authority can get the SS into `nom_voie`.

**Comment by kei42** [comment]
Indeed, I haven't considered the apostrophe and that the accent could be a problem, it's my bad.

thanks @thatdatabaseguy to pointing it out.
