### ISSUE TITLE
machine producing invalid csv files

### ISSUE THREAD

**Issue by missinglink** [openaddresses/openaddresses#3027]
heya, I noticed that some csv files contain rows of mixed column lengths.

eg. in this `kz` extract, the top 2 rows contain 11 columns, the rows below only have 7 columns.

in this case it looks like this is caused by newline character in the source data, this also confuses CSV parsers because the closing `"` is also missing.

```bash
grep '2 кв' /tmp/oa/kz/countrywide.csv
79.2156635,43.0174073,42 кв 2,Дархан көшесі,,,РАЙЫМБЕКСКИЙ РАЙОН,АЛМАТИНСКАЯ,,,c8d603a8717f2b5e
79.2157284,43.0174285,42 кв 1,Дархан көшесі,,,РАЙЫМБЕКСКИЙ РАЙОН,АЛМАТИНСКАЯ,,,d08c389d1349ca6d
82.0105535,46.7754409,д. 12 кв. 1,Джамбула,,,"МАКАНЧИНСКИЙ
82.0109022,46.7753645,д. 12 кв. 2,Джамбула,,,"МАКАНЧИНСКИЙ
82.0099453,46.7738161,д. 2 кв. 2,Джамбула,,,"МАКАНЧИНСКИЙ
82.011556,46.7936102,д. 22 кв. 2,Амангельды,,,"МАКАНЧИНСКИЙ
```

the issue doesn't only affect this file, it's a bit more widespread than this, unfortunately. I can probably enumerate a list for you if you'd like?

sounds like this might require a tooling update to ensure that the CSV files produced are valid (fixed column lengths, machine parsable, etc.)

let me know if you need more info :)

**Comment by missinglink** [comment]
here's another example:

```bash
$ grep edbf41e3224c7286 /tmp/oa/us/ca/riverside.csv
 WAY",,CATHEDRAL CITY,,,92234,,edbf41e3224c7286
```

**Comment by missinglink** [comment]
hmm... so looking at this again, it's probably the issue with my CSV parsing lib, I guess I can probably configure it to remove newlines inside quoted text.

this issue was more difficult to detect because I was using tools like `sort` and `uniq` which scrambled the lines.

**Comment by NelsonMinar** [comment]
FWIW, I think the kz/countrywide.csv file is correctly quoted with  newlines. When I look I see  output like

```
82.0105535,46.7754409,д. 12 кв. 1,Джамбула,,,"МАКАНЧИНСКИЙ
 (НАСЕЛЕННЫЙ ПУНКТ)",ВОСТОЧНО-КАЗАХСТАНСКАЯ,,,c77739bfa71a458a
82.0109022,46.7753645,д. 12 кв. 2,Джамбула,,,"МАКАНЧИНСКИЙ
 (НАСЕЛЕННЫЙ ПУНКТ)",ВОСТОЧНО-КАЗАХСТАНСКАЯ,,,2d5ad45aa8988b64
82.0099483,46.7741494,д. 4 кв. 1,Джамбула,,,"МАКАНЧИНСКИЙ
 (НАСЕЛЕННЫЙ ПУНКТ)",ВОСТОЧНО-КАЗАХСТАНСКАЯ,,,dbf7edf59192c797
```

This doesn't address your point about the CSV being awkward to use, but I think what we are publishing is well formed.
