### ISSUE TITLE
Add `ephemeral` flag

### ISSUE THREAD

**Issue by trescube** [openaddresses/openaddresses#3040]
How do people feel about adding an official flag for sources that have be checked from time to time for updates like [San Bernardino, CA](https://github.com/openaddresses/openaddresses/blob/master/sources/us/ca/san_bernardino.json#L24)?  Something like `ephemeral` = `true` or something that could be easily reported on the dashboard or grepped for.  Perhaps it could be more complex to contain an update cycle like "weekly" or "monthly".

**Comment by nvkelso** [comment]
While I generally like the idea (a flag to check these again because we
know they update on a cadence and they are important, how is that different
than ANY of the other sources we load from s3 / dropbox?

**Comment by trescube** [comment]
There are Esri sources that have date indicators built into the layer names like [Pueblo, CO](https://github.com/openaddresses/openaddresses/blob/master/sources/us/co/pueblo.json#L13): 

https://services1.arcgis.com/IL17xsvNU5Bmw3RY/ArcGIS/rest/services/AddressPoints_UpdateSept2016/FeatureServer/0

**Comment by trescube** [comment]
In fact, there's an update to the points for Pueblo, CO with a layer at https://services1.arcgis.com/IL17xsvNU5Bmw3RY/ArcGIS/rest/services/CityOfPueblo_Address_Points_March2017_Update/FeatureServer/0

**Comment by nvkelso** [comment]
"*Is Data Versioned:* false” lol

**Comment by migurski** [comment]
An alternative approach might look at the opposite: stale data caches. For example, we update Australia ~quarterly and you can see the changes on this page http://results.openaddresses.io/sources/au/countrywide

**Comment by trescube** [comment]
We never got to discussing this in the call the other day, but how do we proceed on this?

**Comment by ingalls** [comment]
I've opened a ticket here to explore options of doing this automatically in the batch service

**Comment by ingalls** [comment]
oops, forgot ticket: https://github.com/openaddresses/batch/issues/53
