### ISSUE TITLE
us-va-covington

### ISSUE THREAD

**Issue by ingalls** [openaddresses/openaddresses#306]
```
{
    "coverage": {
        "country": "us",
        "state": "va",
        "city": "Covington"
    },
    "data": "http://chamaps.com/covington/",
    "type": "CHA Maps",
    "website": "http://www.covington.va.us/index.php/about/maps/gis-maps"
}   
```

@jalbertbowden The data is definitely in raster form but I can't find any download link to process the raw data. Probably worth contacted them.

**Comment by slibby** [comment]
WFS export to Shapefile for Address Points is: 
http://chamaps.com/geoserver/covington/wfs?LAYERS=covington%3AAddressPts&Service=WFS&Request=GetFeature&outputFormat=Shape-Zip&TypeName=covington%3AAddressPts

**Comment by ingalls** [comment]
Closing as stale - we have a statewide layer.
