### ISSUE TITLE
Franklin County AL Parcels

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3104]
@trescube / @iandees did we at one point have this and have to remove? About all the roktech data? or was that a different third party vendor? Just checking before we implement. Thanks!

source:http://www.virtualfranklincounty.org/maps/
nothing in here: http://arcgis4.roktech.net/arcgis/rest/services/FranklinCountyAL
believe these are what we need: http://arcgis4.roktech.net/arcgis/rest/services/Franklin/baseGoMaps4/MapServer/10

**Comment by trescube** [comment]
I think that last one is actually Franklin County, NC.

**Comment by justinelliotmeyers** [comment]
yeah - the first one has parcels, names, no addresses. We can close this ticket
sorry about that

**Comment by trescube** [comment]
No problem, thanks for investigating anyway!

**Comment by trescube** [comment]
The vendor that wanted us to take down their hosted data is 39dn.com which hosted a number of Indiana sources.  They have since said that we can include counties that allow distribution but I haven't gotten around to checking out which ones that would be.
