### ISSUE TITLE
YellowKnife, CA Addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3135]
http://opendata.yellowknife.ca/home/details/92407f76-6c52-449a-a4c3-01fbdc3b30ff
![yk](https://user-images.githubusercontent.com/5324316/27435623-bbc07d78-572a-11e7-862d-a675f3c74f4d.jpg)

**Comment by trescube** [comment]
Wow, that's a tiny city!
