### ISSUE TITLE
Steinbach, MB  Parcels

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3138]
checking on terms - stay tuned
![sb](https://user-images.githubusercontent.com/5324316/27441036-5c41f18c-573a-11e7-800a-eef8cf851ed9.jpg)

**Comment by trescube** [comment]
That looks like a big middle finger.

**Comment by justinelliotmeyers** [comment]
they sent a shapefile and an excel file to join - that okay to upload? or want me to make a .dbf/ csv from the excel?

**Comment by justinelliotmeyers** [comment]
yikes...
In terms of use for this data, you can use the data for your own use, and cannot resell the data to other parties.  The data is to be used for reference purposes only and the City of Steinbach is not responsible for any inaccuracies.  No responsibility is assumed for damages or other liabilities due to the accuracy, availability, use, or misuse of the information herein provided.

Thank you.

Mitchell Eastley, BSc.
GIS Developer/Technician
City of Steinbach
225 Reimer Ave., Steinbach, MB  R5G 2J1
Phone: 204-346-6533
Fax: 204-346-6235
meastley@steinbach.ca
www.steinbach.ca

**Comment by trescube** [comment]
Sounds like a no-go then.

**Comment by iandees** [comment]
Yea, I think we might be able to get around it because we're not *reselling* the data, just redistributing it, but that's probably not what they had in mind.

**Comment by justinelliotmeyers** [comment]
followed up and asked - stay tuned

**Comment by justinelliotmeyers** [comment]
Justin:

You may use that data in Open Source Projects.

Thank you.

Mitchell Eastley, BSc.
GIS Developer/Technician
City of Steinbach
225 Reimer Ave., Steinbach, MB  R5G 2J1
Phone: 204-346-6533
Fax: 204-346-6235
meastley@steinbach.ca
www.steinbach.ca

**Comment by justinelliotmeyers** [comment]
Yeeeeeeeeeehawwwwwwwwww!!!!!!!!!!!!!!!!

**Comment by justinelliotmeyers** [comment]
https://www.dropbox.com/s/manbo8ylt0z2a4t/Parcels_Files.zip?dl=0

**Comment by justinelliotmeyers** [comment]
Its in dropbox link I thought? Let me dl and check again - sorry about this
