### ISSUE TITLE
Manitoba Parcels!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3156]
https://services.arcgis.com/mMUesHYPkXjaFGfS/arcgis/rest/services/ROLL_ENTRY/FeatureServer/0

**Comment by ingalls** [comment]
Wow! I had searched everywhere for these. Amazing find!!

**Comment by nvkelso** [comment]
Looks great! :)
