### ISSUE TITLE
Saskatchewan Civic Address Registry (CAR) Dataset

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#3164]
"To date, there are approximately 470,000 address points mapped, including two provincial parks and one First Nation reserve. "

But...

CAR Full Dataset – 3 year agreement with Maintenance	**$37,500/year**
CAR Partial Dataset – Onetime Purchase	$0.23/point
CAR Full Dataset – Onetime Purchase	**$75,000**
CAR Data Distribution Fee	$100

https://www.isc.ca/MapsandPhotos/GISData/Pages/Civic-Address-Registry-Data-(CAR).aspx

**Comment by justinelliotmeyers** [comment]
e-mailed http://www.geosask.ca/contact/ asking for addresses to join to PPID - may have a workaround.

**Comment by justinelliotmeyers** [comment]
source:https://gisappl.saskatchewan.ca/Html5Ext/index.html?viewer=saskinteractive

- https://gis.saskatchewan.ca/arcgis/rest/services/CadastreSurface/MapServer
