### ISSUE TITLE
Body of water identified as "Occum Pond" in Hanover, NH should be "Occom Pond" 

### ISSUE THREAD

**Issue by jaki1234** [openaddresses/openaddresses#3259]

**Comment by trescube** [comment]
I don't understand.  Are you referring to a particular source?

**Comment by jaki1234** [comment]
From the map on https://openaddresses.io/ homepage -- the body of water labeled "Occum Pond" in Hanover, NH should be spelled "Occom Pond"

**Comment by iandees** [comment]
The map on our homepage has OpenStreetMap data in the background. If you'd like to fix it, you can login at https://openstreetmap.org and fix it yourself! If you'd like one of us to do it, I'm sure we would be happy to.

**Comment by jaki1234** [comment]
Left a note at OpenStreetMap awaiting verification. Thanks!
