### ISSUE TITLE
Ukraine cadaster

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#3305]
Data is shown here, is it downloadable?

http://map.land.gov.ua/kadastrova-karta

**Comment by sergiyprotsiv** [comment]
Hi, I tried to do this for a long time and it seems that only rasters of boundaries are downloadable (and there are no addresses).
I'm in Kyiv right now though, will meet a few government officials, maybe something can be done.

**Comment by msirenko** [comment]
@sergiyprotsiv can you sync up with @Andygol on strategy? Andy knows a few people in the Castadre agency, including the deputy CTO https://www.facebook.com/dmitry.bondarenko.520

**Comment by justinelliotmeyers** [comment]
any update on this? I pulled some of the data into qgis - haven't figured it out 100% but its drawing!

**Comment by nvkelso** [comment]
Picture else it didn't happen ;)

**Comment by sergiyprotsiv** [comment]
Yeah, exactly, you can pull this data all the way down to individual parcel boundaries, but it is a raster without any metadata (as far as I was able to figure out).

**Comment by sergiyprotsiv** [comment]
Will update if I find some interesting info in the field here

**Comment by nvkelso** [comment]
Per Slack conversation marking this as a paid source. I'm curious to see an order form to prove that, though ;)

**Comment by justinelliotmeyers** [comment]
@sergiyprotsiv I've seen a couple updates to random sites over the past month, but nothing address related. Do you have time to poke around and see if we can find anything? I know their national government just passed a law to open admin boundaries, but they wont be available until 2021 I think.

Thanks!
Justin

**Comment by sergiyprotsiv** [comment]
Not that I know of. What I've seen was a list of all valid addresses in Ukraine, but that did not include geometry, only postal codes.
