### ISSUE TITLE
Missing addresses in Los Angeles

### ISSUE THREAD

**Issue by khkwan0** [openaddresses/openaddresses#3325]
Hello, I'm not sure if this is the right place to ask about missing data...so I apologize if I ruffle any feathers.

I was evaluating the dataset found at:

https://s3.amazonaws.com/data.openaddresses.io/openaddr-collected-us_west.zip

I couldn't find some certain addresses in the CSV however, I did test it on the map that is presented on the front page at openaddresses.io.  I can find the address in question on that map (looks like you're using mapbox) but not in the CSV.  I'm guessing mapbox is using a different dataset?  I'm respectfully inquiring if there happens to be a different dataset that does include the street address I was testing against and if it is available under the same license.

Specifically the address is:  9081 Santa Monica Blvd, West Hollywood, CA 90069

**Comment by nvkelso** [comment]
@migurski is the machine MBTiles upload out of date again?

**Comment by iandees** [comment]
@khkwan0 when you say you found it in our website map, do you mean you searched for it in the text box on the web map? That search box does indeed use Mapbox and doesn't necessarily reflect what OpenAddresses has in it's dataset.

**Comment by migurski** [comment]
@nvkelso I believe our dotmap uploads have been behaving themselves lately!

**Comment by khkwan0** [comment]
@iandees Yes, I meant the text box on the web map.  Thank you for the clarification and the quick response.
