### ISSUE TITLE
Jasper/ Newton, Joplin Missouri data sources

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3327]
Can @iandees or @nvkelso  please review the initial splash for terms here: http://joplingis.org/joplinwebmap/

Lands you at Jasper and Newton County Parcels (http://joplingis.org/jop/rest/services/Joplin_Maps/Landbase_New/MapServer )

and Joplin Addresses.

Thanks!

**Comment by iandees** [comment]
It looks OK to me. Seems to be a standard warranty waiver.

**Comment by justinelliotmeyers** [comment]
Thanks! just wanted a second set of eyes on it

**Comment by rbrtmrtn** [comment]
Quick note from six years later that the link above seems to be `404`ing 😕 On a brighter note it looks like Jasper / Joplin have an open data portal now! Documented in #6120.
