### ISSUE TITLE
Lee County, IL

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3332]
source: https://leeil.mygisonline.com/

in Sidwell... Will e-mail

**Comment by justinelliotmeyers** [comment]
wryerson@countyoflee.org

**Comment by justinelliotmeyers** [comment]
just emailed again

**Comment by justinelliotmeyers** [comment]
https://gis.leecountyil.com/server/rest/services/Addresses/MapServer/0

**Comment by justinelliotmeyers** [comment]
![both](https://user-images.githubusercontent.com/5324316/48556195-46d4b280-e8b1-11e8-9d5f-044df3b617e1.jpg)

**Comment by ingalls** [comment]
@justinelliotmeyers is this a replacement for the current lee source? I just added a new label - `Broken Source`, want to just tag issues that are fixes, vs new data with this tag?

**Comment by justinelliotmeyers** [comment]
sorry, i didnt even look for it (*figured we didnt have it because this was Sidwell). I'll check before hand, usually do. Broken Source tag works for me.  Thanks!!
