### ISSUE TITLE
au/countrywide missing id

### ISSUE THREAD

**Issue by jharpster** [openaddresses/openaddresses#3340]
We've noticed that in Australia the ID is missing in the Countrywide file. The source G-NAF includes this ID and we suspect (but are not sure) the issue is in the defining json for that file [here](https://github.com/openaddresses/openaddresses/blob/5d9101e159a594f8994a1a7b32c10f2952649a27/sources/au/countrywide.json
).
We've found that only the ID for Tasmania is consistently populated.

**Comment by andrewharvey** [comment]
@jharpster is it the IDs which look like `GAQLD157763221` that you think are what OpenAddresses should use as the `id` field? If so once #3678 finishes CI I'll merge it in which should add that that `id`.
