### ISSUE TITLE
License violation for French addresses

### ISSUE THREAD

**Issue by jdesboeufs** [openaddresses/openaddresses#3341]
Hello,

I'm the actual product owner of adresse.data.gouv.fr (e.g. Base Adresse Nationale), whose datasets are referenced here.

Sadly our addresses are not currently available under CC0.

They are available under 2 licenses:
- ODbL 1.0
- _Licence gratuite de repartage_,  a country-specific license which is __more restrictive__ than ODbL 1.0, and clearly not compatible with other countries data.

In the future we will certainly provide alternative datasets with only Attribution constraint.

PR is coming.

**Comment by nvkelso** [comment]
Thanks for the heads up @jdesboeufs! 

With your PR they will be flagged as such :)

**Comment by migurski** [comment]
Fixed in https://github.com/openaddresses/openaddresses/pull/3342

**Comment by migurski** [comment]
@jdesboeufs, different parts of the OpenAddresses service update at different frequencies. You can expect these changes to show up everywhere over the course of the next few days.

**Comment by jdesboeufs** [comment]
No problem ;)

I will try to help you to maintain the `sources/fr` directory from today!
Many cities have attribution-only addresses published on their Open Data portal. Are you interested?

**Comment by migurski** [comment]
Thank you, Jérôme! We are definitely interested in additional data. It’s helpful to have new sources even when they're redundant.

**Comment by frodrigo** [comment]
This fix is only a partial fix.
The data pointed is not the ODbL version, is actually the BAN_licence_gratuite_repartage. The links must point to the ODbL version (provided by OSM-FR). (unless @jdesboeufs have now a better dataset to provide ;-) )

**Comment by jdesboeufs** [comment]
The situation is evolving quickly.
The current specific license is not legal anymore, so ODbL is at the moment a good fallback.
