### ISSUE TITLE
Lithuania Addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3349]
almost 1 million records here: http://www.visimarsrutai.lt/arcgis/rest/services/cache/Eismoinfo_cache150518/MapServer/201

or here:
http://www.visimarsrutai.lt/arcgis/rest/services/EismoInfo_cache_150224/MapServer/201

potentially same source:
https://www.eismoinfo.lt/arcgis/rest/services/cache/Eismoinfo_cache150518/MapServer/201

**Comment by nvkelso** [comment]
Nice find!

**Comment by sergiyprotsiv** [comment]
This source seems to be the same as the LAKD (road administration) source we've added back in https://github.com/openaddresses/openaddresses/pull/2355
The Lithuanian OSM community have suggested that this data is not open, so we took the source down after discussion in https://github.com/openaddresses/openaddresses/issues/3015

**Comment by justinelliotmeyers** [comment]
@sergiyprotsiv I just found this today!!!!!!!! https://www.registrucentras.lt/p/1202  I will have to review the data and copyright - but perhaps you have seen it?   Talk soon! Justin

**Comment by sergiyprotsiv** [comment]
Thanks @justinelliotmeyers! I took a quick look and it seems like this follows the exact same naming conventions as the LAKD sources above. Unfortunately it seems incomplete: the address files lack house number field and often the street code (GAT_KODAS) as well. So, it is a strange file: covers all address points, but seemingly not what those addresses are.

However, if you find info that LAKD has been opened up, maybe we could use some of the sources you posted originally?
