### ISSUE TITLE
Moncton, NB, Canada

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3355]
https://services1.arcgis.com/E26PuSoie2Y7bbyI/arcgis/rest/services/Address/FeatureServer/0

**Comment by trescube** [comment]
Sweet, nice find!  They have English names and the fields make it look like there are French names, too, but the data isn't there for street name though street type is there.

**Comment by justinelliotmeyers** [comment]
is there a field we can join the centerline on? https://services1.arcgis.com/E26PuSoie2Y7bbyI/ArcGIS/rest/services/Centerline/FeatureServer/0

**Comment by trescube** [comment]
The `FR` fields appear to be empty there, too.

**Comment by trescube** [comment]
No biggie, at least we'll get English.
