### ISSUE TITLE
Florida Statewide Parcels Updated Source

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3379]
current source seems stale and potentially from 3rd party. This is from official government sources.

Address attributes: ftp://sdrftp03.dor.state.fl.us/Tax%20Roll%20Data%20Files/2017%20Preliminary%20NAL%20-%20SDF%20Files/ (*use NAL files I believe)

GIS Polys for parcels: ftp://sdrftp03.dor.state.fl.us/Map%20Data/00_2017/

Source: http://floridarevenue.com/dor/property/gis/
Notice about potential issues: ftp://sdrftp03.dor.state.fl.us/Map%20Data/00%20GIS%20Data%20Download%20Disclaimer.pdf

Downloaded all data - gis seems to be missing two counties? looking at data quality, attributes to see if it is worthwhile to use this as a new source.

Current Source: http://results.openaddresses.io/sources/us/fl/statewide

**Comment by justinelliotmeyers** [comment]
going to run a sample on a few in the south before Irma hits - Monroe is first. Workflow:
import table to esri fgdb
join table to poly shapefile
export joined table poly to fgdb
repair geometry
reproject to wgs 84
feature to point (centroid)
add xy
export table to csv

will upload Monroe to see if it will work for us.

**Comment by arch0345** [comment]
Statewide datasets were removed in #6554 in favor of county provided data, with FDOR data supplementing counties without any

**Comment by justinelliotmeyers** [comment]
Thanks @arch0345
