### ISSUE TITLE
bounty for data

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#338]
hey guys, sorry i've been annoying ya'll alot...

i came across a locality today offering up address.shp for $15, which is not bad imo....clearly we prefer open, however considering the rest of the prices i've seen (i'm sure ya'll know better), i'm actually not 100% turned off here.
I would actually be inclined to forgo the bounty, just for the sake of getting the data, if you guys wanted to use the bounty money for it.
good idea? horrible idea?
if its good, i'll start paying even more attention to price lists.
I already pinged @waldoj and he said to ping ya'll.

segue: i've come across so many lists that don't offer the exact data and/or theres so much data i'm confused and/or they seem to offer it but the terminology used is different (but i'm sure ya'll would be able to pick through really quick)....can ya'll create a notes page in the wiki, or a new repo just for a dump of these links? i don't want any bounty or anything from any of it, just figure it be a good place to start keeping track.
and again, if thats a dumb idea, please shoot it down.

**Comment by ingalls** [comment]
Closing as stale.

**Comment by waldoj** [comment]
:+1:
