### ISSUE TITLE
Belarus

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3404]
Source:http://map.nca.by/

Can someone review terms before we green light uploading this ? @iandees or @nvkelso ?

I think we want to pay attention to section 3

Thanks!

![byuntitled](https://user-images.githubusercontent.com/5324316/30772921-082cd92a-a034-11e7-8d4f-4f3729a7cf54.jpg)

**Comment by sergiyprotsiv** [comment]
My reading of the license is that most of it refers to the "Cadastral Map" as a piece of software (see section 1.2). I think that this is what the "noncommercial" clause and the "do not put on the open web" refer to (i.e. do not put a copy of their website elsewhere).
On the other hand section 4 states:
"4.1 The information contained in the Public Cadastral Map is freely accessible and is contained in the Appendix"
The Appendix then contains the list of datasources, which includes "Address Points" among other things.

**Comment by justinelliotmeyers** [comment]
Thank you @sergiyprotsiv  !!!

**Comment by justinelliotmeyers** [comment]
Uploading to Dropbox...

**Comment by nvkelso** [comment]
I’m okay with that interpretation – I see the same language when using
Google Translate.

**Comment by migurski** [comment]
Uploaded to https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/migurski/e29094/belarus.zip

Here are some sample rows for building a conform:

```
OBJECTID,nameregion,namedistr,obj_name,elementtyp,elementnam,num_house,num_corp,ind_house,im_type,POINT_X,POINT_Y
1,Минская обл.,Вилейский р-н,д. Роличи,ул.,Зелёная,25.000000000000000,0.000000000000000, ,КС,26.640353226820025,55.063889450537772
2,Витебская обл.,Глубокский р-н,г. Глубокое,ул.,Молодёжная,26.000000000000000,0.000000000000000, ,ЗУ,27.702774862270132,55.148415073996546
3,Витебская обл.,Глубокский р-н,г. Глубокое,ул.,Московская,141.000000000000000,0.000000000000000, ,ЗУ,27.674873328341505,55.121986558532910
4,Витебская обл.,Глубокский р-н,г. Глубокое,ул.,Змитрока Бядули,13.000000000000000,0.000000000000000, ,ЗУ,27.692278842294797,55.154571624081257
5,Витебская обл.,Глубокский р-н,г. Глубокое,ул.,Дроздовича,20.000000000000000,0.000000000000000, ,ЗУ,27.666204067963406,55.146007891950717
6,Витебская обл.,Глубокский р-н,г. Глубокое,ул.,Фридриха Энгельса,13.000000000000000,0.000000000000000, ,ЗУ,27.683850466226090,55.140829165733464
```

**Comment by justinelliotmeyers** [comment]
here are the shapefiles if they are easier to work with: https://www.dropbox.com/sh/l4argho0a79le5p/AAAq3ZCzLfNBh8CVTetZQCZ5a?dl=0

**Comment by sergiyprotsiv** [comment]
Imported in https://github.com/openaddresses/openaddresses/pull/3412
