### ISSUE TITLE
Bad data in Galveston, TX addresses

### ISSUE THREAD

**Issue by gitsno** [openaddresses/openaddresses#3405]
The data in many addresses in Galveston, TX is incorrectly formatted. The main issue is that the full address appears in the postal code, but the street and formatted addresses are wrong too. Examples:
us/tx/galveston:cb6af4ea36a930d7
us/tx/galveston:fdf256f8018e5651
us/tx/galveston:5ad5ce986d6bbfbe
us/tx/galveston:6e55f221590b8a45
us/tx/galveston:86206dbef73444b2
us/tx/galveston:769e473d4d1df892
us/tx/galveston:a943aa88bf60e718
us/tx/galveston:e5407f9852e59436
us/tx/galveston:0db8835c9ed2a341
us/tx/galveston:f784707c6555fba9

**Comment by migurski** [comment]
Thank you for reporting this, @gitsno! We’ll look to see what’s going on.

**Comment by migurski** [comment]
Looks like the SITUS address have turned into a real mess.

Old:

```
27030 ESTUARY DR, UNIT #101, GALVESTON, TX  77554
27130 ESTUARY DR, GALVESTON, TX  77554
```

New:

```
27030 ESTUARY DR UNIT 101GALVESTON, TX 77554
27130 ESTUARY DR GALVESTON, TX 77554
```

I’ve added some failing tests in 381bcd8 for now (branch `migurski/fix-galveston`).

**Comment by migurski** [comment]
Fixed in https://github.com/openaddresses/openaddresses/pull/3406!
