### ISSUE TITLE
Charlevoix County, MI Addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3428]
We do have an address point layer. It is available for purchase for $1000. If you are interested in purchasing it let me know and I will send you an invoice and our data use agreement. 

Thanks,
Emily Selph
GIS Analyst Charlevoix County
301 State Street
Charlevoix, MI 49720

**Comment by justinelliotmeyers** [comment]
followed-up and asked about terms and conditions if purchased

**Comment by justinelliotmeyers** [comment]
[GIS Disclaimer & Licensing Agreement.pdf](https://github.com/openaddresses/openaddresses/files/1360148/GIS.Disclaimer.Licensing.Agreement.pdf)

**Comment by nvkelso** [comment]
$1000 is above my petty cash limit, and for a county with only 26,238 people that's a pretty high cost generally. Adding prohibitive label to capture that. And their terms imply that we couldn't redistribute the data :\

**Comment by justinelliotmeyers** [comment]
yep; just wanted for documentation. I found a different MI county the other day and started poking around in MI again.

**Comment by nvkelso** [comment]
It's certainly a large blank area on the map now, always good to poke around and document :)

**Comment by justinelliotmeyers** [comment]
no data
