### ISSUE TITLE
Cass County, MO

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3437]
$1,500
source: http://www.casscounty.com/2157/GIS

She is sending terms of use/ license to review

**Comment by justinelliotmeyers** [comment]
[licenseagreement.zip](https://github.com/openaddresses/openaddresses/files/1372781/licenseagreement.zip)

**Comment by iandees** [comment]
> Licensee shall not publish, sell, transfer, or otherwise distribute the cadastral map data in digital form to any third party, except as provided in this agreement or with the written permission of Cass County

We can't use this as-is, but maybe we can ask them for extra written permission?

**Comment by justinelliotmeyers** [comment]
no data
