### ISSUE TITLE
Buchanan County, MO Parcels

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3438]
http://gis.co.buchanan.mo.us/arcgis/rest/services/ParcelsTaxData/MapServer/0

**Comment by justinelliotmeyers** [comment]
@iandees or @nvkelso can you look at terms of splash before we use?
http://buchanan.maps.arcgis.com/apps/webappviewer/index.html?id=af63e64cf7a6491a99cd762d2d29075c

Thanks

**Comment by iandees** [comment]
Looks like a standard indemnification disclaimer to me.
