### ISSUE TITLE
Caching problems with new sources

### ISSUE THREAD

**Issue by ingalls** [openaddresses/openaddresses#348]
Here is a list of recently merged sources that can't be cached for one reason or another.
I will be going through and investigating individually once I finish this round of caching.

- [x] us-ar-fayetteville
- [x] us-ca-yolo
- [x] us-ks-city_of_olathe.json
- [ ] us-nc-stanly.json
- [ ] us-ny-cayuga
- [ ] us-ny-ulster.json
- [x] us-wi-vilas.json

**Comment by davidchiles** [comment]
It looks like Yolo county changed their directory structure. The [current URL](https://github.com/openaddresses/openaddresses/blob/master/sources/us-ca-yolo_county.json#L13) should be `ftp://yologis.yolocounty.org/YoloGIS/Tax%20Parcels%20091014.zip`

**Comment by ingalls** [comment]
Closing as stale
