### ISSUE TITLE
Pottawattamie County, IA

### ISSUE THREAD

**Issue by iojjjjiiii** [openaddresses/openaddresses#3499]
http://results.openaddresses.io/sources/us/ia/pottawattamie

Currently using a static source from 2012-->ftp://ftp.igsb.uiowa.edu/gis_library/counties/Pottawattamie/Address_78.zip

Up-to-date source is available here-->https://www.iowagisdata.org/gisdr/county/pottawattamie/open/browse

Actual file-->https://www.iowagisdata.org/gisdr/county/pottawattamie/open/download?filename=shp_PropertyAttributeTables.zip

**Comment by justinelliotmeyers** [comment]
I dont know that we can use this source unless it is stated; can you verify on the terms of use for this data?

**Comment by iojjjjiiii** [comment]
The terms are outlined here and seem to be OK-->https://www.iowagisdata.org/gisdr/county/pottawattamie/open/download?filename=Disclaimer.pdf

**Comment by justinelliotmeyers** [comment]
In obtaining these data from the Pottawattamie County GIS Department, it is understood that you
and/or your organization have the right to use them for any internal purpose. If you modify them, you
should document those changes in a metadata record that should accompany all redistributed data. If
you transmit or provide these data in any form to another user, the data MUST be accompanied by a
copy of this disclaimer and all documentation provided with the original data set including the full
metadata record.
Although the use of these data is not restricted, they may not be sold commercially or privately.
When these data are used in the development of digital or analog (hardcopy) products, Pottawattamie
County, IA must be acknowledged as having contributed data to the development of the product.

**Comment by justinelliotmeyers** [comment]
Can someone else look at the terms please @nvkelso or @iandees 

Thanks

**Comment by justinelliotmeyers** [comment]
@iojjjjiiii typically most of the data on the https://www.iowagisdata.org has restrictive licensing from what I have reviewed.

**Comment by justinelliotmeyers** [comment]
maybe something in here we can use: http://gis.pottcounty-ia.gov/arcgis/rest/services/Public_Basemap_WGS84/ToggleLayers/MapServer

**Comment by iandees** [comment]
I don't think we have a great way to include that disclaimer and metadata with every transmission of this data. Maybe it's good enough to link to the disclaimer/metadata?

**Comment by justinelliotmeyers** [comment]
https://www.iowagisdata.org has 33k
http://gis.pottcounty-ia.gov/arcgis/rest/services/Public_Basemap_WGS84/ToggleLayers/MapServer/3 has 36k

I think http://gis.pottcounty-ia.gov/arcgis/rest/services/Public_Basemap_WGS84/ToggleLayers/MapServer/3 might be a good source; sound okay @iojjjjiiii ?

**Comment by iojjjjiiii** [comment]
Whatever you think is best, guys. I'm pretty new at this! Thanks for all your help.

**Comment by justinelliotmeyers** [comment]
Thanks for your help finding sources!

**Comment by nvkelso** [comment]
I’m fine considering this source CC-BY. We have work planned for the next
3-4 months that will help clarify some of the metadata requirements. In the
meantime it’s not very different than some of our other sources.

**Comment by justinelliotmeyers** [comment]
killing to update new source and keep track of

**Comment by iandees** [comment]
When you close these, can you link to the ticket you're using to track the new source?

**Comment by justinelliotmeyers** [comment]
I didnt know the best way to handle since so many of these are way outdated.  Moving forward I will close out with new link in them. Sorry about that.
https://github.com/openaddresses/openaddresses/issues/5000

**Comment by iandees** [comment]
Thanks for closing out these old tickets!
