### ISSUE TITLE
Scott County, IA

### ISSUE THREAD

**Issue by iojjjjiiii** [openaddresses/openaddresses#3505]
This was set up in 2015 and run successfully not even once-->http://results.openaddresses.io/sources/us/ia/scott

Upon further investigation, the issue is that the source requires the downloader to be logged in; otherwise it returns a login page instead of the zip file. Registration is free and data are open for use by all, so hopefully the fix should be an easy one?

**Comment by justinelliotmeyers** [comment]
updating new issue to track more current version

**Comment by iandees** [comment]
New source in #4999
