### ISSUE TITLE
City of Columbus, Ohio Parcels

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3510]
http://maps.columbus.gov/arcgis/rest/services/CityServices/Parcels/FeatureServer/0
Includes the parcel layer from Franklin, Delaware, Licking, Fairfield, Union and Madison.  Which we have, so not sure if we want to bring it in?

**Comment by nvkelso** [comment]
We have plenty of dups in our sources already, fine to bring in.

**Comment by trescube** [comment]
This is a new one, they place the unit between the street name and type, eg: "974 N HIGH A ST"

**Comment by justinelliotmeyers** [comment]
CHECKED, WE ARE ULLING A CURRENT SERVICE HERE: http://results.openaddresses.io/sources/us/oh/city_of_columbus
