### ISSUE TITLE
Missing Alta Pine Dr 91001 Addresses 

### ISSUE THREAD

**Issue by deharlow** [openaddresses/openaddresses#3575]
The following addresses are missing from the database

"34.202003","-118.130543","906","Alta Pine Dr","Altadena","91001"
"34.201946","-118.130362","920","Alta Pine Dr","Altadena","91001"
"34.201924","-118.130145","930","Alta Pine Dr","Altadena","91001"
"34.201869","-118.129977","940","Alta Pine Dr","Altadena","91001"
"34.201786","-118.129761","950","Alta Pine Dr","Altadena","91001"
"34.201657","-118.129418","970","Alta Pine Dr","Altadena","91001"
"34.201627","-118.129203","978","Alta Pine Dr","Altadena","91001"
"34.201525","-118.129039","988","Alta Pine Dr","Altadena","91001"
"34.201541","-118.128848","998","Alta Pine Dr","Altadena","91001"
"34.201464","-118.128666","1006","Alta Pine Dr","Altadena","91001"
"34.201376","-118.128485","1016","Alta Pine Dr","Altadena","91001"
"34.201345","-118.128284","1026","Alta Pine Dr","Altadena","91001"
"34.20131","-118.128105","1038","Alta Pine Dr","Altadena","91001"
"34.201092","-118.127951","1050","Alta Pine Dr","Altadena","91001"

**Comment by justinelliotmeyers** [comment]
I'll look in LA County to see if any datasets have this

**Comment by justinelliotmeyers** [comment]
906 Alta Pine Dr. is in here:
http://assessor.gis.lacounty.gov/assessor/rest/services/PAIS/pais_parcels/MapServer/0

**Comment by justinelliotmeyers** [comment]
@deharlow I just downloaded what is in OA, and these are all in there? Is there a reason you believe they are missing?  Thanks!

**Comment by justinelliotmeyers** [comment]
![la_points](https://user-images.githubusercontent.com/5324316/32372192-3652901e-c06a-11e7-9800-085aefba42ac.png)

**Comment by deharlow** [comment]
They were not in the data sent I downloaded on 10/31/2017. Sorry about the confusion, will double check with a new data set from today.

**Comment by justinelliotmeyers** [comment]
Should be good to go! what dataset did you download? I just grabbed the https://s3.amazonaws.com/data.openaddresses.io/runs/287602/us/ca/los_angeles.zip and it is in there. Cheers!

Can I close out the issue, or would you like to double check first?

**Comment by deharlow** [comment]
Ok, so they are showing up incorrectly on Alpine Villa Dr, not Alta Pine Dr.
![screen shot 2017-11-03 at 9 35 25 am](https://user-images.githubusercontent.com/33338991/32385141-693a5df8-c07a-11e7-9142-d2a740ae9969.png)

![screen shot 2017-11-03 at 9 36 34 am](https://user-images.githubusercontent.com/33338991/32385183-87c4dc8a-c07a-11e7-8503-f71194ebb606.png)

**Comment by justinelliotmeyers** [comment]
do you have an example of the error(s) on Alpine Villa Dr?

**Comment by deharlow** [comment]
From your own screenshot...

![2017-11-03_09-44-18](https://user-images.githubusercontent.com/33338991/32385499-a3c1177c-c07b-11e7-9b66-0f40a9b20b8f.png)

**Comment by justinelliotmeyers** [comment]
yep, just looked and you are right. Let me find out source. I may have to call assessor's/ gis dept and let them know their base data is bad. Give me a bit.
Thanks!

**Comment by deharlow** [comment]
My second screenshot was from http://maps.assessor.lacounty.gov/ so I know they have it right there.

**Comment by justinelliotmeyers** [comment]
yep, i checked there. It may be coming from the gis dept and not assessor. checking now

**Comment by justinelliotmeyers** [comment]
just called; the file is current to 10/30
Mark Greninger
Geographic Information Officer
County of Los Angeles
Internal Services Department
350 South Figueroa St
Suite 188
Los Angeles, CA 90071
mgreninger@isd.lacounty.gov
(213) 253-5624

If the data is bad, e-mail him and they will get in their work order I was told.  Almost done downloading on my end, then I will update you.

**Comment by justinelliotmeyers** [comment]
this data is bad.

**Comment by justinelliotmeyers** [comment]
@deharlow did you notice any other issues?

**Comment by deharlow** [comment]
Not so far. Did you email them or should I?

**Comment by trescube** [comment]
There are addresses with timestamps in 2017 in the filed available so the source at least needs to be refreshed.  The cached GDB appears to have been created over a year ago.

**Comment by justinelliotmeyers** [comment]
I emailed them and mentioned addresses in this area are not correct.

**Comment by justinelliotmeyers** [comment]
You are right – those should be Alta Pine – I’ll make sure that gets fixed.

If you see anything else like this let me know and we’ll research and fix.  Sometime the algorithm that connected the points to the streets got confused …



Mark Greninger
(213) 253-5624

**Comment by deharlow** [comment]
@justinelliotmeyers Another address 1671 VERANADA AVE ,ALTADENA,CA,91001 34.174917, -118.099296 is missing, would you like me to add a new ticket or just continue on this one.

**Comment by justinelliotmeyers** [comment]
@deharlow I think if you notice issues with the dataset, send them directly to Mark. They are the ones who created/ maintain the data. we just use as a source, and do not actually update the raw data. You might want to ask him if they ever compare to the assessors office data to make sure errors are not created along their processing. Let me know if you want me to reach out to him, or if you do, either is fine with me.
Cheers

**Comment by deharlow** [comment]
I sent him a note this morning. A few more are coming out of the woodwork as people view the map I made.

**Comment by ingalls** [comment]
@deharlow Thanks a ton for reaching back to the source! Going to close this ticket as we will automatically pull the corrected data every week.
