### ISSUE TITLE
Monroe County, IN

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3584]
https://elb2.39dn.com/arcgis/rest/services/eGISDynamicServices/MonroeINDynamic/MapServer/5

**Comment by trescube** [comment]
The folks at 39dn.com got a little upset with us a few months ago about using their hosted endpoint.  @iandees got an email about it so all the 39dn.com-hosted sources were flagged to skip.

**Comment by justinelliotmeyers** [comment]
sorry, lets remove
