### ISSUE TITLE
Sweetwater:Wyoming 

### ISSUE THREAD

**Issue by tlpinney** [openaddresses/openaddresses#36]
http://maps.sweet.wy.us/

Has a WFS but none of the attributes are sent back.

Uses mapserver 6

**Comment by justinelliotmeyers** [comment]
emailed:
https://maps.greenwoodmap.com/contact.html

info@greenwoodmap.com

**Comment by justinelliotmeyers** [comment]
emailed landuse@sweet.wy.us

**Comment by justinelliotmeyers** [comment]
Hi Justin,

 

The SWC parcel data can’t be downloaded.   It is available for purchase for $250.00. 

You can contact the SWC Treasurer’s Office(307-872-3720) and pay by credit card

or sent a check Attention to me.  Once we receive payment, I can email you the Parcel Data.

 

Jeannie

 

 

Jeannie Fisher

Mapping/GIS

fisherj@sweet.wy.us

Sweetwater County

80 West Flaming Gorge Way, Suite 23

Green River, WY  82935

p. (307) 872-3924

fax (307) 872-3991

 

MapServer www.sweet.wy.us  Maps/GIS

**Comment by ingalls** [comment]
@justinelliotmeyers Can you request this through a FOIA request via muckrock? I can cover the cost of this one through there.

**Comment by justinelliotmeyers** [comment]
@ingalls followed up with her to make sure the parcels have situs/ physical address. Once confirmed I will formally file the request. Thanks!

**Comment by justinelliotmeyers** [comment]
emailed again - locked up in a junk mapservice...  stay tuned

**Comment by justinelliotmeyers** [comment]
https://maps.greenwoodmap.com/sweetwater/download/

**Comment by justinelliotmeyers** [comment]
@ingalls sup! lets giv'r!
