### ISSUE TITLE
possible replacements

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#362]
wake county, nc
ftp://wakeftp.co.wake.nc.us/gis/AddressPoints/

**Comment by nvkelso** [comment]
I see data for Wake County, NC around Raleigh on the map preview, is there more work that needs to be done for Wake County?

![image](https://cloud.githubusercontent.com/assets/853051/18562405/6cb438a6-7b38-11e6-9dda-7f3b5ca1c12b.png)
