### ISSUE TITLE
wayne-detroit-mi 

### ISSUE THREAD

**Issue by dexterslu** [openaddresses/openaddresses#363]
hey y'all, here's a decent resource for addresses in Detroit directly from the city's GIS portal  <a href ="http://www.detroitmi.gov/Portals/0/docs/planning/planning/cinfo/adv/SHP/RoadsMGF_polyline.ZIP ">line shapefile</a>

Additionally, if you'd just like a flat file - I cut that up into a csv that's available here <a href="https://www.dropbox.com/s/jplz3ojtmcqo7si/addresses_detroit.csv?dl=0">Here</a>

**Comment by hampelm** [comment]
Hey @dexterslu! Looks like that page fell victim to the website update, but the parcel file is now on the Open Data Portal under a Public Domain license. I opened #933 to get it added.

**Comment by dexterslu** [comment]
I was wondering what happened, thanks for following up @hampelm
