### ISSUE TITLE
Grad Rijeka, Croatia Addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3645]
e-mailed and asked if data was available in a geospatial format.

http://data.rijeka.hr/dataset/ulice-i-kucni-brojevi-grada-rijeke

**Comment by stefanb** [comment]
Was there any response?
Sadly the addresses on the national level are for purchase only ... 
http://www.dgu.hr/proizvodi-i-usluge/katastarski-podaci/podaci-registra-prostornih-jedinica.html

**Comment by stefanb** [comment]
URL for the national level changed to
https://dgu.gov.hr/proizvodi-i-usluge/registar-prostornih-jedinica-172/172

Prices are defined in official gazette: [NN 148/2008](https://narodne-novine.nn.hr/clanci/sluzbeni/2008_12_148_4082.html) states prices as:
> Popis kućnih brojeva za područje Republike Hrvatske: 6000,00 kn (whole country: 800 EUR / 1000 USD)
> Popis kućnih brojeva za područje jedne županije: 1000,00 kn (each of 21 counties individually: 135 EUR / 166 USD)

Not sure about the license of data purchased this way.

**Comment by justinelliotmeyers** [comment]
killing - no response or update. Will implement when their government opens data.
