### ISSUE TITLE
Melbourne, Australia

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3669]
https://data.melbourne.vic.gov.au/Property-Planning/Street-addresses/a7rp-xtya
![m_st_addr](https://user-images.githubusercontent.com/5324316/33690560-0fccdbe0-dab2-11e7-8ae6-6adb548e0d3e.jpg)

http://creativecommons.org/licenses/by/4.0/legalcode

**Comment by andrewharvey** [comment]
#3426 implements this.
