### ISSUE TITLE
Big Horn:Wyoming

### ISSUE THREAD

**Issue by tlpinney** [openaddresses/openaddresses#37]
http://maps.bighorncountywy.gov/mapserver/

http://maps.bighorncountywy.gov/cgi-bin/mapserv?map=MAP_09_MAIN6

WFS server does not bring back attributes

**Comment by justinelliotmeyers** [comment]
@iandees @ingalls 
data download for address points here:
https://maps.greenwoodmap.com/bighorn/mapserver/download/?
