### ISSUE TITLE
Cottonwood County, MN

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3771]
marty.mollenhauer@co.cottonwood.mn.us

**Comment by justinelliotmeyers** [comment]
LEFT A VOICEMAIL

**Comment by justinelliotmeyers** [comment]
Hey Justin,

 

Unfortunately, we only have address points for rural county addresses, we don’t have data for any of our municipalities. So the data is very limited.  If you would like the county address points let me know.

 

Thanks

 

 

Marty Mollenhauer | GIS Specialist | Info Systems Assistant

 

COTTONWOOD COUNTY INFORMATION SYSTEMS

339 9TH ST  

WINDOM MN 56101

 

( (763) 442-5497 | * marty.mollenhauer@co.cottonwood.mn.us | ü www.co.cottonwood.mn.us

**Comment by justinelliotmeyers** [comment]
Hey Justin,

 

The cost for the rural address points would be $30. I’ve attached our data user agreement and GIS fee schedule, please review the documents and let me know if you have any questions.

 

Thanks

**Comment by justinelliotmeyers** [comment]
doc here: https://www.dropbox.com/s/64wi5lg36y2qix6/GIS%20Data%20Requests%20.doc?dl=0

**Comment by justinelliotmeyers** [comment]
not sure we can use unless they give us permission - am I reading that right @iandees or @nvkelso ? Thanks!

**Comment by iandees** [comment]
Yep, they'd need to give us permission to share this data.

**Comment by justinelliotmeyers** [comment]
Thaks @iandees I just e-mailed them back and asked if they would grant us permission. fingers crossed!!

**Comment by justinelliotmeyers** [comment]
he just emailed me this:
Hello Justin,

 

I forwarded your request to my department head and they have determined acceptable use  in your current case. so your GIS data request has been approved, under the condition that reproduced data is not re-sold or distributed to third party vendors. You should be able to send a payment and signed user agreement, as per the instructions sent earlier. If you have any questions about moving forward give me a shout.

 

Thanks
