### ISSUE TITLE
Conform columns

### ISSUE THREAD

**Issue by MiniCodeMonkey** [openaddresses/openaddresses#378]
Hey,

It looks like processed files that have been through openaddresses-conform have the following fields: `lat`, `lon`, `number`, `street`. (Correct me if I'm wrong, this might only be the case for the sources that I'm looking at).

In order to improve the usefulness of the data, I would like to open up the discussion for considering adding additional fields to the data source json files.

US Addresses generally conform to the following structure:
* Street number
* Directional prefix (e.g. N or S)
* Street name (e.g. Quincy)
* Street suffix (e.g. Street, Court, etc.) - USPS has a [full list of street suffixes](https://www.usps.com/send/official-abbreviations.htm)
* Directional suffix (e.g. N or SE)

Right now all of these seems to be stored in only two fields -- street number and street name even though many data sources have addresses stored in multiple fields.

Here's an example from the `us-va-arlington` data source.

```json
{
      "type": "Feature",
      "properties": {
        "OBJECTID": 15163,
        "STNUM": 2765,
        "STCODE": "NQCYST",
        "STRTDIR": "N",
        "STRTDIRPREFIX": "N",
        "STRTNAME": "QUINCY",
        "STRTTYPE": "ST",
        "STRTDIRSUFFIX": "",
        "FULL_ADDRESS": "2765 N QUINCY ST",
        "STATUS": "VERIFIED",
        "UNITCOUNT": 1,
        "STNAME": "N QUINCY ST",
        "UNIT": null,
        "UPDATE_DATE": 1156291200000,
        "ZIP5": 22207
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -77.1007728,
          38.908486
        ]
      }
    }
```

Would it make sense to add the above standardized street components in the json source files when available in addition to the full street name?

Another component is the zip code which could be added as well.

Mathias

**Comment by geobrando** [comment]
Has there been any more discussion about additional fields in the conform object to capture other address elements?  Even if there's no plan in place to process these, shouldn't we at least be capturing these in new sources as we go along as previously mentioned?

**Comment by ingalls** [comment]
@geobrando yes, they are part of the spec here: https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md they just aren't being actively processed as of yet.

**Comment by geobrando** [comment]
@ingalls Is  ```district``` meant for data such as Washington, DC quadrants?  That wasn't clear.  What about street directional prefixes or suffixes?  They're sometimes stored in a field with the street name and other times as a separate field.

**Comment by ingalls** [comment]
@geobrando Yes we do need to add fields for street prefix/postfixes

region=> state/province
district=> county/parish

**Comment by ingalls** [comment]
This discussion is pretty old and a lot of improvements have been made to the output format. If people have more suggestions/concerns about the current format lets open a new issue as a lot of the info in this ticket is now irrelevant.
