### ISSUE TITLE
San Francisco Addresses

### ISSUE THREAD

**Issue by johnhickok** [openaddresses/openaddresses#3784]
I did a sweep of California, and found the City/County of San Francisco's data is missing. Here is their link on their open data portal: 

https://data.sfgov.org/Geographic-Locations-and-Boundaries/Addresses-with-Units-Enterprise-Addressing-System-/dxjs-vqsy

**Comment by justinelliotmeyers** [comment]
where did you not see the data?  Thanks!!

**Comment by johnhickok** [comment]
I downloaded the western United States, loaded all of California into
PostGIS and saw it wasn't there. I verified the regular individual
downloads and didn't see it there either.

This site is exciting.

On Jan 5, 2018 5:45 AM, "Justin Meyers" <notifications@github.com> wrote:

where did you not see the data? Thanks!!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openaddresses/openaddresses/issues/3784#issuecomment-355557904>,
or mute the thread

**Comment by justinelliotmeyers** [comment]
https://openaddresses.io/dotmap.html#10.6/37.7184/-122.4365

That shows what is in there now; 

http://results.openaddresses.io/?runs=all#runs is all downloads. 

http://results.openaddresses.io/sources/us/ca/san_francisco is the current files for SF.

**Comment by johnhickok** [comment]
Many thanks for the kind of hope this project brings to the world. Will any
of your reps speak at FOSS4G North America?

John Hickok, PLS, GISP

*Try paperless...*

**Comment by ingalls** [comment]
@sbma44 @iandees Are either of you planning on attending?

**Comment by iandees** [comment]
I'm not at this point.

**Comment by sbma44** [comment]
I'm afraid we missed the deadline for talk submissions this year.

**Comment by johnhickok** [comment]
I'll be attending. Hope to meet if you are there.

**Comment by sbma44** [comment]
@johnhickok I'm not currently set to, John, but to be honest I haven't looked closely enough at it as an option. If I do I would love to meet.
