### ISSUE TITLE
Finding the next set of data for Open Addresses

### ISSUE THREAD

**Issue by iandees** [openaddresses/openaddresses#384]
We're bumping into the ceiling of easily accessible address/parcel data. Let's start figuring out how we reach the next group of data that's much harder to access for whatever reason:
- stuck behind non-open licenses
- costs money
- is simply not online

My proposal:

1. Start/continue making issues for data sources that we find but aren't immediately useful
  * Describe a "CRM" process for keeping these people talking to us and flowing data our way
  * Who/How do we pay people to chase these contacts?
2. Create an single-page information sheet selling the idea of open parcel and address data to local municipalities
3. Begin contacting municipalities and gauging interest in opening data, making that process as easy as possible
4. ???
5. Profit!!!

I know that @randymeech @lyzidiamond @migurski have all very recently expressed interest in this. Let's keep chatting!

**Comment by ingalls** [comment]
Closing as stale - luckily lots more address sources coming online and to be found!
