### ISSUE TITLE
North Vancouver, Buildings with addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3856]
buildings data and addresses:
addresses: http://geoweb.dnv.org/Products/Data/CSV/BldAddress_csv.zip
buildings: http://geoweb.dnv.org/Products/Data/SHP/BldBuilding_shp.zip

Join on Asset_ID I believe

Will resolve:
https://github.com/openaddresses/openaddresses/issues/898
https://github.com/openaddresses/openaddresses/pull/1262

**Comment by justinelliotmeyers** [comment]
joined attributes to shp here: https://www.dropbox.com/sh/6jfslr0e2bdq1ep/AABZhJQkKxErlxjxwX5YZvKFa?dl=0

**Comment by arch0345** [comment]
It looks like the shapefile linked above was deleted. I've joined the shapefiles again here:
[BldAddress_shp.zip](https://github.com/openaddresses/openaddresses/files/10798027/BldAddress_shp.zip)

@justinelliotmeyers would you be able to upload this to data.openaddresses.io?
