### ISSUE TITLE
Zwolle, Netherlands Addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3862]
http://gisservices.zwolle.nl/ArcGIS/rest/services/Nabijheid_voorzieningen_WWZ38/MapServer/1

**Comment by emacgillavry** [comment]
Not available anymore... suggest to close.

**Comment by justinelliotmeyers** [comment]
@emacgillavry I think this is the new source:
http://opendata-zwolle.opendata.arcgis.com/datasets/c3e6a2ef5fc2459f8f2b458f730c8e84_1

Could you verify?  Thanks!!

**Comment by emacgillavry** [comment]
New link points to a temporary (tijdelijke) service created by students of the local polytech. It's based on an extract of the national address database (BAG) clipped on the boundaries of the Zwolle municipality. Hence does not provide additional records or attributes beyond what's already available.

**Comment by justinelliotmeyers** [comment]
Thanks for your help @emacgillavry
