### ISSUE TITLE
us-pa-philadelphia - multiple potential sources

### ISSUE THREAD

**Issue by rcheetham** [openaddresses/openaddresses#387]
I'm opening an issue as I'm not sure how to best use the repo when there are multiple sources and differing data types.  

Philadelphia does not have a single source of address.  The currently listed file is the property parcel shapefile maintained by the Department of Records based on deed filings.  It is pretty good, but it has mistakes, is missing data, and is not canonical (there is currently no canonical address source).  There are at least two other potential sources for address data in Philadelphia.  These include the property tax assessment data, recently published as open data (see http://www.opendataphilly.org/opendata/resource/225/opa-property-assessments/ ) and the Water Department's billing database (see http://www.opendataphilly.org/opendata/resource/248/philadelphia-water-department-stormwater-billing-parcels/ )

In addition, the best list is the Master Address table maintained as part of the Unified Land Record System (ULRS).  This table has sometimes been published in the past and is likely available through an Open Records request.  The Master Address table is a unified list of all trusted address sources and is a best effort attempt to assign coordinates to each entry.  It is updated on a daily basis based on new information from the Records, Assessment, Water and other databases.

**Comment by ingalls** [comment]
Closing as stale.
