### ISSUE TITLE
Inyo County, California fix broken source

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3877]
addresses:https://services.arcgis.com/0jRlQ17Qmni5zEMr/ArcGIS/rest/services/AddressPolys/FeatureServer/0

Parcels: https://services.arcgis.com/0jRlQ17Qmni5zEMr/arcgis/rest/services/Parcels/FeatureServer/0

Broken Source: http://results.openaddresses.io/sources/us/ca/inyo

**Comment by skylarmt** [comment]
It's broken again, all addresses are just the city name and coordinates.
