### ISSUE TITLE
Data currency

### ISSUE THREAD

**Issue by colinreilly** [openaddresses/openaddresses#388]
What is the plan for keeping data current? Are the source sites being polled periodically to check for updates or has that phase of the project not yet begun? I ask specifically because we (NYC DoITT) are considering different methods for publishing address data on a more frequent basis. 

It's currently done manually on a quarterly basis. I'd like to move to an automated process that runs daily or weekly. Options are Socrata, where NYC open data exists, or alternatively use GeoGig. Would love to get feedback on this.

**Comment by ingalls** [comment]
Machine now runs these on a schedule. Sources are updated weekly.
