### ISSUE TITLE
us/co/statewide.csv - cities are empty

### ISSUE THREAD

**Issue by nigelhorne** [openaddresses/openaddresses#3897]
For example, look at this entry:

-104.7201451,40.5250514,10,Birch Avenue,,,,,80615,,8512912b6c2444a9

Since the file-name is statewide.csv, I can't figure out what the city is.  Should I get it from the zip code (80615)?

**Comment by trescube** [comment]
The city value is being pulled from the `PlaceName` column but unfortunately it appears that only 1,458,595 out of 2,171,595 (67%) of the entries have this column populated.  I'm not sure why this is the case, but you could use the `postcode` value to get the city name.

**Comment by trescube** [comment]
I just confirmed that the `city` field is populated from `PlaceName` when available in the output:

```bash
$ [trescube@flatiron co]$ awk -F ',' '{ if ($6 != "") print $0 }' statewide.csv | head -5
LON,LAT,NUMBER,STREET,UNIT,CITY,DISTRICT,REGION,POSTCODE,ID,HASH
-104.8628599,40.5163706,609,Ponderosa Drive,,SEVERANCE,,,80550,,3dd6a66a5b032710
-104.8628599,40.5163706,418,Ptarmigan Street,,SEVERANCE,,,80550,,5745296c7e49907b
-104.8633861,40.5165803,613,Ponderosa Drive,,SEVERANCE,,,80550,,bd2c046a1c40c349
-104.8633861,40.5165803,413,Ptarmigan Street,,SEVERANCE,,,80550,,8dfd003a82abdc6e
$ [trescube@flatiron co]$ awk -F ',' '{ if ($6 != "") print $0 }' statewide.csv | wc -l   
1458597
```

**Comment by nigelhorne** [comment]
Got it, thank you!
