### ISSUE TITLE
us/ne/dawes.csv - zip codes

### ISSUE THREAD

**Issue by nigelhorne** [openaddresses/openaddresses#3905]
The zip codes in us/ne/dawes.csv have been put into the street field instead of the postcode field.

**Comment by ingalls** [comment]
Thanks for reporting this @nigelhorne! Looks like the original source has turned off MapServer Directory listing. Can you add a sample of 10 or so addresses that are causing issues.

**Comment by nigelhorne** [comment]
$ egrep " \d\d\d\d\d" dawes.csv |wc -l
    4198

$ egrep " \d\d\d\d\d" dawes.csv | head -10
-103.3152251,42.9947185,,"WAYSIDE RD, WHITNEY, NE 69367",,,,,,,6f188ee702edd951
-103.2337367,42.9948398,460,"WAYSIDE RD, CHADRON, NE 69337",,,,,,,a289937abcb614e9
-103.2096575,42.9977177,18574,"HWY 385, CHADRON, NE 69337",,,,,,,9fce07ff4b01da82
-103.2430395,42.9919228,460,"WAYSIDE RD, CHADRON, NE 69337",,,,,,,cd59ccc3fe2c1b69
-103.0760659,42.994241,541,"BRADDOCK RD, CHADRON, NE 69337",,,,,,,28c01ac5b89e65e4
-103.175999,42.9914686,771,"N WHITNEY LAKE RD, WHITNEY, NE 69367",,,,,,,0617c855d546fc16
-103.2322911,42.9902774,462,"WAYSIDE RD, CHADRON, NE 69337",,,,,,,d8880b9460e0ff76
-102.9993683,42.7008008,,"BERRYVILLE RD, CHADRN, NE 69337",,,,,,,155cc172eeff49c3
-103.0097031,42.7341251,16130,"HWY 385, CHADRON, NE 69337",,,,,,,ed024b6e4a46a288
-103.2316533,42.9844187,463,"WAYSIDE RD, CHADRON, NE 69337",,,,,,,8585694927521c8d

**Comment by ingalls** [comment]
Thanks a ton @nigelhorne, @trescube is taking a look at getting this fixed

**Comment by trescube** [comment]
<img width="752" alt="screen shot 2018-03-16 at 12 51 35 pm" src="https://user-images.githubusercontent.com/658991/37533655-d471a8a4-2918-11e8-9ab4-3a0392346739.png">
