### ISSUE TITLE
OpenAddresses-based geocoder

### ISSUE THREAD

**Issue by waldoj** [openaddresses/openaddresses#391]
Is there any effort afoot to create a geocoder based on OpenAddresses data? If not, can we talk about what @opendata can do to facilitate that?

I need a geocoder quite badly for Virginia (for [a business project](https://github.com/openva/crump), and for [a campaign finance project](https://github.com/openva/saberva))—not having that is a blocker to further progress. The cost of geocoding this data via any existing service is north of a thousand dollars apiece, which certainly isn't going to happen. Surely lots of other projects are in the same position.

IMHO, the fact that OpenAddresses's data isn't comprehensive (for almost any states, for the U.S., or for the world) isn't a problem, but is instead an opportunity. A geocoder built on top of it then becomes a good reason to add new places—instead of the abstract value of a collection of data, instead there's an immediate need to add additional localities (_jeez, I can't geocode a third of my state...I need to track down that data and add it to OpenAddresses_).

**Comment by b-may** [comment]
The latest using OpenSddresses: https://github.com/pelias/pelias

**Comment by waldoj** [comment]
Oh, hey—I should have closed this a long time ago. :) Pelias definitely solved this well. Thanks for the nudged, @b-may!
