### ISSUE TITLE
Italy - Duplicate entries 

### ISSUE THREAD

**Issue by nlehuby** [openaddresses/openaddresses#3925]
Italy have many datasets, with various coverage. Some of them overlap, and this can create duplicates.

For instance, this entry :
STREET : Via Messina
NUMBER : 12
CITY : TORINO

can be found in both countrywide dataset, and 21 statewide dataset, with slightly different coordinates.

Is it the expected behaviour ? Do we have some mechanism to conflate or dedupe the addresses between and within the data sources ?

**Comment by iandees** [comment]
Yup, this is expected. We don't have a dedupe process yet and rely on users to decide how they want to do that.

We'd like to have a pipeline to improve the data at some point but don't right now.

**Comment by nigelhorne** [comment]
I can probably write one as part of the ingest process for https://github.com/nigelhorne/Geo-Coder-Free.  Let me know if that would help.

**Comment by sabas** [comment]
The national dataset which was added imho is a bit bad.
