### ISSUE TITLE
Duplication in Alberta

### ISSUE THREAD

**Issue by nigelhorne** [openaddresses/openaddresses#3928]
There are two files in ca/ab: airdrie.csv and city_of_airdrie.csv which contain a lot of duplicated data.  I can't work out the need for two files.

**Comment by ingalls** [comment]
@nigelhorne we intentionally track data from multiple sources, it is up to the end user to conflate a set of files or to pick one source above another.

"duplicate" sources are rarely perfectly identical, and also often update at different times. On top of that, if a source goes down and we are already tracking another source we continue to receive updates.
