### ISSUE TITLE
us-ak-fairbanks

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#393]
fairbanks data is here
ftp://co.fairbanks.ak.us/GIS/Shapes/FNSB_Shapefiles.zip
has address points
need to contact admin and request separate .zip with only address points
may as well ask for parcels zipped up too

however you need pw for access, which costs
ftp://co.fairbanks.ak.us/GIS/CD_sale_permission.pdf
read more http://gis.co.fairbanks.ak.us/

**Comment by slibby** [comment]
Data has been added here: https://github.com/openaddresses/openaddresses/blob/master/sources/us/ak/fairbanks_north_star_borough.json -- I believe this can be closed.
