### ISSUE TITLE
Embedded LF (x0a) in .csv file for ventura ca (US WEST)

### ISSUE THREAD

**Issue by jonlindner** [openaddresses/openaddresses#3943]
See data below (LF after the street name column):

```
-119.2846342,34.3046271,707,SENECA ST,A3,Ventura,,,93001,,7b68a3dec852edc1
-118.7064036,34.2875046,4553,ALAMO ST,"B
B",Simi Valley,,,93063,,23501273288dcc54
-118.7059848,34.2871785,4549,ALAMO ST,"A
A",Simi Valley,,,93063,,850d95318933fffd
-119.2054746,34.1770244,2528,BOLKER DR,,Port Hueneme,,,93041,,e859902c41bdd7b3
```

**Comment by iandees** [comment]
While annoying, that is correct CSV and your parser should be able to handle that.

**Comment by jonlindner** [comment]
Ok thanks, I already had it handled in my code but just wanted to give you a heads up.

**Comment by iandees** [comment]
Thanks! I think stuff like this should at least be flagged in our future "processing pipeline" task that we haven't started yet. For now, I'm going to close this.
