### ISSUE TITLE
Analyze and fix santa clara county, california, US

### ISSUE THREAD

**Issue by 3vivekb** [openaddresses/openaddresses#3981]
The old dataset config at [SC County.json](https://github.com/openaddresses/openaddresses/blob/master/sources/us/ca/santa_clara.json) seems old, it should be compared and updated to a source at this [scc addresses collaborative portal](http://sccgov.maps.arcgis.com/apps/PublicGallery/index.html?appid=a53fdd7dc0464664be045481dc422ed4).

@orangejulius told me to do it.  Please give me a week to update the config myself :P otherwise you guys can do it.

**Comment by arch0345** [comment]
Resolved in #4723
