### ISSUE TITLE
Croatia

### ISSUE THREAD

**Issue by stefanb** [openaddresses/openaddresses#3982]
URL for the Croatian national register ("Registar prostornih jedinica") is:
https://dgu.gov.hr/proizvodi-i-usluge/registar-prostornih-jedinica-172/172

Prices are defined in official gazette: [NN 148/2008](https://narodne-novine.nn.hr/clanci/sluzbeni/2008_12_148_4082.html) states prices as:
> Popis kućnih brojeva za područje Republike Hrvatske: 6000,00 kn (whole country: 800 EUR / 1000 USD)
> Popis kućnih brojeva za područje jedne županije: 1000,00 kn (each of 21 counties individually: 135 EUR / 166 USD)

Not sure about the license of data purchased this way.

Some data seems to be available from local officials, eg Rijeka #3645.

**Comment by stefanb** [comment]
Croatia is opening up in terms of public data, but I don't know the details...

@hbogner, do you know how the terms changed?

**Comment by justinelliotmeyers** [comment]
when they have open data, we will implement. Thank you!

**Comment by hbogner** [comment]
> Croatia is opening up in terms of public data, but I don't know the details...
> @hbogner, do you know how the terms changed?

DGU(SGA -State Geodetic Administration) sells that data. There were attempts to get them to open it up for free use and reuse, but last attempt was rejected. So it's off limits fo us.

But we managed to get them to change the rights and were granted rights to reuse their ortophoto wms last year, but we were rejected few years before that.

It's time to ask again for addresses :)

Until then it's closed :(

**Comment by StephanGeorg** [comment]
Not paid anymore: #7170

FYI @stefanb

**Comment by stefanb** [comment]
Open data portal of DGU: https://dgu.gov.hr/otvoreni-podaci/6116

**Comment by justinelliotmeyers** [comment]
the croatia data is open.

**Comment by stefanb** [comment]
It seems that WFS service of GDU requires authentication:

https://geoportal.dgu.hr/services/sla/inspire/wfs_ad/wfs?request=GetFeature reports:

>Access Denied Error 403
The requested resource requires an authentication.

**Comment by stefanb** [comment]
https://registri.nipp.hr/izvori/view.php?id=442 mentions
> Ograničenje pristupa i korištenja izvora: ugovor/sporazum

which roughly translates to:

Limitation of access and use of the source: contract/agreement

**Comment by stefanb** [comment]
...even though https://data.gov.hr/ckan/en/dataset/adrese states
> Access rights:	Open

**Comment by StephanGeorg** [comment]
EU HVD lists this link: https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/datasetdetails?country=hr&view=themeOverview&theme=none&resourceId=d3104048-688a-4305-9471-77288cc6e350

> Otvorena dozvola
Otvorena dozvola omogućava korisniku svaku uporabu informacija na koje se odnosi, uključujući prostorno i vremenski neograničeno, besplatno, neisključivo i osobno pravo uporabe informacija koje su predmet dozvole.

Address data:
<img width="1067" alt="image" src="https://github.com/openaddresses/openaddresses/assets/7861660/c942d4fa-22c5-48d1-bef3-0ea5af3b947c">

**Comment by stefanb** [comment]
After consulting the Croats the PR #7172 is ready for review.
