### ISSUE TITLE
City of Vaughan, Ontario, CA

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4048]
https://maps.vaughan.ca/arcgis/rest/services/PLANitTest/PLANit/MapServer/9

![vaug](https://user-images.githubusercontent.com/5324316/41114119-7b15df08-6a51-11e8-9619-479261b61d91.png)

**Comment by nvkelso** [comment]
My people :)

**Comment by migurski** [comment]
Huh, our Mapbox tiles aren't working.
