### ISSUE TITLE
City and County of San Francisco source change

### ISSUE THREAD

**Issue by jasonlally** [openaddresses/openaddresses#4060]
In reference to the data source: https://github.com/openaddresses/openaddresses/blob/f090841936bd20566a7a7498b2ac1aa0296e2ab9/sources/us/ca/san_francisco.json#L13

We have an internal ETL that extracts and syncs the shapefile to a table with point geometry on the portal. Over time we are looking to swap in an internal ETL that connects closer to the source to make the ETL more resilient and easier to monitor. The zipped shapefile isn't going away anytime soon, but I just wanted to see if it would make sense to hook this up to a new endpoint. The data is the same, the endpoints change.

The portal page is here: https://data.sfgov.org/Geographic-Locations-and-Boundaries/Addresses-with-Units-Enterprise-Addressing-System-/dxjs-vqsy

The CSV bulk link is here: https://data.sfgov.org/api/views/dxjs-vqsy/rows.csv?accessType=DOWNLOAD

The GeoJSON bulk link is here: https://data.sfgov.org/api/geospatial/c59h-mc8k?method=export&format=GeoJSON

The Shapefile bulk link is here: https://data.sfgov.org/api/geospatial/c59h-mc8k?method=export&format=Shapefile

1. Is there a preference on source type w/r/t the ETL engine for open addresses?
2. Does it make sense to swap in the new endpoint? There's no end of life yet on the zip shapefiles at the existing source, but by switching any changes to data will be documented and communicated at the portal level.
3. I'm happy to put in the PR if it makes sense

**Comment by jasonlally** [comment]
On second look, I would not use the shape file bulk link because of the truncation issue. The CSV and GeoJSON will retain the full names in the schema.

**Comment by arch0345** [comment]
Resolved in #4778
