### ISSUE TITLE
Tagging sources for skip

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#4069]
While the service is accessible, the terms state no-use allowed:

- https://github.com/openaddresses/openaddresses/blob/232785bf2a57dc32bac0b8530a826d04b5c45ce1/sources/ca/on/elgin.json
- https://github.com/openaddresses/openaddresses/blob/232785bf2a57dc32bac0b8530a826d04b5c45ce1/sources/ca/on/haliburton.json
- https://github.com/openaddresses/openaddresses/blob/232785bf2a57dc32bac0b8530a826d04b5c45ce1/sources/ca/on/simcoe.json

EG: restricted license/ no right to copy, modify, or distribute, transmit, etc.

**Comment by justinelliotmeyers** [comment]
@nvkelso I'm going to work on Simcoe to open their data to the public, or potentially change their license :) https://twitter.com/MapMakinMeyers/status/1009989360710815745

**Comment by ingalls** [comment]
Stale
