### ISSUE TITLE
North Saanich, BC, Canada

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4075]
https://services1.arcgis.com/CppIoMHWYIrPO1GU/ArcGIS/rest/services/Public_AddressCadastral/FeatureServer/0

**Comment by justinelliotmeyers** [comment]
@iandees or @ingalls can you review terms of this: https://northsaanich.maps.arcgis.com/apps/webappviewer/index.html?id=7457a1e62fcc4ae9aa0a236f3b79321b

**Comment by nvkelso** [comment]
Needs the new non-commercial flag added on indexing.
