### ISSUE TITLE
STATSSA Dwelling Frame - licensing conditions

### ISSUE THREAD

**Issue by sindile** [openaddresses/openaddresses#4106]
Dear Community,

Attached is dwelling frame document.
Whilst the intended purpose of this dataset was not to create a National Address dataset I think it might be relevant.
What concerns does the community have with licensing conditions of the dataset - if there are any I could try and raise these with STATSSA.

[Dwelling Frame 20160722.docx](https://github.com/openaddresses/openaddresses/files/2215977/Dwelling.Frame.20160722.docx)
Thank you.

**Comment by ingalls** [comment]
cc/ @openaddresses/contributers

**Comment by justinelliotmeyers** [comment]
whoa! amazing! do you have a way for us to download and evaluate the data? Thanks @sindile

**Comment by justinelliotmeyers** [comment]
is it right around 13 million points? or are they polygons? Thanks!

**Comment by sindile** [comment]
Uploading to google drive and will send link for downloading. It is only points, but some of them are not street addresses.

**Comment by sindile** [comment]
Here is the link - 
[Dwelling Frame 201712.docx](https://github.com/openaddresses/openaddresses/files/2272911/Dwelling.Frame.201712.docx)
https://drive.google.com/open?id=1KpLwbwq9YeYNLVFJDFsGwx8egfw6eeay

**Comment by andrewharvey** [comment]
looks like this is closed by #4132

**Comment by justinelliotmeyers** [comment]
@sindile can you assist me with a question I have about this data and other data for South Africa?  Thanks!

**Comment by sindile** [comment]
@justinelliotmeyers I could try to do that. Thanks

**Comment by justinelliotmeyers** [comment]
@sindile email might be best instead of here - what is your email? I am trying to find a current version of these addresses if possible. Also, do you know where to find a current version of the South African Geographical Names Council Database?

I appreciate your time and help!
Justin

**Comment by sindile** [comment]
@justinelliotmeyers sindile.bidlaATgeoilocate dot co dot za
