### ISSUE TITLE
us-co-boulder

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#411]
tons o data, including control points and parcel data.
+100 for weed zone shapefiles
http://www.bouldercounty.org/gov/data/pages/gisdldata.aspx

**Comment by slibby** [comment]
Unfortunately the county doesn't have address data published. I've reached out to them at gisinfo@bouldercounty.org to ask if they have more info.

**Comment by slibby** [comment]
I got a response from the County with directions on how to join their owner/addresses CSV with their parcel boundaries. I tried once and wasn't able to get it to work but will try again.

**Comment by nvkelso** [comment]
While we have Boulder city, looks like we're still missing Boulder county.

This page [describes](http://gis.bouldercounty.opendata.arcgis.com/datasets/89ae49d4ddf246388ee5f5e952aa84db_0) parcel data, including download options:

- http://maps.bouldercounty.org/arcgis/rest/services/Emap/BOCO_Parcels/MapServer/0
- http://gis.bouldercounty.opendata.arcgis.com/datasets/89ae49d4ddf246388ee5f5e952aa84db_0.zip

Parcel shapefile data still only has APN numbers (no address info), so needs to be joined with CSV files listed on the [assessor](http://www.bouldercounty.org/dept/assessor/pages/propertydatadownload.aspx) page, which are apparently updated daily at 4 am:

- http://assessor.boco.solutions/ASR_PublicDataFiles/Account_Parcels.csv
- http://assessor.boco.solutions/ASR_PublicDataFiles/Owner_Address.csv

**Comment by nvkelso** [comment]
Verified the join of those 3 files will result in the correct addresses (but PR still needed to automate this).

QGIS preview:

<img width="978" alt="screen shot 2016-12-13 at 22 32 45" src="https://cloud.githubusercontent.com/assets/853051/21171964/2f9201be-c184-11e6-8d78-bef731203163.png">

**Comment by nvkelso** [comment]
We have coverage here now, closing.

<img width="385" alt="screen shot 2017-07-25 at 20 39 50" src="https://user-images.githubusercontent.com/853051/28603504-6fc07af4-7179-11e7-934d-f6eaeb52a0b3.png">
