### ISSUE TITLE
us-co-broomfield

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#412]
city and county
http://www.broomfield.org/index.aspx?nid=1761

**Comment by slibby** [comment]
This has been added and can be closed

**Comment by geobrando** [comment]
@slibby If these are equivalent we should change to the shapefile

**Comment by slibby** [comment]
@geobrando 37,000 features in the REST service, 23,300 in the shapefile download. My vote would be for the REST service in this case.

**Comment by geobrando** [comment]
Ahh..  So not the same data.  Could still be added for the sake of redundancy. Wonder what the difference is
