### ISSUE TITLE
us-co-el-paso

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#417]
el paso county  
http://adm.elpasoco.com/InformationTechnologies/GeographicInformationSystems/Pages/FreeDataCatalog.aspx

**Comment by slibby** [comment]
Parcel data only available as paid source: http://adm.elpasoco.com/InformationTechnologies/GeographicInformationSystems/Pages/LicensedDataCatalog.aspx

**Comment by nvkelso** [comment]
Too expensive.

**Comment by nvkelso** [comment]
More than $10,000 and no redistribution.

**Comment by justinelliotmeyers** [comment]
closing as we have a source: http://results.openaddresses.io/sources/us/co/el_paso
