### ISSUE TITLE
Burlington, Ontario, Canada Addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4170]
https://navburl-burlington.opendata.arcgis.com/datasets/address-points

**Comment by justinelliotmeyers** [comment]
![bur](https://user-images.githubusercontent.com/5324316/44664752-1b44d900-a9e2-11e8-950e-a5b135961cac.png)

**Comment by trescube** [comment]
Already got this one! https://github.com/openaddresses/openaddresses/blob/master/sources/ca/on/city_of_burlington.json
