### ISSUE TITLE
Duplicate CSVs

### ISSUE THREAD

**Issue by nigelhorne** [openaddresses/openaddresses#4192]
There are a number of duplicate CSVs in the current zip files.  Is that to be expected?

./us/pa/armstrong.csv and ./us/pa/bedford.csv are identical
./us/mi/grand_traverse.csv and ./us/pa/fayette.csv are identical
./us/tx/city_of_hurst.csv and ./us/tx/hurst.csv are identical
./us/mi/grand_traverse.csv and ./us/wa/benton.csv are identical
./us/mi/grand_traverse.csv and ./us/wa/asotin.csv are identical
./us/mi/grand_traverse.csv and ./us/la/west_feliciana.csv are identical
./us/ga/seminole.csv and ./us/ga/pierce.csv are identical

**Comment by trescube** [comment]
Hey, thanks for sorting through all of this!  

- us/pa/armstrong and us/pa/bedford both appear to point to the Bedford data file and is probably a typo as the 
- us/mi/grand_traverse, us/pa/fayette, us/wa/benton, us/wa/asotin, and us/la/west_feliciana are all empty
- us/tx/city_of_hurst and us/tx/hurst both point to the city and the latter should be removed
- us/ga/seminole and us/ga/pierce are indeed the same but I'm not sure why.  @ingalls?

**Comment by ingalls** [comment]
Closing as stale
