### ISSUE TITLE
fix broken issue Garfield County, CO, USA

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4198]
broken issue: http://results.openaddresses.io/sources/us/co/garfield

PHYSADDRES is field in new parcel polys located here: 
https://www.garfield-county.com/geographic-information-systems/download-gis-data.aspx
https://www.garfield-county.com/geographic-information-systems/documents/parcels/ParcelsSHP.zip

**Comment by ingalls** [comment]
Fixed
