### ISSUE TITLE
us-co-garfield

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#420]
garfield county
http://www.garfield-county.com/geographic-information-systems/download-gis-data.aspx

**Comment by slibby** [comment]
Shapefile and current GIS Service have same number of records (parcels).

@geobrando you mentioned on another issue that shapefile > Esri REST Service if they are the same data - is that something to stick to?

**Comment by geobrando** [comment]
@slibby That's what the consensus seems to be.

https://github.com/openaddresses/openaddresses/issues/889#issuecomment-73934214
https://github.com/openaddresses/openaddresses/pull/336#issuecomment-52409211

**Comment by iandees** [comment]
The thinking is that a file download of a shapefile is less time consuming
on our side and less work for the server in the other end, too.

**Comment by slibby** [comment]
closed via https://github.com/openaddresses/openaddresses/pull/1461
