### ISSUE TITLE
License issues with nl/countrywide

### ISSUE THREAD

**Issue by andrewharvey** [openaddresses/openaddresses#4227]
The current nl/countrywide source has terms and conditions at https://www.esri.nl/nl-nl/legal/voorwaarden/esri-nederland-terms-of-use which specify:

> The data remain the property of Esri Nederland and use is only permitted in combination with Esri software based on our Fair Use Policy.

I don't think that meets the "free and open" criteria.

It looks like the upstream source provides the data under CC0, but change for the data extracts. I tried to pull from their WFS service but it seems like it only provides a small subset of data. https://www.kadaster.nl/bag-producten

**Comment by sergiyprotsiv** [comment]
I'm pretty sure the data can be downloaded freely.
E.g. you can follow the links from the Dutch open data portal
https://www.pdok.nl/introductie?articleid=1948590 to get to the download URL: http://geodata.nationaalgeoregister.nl/inspireadressen/extract/inspireadressen.zip

This one is 1.6 GB compressed, so it should include all addresses. Not so sure on the license. The atom feed says "Copyright (c) 2012, Kadaster en Openbare Registers", the downloaded file has no license info. But perhaps we can use the licensing from the upstream links you suggested?

**Comment by stvno** [comment]
#4573 solves this problem, since it doesn't use ESRI, but the opensource nlextract
