### ISSUE TITLE
Link suggestion for address points of us/ga/clayon (old link failed)

### ISSUE THREAD

**Issue by eugeneYWang** [openaddresses/openaddresses#4230]
In order to replace [us/ga/clayon](https://github.com/openaddresses/openaddresses/blob/e688519fbf168e2a8a441eeb3ada2fb4d7da7c0c/sources/us/ga/clayton.json), which has failed several times, I want to contribute a candidate link that might be the right one. 

Please check out: 
https://weba.co.clayton.ga.us:5443/server/rest/services/Reference/AddressPoints/MapServer/0

**Comment by ingalls** [comment]
thanks a ton for finding a replacement source! We depend heavily on folks having a few seconds to go out and find new sources as the occasionally get moved around.

I've created a PR here to update this source: https://github.com/openaddresses/openaddresses/pull/4232

Provided it passes we will include the new data in our next run.
