### ISSUE TITLE
Box Elder County, Utah

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4239]
Currently at library in Brigham City, UT... Middle of nowhere. Found their service!

http://gis.boxeldercounty.org/arcgis/rest/services/Webmap/Cadastral_Layers/MapServer/0

![bec](https://user-images.githubusercontent.com/5324316/47307159-563b4580-d5fc-11e8-8630-84f7894b0147.jpg)

**Comment by iandees** [comment]
❤️

**Comment by migurski** [comment]
Curious about that Tetris piece in the west.
