### ISSUE TITLE
us-co-montezuma

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#425]
montezuma county	
http://montezumacounty.org/web/departments/gis-mapping/gis-download/

**Comment by slibby** [comment]
This should be switched from the current source (old ArcGIS Server) to the shapefile here: ftp://206.123.215.195/GIS/Addresses.zip

**Comment by slibby** [comment]
closed via https://github.com/openaddresses/openaddresses/pull/1460
