### ISSUE TITLE
Fix La Plata County, CO

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4254]
returning 1 record (they must have moved records around and is pulling from county boundary)
http://results.openaddresses.io/sources/us/co/la_plata

Updated source:
https://lpcgis.laplata.co.us/arcgis/rest/services/Map_LayersJSC/MapServer/78

**Comment by ingalls** [comment]
Tracking fix: https://github.com/openaddresses/openaddresses/pull/4255

**Comment by ingalls** [comment]
@justinelliotmeyers looks like the service is down? https://lpcgis.laplata.co.us/arcgis/rest/services/Map_LayersJSC/MapServer/78

![screenshot from 2018-11-14 09-09-22](https://user-images.githubusercontent.com/1297009/48487712-fc89fd80-e7ec-11e8-839f-530732b0e5b9.png)

**Comment by justinelliotmeyers** [comment]
Strange, I just opened it in chrome and ran a query to make sure the amount was roughly similar to the previous count and it worked!?

**Comment by justinelliotmeyers** [comment]
@ingalls !!!!!!!!!

ftp://ftp.laplata.co.us/shapefiles/

ftp://ftp.laplata.co.us/shapefiles/AddressPoints.zip

**Comment by ingalls** [comment]
Running: https://github.com/openaddresses/openaddresses/pull/4255
