### ISSUE TITLE
City of Bothell, WA Addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4257]
main page:
http://www.bothellwa.gov/238/GIS-Data
cadastral addresses:
ftp://gisvisitor:mapping$98011@search.ci.bothell.wa.us/GIS_Base_Data/GIS_Data/ESRI%2010.X%20SHP/Cadastre_shp.zip

**Comment by justinelliotmeyers** [comment]
![both](https://user-images.githubusercontent.com/5324316/48526067-4528d180-e854-11e8-9067-9f2cf797afdb.jpg)

**Comment by ingalls** [comment]
Ref: https://github.com/openaddresses/openaddresses/pull/4258
