### ISSUE TITLE
US/PA/FAYETTE - US Northeast Download Issue

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4261]
https://s3.amazonaws.com/data.openaddresses.io/openaddr-collected-us_northeast.zip

US / PA / FAYETTE - is coming through as an empty CSV?

@iandees or @ingalls any ideas?

I think they are coming through fine here: http://results.openaddresses.io/sources/us/pa/fayette

**Comment by justinelliotmeyers** [comment]
I think its because the coordinate system isnt in wgs84?

**Comment by rbrtmrtn** [comment]
Thanks for opening this @justinelliotmeyers. It looks like it's still relevant a few years later 😄 

Here's a sample row from Fayette:

```json
{"type":"Feature","properties":{"hash":"f3209f84d2661d38","number":"308","street":"MARKET ST","unit":"","city":"","district":"","region":"","postcode":"15012","id":""},"geometry":{"type":"Point","coordinates":[-8891070.99454,4884506.93247]}}
```

That lat/long is for sure not in WGS84 😭 If I fetch metadata from GeoServer:

http://fayettemaps.rba.com:8080/geoserver/fayette/ows?service=WFS&version=1.1.1&request=GetCapabilities&typename=fayette:ParcelsPolygon&outputFormat=json

it looks like the layer is in Web Mercator (`EPSG:3857`). I'll submit a PR to set the `conform.srs`.

**Comment by rbrtmrtn** [comment]
The PR ran and I still can't get the addresses to show up in PA.

Oh, derp, I missed this in [`CONTRIBUTING.md`](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#processing-tags) that the `conform.srs` tag is currently only supported for CSV and SHP. Hmm... wondering if there's a way to make this GeoServer source output one of those...
