### ISSUE TITLE
fix San Mateo County, CA, USA

### ISSUE THREAD

**Issue by jdstone-loansnap** [openaddresses/openaddresses#4271]
The path to the file changed as did the path to the file within the zip file.  I updated the file and submitted a new PR (#4270), but it's still not able to successfully parse the .shp file.

Broken Link:
http://results.openaddresses.io/sources/us/ca/san_mateo

--new source:
http://maps.smcgov.org/GIS_data_download/

Parcels:
http://maps.smcgov.org/GIS_data_download/SAN_MATEO_COUNTY_ACTIVE_PARCELS.zip

**Comment by migurski** [comment]
Try the change I suggest in the comment thread? https://github.com/openaddresses/openaddresses/pull/4270#issuecomment-442258600

**Comment by arch0345** [comment]
Resolved in #6062
