### ISSUE TITLE
us-co-ouray

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#428]
ouray county  
http://ouraycountyco.gov/gis.html

**Comment by slibby** [comment]
@ingalls have you reached out to Ouray recently? I can do so but didn't want to duplicate. I'll see if we can get a shapefile version of that .kmz.

**Comment by ingalls** [comment]
@slibby no I haven't reached out recently, feel free to go for it.

**Comment by justinelliotmeyers** [comment]
Just e-mailed jbockes@ouraycountyco.gov

**Comment by justinelliotmeyers** [comment]
sent follow-up email to gis and assessor

**Comment by ingalls** [comment]
We have address & parcel data for ouray now
