### ISSUE TITLE
fix Elgin, Ontario

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4298]
new source:
https://gisdata.elginmapping.ca/arcgis/rest/services/Public/MapServer/1

changed broken issue:
http://results.openaddresses.io/sources/ca/on/elgin

**Comment by ingalls** [comment]
Having a hard time caching this one :(

![screenshot from 2018-12-19 08-09-19](https://user-images.githubusercontent.com/1297009/50219397-715cd400-0365-11e9-88ea-3280aa8ee610.png)
