### ISSUE TITLE
London, Ontario

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4311]
https://apps.london.ca/generateform/default.aspx?form=opendatarequests

**Comment by justinelliotmeyers** [comment]
all four of these might have to be used to make one layer?
https://maps.london.ca/arcgisa/rest/services/Addresses/MapServer

**Comment by justinelliotmeyers** [comment]
@ingalls This is a pretty big gap in Ontario
Should I wait to hear back from their formal data request system, or do you think we should try to just pull these?

Thanks!

**Comment by justinelliotmeyers** [comment]
| Gerry BockTechnologistGeomatics DivisionCity of London
-- | --
 
300 Dufferin Ave. London, On. N6A 4L9
P: 519.661.2489 x 2345 \| Fax: 519.661.6422
gbock@london.ca \| www.london.ca

**Comment by justinelliotmeyers** [comment]
| Gerry BockTechnologistGeomatics DivisionCity of London
-- | --

**Comment by justinelliotmeyers** [comment]
Hi Justin,

 

Unfortunately I cannot send the data you have requested without referring to a City project and project manager;

see link below…..

 

https://www.london.ca/business/Resources/Consultant-Resources/Pages/GISDataRequest.aspx

**Comment by justinelliotmeyers** [comment]
I asked how to formally request it again although I filled out their formal request!?! Stay Tuned 'eh!

**Comment by justinelliotmeyers** [comment]
they sent data attached here:
https://www.dropbox.com/s/xxe4oybgpxbza2d/attachments_20181219.zip?dl=0

**Comment by justinelliotmeyers** [comment]
Justin,
--
 
Spoke to my boss – Gary Irwin, the City Surveyor.
 
I was informed that addresses are now open source data.
 
 
 
 
 
Gerry Bock
 
Technologist
 
Geomatics Division
 
City of London
 
 
 
300 Dufferin Ave. London, On. N6A 4L9
 
P: 519.661.2489 x 2345 \| Fax: 519.661.6422
 
gbock@london.ca \| www.london.ca

**Comment by iandees** [comment]
Awesome! 🎉
