### ISSUE TITLE
Alex, SD Parcels

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4349]
http://ims.districtiii.org/arcgis/rest/services/ALEX_PARCEL/MapServer/1

**Comment by ingalls** [comment]
Broken URL :/ (My bad for getting to it late)

**Comment by justinelliotmeyers** [comment]
@ingalls whoa.... http://www.districtiii.org/gis/interactive_mapping.php

I'll go through these tonight/ tomorrow and sort out. JACKPOT!

**Comment by ingalls** [comment]
@justinelliotmeyers Haha  you already have! A year ago
