### ISSUE TITLE
Webster County, KY Parcels

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4378]
http://kygisserver.ky.gov/arcgis/rest/services/WGS84WM_Services/Ky_PVA_Webster_Parcels_WGS84WM/MapServer/1

**Comment by ingalls** [comment]
@justinelliotmeyers unfortunately the address in this service is the postal address, not the situs address. If you query it contains a ton of PO boxes

**Comment by justinelliotmeyers** [comment]
@ingalls should we reopen and have me look into it? Or what are your thoughts? sorry about this amigo!

**Comment by ingalls** [comment]
@justinelliotmeyers feel free to re-open or just add a new ticket if you find something! Just trying to wrap up all the tickets I'm assigned to
