### ISSUE TITLE
us-co-rifle

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#439]
http://www.rifleco.org/index.aspx?nid=74

**Comment by justinelliotmeyers** [comment]
emailed ericagentry@rifleco.org

**Comment by justinelliotmeyers** [comment]
Hi Justin,

 

Thank you for your interest in the City of Rifle and our City data.  The parcel data with ownership information is officially managed by Garfield County. You can reach their offices in Glenwood Springs at 970-945-1377.

 

Thank you,

Erica Gentry

**Comment by justinelliotmeyers** [comment]
called; they said parcels are open data - left voicemail with gis technician in assessors office

**Comment by justinelliotmeyers** [comment]
https://github.com/openaddresses/openaddresses/issues/4269will fix this
