### ISSUE TITLE
us/az/santa_cruz has incorrect conform and data source seems to be down

### ISSUE THREAD

**Issue by MiniCodeMonkey** [openaddresses/openaddresses#4401]
The current conform fields for the `street` includes the city name in the output. I was looking into fixing it, but the source seems to be unavailable: https://gis.santacruzcountyaz.gov/arcgis/rest/services/ParcelSearch/Parcels/MapServer/0

What do we do in case like this? Can we temporarily disable the source until it is resolved? I would argue that we would rather have no output for this source, rather than output with errors/incorrect format.

https://github.com/openaddresses/openaddresses/blob/master/sources/us/az/santa_cruz.json

**Comment by justinelliotmeyers** [comment]
https://mapservices.santacruzcountyaz.gov/wagis01/rest/services/ParcelSearch/Parcels/MapServer/0

**Comment by MiniCodeMonkey** [comment]
Thanks!!

**Comment by geobrando** [comment]
Per @trescube Point layer with good address fields found here
https://mapservices.santacruzcountyaz.gov/wagis01/rest/services/Buildings/AddressPoints/MapServer/0
