### ISSUE TITLE
us/wa/king conform has no region attribute

### ISSUE THREAD

**Issue by petershank** [openaddresses/openaddresses#4404]
Yay, my first contribution!  I want to dig deeper and learn to write better issues and help fix things, but I am still finding my way around.  Please point me in the right direction!

us/wa/king conform has no region attribute. If the source truly lacks a field for "state", could we create a function that hard-codes "WA" into a region property?  Seems pretty safe...

-Peter

**Comment by ingalls** [comment]
@petershank Unfortunately at the moment we don't hardcode values. If values are missing it's up to the data consumer to backfill these values.
