### ISSUE TITLE
Fix Broken Humboldt County, Ca

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4427]
broken:
http://results.openaddresses.io/sources/us/ca/humboldt

new source:
https://humboldtgov.org/276/GIS-Data-Download

JOINED ADDR DATA TO PARCELS:
https://www.dropbox.com/sh/f2r6sp8jvrfd698/AAAZvKaW_oOyaUinndOVyx0xa?dl=0

**Comment by arch0345** [comment]
Resolved in #5820
