### ISSUE TITLE
St. Joseph, Indiana: new source

### ISSUE THREAD

**Issue by bertday** [openaddresses/openaddresses#4441]
It looks like St. Joseph County, Indiana has been [erroring](http://results.openaddresses.io/sources/us/in/st_joseph) for a few years now.

It seems it used to be coming from a Socrata site which has since been shut down. The City's new [open data portal](https://data-southbend.opendata.arcgis.com), hosted on ArcGIS Online, does not have parcels or addresses (that I've found). However, the county GIS office does maintain shapefiles for property parcels and addresses for download on this page:

http://www.sjcindiana.com/788/Layer-List

I might be able to help with updating this -- will just need some time to look over the docs and get up to speed.

**Comment by rbrtmrtn** [comment]
A few years later... the source above ^^ is no longer valid. It looks like there are open parcels here:

https://sjcgis-stjocogis.hub.arcgis.com/datasets/stjocogis::parcel-boundaries/about
