### ISSUE TITLE
us/mn/carlton missing all street names

### ISSUE THREAD

**Issue by colin-umn** [openaddresses/openaddresses#4457]
The STREET column in us/mn/carlton.csv is missing the actual street name for all rows.  Looking at the source file, it appears that the problem is
```
        "street": [
            "Pre_Dir",
            "Street_Name",
            "Suf_Type",
            "Suf_Dir"
        ],
```
should be
```
        "street": [
            "Pre_Dir",
            "StreetName",
            "Suf_Type",
            "Suf_Dir"
        ],
```
Note that the underscore should not appear in StreetName.

I have contributed pull requests to other GitHub repositories, but I have not done so in this case because I have not figured out how to actually test my change.  Since this is a significant breakage (at least for this small county), I would like to get it fixed quickly.  I would accept any suggestions on how to test a change in this repository.

**Comment by iandees** [comment]
Hi @colin-umn! Thanks for pointing this out. You can just change the source file and GitHub will run the tests and generate new data for you to check out.

**Comment by colin-umn** [comment]
Hi @iandees.  I submitted the pull request and the test is in progress.  How long do these test typically take?  If it's going to be while, I will stop watching it :)

Also, if the testing is successful how long does it take for a change to appear in the downloads?

**Comment by colin-umn** [comment]
My first pull request resulted in duplicate prefixes and suffixes in STREET (Komoko Rd Rd), so I closed that and changed the JSON for street to simply "street": "StreetName".  The result from the new pull request looks much better.  Since I can't execute the merge, I would greatly appreciate it if somebody with that power could do so.  It is #4459.

**Comment by trescube** [comment]
Looks great, thanks for the contribution!
