### ISSUE TITLE
ca/on/waterloo has no city/district name

### ISSUE THREAD

**Issue by Valachio** [openaddresses/openaddresses#4466]
As the title states.  There are only coordinates, street number, and street names.  No city or district names.

**Comment by iandees** [comment]
It's likely that the data source we use doesn't have that information. You can look in the source information to see what the source is and look to see what data they make available. If it's not there you can look for a better source that might have the information you seek.

**Comment by trescube** [comment]
It may be that the `Municipality` field did not exist in data when the source was first added.

**Comment by Valachio** [comment]
Just wanted to say a big thank you for fixing this quickly.  I'm compiling a database of all the addresses in Ontario and I'll see if I can help OA become 100% complete in Ontario.
