### ISSUE TITLE
Parsing address codes

### ISSUE THREAD

**Issue by smrazaabbas** [openaddresses/openaddresses#4493]
Its not an issue, but I was hoping if I could be directed to a resource (if there is) that can help me parse the codes used in addresses - for example BLVD translates to boulevard while RD translated to Road. I need the resource to compare against existing addresses so can someone direct me to the coding convention of openaddresses.

Thanks

**Comment by trescube** [comment]
Hi @smrazaabbas, the OpenAddresses project doesn't use any coding standards itself for BLVD->Boulevard or RD->Road, we're mostly a collection point for addresses wherever we can find them.  If you're looking for a USPS-official list of those abbreviations, check out Appendix C in [Publication 28 - Postal Addressing Standards](https://pe.usps.com/cpim/ftp/pubs/pub28/pub28.pdf).  Does that answer your question?

**Comment by smrazaabbas** [comment]
It really does. Thanks a lot.
