### ISSUE TITLE
Bexar County has been broken since jan-2017

### ISSUE THREAD

**Issue by moff3tt** [openaddresses/openaddresses#4496]
Looks like bexar county texas hasn't had a successful pull since jan 2017. Probably a bad url, I found the one in the code was bad and found this url which I think may be a functioning update?

Old: http://mapservices.bexar.org/arcgis/rest/services/Parcels/MapServer/0
New: https://maps.bexar.org/arcgis/rest/services/Parcels/MapServer/0

**Comment by justinelliotmeyers** [comment]
Count: 617851
