### ISSUE TITLE
Fix Anoka County, MN, USA

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4521]
broken issue:
http://results.openaddresses.io/sources/us/mn/anoka

new source:
ftp://gisdata.co.anoka.mn.us/Address_Pts.zip

**Comment by trescube** [comment]
I think this was a temporary hiccup, original source appears to work now: http://gis.msa-ps.com/arcgis/rest/services/AnokaCoMN/AnokaCoMN_GIS/MapServer/1

**Comment by ingalls** [comment]
Fixed
