### ISSUE TITLE
Fix Halifax, Canada

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4558]
new source:
http://catalogue-hrm.opendata.arcgis.com/datasets/2bc8323870fe44eab50630404713be6a_0
https://services2.arcgis.com/11XBiaBYA9Ep0yNJ/arcgis/rest/services/CivicAddresses/FeatureServer/0

broken issue:
http://results.openaddresses.io/sources/ca/ns/halifax

**Comment by ingalls** [comment]
Fixed: https://github.com/openaddresses/openaddresses/pull/4562
