### ISSUE TITLE
Fix Flanders Belgium Source

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4560]
new source: 
https://downloadagiv.blob.core.windows.net/crab-adressenlijst/Shapefile/CRAB_Adressenlijst_Shapefile.zip

broken link:
http://results.openaddresses.io/sources/be/flanders

**Comment by barthanssens** [comment]
See also #3002

**Comment by barthanssens** [comment]
I guess this issue could be closed, since it's solved by #3002 ?

**Comment by barthanssens** [comment]
Can be closed, as #3002 fixes this
