### ISSUE TITLE
[POLAND] Missing postal codes for polish addresses.

### ISSUE THREAD

**Issue by macieg** [openaddresses/openaddresses#4586]
Hi,
I've found that many polish addresses are missing postal codes (or actually they have value 00-000).
After some analysis, it seems that the root cause for that situation is the wrong data provided by authorities.

However, I think there is a solution. All polish postal codes are provided by The Polish Post and it's updated monthly. 
Here is the link - https://www.poczta-polska.pl/hermes/uploads/2013/11/spispna.pdf

Combining the current data and the postal code data can improve the data significantly. I'm happy to contribute, but I need some guidance :)

**Comment by migurski** [comment]
That list is great! In terms of guidance, I think the most reasonable step would be to convert the PDF into a tabular data file, or find a machine readable version. Does Poczta Polska offer this list in a spreadsheet or database format?

**Comment by macieg** [comment]
It seems that Poczta Polska is not allowing to use that data for free.
