### ISSUE TITLE
Seeking the ./sources/

### ISSUE THREAD

**Issue by mappy13** [openaddresses/openaddresses#4590]
Under the "Contributing to OpenAddresses," it's recommended I check out other sources in ./sources/ before moving forward. However, openaddresses.io/sources is not found. I'm sure I'm doing this wrong. I've gone through the wiki, and there's no duplicate there. How do I check ./sources/?

**Comment by iandees** [comment]
It's referring to this GitHub repo you're commenting in 😄 . Sources are in here: https://github.com/openaddresses/openaddresses/tree/master/sources

I'll update the doc to include that link.
