### ISSUE TITLE
resolution of lat/long on addresses?

### ISSUE THREAD

**Issue by burtonator** [openaddresses/openaddresses#4592]
Trying to find this in the documentation and can't find the right source.

I'm trying to see what level I can resolve addresses.  I need to nail the address to the rooftop basically.  OR at least know the precision.  I'm not finding this in the documentation so maybe someone can point me in the right direction?

**Comment by iandees** [comment]
When a contributor is able to ascertain that information and remembers to add it to the source metadata, it will be in the `accuracy` attribute. Check the [CONTRIBUTING.md doc](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#processing-tags) for more details.
