### ISSUE TITLE
Dubai datasource is broken.

### ISSUE THREAD

**Issue by Duiesel** [openaddresses/openaddresses#4610]
Hello!
Dubai datasource in https://github.com/openaddresses/openaddresses/blob/master/sources/ae/du/dubai-en.json
is broken.

Probably I can find a new one but for now it doesn't work.
http://www.makani.ae/arcgis/rest/services/DMap_EL_2015/MapServer/14
So I've been checked makani.ae site - it works but
I have no idea where to find files to download, seems they doesn't provide this feature anymore or it's hidden.

**Comment by arch0345** [comment]
Resolved in #6303
