### ISSUE TITLE
Maine Missing from download data

### ISSUE THREAD

**Issue by colelloa** [openaddresses/openaddresses#4624]
when downloading in batch from https://data.openaddresses.io/openaddr-collected-us_northeast.zip  - it appears there is no ME directory, and all addresses are missing. Why?

**Comment by colelloa** [comment]
maine should have nearly 100% coverage via https://results.openaddresses.io/coverage/us/

**Comment by colelloa** [comment]
perhaps this issue is related to https://github.com/openaddresses/openaddresses/issues/4619 ?

**Comment by iandees** [comment]
Yup, probably. We should see a complete run soon.
