### ISSUE TITLE
Download Link Changed

### ISSUE THREAD

**Issue by Jnb2387** [openaddresses/openaddresses#4636]
Not an issue just a update. The link to download the collected addresses seems to have been updated.

Old one was:
https://s3.amazonaws.com/data.openaddresses.io/openaddr-collected-us_west.zip 

New one is:
https://data.openaddresses.io/openaddr-collected-us_west.zip 

This was an issue for us as we do an automated pull from the link. No issues after we updated our script

**Comment by iandees** [comment]
Yep, I changed the download link so that we were more defended against someone accidentally downloading a ton of copies of the same data. This happened last month and cost us ~$2,000 in Amazon bills.

All download links should point to `data.openaddresses.io` now.
