### ISSUE TITLE
Slovenian addresses contain wrong and/or duplicated postal codes

### ISSUE THREAD

**Issue by techouse** [openaddresses/openaddresses#4651]
I just recently stumbled upon this repository and found that it featured [data for Slovenian addresses](https://github.com/openaddresses/openaddresses/blob/master/sources/si/countrywide.json) as well. Now I simply wanted to parse the CSV in order to obtain a recent relation of `Post Office (postal code) <-> Commune (municipality) <-> Region`, however after I crunched the data with `pandas` I saw that there were some inconsistencies. I wanted to contact somebody at _The Surveying and Mapping Authority of the Republic of Slovenia_, however that proved to be difficult. However I somehow stumbled upon the information that @stefanb has some ties with this data set. So posting this as a GitHub issue seemed the most obvious course of action.

Here's a simple Python script I used to extract the data that yields inconsistencies:

```python
import pandas as pd

df = pd.read_csv(
    "si-addresses-2019-10-13.csv", sep=";", header=0,
    index_col=["id"],
    usecols=["postcode", "commune", "region", "id"]
)

df.drop_duplicates(["postcode", "commune", "region"], keep="last", inplace=True)

df.sort_values(by=["postcode"], inplace=True)

df.to_excel("si-post-offices-2019-10-13.xlsx")
```

Here's the data with marked duplicates [si-post-offices-2019-10-13.xlsx](https://github.com/openaddresses/openaddresses/files/3723689/si-post-offices-2019-10-13.xlsx).

There are also some postal codes that are wrong for some reason, so I suggest someone from the Slovenian government takes a look at the data again.

**Comment by stefanb** [comment]
In Slovenia postal code areas are not drawn by municipality (=commune in openaddresses) borders, but by the national post office as they saw convenient for their business (sorting, delivery...).
Does this explain the problems you see in the data?

**Comment by stefanb** [comment]
You might also want to check
https://github.com/openaddresses/openaddresses/tree/master/scripts/si

**Comment by techouse** [comment]
I am aware of that fact, however look at [this spreadsheet](https://github.com/openaddresses/openaddresses/files/3731703/diff.xlsx). There are many inconsistencies.

The sourcecode for the spreadsheet is this:

```python
import pandas as pd

communes_df = pd.read_excel("si-post-offices-2019-10-13.xlsx", usecols=["postcode", "commune"])

posts_df = pd.read_csv("post_offices.txt", index_col=["Postal code"])

merged = pd.merge(communes_df, posts_df, left_on="postcode", right_on="Postal code")

merged.set_index("postcode", inplace=True)

merged.to_excel("diff.xlsx")
```

The [post offices](https://github.com/openaddresses/openaddresses/files/3731715/post_offices.txt) were sourced from [posta.si](https://www.posta.si/zasebno-site/Documents/Seznami/Seznam%20poštnih%20številk%20za%20naslavljanje.pdf).

**Comment by stefanb** [comment]
Your generated `diff.xlsx` shows that the names of the postal areas are often not matching the municipality names and areas are not equal (1 post code spreading over several municipalities or vice versa). This is what I was describing too. Yes, it is weird, but not necessarily wrong, just matching the official data. I think that the reason for this is that ~500 postal areas predate the ~200 municipalities.

Are you perhaps bothered by the fact that there is no postal area name in the openaddresses dataset? There is just the 4-digit number, which can be easily mapped to the postal area name if needed. We can add that too, but am not sure where to squeeze it in to match the openaddresses schema - https://github.com/openaddresses/openaddresses/blob/master/schema/source_schema.json
