### ISSUE TITLE
Dufferin, Ontario, Canada incorrect coordinates

### ISSUE THREAD

**Issue by JosephKuchar** [openaddresses/openaddresses#4659]
The geocoordinates for this source are all over the place (example longitudes: -108, 0.8, 85). Maybe a projection issue?

**Comment by iandees** [comment]
The [source](https://github.com/openaddresses/openaddresses/blob/addc351d4ec046bf16c2e9f057a6af471033020e/sources/ca/on/dufferin.json) points to [this layer](https://services5.arcgis.com/C0BEdgagVaXzcw0W/arcgis/rest/services/Dufferin_County_Entrances_July2018/FeatureServer/0) which [appears to be](http://www.arcgis.com/home/webmap/viewer.html?url=https://services5.arcgis.com/C0BEdgagVaXzcw0W/ArcGIS/rest/services/Dufferin_County_Entrances_July2018/FeatureServer/0&source=sd) points spread across CONUS, not address points for the city.

Can you help us find a new source for the city?

**Comment by JosephKuchar** [comment]
Good idea! I just found this one: https://data-dufferincounty.opendata.arcgis.com/datasets/dufferin-county-entrances/data
A quick glance makes it seem like it's the better option.
