### ISSUE TITLE
Benton County, WA Source Update

### ISSUE THREAD

**Issue by pnoll1** [openaddresses/openaddresses#4676]
https://services7.arcgis.com/NURlY7V8UHl6XumF/ArcGIS/rest/services/Addresses/FeatureServer/5 works but excludes Kennewick, Richland, West Richland, Benton City and Prosser.

https://services7.arcgis.com/NURlY7V8UHl6XumF/ArcGIS/rest/services/Parcels_and_Assess/FeatureServer/0 looks to contain the whole county but esridump errored out when downloading.

Arcgis webapp is at https://bentonco.maps.arcgis.com/apps/webappviewer/index.html?id=428dcedbce17467b841844e8908bf3e7

**Comment by arch0345** [comment]
Resolved in https://github.com/openaddresses/openaddresses/pull/5207
