### ISSUE TITLE
Indian address download

### ISSUE THREAD

**Issue by gudduIgn** [openaddresses/openaddresses#4677]
I have downloaded data for ASIA, but there are so many csv files inside it, how do i get data for india only.

**Comment by iandees** [comment]
We distribute files per source. You'll need to process the data to get just the geographic area that you want.

**Comment by trescube** [comment]
Now that you have the data downloaded, look for directories prefixed with `in/`.  Looking at the [map](https://results.openaddresses.io/), however, I don't think that there is any data for India.
