### ISSUE TITLE
italy

### ISSUE THREAD

**Issue by sbma44** [openaddresses/openaddresses#475]
Italy's INSPIRE report isn't among the most helpful, but it does supply some contact points. The country is in the process of embracing open data, and it might well be that address information is available but not yet well organized/easily found. 

Contact points:
-  NCP.Inspire@minambiente.it, inspire@sprambiente.it (INSPIRE)
- [data.gov.it contact form](http://www.dati.gov.it/content/scrivi-alla-redazione)

data.gov.it is CC-BY-SA. There are a number of municipal and regional data portals will probably have to be contacted if/when national inquiries come up empty:
- [Comune di Bologna](http://dati.comune.bologna.it)
- [Comune di Firenze](http://opendata.comune.fi.it/)
- [Comune di Milano](http://dati.comune.milano.it/)
- [Comune di Roma](http://dati.comune.roma.it)
- [Comune di Torino](http://aperto.comune.torino.it/)
- [Provincia autonoma di Trento](http://dati.trentino.it/)
- [Provincia di Roma](http://www.opendata.provincia.roma.it/)
- [Regione Emilia Romagna](http://dati.emilia-romagna.it/)
- [Regione Liguria](http://www.regione.liguria.it/opendata.html)
- [Regione Lombardia](https://dati.lombardia.it)
- [Regione Piemonte](http://www.dati.piemonte.it/)
- [Regione Puglia](http://www.dati.puglia.it/portal/page/portal/datipuglia)
- [Regione Toscana](http://dati.toscana.it)
- [Regione Veneto](http://dati.veneto.it/)

**Comment by sbma44** [comment]
Some ideas about how Italy could be tackled on a national scale:

[This slide deck](http://www.slideshare.net/slideistat/di-pede-patruno-cimbelli-zullofardelli-istat-officinail-15censimento-generale-della-pope-delle-abitarchivi-comunali?next_slideshow=2) provides a good overview of the situation. The short version:

1. Italy provides geometry for their equivalent of Census tracts (*sezioni*). 
  ![image](https://cloud.githubusercontent.com/assets/31717/5460418/8ed11fe4-8530-11e4-88a9-aa739cd5b377.png)

2. A flat file of address numbers (*numeri civici*) and streets (*denominazioni*) is available, and has a column to join against *sezioni*
  ![image](https://cloud.githubusercontent.com/assets/31717/5460503/7430ae24-8531-11e4-9e43-5f0b456b8885.png)

3. IStat, the Census agency, intends to reconcile these datasets, dropping points for individual buildings. This effort is known as GeoCIV; there's a related effort called ANNSCU. 
  ![image](https://cloud.githubusercontent.com/assets/31717/5460543/c230c230-8531-11e4-8c0c-0f3512c19797.png)
  Sounds great, but it's already several years overdue. In email, I have been promised only docs next year. I think we can take this as an endorsement of viability but not a likely source of data.

Clearly we can geocode to *sezioni* centroids. **Can we do better by defining address ranges per *sezioni* edge, ordering them according to adjacent *sezioni*, and dropping interpolated address points onto those edges?**

In cities I think this might be able to produce good results:

![image](https://cloud.githubusercontent.com/assets/31717/5460758/7dc60202-8533-11e4-920b-7d34fa46f397.png)

In rural areas it seems unlikely that we can do much better than centroids (though snapping to roads is still probably worthwhile).

Questions:
- What's your gut sense? Could this produce usably accurate data?
- What are the holes in the above? I can imagine how to code much of the above, but am sure there are pitfalls I'm not anticipating.
- If we used OSM for the road-snapping piece, would there be ODbL implications? If so, could we assign road names solely through polygon adjacency?
- There are 21.6 million addresses in the CSV. I don't think we want to drag points to roofs for all of them, but perhaps there's a way to target only the less-dense areas where interpolated results will produce unacceptably large errors.

**Comment by justinelliotmeyers** [comment]
@sbma44 think we have a nation-wide dataset - can i close this? Thanks!!

**Comment by sbma44** [comment]
yup this is super-stale. thanks for the gardening! 🌱
