### ISSUE TITLE
canada

### ISSUE THREAD

**Issue by sbma44** [openaddresses/openaddresses#476]
Canada has an [excellent open government license](http://geogratis.gc.ca/geogratis/licence?lang=en) that should amount to CC-BY. They also maintain a [geolocation service](http://data.gc.ca/data/en/dataset/31c77624-498d-4716-837d-c26bfc22445a) but do not appear to expose the underlying data.

**Comment by justinelliotmeyers** [comment]
Closing this as we have numerous sources in Canada and the mentioned canvec and geobase data are not going to help us. Thanks!
