### ISSUE TITLE
North Myrtle Beach, SC, USA Addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4771]
https://gis.nmb.us/arcgis/rest/services/Viewpoint/Viewpoint/MapServer/1

**Comment by iandees** [comment]
This looks to be the source for Horry county, SC, which we already have 👍.

**Comment by justinelliotmeyers** [comment]
Yikes. Sorry about that. Website looked unique to the municipality. Thanks for catching!!

**Comment by iandees** [comment]
No problem! Thanks for posting it.
