### ISSUE TITLE
Montreal, Quebec - Possible to separate address ranges?

### ISSUE THREAD

**Issue by JosephKuchar** [openaddresses/openaddresses#4790]
Hi All,

I noticed that the Montreal source file (https://github.com/openaddresses/openaddresses/blob/master/sources/ca/qc/montreal.json) uses the "TEXTE" column for the street number, which actually contains slightly weirdly formatted street number ranges (e.g., 108-112 would be written \# 108-12). However, the original source file also contains ADDR_DE and ADDR_A columns, which are essentially start and end street numbers for each entry.
Would it be worthwhile to add a step in processing for this file to use those columns and duplicate rows? So that instead of a single \# 108-12 entry, you would have separate rows for 108, 110, and 112 all with identical geocoordinates? This is something I plan to do for my own purposes (separate entries will make it easier to match addresses in my scripts), but maybe there's a clever way to do it so that it can be used by OpenAddresses as well.
Cheers,
Joseph

**Comment by JosephKuchar** [comment]
I have a simple loop that seems to do the trick for my purposes, it just appends new row information to lists depending on the beginning and ending street numbers. Maybe something like this could be done in the processing? 
```

N=len(df)
for i in range(N):
    num1=NUM1[i]
    num2=NUM2[i]
    while num2>num1:
        num1+=2
        
        NUM1.append(min(num2,num1))
        NUM2.append(num2)
        GEN.append(GEN[i])
        SPEC.append(SPEC[i])
        LON.append(LON[i])
        LAT.append(LAT[i])
```
Doing this essentially doubles the number of addresses rows in Montreal.

**Comment by andrewharvey** [comment]
You could try with the format function https://github.com/openaddresses/openaddresses/blob/master/ATTRIBUTE_FUNCTIONS.md#format ?

**Comment by JosephKuchar** [comment]
I've looked into it, and while that would be an option to separate a string containing a range of numbers, it isn't quite what I have in mind. What I'm suggesting (and I suppose this isn't particular to Montreal, it's just where I noticed it) is to separate ranges of street numbers into individual lines. So for instance, the single entry in the original data of 
`188-92  Main Street  45.50 -76.60`
would be transformed into three rows in the processed data, of
```
188  Main Street  45.50 -76.60
190  Main Street  45.50 -76.60
192  Main Street  45.50 -76.60
```
I don't think the format function can handle this sort of thing, but I could be wrong.

**Comment by andrewharvey** [comment]
Right so I think the approach in OA is to represent address the same way the source data represents it. So if the source data uses a range, then we try to output a range.

If you want that exploded I'd say that's up to you as a post processing step.

**Comment by iandees** [comment]
Unfortunately OpenAddresses doesn't support address range linestrings right now. You'd need to separate it out manually, upload the resulting points, and use that as a source.

**Comment by JosephKuchar** [comment]
> Unfortunately OpenAddresses doesn't support address range linestrings right now. You'd need to separate it out manually, upload the resulting points, and use that as a source.

I actually have processed the Montreal data to create the semi-duplicate rows I was talking about - if you'd prefer to have that data as a source, then I can certainly upload it. I guess it depends on whether you would like the processed data to as accurately as possible mirror the original source data (as suggested by Andrew), or if you'd rather process it a bit for extra usability.

**Comment by nvkelso** [comment]
We lightly process some other sources. So I vote yes but let’s hear other opinions.

**Comment by iandees** [comment]
If the data is of suitable license, we can definitely host the processed data and use it as a source. Typically we store the code to do the processing in the [`scripts/`](https://github.com/openaddresses/openaddresses/tree/master/scripts) directory of this repo and then add a note in the source describing which script was run to generate the cached data.
