### ISSUE TITLE
us-in-evansville

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#483]
Evansville  
http://maps.evansvillegis.com/arcgis_server/rest/

**Comment by nvkelso** [comment]
(#487 was closed in favor of this issue.)

**Comment by nvkelso** [comment]
Has data now, closing.

<img width="533" alt="screen shot 2017-07-25 at 20 33 15" src="https://user-images.githubusercontent.com/853051/28603380-85bd2718-7178-11e7-93e4-6b1ad0c57e06.png">
