### ISSUE TITLE
Better support for `/vsizip/vsicurl/`

### ISSUE THREAD

**Issue by bahoo** [openaddresses/openaddresses#4837]
GDAL added support for just curling + unzipping files on the fly, which is simple change, but makes scripting much more elegant. 👍 👍 

When I upload the zip file to my own S3 bucket, and use this approach, it works great:

    ogrinfo /vsizip/vsicurl/https://www.jonculver.com/king.zip/us/wa/king.vrt

    INFO: Open of `/vsizip/vsicurl/https://www.jonculver.com/king.zip/us/wa/king.vrt'
          using driver `OGR_VRT' successful.
    1: king (Point)

But I'm having trouble executing this consistently from `data.openaddresses.io`. This is perhaps more a feature than a bug :D and I might be telling on myself here as getting egregious with bandwidth use, but ...the same file direct from the source doesn't work — it needs a few more params ( to not do a `HEAD` operation, use a less suspicious `User-Agent`, and generally just log everything as loudly as possible) which in my case, looks like:

    GDAL_HTTP_USERAGENT="Mozilla/5.0" CPL_VSIL_CURL_USE_HEAD=NO ogrinfo --debug ON --config CPL_CURL_VERBOSE YES /vsizip/vsicurl/https://data.openaddresses.io/runs/796972/us/wa/king.zip/us/wa/king.vrt
    HTTP: libcurl/7.69.1 OpenSSL/1.1.1d zlib/1.2.11 brotli/1.0.7 c-ares/1.15.0 libssh2/1.9.0 nghttp2/1.40.0 librtmp/2.3
    HTTP: GDAL was built against curl 7.69.0, but is running against 7.69.1.
    * Couldn't find host data.openaddresses.io in the .netrc file; using defaults
    *   Trying 185.152.67.139:443...
    * Connected to data.openaddresses.io (185.152.67.139) port 443 (#0)
    * ALPN, offering h2
    * ALPN, offering http/1.1
    * successfully set certificate verify locations:
    *   CAfile: /usr/local/etc/openssl@1.1/cert.pem
      CApath: /usr/local/etc/openssl@1.1/certs
    * SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
    * ALPN, server accepted to use h2
    * Server certificate:
    *  subject: CN=data.openaddresses.io
    *  start date: Mar 16 21:08:40 2020 GMT
    *  expire date: Jun 14 21:08:40 2020 GMT
    *  subjectAltName: host "data.openaddresses.io" matched cert's "data.openaddresses.io"
    *  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
    *  SSL certificate verify ok.
    * Using HTTP2, server supports multi-use
    * Connection state changed (HTTP/2 confirmed)
    * Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
    * Using Stream ID: 1 (easy handle 0x7f90e4000e00)
    > GET /runs/796972/us/wa/king.zip HTTP/2
    Host: data.openaddresses.io
    user-agent: Mozilla/5.0
    accept: */*

    * old SSL session ID is stale, removing
    * Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
    < HTTP/2 200 
    < date: Sat, 21 Mar 2020 04:47:12 GMT
    < content-type: application/zip
    < content-length: 18677731
    < server: BunnyCDN-LA1-470
    < cdn-pullzone: 88615
    < cdn-uid: a4740746-4c22-48f3-a707-b99dd3d400b1
    < cdn-requestcountrycode: US
    < cdn-edgestorageid: 603
    < last-modified: Fri, 13 Mar 2020 23:09:00 GMT
    < cdn-cachedat: 2020-03-20 18:33:51
    < cache-control: public, max-age=31556926
    < cdn-requestid: e48b2f7fe8297739a0d178c7bd6eede4
    < cdn-cache: HIT
    * Failed writing header
    * stopped the pause stream!
    * Connection #0 to host data.openaddresses.io left intact
    VSICURL: GetFileSize(https://data.openaddresses.io/runs/796972/us/wa/king.zip)=18677731  response_code=200
    VSICURL: Downloading 18661376-18677730 (https://data.openaddresses.io/runs/796972/us/wa/king.zip)...
    * Couldn't find host data.openaddresses.io in the .netrc file; using defaults
    * Found bundle for host data.openaddresses.io: 0x7f90e2f004b0 [can multiplex]
    * Re-using existing connection! (#0) with host data.openaddresses.io
    * Connected to data.openaddresses.io (185.152.67.139) port 443 (#0)
    * Using Stream ID: 3 (easy handle 0x7f90e380ae00)
    > GET /runs/796972/us/wa/king.zip HTTP/2
    Host: data.openaddresses.io
    user-agent: Mozilla/5.0
    accept: */*
    range: bytes=18661376-18677730

    [ ... many snipped ... ]

    < HTTP/2 200 
    < date: Sat, 21 Mar 2020 04:48:14 GMT
    < content-type: application/zip
    < content-length: 18677731
    < server: BunnyCDN-LA1-470
    < cdn-pullzone: 88615
    < cdn-uid: a4740746-4c22-48f3-a707-b99dd3d400b1
    < cdn-requestcountrycode: US
    < cdn-edgestorageid: 603
    < last-modified: Fri, 13 Mar 2020 23:09:00 GMT
    < cdn-cachedat: 2020-03-20 18:33:51
    < cache-control: public, max-age=31556926
    < cdn-requestid: 47a532ff73312bdb82d9a6cdd83ea214
    < cdn-cache: HIT
    ERROR 1: Range downloading not supported by this server!
    * Failed writing header
    * stopped the pause stream!
    * Connection #0 to host data.openaddresses.io left intact
    VSICURL: DownloadRegion(https://data.openaddresses.io/runs/796972/us/wa/king.zip): response_code=200, msg=Failed writing header
    VSICURL: Got response_code=200
    VSICURL: Downloading 0-16383 (https://data.openaddresses.io/runs/796972/us/wa/king.zip)...
    * Couldn't find host data.openaddresses.io in the .netrc file; using defaults
    * Found bundle for host data.openaddresses.io: 0x7f90e2f004b0 [can multiplex]
    * Re-using existing connection! (#0) with host data.openaddresses.io
    * Connected to data.openaddresses.io (185.152.67.139) port 443 (#0)
    * Using Stream ID: f1 (easy handle 0x7f90e380a800)
    > GET /runs/796972/us/wa/king.zip HTTP/2
    Host: data.openaddresses.io
    user-agent: Mozilla/5.0
    accept: */*
    range: bytes=0-16383

    < HTTP/2 200 
    < date: Sat, 21 Mar 2020 04:48:14 GMT
    < content-type: application/zip
    < content-length: 18677731
    < server: BunnyCDN-LA1-470
    < cdn-pullzone: 88615
    < cdn-uid: a4740746-4c22-48f3-a707-b99dd3d400b1
    < cdn-requestcountrycode: US
    < cdn-edgestorageid: 603
    < last-modified: Fri, 13 Mar 2020 23:09:00 GMT
    < cdn-cachedat: 2020-03-20 18:33:51
    < cache-control: public, max-age=31556926
    < cdn-requestid: bba52b4ae69bc3b0e54f0c00bc088442
    < cdn-cache: HIT
    ERROR 1: Range downloading not supported by this server!
    * Failed writing header
    * stopped the pause stream!
    * Connection #0 to host data.openaddresses.io left intact
    VSICURL: DownloadRegion(https://data.openaddresses.io/runs/796972/us/wa/king.zip): response_code=200, msg=Failed writing header
    VSICURL: Got response_code=200
    FAILURE:
    Unable to open datasource `/vsizip/vsicurl/https://data.openaddresses.io/runs/796972/us/wa/king.zip/us/wa/king.vrt' with the following drivers.
      -> PCIDSK
      -> netCDF
      -> PDS4
      -> JP2OpenJPEG
      -> JPEG2000
      -> PDF
      -> MBTiles
      -> EEDA
      -> ESRI Shapefile
      -> MapInfo File
      -> UK .NTF
      -> OGR_SDTS
      -> S57
      -> DGN
      -> OGR_VRT
      -> REC
      -> Memory
      -> BNA
      -> CSV
      -> NAS
      -> GML
      -> GPX
      -> LIBKML
      -> KML
      -> GeoJSON
      -> GeoJSONSeq
      -> ESRIJSON
      -> TopoJSON
      -> Interlis 1
      -> Interlis 2
      -> OGR_GMT
      -> GPKG
      -> SQLite
      -> OGR_DODS
      -> ODBC
      -> WAsP
      -> PGeo
      -> MSSQLSpatial
      -> PostgreSQL
      -> OpenFileGDB
      -> XPlane
      -> DXF
      -> CAD
      -> Geoconcept
      -> GeoRSS
      -> GPSTrackMaker
      -> VFK
      -> PGDUMP
      -> OSM
      -> GPSBabel
      -> SUA
      -> OpenAir
      -> OGR_PDS
      -> WFS
      -> WFS3
      -> HTF
      -> AeronavFAA
      -> Geomedia
      -> EDIGEO
      -> GFT
      -> SVG
      -> CouchDB
      -> Cloudant
      -> Idrisi
      -> ARCGEN
      -> SEGUKOOA
      -> SEGY
      -> XLS
      -> ODS
      -> XLSX
      -> ElasticSearch
      -> Walk
      -> Carto
      -> AmigoCloud
      -> SXF
      -> Selafin
      -> JML
      -> PLSCENES
      -> CSW
      -> VDV
      -> GMLAS
      -> MVT
      -> TIGER
      -> AVCBin
      -> AVCE00
      -> NGW
      -> HTTP

I'm guessing the actual technical solution ( if desired ) is somewhere in the CDN configuration, but I wanted to raise the question before just scripting around it lol

1. Is this a use-case the porject is comfortable supporting?
2. And if so, is anybody more gifted with [GDAL virtual file systems](https://gdal.org/user/virtual_file_systems.html) to know what might be amiss here?

Thank you.

**Comment by ingalls** [comment]
@bahoo Yes, the data is currently behind a CDN that does not support HTTP range requests. As such you would need to modify the behavior of the GDAL curl call to perform a full download, instead of a range download.

Unfortunately we had full unrestricted access, but were paying thousands of dollars of AWS egress costs.

If you are performing mass downloads against OA we would love it if you could hit our S3 bucket directly (Requester Pays): 

A source such as
```
https://data.openaddresses.io/runs/802766/ca/bc/nanaimo.zip
```

can be obtained from:
```
s3://data.openaddresses.io/runs/802766/ca/bc/nanaimo.zip
```

**Comment by ingalls** [comment]
Going to close this as it is not currently actionable. Obtaining data directly from s3 is the workaround.
