### ISSUE TITLE
ingham.csv

### ISSUE THREAD

**Issue by eruci** [openaddresses/openaddresses#4918]
All addresses here are in Naperville, IL; but it is filed under us/mi/ingham

**Comment by ingalls** [comment]
Thanks a ton for bringing this to our attention! @justinelliotmeyers do you mind taking a look?

**Comment by justinelliotmeyers** [comment]
Will review 1st thing in the morning!

**Comment by justinelliotmeyers** [comment]
Part 1:
Ingham County, MI - I emailed: rfrancis@ingham.org
http://ingham-equalization.rsgis.msu.edu/Viewer

WMS:
http://35.9.246.204/mapserver?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=parcels%2Cdimensions&MAP=C%3A%2FMapServer%2Fapps%2Fingham%2Fparcel_data_layers_2019.map&EPSG=4326&cross-origin=anonymous&SRS=EPSG%3A3857&STYLES=&WIDTH=1201&HEIGHT=628&BBOX=-9517480.139900437%2C5175398.311132714%2C-9150276.656018449%2C5367408.126185076

**Comment by eruci** [comment]
I suppose you can just file it under 'IL' instead. The addresses seem correct otherwise:
LON,LAT,NUMBER,STREET,UNIT,CITY,DISTRICT,REGION,POSTCODE,ID,HASH
-88.1184657,41.8024864,4S631,Naperville Rd,,Unincorporated Area,,,,SID-1,9aed439cc87fa43b
-88.1194811,41.8030196,1804,N Naper Blvd,,Naperville,,,,SID-2,f354edba0b7f3c9b
eg: https://geocoder.ca/41.8030196,-88.1194811

**Comment by justinelliotmeyers** [comment]
@eruci https://github.com/openaddresses/openaddresses/issues/1985 will realign the proper source. I need to research if we have current data in Illinois for the county/ city. Otherwise, let me know your thoughts. Thanks!!

**Comment by justinelliotmeyers** [comment]
This is honestly a goofy issue! Source: https://data.openaddresses.io/runs/818432/output.txt
Pulls from http://hdgis.ingham.org/arcgis/rest/services/GeneralPurpose/MapServer/2 > http://hdgis.ingham.org/ichd/map.aspx

But data is actually for Naperville. Which splits DuPage and Will County. 

This current broken resource has 49,672points.
The current https://data.openaddresses.io/runs/818370/output.txt has 52,102

I think we just fix this and remove the current source. See https://github.com/openaddresses/openaddresses/issues/1985

Does this work @eruci and @ingalls ?

**Comment by eruci** [comment]
> This is honestly a goofy issue! Source: https://data.openaddresses.io/runs/818432/output.txt
> Pulls from http://hdgis.ingham.org/arcgis/rest/services/GeneralPurpose/MapServer/2 > http://hdgis.ingham.org/ichd/map.aspx
> 
> But data is actually for Naperville. Which splits DuPage and Will County.
> 
> This current broken resource has 49,672points.
> The current actual Naperville data here https://data.openaddresses.io/runs/818370/output.txt has 52,102
> 
> I think we just fix this and remove the current source. See #1985
> 
> Does this work @eruci and @ingalls ?

Sounds Good!
