### ISSUE TITLE
Fix Larimer County, CO

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4928]
Broken:
http://results.openaddresses.io/sources/us/co/larimer

not sure why current pull is failing. went to service and it works manually:
https://maps1.larimer.org/arcgis/rest/services/MapServices/Parcels/MapServer/0

New:
ftp://ftp.larimer.org/GISData/GIS_CadastralSHP.zip

**Comment by ingalls** [comment]
Fixed.
