### ISSUE TITLE
Fix Humboldt County, CA

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4953]
Broken:
http://results.openaddresses.io/sources/us/ca/humboldt
New:
https://webgis.co.humboldt.ca.us/arcgis/rest/services/Parcels/MapServer

![arcata](https://user-images.githubusercontent.com/5324316/79570330-3ec10980-8087-11ea-97df-67c50fc50598.png)

**Comment by nvkelso** [comment]
My home county!

**Comment by ingalls** [comment]
![Screenshot from 2020-04-18 18-25-44](https://user-images.githubusercontent.com/1297009/79677082-06fab480-81a2-11ea-9641-fdb182922fbc.png)

**Comment by justinelliotmeyers** [comment]
[humboldt_county_parcels_shapefile.zip](https://github.com/openaddresses/openaddresses/files/4498920/humboldt_county_parcels_shapefile.zip)

They disable the services for all, the link for them is https://webgis.co.humboldt.ca.us/arcgis/rest/services/Parcels/MapServer/0

Attached shapefile if machine will not work. Let me know if you need anything else from me. Thanks!
