### ISSUE TITLE
Fix Broken Canada Resource

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4956]
Broken, lets delete this as it is a small insersection inside the resource we already have:
http://results.openaddresses.io/sources/ca/on/adelaide

![image](https://user-images.githubusercontent.com/5324316/88219711-f853eb80-cc2f-11ea-81f4-d3f7c24214ec.png)

current larger source overlapping this area that 100% accounts for all of these:
http://results.openaddresses.io/sources/ca/on/middlesex_centre

**Comment by justinelliotmeyers** [comment]
@iandees can we delete http://results.openaddresses.io/sources/ca/on/adelaide as a source?  I dont like to delete duplicate sources, but this is a super small area and the source is down and the larger Middlesex County/ Centre accounts fr tis area 100%.

I'm fine either way. Thanks!!

**Comment by iandees** [comment]
Done!

**Comment by justinelliotmeyers** [comment]
Thank You!!
