### ISSUE TITLE
Statewide Wyoming Update!

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4963]
Current Source:
http://results.openaddresses.io/sources/us/wy/statewide
@iandees do you recall where this came from? Not important, just curious. Thanks!

New:
https://services3.arcgis.com/r0iJ85SKZ4zAzz3P/ArcGIS/rest/services/Wyoming_Parcels_for_2019/FeatureServer/0

Source:
https://www.arcgis.com/apps/webappviewer/index.html?id=4bb9a66f7287402b8f650aa9f21d3fa5

**https://twitter.com/vonparcel sent to me ;)

**Comment by iandees** [comment]
See the note here: https://github.com/openaddresses/openaddresses/blob/master/sources/us/wy/statewide.json

**Comment by ingalls** [comment]
@iandees @justinelliotmeyers not sure what to do here, am I adding the MapServer that @justinelliotmeyers found, or should we recache and host per the note.

**Comment by arch0345** [comment]
Resolved in #5171
