### ISSUE TITLE
Fix Pierce County, WI

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#4973]
Broken:
http://results.openaddresses.io/sources/us/wi/pierce
http://www.co.pierce.wi.us/arcgis/rest/services/Pierce_Sheriff_EmergencyServices/MapServer/8
New:
https://data-piercecounty-wi.hub.arcgis.com/datasets/pierce-parcels

**Comment by ingalls** [comment]
@justinelliotmeyers Looks like that page points to 

```
https://www.co.pierce.wi.us/arcgis/rest/services/Pierce_Parcels/MapServer/0/
```

But it doesn't seem to load successfully for me, do you have any better luck?

**Comment by justinelliotmeyers** [comment]
@ingalls damn. I was hoping that wouldn't happen as the pull was somewhat similar to the current one. I will call them now.

**Comment by justinelliotmeyers** [comment]
Just spoke to Kevin on the phone. He wanted to know how often we are pulling the data so we dont kill their server. He wanted me to send a formal email about the project so he could review. I sent the request and he is reviewing. If he thinks its okay, he will send us a working service link.

I will update the issue as soon as I hear back.

Email - kevin.etherton@co.pierce.wi.us
Phone - 715-273-6746

**Comment by justinelliotmeyers** [comment]
@ingalls he sent this: https://www.co.pierce.wi.us/arcgis/rest/services/Pierce_Public_BaseData/MapServer/3

If we cant get a consistent pull, let me know and i will do a one and done shapefile grab for the time being. Thanks!!
