### ISSUE TITLE
Russia address information

### ISSUE THREAD

**Issue by antonevane** [openaddresses/openaddresses#5066]
Russan address database can be obtained from 
https://fias.nalog.ru/Updates

XML schemas for XML download: https://fias.nalog.ru/docs/Выгрузка%20из%20ФИАС%20в%20XML%20xsd%20схемы%20с%2009%20июня%202016%20года.zip

The latest version can be found using the following link:
https://fias.nalog.ru/WebServices/Public/GetLastDownloadFileInfo

Data update service description can be found:
https://fias.nalog.ru/docs/Описание%20службы%20получения%20обновлений.doc

**Comment by justinelliotmeyers** [comment]
@antonevane the data here:
The latest version can be found using the following link:
https://fias.nalog.ru/WebServices/Public/GetLastDownloadFileInfo

what format is that in? Thanks!

**Comment by antonevane** [comment]
> @antonevane the data here:
> The latest version can be found using the following link:
> https://fias.nalog.ru/WebServices/Public/GetLastDownloadFileInfo
> 
> what format is that in? and where can we find associated latitude/ longitude values?
> 
> Thanks!

The url return a JSON payload

```javascript
{
   "VersionId":617,
   "TextVersion":"БД ФИАС от 11.05.2020",
   "FiasCompleteDbfUrl":"https://fias-file.nalog.ru/ExportDownloads?file=7eb2b812-fb43-4ce6-8d7f-b34cc1f0af61",
   "FiasCompleteXmlUrl":"https://fias-file.nalog.ru/ExportDownloads?file=396da8c0-3e13-40a2-90a3-00925603b511",
   "FiasDeltaDbfUrl":"https://fias-file.nalog.ru/ExportDownloads?file=8e6f1c30-6ac8-4e3d-9b4e-234fbd0aa3e7",
   "FiasDeltaXmlUrl":"https://fias-file.nalog.ru/ExportDownloads?file=2dea6c9e-0eb2-49fe-86be-de0407efde0c",
   "Kladr4ArjUrl":"https://fias-file.nalog.ru/ExportDownloads?file=70500ee4-2c58-4df5-b195-d3a3f5edf2a0",
   "Kladr47ZUrl":"https://fias-file.nalog.ru/ExportDownloads?file=42b7b4f1-d329-431e-98d7-da316c5b15ca"
}
```

**FiasCompleteXmlUrl** - full database in XML format
**FiasDeltaXmlUrl** - delta in XML formar
**TextVersion** - has a date when the latest update has been made (11.05.2020),

I did attach the XSD schemas. (Unfortunately comments only in Russian)
[fias_xsd.zip](https://github.com/openaddresses/openaddresses/files/4624554/fias_xsd.zip)

**Comment by justinelliotmeyers** [comment]
@antonevane thanks for the quick response! what one of those files has the latitude/ longitude? That is one of the more important files needed for the project.  Cheers! Justin

**Comment by antonevane** [comment]
@justinelliotmeyers Unfortunately there is no information.
Usually, it can be obtained via openstreetmap.org
There is OpenStreet map dumps: http://osm.sbin.ru/osm_dump/
Polygon data collection - https://github.com/shurshur/osmdump_poly created via https://gis-lab.info/projects/osm_dump/ + some BY and UA has been added

I did find translate article about it - https://geeks-world.github.io/articles/467787/index.html

**Comment by justinelliotmeyers** [comment]
@antonevane This would be an amazing resource, but we need coordinates. We identified this in a previous issue: https://github.com/openaddresses/openaddresses/issues/127

If you know of any other ideas or ways to implement coordinates from the FIAS without OSM, that would be ideal. Thanks!

**Comment by justinelliotmeyers** [comment]
@antonevane until we can join a table from FIAS, KLADR, or any other official Russia agency with coordinates, we cannot use. Please submit an issue in the future if you find any more data like this. It would be an amazing dataset, but without the latitude/ longitude, it is just a list. Thank you!!
