### ISSUE TITLE
Can Single Address Field Be Used As a Data Source?

### ISSUE THREAD

**Issue by pmacMaps** [openaddresses/openaddresses#5069]
I've come across a few tax-parcel Esri REST services where the address (i.e., 123 Main Street) is in a single field.

Can this data schema be used?  Or does the street number component need to be in a separate field?

**Comment by iandees** [comment]
It's possible to parse a single-string address with one of the attribute functions ([documented here](https://github.com/openaddresses/openaddresses/blob/master/ATTRIBUTE_FUNCTIONS.md)), but it's pretty brittle and annoying to debug. We definitely prefer separated address fields.

**Comment by iandees** [comment]
I'm going to close this, but feel free to ask more questions here if you have them.
