### ISSUE TITLE
Saudi Arabia Addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#5071]
![sa_full_05072020_zoom_low_res](https://user-images.githubusercontent.com/5324316/82261025-4ac11500-992c-11ea-9f15-5123391bd2a4.png)

https://drive.google.com/file/d/1MZnspxgaYjEO3snR3OGnRjJRYFZoc7T-/view?usp=sharing

**Comment by ingalls** [comment]
```
 https://data.openaddresses.io/cache/uploads/ingalls/10e26c/ksa_FeatureToPoint_RESTACKED.zip 
```

**Comment by ingalls** [comment]
@justinelliotmeyers Can you link  to or post a quick writeup of where this data came from so we can potentially recache it in the future

**Comment by iandees** [comment]
@justinelliotmeyers do you remember where you downloaded this from?

**Comment by justinelliotmeyers** [comment]
Yes. Who is asking? 

Let me look into something before you ask what I know you are about to ask.

**Comment by iandees** [comment]
I'm just starting to do research on license/sourcing for some of the bigger/countrywide datasets. No particular concerns at this time.

**Comment by justinelliotmeyers** [comment]
![image](https://github.com/openaddresses/openaddresses/assets/5324316/d3f12503-bf95-42c1-b9a9-bb44160fd669)

**Comment by justinelliotmeyers** [comment]
I'll try to find something for the actual data itself, but think that is the overall vibe for most of SA. There are a few open data sites with geospatial data that have friendlier licenses, but for the most part, gis data there is heavily guarded.
