### ISSUE TITLE
Alamance County, NC, issue with format conversion.

### ISSUE THREAD

**Issue by BjornRasmussen** [openaddresses/openaddresses#5110]
I'm new here, but I'm pretty sure I've found an issue with a data source.  I think the openaddresses.io conversion of the Alamance County NC address dataset is using the wrong "city" field.  There are two fields in the source dataset representing the city.  `CITYLIMITS` is what I believe openaddresses is currently using, but this field represents which city limits the address is physically within, not the postal city.  `COMMUNITY` should be used instead.

**Comment by iandees** [comment]
Thanks, I merged in your suggested change.
