### ISSUE TITLE
us/ca/san_bernadino download failing 

### ISSUE THREAD

**Issue by bookest** [openaddresses/openaddresses#5115]
The download for us/ca/san_bernadino has been failing since 2020/06/22 due to an FTP error:

```
2020-07-10 21:43:31,274     INFO: Getting ftp://gisftp:1sbcftp1@gis1.sbcounty.gov/gims/parcel_basemap_data/countywide_parcels_03_04_2020.zip via FTP
2020-07-10 21:43:31,703  WARNING: Got an error from gis1.sbcounty.gov: 530 User cannot log in.
2020-07-10 21:43:31,704  WARNING: Could not download source data
2020-07-10 21:43:31,704  WARNING: Error in process_one.process()
```

It looks like the password may have changed. I looked into their [docs](http://cms.sbcounty.gov/gis/FTPServices.aspx) and it seems like they issue a password on request. I'm happy to reach out to them about getting this resolved, but wanted to check in here first to make sure I follow any existing processes for ensuring this data is still allowed for use by OpenAddresses.

**Comment by ingalls** [comment]
@bookest If you're willing to take on requesting a new password that would be a fantastic help! Give us a shout here when you have it and we'll happily create a fix (or merge a PR) to get this working again.

**Comment by bookest** [comment]
Cool, I reached out to them and will submit a PR if a password change is necessary.

**Comment by bookest** [comment]
Looks like the 2020-08-03 build of us/ca/san_bernadino was successful: 

![Screen Shot 2020-08-03 at 9 25 18 PM](https://user-images.githubusercontent.com/14640/89242568-dfecb500-d5cf-11ea-9804-28908001d5c5.png)

Thanks for the the help getting the PR in @iandees.
