### ISSUE TITLE
Ville de Rouyn-Noranda, Quebec, Canada

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#5120]
https://cartes.rouyn-noranda.ca/server/rest/services/Donnees_ouvertes/Adresses_ponctuelles/MapServer/0

**Comment by ingalls** [comment]
Accidentally pushed this one directly to master

![](https://media.tenor.com/images/86aba1cff76f7064be857ed4aa13cc3d/raw)
