### ISSUE TITLE
Lithuania

### ISSUE THREAD

**Issue by truewayapi** [openaddresses/openaddresses#5226]
In \sources\lt\countrywide.json:
bad url:
http://lakis.lakd.lt/ArcGIS/rest/services/LAKD_lokatorius/MapServer/0
new url:
http://www.visimarsrutai.lt/arcgis/rest/services/LAKD_lokatorius/MapServer/0
or
https://eismoinfo.lt/arcgis/rest/services/LAKD_lokatorius/MapServer/0
~700k address, but they are very old 2012.

The newest addresses are presented here:
http://www.visimarsrutai.lt/services-ext/api/gazetteer/search
addressFound:1012423
another APIs: http://www.visimarsrutai.lt/services-ext/api?_wadl
or Lithuania Address Register:
https://www.registrucentras.lt/adr/index_en.php
on map: 
https://www.regia.lt/map/vilniaus_m?x=583001&y=6059623&identify=true&aobkodas=175-327-181&lang=3
https://www.regia.lt/map/resources/AdresuServisas/search_new/query=?query=a&sav_adm_id=461&searchAll=true&start=0&count=Infinity

**Comment by truewayapi** [comment]
Adreso Numeris:
https://www.registrucentras.lt/gwa/rest/services/GR/LinLab/MapServer/2

**Comment by justinelliotmeyers** [comment]
If you can find something where their license is open, that would be great!

**Comment by justinelliotmeyers** [comment]
Closing this and tracking with new issue with verified okay copyright: https://github.com/openaddresses/openaddresses/issues/5728
