### ISSUE TITLE
Vancouver Canada

### ISSUE THREAD

**Issue by jordola** [openaddresses/openaddresses#5237]
Hi, thanks for the project. In the last few days Vancouver Canada has changed to have the lat and long appear in the wrong order for geojson.

Used to be:
{"type":"Feature","properties":{"id":"","unit":"","number":"2150","street":"E 13TH AV","city":"","district":"","region":"","postcode":"","hash":"ee9420d31a30ea50"},"geometry":{"type":"Point","coordinates":[-123.0609521,49.2583243]}}

Now:
{"type":"Feature","properties":{"id":"","unit":"","number":"3355","street":"DEERING ISLAND PLACE","city":"","district":"","region":"","postcode":"","hash":"98ba2d2d3078766e"},"geometry":{"type":"Point","coordinates":[49.2173688,-123.181671]}}

I would be happy to understand how the system works and fix it myself if you could point me in the right direction. We work on address data a lot so would be happy to contribute when it overlaps with OpenAddresses.

Thanks.

**Comment by ingalls** [comment]
Hey @jordola, thanks a ton for reporting this. Just got to the bottom of this myself while investigating another canadian shapefile source.

I've opened a ticket here: https://github.com/openaddresses/batch/issues/51 about the issue and will try to get it resolved in the next day or two.

**Comment by ingalls** [comment]
Fixed
