### ISSUE TITLE
Fix West Kelowna, BC, Canada

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#5243]
Broken:
https://batch.openaddresses.io/job/7958/log

New Source:
https://www.westkelownacity.ca/en/building-business-and-development/maps-and-gis1.aspx - main page
https://gis.westkelownacity.ca/GISFiles/wk_cvcpoints.zip - download

License:
https://gis.westkelownacity.ca/GISFiles/disclaimer.pdf

Terms of Use
The following geographic data available from this web page is provided as a public service by the City of
West Kelowna on the following terms.
In consideration for the City of West Kelowna (the City) granting access to this geographic data, the
person (the 'User') agrees to and accepts these Terms of Use.
The geographical data is supplied on an as is, where is basis. The City assumes no obligation or liability
for the use of this data by any person and makes no representations or promises regarding the
completeness or accuracy of the data or its fitness for a particular purpose. This data represents a onetime capture of information as it exists at the time the information is posted to this website and the City
makes no representation as to the accuracy of such information and does not necessarily include the
ongoing updates or corrections to the source databases maintained by the City or other agencies.

The User agrees to indemnify and hold harmless the City and its officials, employees and agents from
and against all losses, claims, demands, actions, payments, expenses, costs, suits, and damages
(including any damages that are direct, indirect, incidental, special or consequential), whether or not
caused by any form of negligence of the City, or its officials, employees or agents, which are incurred by
the City and would not or could not have been incurred but for the User's use of the geographical data
or the User's breach of these Terms of Use.

Where a conflict between the information on this web site and information contained in any other
records of the City or documents that may be prepared by or delivered to the City, the City reserves the
right to rely in all cases upon the record which it considers to be the most accurate and complete.

These Terms of Use are governed by the laws of British Columbia, Canada. If any part of these Terms of
Use is found to be unenforceable, then that part will be severed so that the remainder of these Terms of
Use can continue to be enforceable.

**Comment by ingalls** [comment]
Updated!
