### ISSUE TITLE
Commerce City CO Street Name value

### ISSUE THREAD

**Issue by Jnb2387** [openaddresses/openaddresses#5264]
Commerce City looks to have changed the schema of their data and now list Street Name as having all DEPRECATED as a value and then the actual street name is in Complete Street Name. Not sure on the methodology behind their change but is there a way to pull that Complete Street Name column instead of Street Name. The URL was updated in #4612

**Comment by iandees** [comment]
Thanks for letting us know. I've updated the data source.
