### ISSUE TITLE
Street number fix - Gladitei 4, Bucharest

### ISSUE THREAD

**Issue by mihneadb** [openaddresses/openaddresses#5272]
Hi,

The point with id a4432680439453d8 for street "Gladitei 4" in Bucharest, Romania should actually be "str Gladitei 42". https://www.openstreetmap.org/node/7133184708

Thanks!

**Comment by iandees** [comment]
Thanks for letting us know. Unfortunately, we're not currently in a position to fix data on a one-off basis like this yet. You can reach out to the data source to let them know they might have an error in their data and we'll pull down any fix they deploy, but we don't have a system for applying changes on our end.

**Comment by mihneadb** [comment]
Gotcha, thanks for the answer. Closing it then. 👍
