### ISSUE TITLE
Are CSV files available for download?

### ISSUE THREAD

**Issue by gizmoGremlin** [openaddresses/openaddresses#5436]
Hi, Like the title says, the geojson files downloaded from the openaddress website are very difficult to load into a postgres database. Mabye im missing something?

Right now, I'm going through each file row by row and inserting the contents into a database. 
Also, I've tried various scripts for converting geojson to csv but they have failed because the geojson files are a collection of seperate geojson objects and the scripts tried seem designed to deal with feature collections. I may have to write my own but I'm quite short on time.

Any help greatly appreciated.

**Comment by ingalls** [comment]
@gizmoGremlin, yes, the new system is currently GeoJSON only as we are working to expand the project to include building polygons & parcels in addition to the current address data.

The easiest way to get back to a CSV would likely be with `jq`. It supports running on line-delimited GeoJSON

The following is an example:
```sh
jq -r '[.geometry.coordinates[0], .geometry.coordinates[1], .properties.number, .properties.city] | @csv' ca_nb_city_of_fredericton-addresses-city.geojson
```

**Comment by gizmoGremlin** [comment]
Thanks
