### ISSUE TITLE
Data Issue

### ISSUE THREAD

**Issue by kmcrawford** [openaddresses/openaddresses#5445]
When I search for 2481 S JENKINS RD on your site the data looks correct(bottom).  However in the `us/fl/statewide-addresses-state.geojson` I see the following:

Notice the city is `Saint Lucie County` when the city is Fort Pierce.  This is true from many entries.

```{"type":"Feature","properties":{"id":"2324-141-0006-000-7","unit":"","number":"2481","street":"S JENKINS RD","city":"Saint Lucie County","district":"ST_LUCIE","region":"FL","postcode":"34950","hash":"7702e2037bbd9458"},"geometry":{"type":"Point","coordinates":[-80.383311,27.4203826]}}```

Additionally from the `us/fl/st-lucie-addresses-county.geojson` I see the following where city is missing.

{"type":"Feature","properties":{"id":"","unit":"","number":"2481","street":"S JENKINS RD","city":"","district":"","region":"","postcode":"34947","hash":"87d1e718d87fde8b"},"geometry":{"type":"Point","coordinates":[-80.3831434,27.4203123]}}

Here I can see the city is Fort Pierce:
![image](https://user-images.githubusercontent.com/40531/96845004-35da3780-141e-11eb-9cba-a50850edc77a.png)

**Comment by iandees** [comment]
The search box on the map uses Mapbox's geocoder and is not purely an OpenAddresses search. Mapbox brings in other non OpenAddresses data and performs cleanups on OpenAddresses data.

**Comment by iandees** [comment]
To help reduce confusion, I removed address results from the geocoder box on the map.

**Comment by kmcrawford** [comment]
@iandees what about the invalid data?

**Comment by iandees** [comment]
Not all sources have all the data. It looks like the source doesn't have city information available.

**Comment by kmcrawford** [comment]
And some sources have wrong data apparently too.

**Comment by iandees** [comment]
Yes, some data sources have errors.

If you have a specific examples, please file separate issues so that we can confirm that we're pulling in the right columns for that source.

**Comment by kmcrawford** [comment]
@iandees please refer to this original issue and reopen.
