### ISSUE TITLE
Florida statewide data has incorrect data

### ISSUE THREAD

**Issue by kmcrawford** [openaddresses/openaddresses#5447]
In the us/fl/statewide-addresses-state.geojson I see the following:

Notice the city is Saint Lucie County when the city is Fort Pierce. This is true from many entries.

```json
{"type":"Feature","properties":{"id":"2324-141-0006-000-7","unit":"","number":"2481","street":"S JENKINS RD","city":"Saint Lucie County","district":"ST_LUCIE","region":"FL","postcode":"34950","hash":"7702e2037bbd9458"},"geometry":{"type":"Point","coordinates":[-80.383311,27.4203826]}}
```

Additionally from the us/fl/st-lucie-addresses-county.geojson I see the following where city & state is missing.

```json
{"type":"Feature","properties":{"id":"","unit":"","number":"2481","street":"S JENKINS RD","city":"","district":"","region":"","postcode":"34947","hash":"87d1e718d87fde8b"},"geometry":{"type":"Point","coordinates":[-80.3831434,27.4203123]}}
```

**Comment by iandees** [comment]
As I mentioned in the other ticket (#5445), we aggregate data from other sources. It looks like both of these cases are present in the source data. At this point, we don't make changes to the source data that we fetch.

If you pull data from these sources and see that the data is correct, please let me know.

**Comment by kmcrawford** [comment]
Where can I find the source data for this?  Since you have the lat/long this data could be enriched if data elements are missing.  I am looking to use this data as part of an expensive autocomplete replacement for all US addresses. Having accurate complete data will not only help me but this project too.

**Comment by iandees** [comment]
All of our sources are here: https://github.com/openaddresses/openaddresses/tree/master/sources

The first example you gave is this source file: https://github.com/openaddresses/openaddresses/blob/master/sources/us/fl/statewide.json and the second example is https://github.com/openaddresses/openaddresses/blob/master/sources/us/fl/st-lucie.json.

Look at the "data" attributes in there to see what we download.
