### ISSUE TITLE
lat,lon are flipped in ch_countrywide-addresses-country.geojson

### ISSUE THREAD

**Issue by eruci** [openaddresses/openaddresses#5465]
ch_countrywide-addresses-country.geojson:{"type":"Feature","properties":{"id":"191264570-2","unit":"","number":"1b","street":"Via degli Albrici","city":"","district":"","region":"TI","postcode":"","hash":"096636af5894e71c"},"geometry":{"type":"Point","coordinates":[45.8337298,9.0340612]}}

..
whereas all other CH files are ok:
{"type":"Feature","properties":{"id":"","unit":"","number":"1500","street":"Fortunagasse","city":"","district":"","region":"","postcode":"8001.0","hash":"cce5d936fd3c8610"},"geometry":{"typ
e":"Point","coordinates":[8.5408935,47.3744784]}}

**Comment by iandees** [comment]
Is this just one line or the whole file?

**Comment by eruci** [comment]
the whole file.

**Comment by iandees** [comment]
It looks like this might be a bug specific to batch. Can you try the latest run from the older downloader? https://results.openaddresses.io/sources/ch/countrywide

**Comment by eruci** [comment]
The CSV file is correct. It is the geojson where the lat,lon is flipped.

**Comment by ingalls** [comment]
CH Countrywide now has proper coordinate order.
