### ISSUE TITLE
Slovenia countrywide data is also double encoded.

### ISSUE THREAD

**Issue by eruci** [openaddresses/openaddresses#5469]
more si_countrywide-addresses-country.geojson

{"type":"Feature","properties":{"id":"11028489","unit":"","number":"1","street":"Cankarjev trg","city":"AjdovĹˇÄŤina","district":"AjdovĹˇÄŤina","region":"GoriĹˇka","postcode":"5270","hash"
:"ec89c411e71c7917"},"geometry":{"type":"Point","coordinates":[13.9095556,45.8873882]}}
{"type":"Feature","properties":{"id":"11028497","unit":"","number":"2","street":"Cankarjev trg","city":"AjdovĹˇÄŤina","district":"AjdovĹˇÄŤina","region":"GoriĹˇka","postcode":"5270","hash"
:"74080beb3dcb970b"},"geometry":{"type":"Point","coordinates":[13.909424,45.8875309]}}
{"type":"Feature","properties":{"id":"19574024","unit":"","number":"2A","street":"Cankarjev trg","city":"AjdovĹˇÄŤina","district":"AjdovĹˇÄŤina","region":"GoriĹˇka","postcode":"5270","hash
":"93081ca22ba44734"},"geometry":{"type":"Point","coordinates":[13.9094771,45.8874504]}}
{"type":"Feature","properties":{"id":"11028519","unit":"","number":"3","street":"Cankarjev trg","city":"AjdovĹˇÄŤina","district":"AjdovĹˇÄŤina","region":"GoriĹˇka","postcode":"5270","hash"
:"9da045a6457f5ef3"},"geometry":{"type":"Point","coordinates":[13.9095006,45.8875676]}}
{"type":"Feature","properties":{"id":"11028543","unit":"","number":"4","street":"Cankarjev trg","city":"AjdovĹˇÄŤina","district":"AjdovĹˇÄŤina","region":"GoriĹˇka","postcode":"5270","hash"
:"2468c7064c7abac9"},"geometry":{"type":"Point","coordinates":[13.909577,45.8876134]}}
{"type":"Feature","properties":{"id":"11028527","unit":"","number":"4A","street":"Cankarjev trg","city":"AjdovĹˇÄŤina","district":"AjdovĹˇÄŤina","region":"GoriĹˇka","postcode":"5270","hash
":"61d014428391c510"},"geometry":{"type":"Point","coordinates":[13.9096015,45.8876766]}}
{"type":"Feature","properties":{"id":"11028535","unit":"","number":"4B","street":"Cankarjev trg","city":"AjdovĹˇÄŤina","district":"AjdovĹˇÄŤina","region":"GoriĹˇka","postcode":"5270","hash
":"5939e5f6e417f925"},"geometry":{"type":"Point","coordinates":[13.9096393,45.8877219]}}
{"type":"Feature","properties":{"id":"11028551","unit":"","number":"5","street":"Cankarjev trg","city":"AjdovĹˇÄŤina","district":"AjdovĹˇÄŤina","region":"GoriĹˇka","postcode":"5270","hash"
:"86692405557164c6"},"geometry":{"type":"Point","coordinates":[13.9095089,45.8878017]}}
{"type":"Feature","properties":{"id":"11028560","unit":"","number":"6","street":"Cankarjev trg","city":"AjdovĹˇÄŤina","district":"AjdovĹˇÄŤina","region":"GoriĹˇka","postcode":"5270","hash"
:"b66604e93a743372"},"geometry":{"type":"Point","coordinates":[13.909429,45.8879359]}}
{"type":"Feature","properties":{"id":"11028586","unit":"","number":"7","street":"Cankarjev trg","city":"AjdovĹˇÄŤina","district":"AjdovĹˇÄŤina","region":"GoriĹˇka","postcode":"5270","hash"
:"d0a4a96a937361bd"},"geometry":{"type":"Point","coordinates":[13.9093886,45.8880255]}}

**Comment by stefanb** [comment]
This is fixed for Slovenia in https://github.com/openaddresses/openaddresses/pull/5776
