### ISSUE TITLE
us-nc-warren

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#548]
warren county
http://www.warrencountync.com/gis.aspx
http://maps2.roktech.net/warren/

**Comment by nvkelso** [comment]
Well, we added it anyhow in https://github.com/openaddresses/openaddresses/pull/2816.

**Comment by trescube** [comment]
Apparently statewide NC hasn't worked in years:  https://results.openaddresses.io/sources/us/nc/statewide

I'll see if I can find it again.

**Comment by nvkelso** [comment]
Thank you!

**Comment by trescube** [comment]
Found it here:  https://services.nconemap.gov/secure/rest/services/NC1Map_Location/MapServer/0

I can't tell for certain but it doesn't look like it's been updated since 2014.  I'm going to keep pushing forward on individual counties in the hope that their data is updated more often.
