### ISSUE TITLE
JSON Data in Wisconsin Appears to Have Improper Key-Value Pairs

### ISSUE THREAD

**Issue by kwesiRutledge** [openaddresses/openaddresses#5595]
I've found that in Kenosha, Wisconsin, there are many entries in the JSON file which appear to have a misplaced hash value. For example,
`{"type":"Feature","properties":{"id":"53105","unit":"288TH AVE","number":"1cc1833df0e5956a","street":"706","city":"","district":"Brighton","region":"","postcode":"","hash":""},"geometry":{"type":"Point","coordinates":[-88.1595359,42.6548342]}}
`
And in other entries, the value of the _unit_ entry also appears to actually refer to the street name?

`{"type":"Feature","properties":{"id":"53105","unit":"BURLINGTON RD","number":"c527999a2df6ce13","street":"30911","city":"","district":"Brighton","region":"","postcode":"","hash":""},"geometry":{"type":"Point","coordinates":[-88.1846599,42.6424626]}}
`

It may be necessary to parse the original data source again, to create a more consistent JSON file but I am not sure how to do it. Can someone show me where the issue is coming from?

**Comment by ingalls** [comment]
Hey @kwesiRutledge Thanks for reporting, I'll look into this today

**Comment by ingalls** [comment]
Hey @kwesiRutledge I'm not seeing a problem with the current source. Can you try re-downloading again and see if you are still seeing this issue? If you are, feel free to open a new ticket.

Thanks again for reporting.
