### ISSUE TITLE
Data drop for few sources

### ISSUE THREAD

**Issue by amishas157** [openaddresses/openaddresses#5597]
Hi :wave: I am noticing that few sources experienced a data drop

  index | source | state | old count | new count | diff
-- | -- | -- | -- | -- | --
1 | us/fl/collier | US-FL | 229776 | 609 | 229167
2 | us/nc/davidson | US-NC | 73354 | 511 | 72843
3 | us/ms/rankin | US-MS | 69937 | 54808 | 15129
4 | us/sc/jasper | US-SC | 11476 | 354 | 11122
5 | us/ks/statewide | US-KS | 1471232 | 1467957 | 3275
6 | us/oh/seneca | US-OH | 28540 | 25760 | 2780
7 | us/mn/ramsey | US-MN | 220019 | 219274 | 745
8 | us/il/kendall | US-IL | 51512 | 50840 | 672
9 | us/la/livingston | US-LA | 60243 | 59861 | 382
10 | us/sc/darlington | US-SC | 35461 | 35117 | 344
11 | us/ga/glynn | US-GA | 63057 | 62941 | 116

**Example: us/fl/collier**

![image](https://user-images.githubusercontent.com/4952872/112658853-32623680-8e2a-11eb-96ad-43c6de96bb50.png)
![image](https://user-images.githubusercontent.com/4952872/112658880-3a21db00-8e2a-11eb-8206-6e3284e47e8d.png)

**Questions:**
- Is there a way for downstream consumers to understand if the data drop is expected or has some issues?
- Is data drop an often situation which happens or should be more scrutinized?

Thank you for any answers :bowing_woman:

**Comment by iandees** [comment]
If the feature count drops significantly as in your example, it's likely a problem that needs to be addressed. Thanks for bringing it to our attention.

In most cases, this happens because the provider has changed URLs and we need to update our information to point to a new URL.

**Comment by amishas157** [comment]
Thank you for the response @iandees . Will keep the ticket open in case there is any triage works needs to be done on your end. Otherwise, ticket is good to close as my questions are resolved.

**Comment by ingalls** [comment]
@amishas157 I'd highly recommend starting to switch your processing pipeline to use the new infrastructure at https://batch.openaddresses.io/data. We implemented basic protection for this exact scenario. When a source drops a significant amount of address points it is flagged and quarantined for human review. A human than has to verify the changes are accepted before it is pushed out to the main data API.

In the near future we will being adding deprecation notices to the old results.oa.io processing page.

**Comment by amishas157** [comment]
@ingalls :wave: We have switched to using https://batch.openaddresses.io/data. While we were working with OA, we found that there were few sources which had corrupt data i.e. no street/number even the count was good. In such situations, we pinned data to last known valid job and accessing data from `s3://data.openaddresses.io/runs/{}/{}.zip".format(last_valid_job_id, source_name)`

<details>
<summary>
source: pinned job id
</summary>

```
run_ids = {
    "us/de/new_castle": "618277",  # 255,228	2019-04-20	8ff09a8 (0:01:20)
    "us/ga/paulding": "656746",  # 70,510	2019-07-23	1483138 (0:00:18)
    "us/or/city_of_salem": "665517",  # 58,386	2019-08-12	d2f0e2e (0:00:16)
    "us/ga/city_of_savannah": "219816",  # 115,199	2017-07-07	33c0e5e (0:01:15)
    "us/ok/rogers": "591836",  # 48,020	2019-03-11	ddf67e6 (0:00:30)
    "us/ky/kenton": "507086",  # 84,672	2018-10-22	28b79a2 (0:00:41)
    "us/ca/sutter": "",  # never had a valid set
    "us/al/etowah": "768080",  # 76,991	2020-02-10	32daa24 (0:00:16)
    "us/il/city_of_east_peoria": "",  # Cannot access - Error reading from remote server
    "us/nc/richmond": "",  # never had a valid set
    "us/tx/hood": "829245",  # 31,014	2020-05-04	df37d8e (0:00:02)
    "us/nv/nye": "327843",  # 60,178	2017-12-11	8c72dc6 (0:00:36)
    "us/wi/douglas": "279693",  # 22,409	2017-10-16	9a00c2d (0:00:05)
    "us/ky/pendleton": "479214",  # 7,932	2018-09-03	6961003 (0:00:02)
    "us/id/blaine": "227649",  # 23,282	2017-07-24	5956932 (0:00:08)
    "us/al/blount": "318021",  # 42,796	2017-12-11	e9e171a (0:00:28)
    "us/al/city_of_auburn": "656709",  # 40,422	2019-07-23	11f7850 (0:00:11)
    "us/co/park": "337694",  # 16,527	2018-01-08	a2d2e84 (0:00:09)
    "us/nc/rutherford": "104875",  # 37,539	2016-08-15	zip (0:00:26)
    "us/ct/city_of_new_britain": "709056",  # 17,443	2019-11-18	1958164 (0:00:02)
    "us/vt/city_of_burlington": "649964",  # 8,695	2019-06-23	8547533 (0:00:02)
    "us/wa/pend_oreille": "592004",  # 16,695	2019-03-11	30d6716 (0:00:05)
    "us/mn/carlton": "779215",  # 16,431	2020-02-24	07312e9 (0:00:01)
    "us/ks/pottawatomie_county": "566592",  # 11,585	2019-01-15	dd63589 (0:00:06)
    "us/nc/caswell": "749009",  # 12,342	2020-01-13	7301172 (0:00:01)
    "us/nc/montgomery": "609120",  # 29,952	2019-04-09	de64d27 (0:00:09)
    "us/va/giles": "438754",  # 9,255	2018-06-25	3cec78d (0:00:05)
    "us/sd/bon_homme": "592190",  # 8,672	2019-03-11	fcbe60f (0:00:02)
    "us/nc/yancey": "253051",  # 16,944	2017-09-04	8cf160c (0:00:05)
    "us/va/amherst": "1044893",  # 16,220	2021-03-03	9a8b4f2 (0:00:01)
    "us/mo/perry": "406587",  # 14,115	2018-04-30	3519d47 (0:00:10)
    "us/il/clark": "27905",  # 14,016	2015-10-24	zip (0:00:09)
    "us/ok/wagoner": "748226",  # 46,531	2020-01-13	617c878 (0:00:05)
    "us/mo/iron": "601941",  # 11,384	2019-03-26	b8ab2c1 (0:00:03)
    "us/il/massac": "630600",  # 11,049	2019-05-21	d1c1e26 (0:00:04)
    "us/ms/city_of_diberville": "709455",  # 5,072	2019-11-18	153f967 (0:00:00)
    "us/nv/eureka": "709268",  # 4,542	2019-11-18	5193e14 (0:00:00)
    "us/va/appomattox": "347647",  # 8,411	2018-01-19	a0f4b3e (0:00:03)
    "us/nc/avery": "346913",  # 23,034	2018-01-19	4c8e0a8 (0:00:13)
    "us/va/amelia": "620046",  # 6,755	2019-04-21	68635c8 (0:00:02)
    "us/va/franklin": "686078",  # 31,613	2019-10-01	2464d52 (0:00:04)
    "us/nh/jaffrey": "640357",  # 2,540	2019-06-02	fca2443 (0:00:01)
    "us/wy/crook": "798317",  # 4,756	2020-03-23	3f5486b (0:00:00)
    "us/va/warrenton": "837389",  # 29,870	2020-05-18	f5822d1 (0:00:02)
    "us/co/logan": "364067",  # 12,043	2018-02-26	61dd59b (0:00:04)
    "us/ga/liberty": "665930",  # 18,919	2019-08-13	9ded3c7 (0:00:08)
    "us/nc/cleveland": "728480",  # 56,958	2019-12-16	57da59c (0:00:08)
    "us/nc/rockingham": "374865",  # 49,396	2018-03-12	95fd94f (0:00:16)
    "us/ne/omaha": "346025",  # 211,899	2018-01-19	06f7fce (0:01:57)
    "us/va/greene": "657776",  # 9,461	2019-07-23	2f7635e (0:00:02)
    "us/va/madison": "513084",  # 7,007	2018-10-29	a78099c (0:00:03)
    "us/va/city_of_rural_retreat": "347881",  # 1,059	2018-01-19	04f3299 (0:00:00)
    "us/va/halifax": "455133",  # 18,891	2018-07-23	185cc1a (0:00:10)
    "us/la/washington": "100052",  # 33,147	2016-07-23	zip (0:00:35)
    "us/ks/johnson_county": "25136"  # 215,060	2015-10-03	zip (0:16:31)
    # "us/ks/cheyenne_county": "12996", # 4,724	2015-08-23	zip (0:00:12) 
    # "us/nc/perquimans": "", # never had a valid set
}

```
</details>

Do you think using data from `s3://data.openaddresses.io/` is fine for few of the sources?

**Comment by ingalls** [comment]
@amishas157 Absolutely, you can use the old system in the meantime. Just know that we don't plan to do any significant work on that system, nor does it offer any protection for the problem you are reporting. 

@amishas157 Generally you can trust that any data that is added to the `/data` endpoint is intended, as drops would be flagged and reviewed by me. However the system isn't perfect and also the validation depends on the inital numbers. so if an address starts with 0 addresses and stays at 0 addresses it will never be flagged. I'll add this to the roadmap.

One option is to use the https://batch.openaddresses.io/docs/#api-Job-Single API and check the stats object? It will include a count of addresses/streets & then also a validity column which ensure the number looks number like etc.

**Comment by ingalls** [comment]
### Sources To Fix

- [ ] us/de/new_castle
- [ ] us/ga/paulding
- [ ] us/or/city_of_salem
- [ ] us/ga/city_of_savannah
- [ ] us/ok/rogers
- [ ] us/ky/kenton
- [ ] us/ca/sutter
- [ ] us/al/etowah
- [ ] us/il/city_of_east_peoria
- [ ] us/nc/richmond
- [ ] us/tx/hood
- [ ] us/nv/nye
- [ ] us/wi/douglas
- [ ] us/ky/pendleton
- [ ] us/id/blaine
- [ ] us/al/blount
- [ ] us/al/city_of_auburn
- [ ] us/co/park
- [ ] us/nc/rutherford
- [ ] us/ct/city_of_new_britain
- [ ] us/vt/city_of_burlington
- [ ] us/wa/pend_oreille
- [ ] us/mn/carlton
- [ ] us/ks/pottawatomie_county
- [ ] us/nc/caswell
- [ ] us/nc/montgomery
- [ ] us/va/giles
- [ ] us/sd/bon_homme
- [ ] us/nc/yancey
- [ ] us/va/amherst
- [ ] us/mo/perry
- [ ] us/il/clark
- [ ] us/ok/wagoner
- [ ] us/mo/iron
- [ ] us/il/massac
- [ ] us/ms/city_of_diberville
- [ ] us/nv/eureka
- [ ] us/va/appomattox
- [ ] us/nc/avery
- [ ] us/va/amelia
- [ ] us/va/franklin
- [ ] us/nh/jaffrey
- [ ] us/wy/crook
- [ ] us/va/warrenton
- [ ] us/co/logan
- [ ] us/ga/liberty
- [ ] us/nc/cleveland
- [ ] us/nc/rockingham
- [ ] us/ne/omaha
- [ ] us/va/greene
- [ ] us/va/madison
- [ ] us/va/city_of_rural_retreat
- [ ] us/va/halifax
- [ ] us/la/washington
- [ ] us/ks/johnson_county
- [ ] us/ks/cheyenne_county
- [ ] us/nc/perquimans

**Comment by amishas157** [comment]
> One option is to use the https://batch.openaddresses.io/docs/#api-Job-Single API and check the stats object? It will include a count of addresses/streets & then also a validity column which ensure the number looks number like etc.

Perfect. And when stats say invalid data, do we:
- fallback  on whatever data we had earlier?
- report the issue in this repo?

**Comment by ingalls** [comment]
@amishas157 Idealy once there is a good source in `/data` we don't regress. I can't 100% guarentee it, but yes, just don't update to the new source if you identify a bad source - and if you could open a ticket in this repo - or even better submit a PR if you have time that would be fantastic.

**Comment by amishas157** [comment]
>  even better submit a PR if you have time that would be fantastic.

Oh would love to learn the process if there is any quick doc/summary to share.

**Comment by ingalls** [comment]
Yeah, docs can be found here: https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md. Most of the time the actual PR on github is the easy part, finding and fixing the data can be tougher. If there is a time next week that you and/or other mapboxers would like to jump on a call with me to do a walk through and Q&A I'd be happy to make that happen.

**Comment by amishas157** [comment]
Yes, I will definitely like to learn more about OA source in general and also the contribution part. Going to check in with team next week if anyone else would like to join. and thank you for offering walk through session

**Comment by ingalls** [comment]
Awesome :) Shoot me an email at `nick@ingalls.ca` and we'll find a time that works.
