### ISSUE TITLE
Issue with us/fl/_loveland data

### ISSUE THREAD

**Issue by collinjc** [openaddresses/openaddresses#5694]
We're using openaddresses data in conjunction with Pelias and have noticed a few issues with the data coming back from the us/fl/_loveland dataset. First of all, it seems that this data is missing ZIP codes. More frustrating, however, is that there appears to be a great deal of bad data where the house number and street have the same value duplicated. For example:
{"type":"Feature","properties":{"hash":"22f4d81746a5a6f6","number":"325","street":"325","unit":"","city":"mayo","district":"lafayette","region":"fl","postcode":"","id":""},"geometry":{"type":"Point","coordinates":[-82.9529545,29.9342789]}}
From what I can tell, there is no 325 325 Mayo, FL.

**Comment by collinjc** [comment]
This may need to be a separate issue, but I'm unable to see the results of this change, seemingly due to a failure in processing the _loveland data. [https://results.openaddresses.io/sources/us/fl/_loveland](https://results.openaddresses.io/sources/us/fl/_loveland) is showing that the job has been failing since 2021-03-23 due to the source file being unavailable. This is presumably causing the "old" data to still be returned.

**Comment by arch0345** [comment]
Loveland source was removed in #6554

**Comment by arch0345** [comment]
Resolved in #6554
