### ISSUE TITLE
[new source] us/pa/indiana/parcels

### ISSUE THREAD

**Issue by rodonnell23** [openaddresses/openaddresses#5726]
[ftp://ftp.pasda.psu.edu/pub/pasda/indianacounty/](url)
[IndianaCountyParcels201912.zip](https://github.com/openaddresses/openaddresses/files/6312755/IndianaCountyParcels201912.zip)

**Comment by MiniCodeMonkey** [comment]
This source unfortunately seems to have the same issue as described here https://github.com/openaddresses/openaddresses/pull/5091#issuecomment-643302188

**Comment by bertday** [comment]
It looks like this was resolved by your PR #5922 @MiniCodeMonkey , but not auto-closed by the commit message — just FYI!

**Comment by iandees** [comment]
The keyword is "Close" or "Closes" and it has to be in the description 👍🏻 

I'll close this one.
