### ISSUE TITLE
Lithuania Addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#5728]
New Source with good copyright:
https://www.registrucentras.lt/p/1202

Closing old issue because previous iterations of grabbing had unknown or not good license:
https://github.com/openaddresses/openaddresses/issues/5226

**Comment by sergiyprotsiv** [comment]
Great find, @justinelliotmeyers! It looks like the JSON files only have address codes, but the key for addresses is at https://www.registrucentras.lt/p/1194 and for streets at https://www.registrucentras.lt/p/1192. 
I'll write a script one of these days to merge them together.

**Comment by sergiyprotsiv** [comment]
I went through the data and it looks good. There are about 1M addresses and the coverage is excellent.

I had some issues with SQLite performance, so had to do a few things manually, but overall this script contains enough info https://www.dropbox.com/s/i7f1z1q1npcndkm/lt_download.py.zip?dl=1.

Can't deal with Git/Github now, so if someone want to add a PR, please go ahead. The source description is like below, but you might want to upload it to the OA server:

`{
    "schema": 2,
    "coverage": {
        "country": "lt"
    },
    "layers": {
        "addresses": [{
            "data": "https://www.dropbox.com/s/kvdpd71xrz4te29/lt_countrywide.csv.zip?dl=1",
            "protocol": "http",
            "compression": "zip",
            "conform": {
                "number": "NR",
                "street": ["tipas", "vardas_k"],
                "unit": "korpuso_nr",
                "city": "vardas",
                "postcode": "pasto_koda",
                "lat": "n_koord",
                "lon": "e_koord",
                "format": "csv",
            }
        }]
    }
}`

**Comment by justinelliotmeyers** [comment]
@sergiyprotsiv do you by chance have any colleagues in Lithuania? Trying to figure out something with the residential areas data from the geojsons on the same site.  Thanks!
