### ISSUE TITLE
us-ny-orange

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#576]
Orange County  
https://ocgis.orangecountygov.com/requests/usr/viewDownloads.xsp?typeId=4

**Comment by geobrando** [comment]
Contains ~45 separate parcel shapefiles for cities/towns/villages in Orange County with account creation/login required for download (no addresses).

**Comment by nvkelso** [comment]
Related to another NYC suburbs issue: https://github.com/openaddresses/openaddresses/issues/1987

**Comment by davidchiles** [comment]
Found possible source here: http://ocgis.orangecountygov.com/ArcGIS/rest/services/Dynamic/LandBase/MapServer/0

**Comment by trescube** [comment]
Orange County, NY appears to be missing from the statewide file, so great catch!  I poked around in the data and care should be taken with parsing the fields, since the `StreetAddress` field is the house number, street, and optional unit info all jammed together.

**Comment by nvkelso** [comment]
Related: #2285

**Comment by nvkelso** [comment]
Closed by NY state update: https://github.com/openaddresses/openaddresses/pull/3204#event-1163036812.
