### ISSUE TITLE
_loveland job failing

### ISSUE THREAD

**Issue by collinjc** [openaddresses/openaddresses#5768]
This may need to be a separate issue, but I'm unable to see the results of this change, seemingly due to a failure in processing the _loveland data. [https://results.openaddresses.io/sources/us/fl/_loveland](https://results.openaddresses.io/sources/us/fl/_loveland) is showing that the job has been failing since 2021-03-23 due to the source file being unavailable. This is presumably causing the "old" data to still be returned.

_Originally posted by @collinjc in https://github.com/openaddresses/openaddresses/issues/5694#issuecomment-833839066_

**Comment by arch0345** [comment]
Loveland source was removed in https://github.com/openaddresses/openaddresses/pull/6554

**Comment by arch0345** [comment]
Resolved in #6554
