### ISSUE TITLE
Incorrect cities for us/co/archuleta

### ISSUE THREAD

**Issue by rbrtmrtn** [openaddresses/openaddresses#5790]
Hello,

Looking at the data for `us/co/archuleta` I noticed that the city is always set to `ARCHULETA`. That's actually the county name and there are a number of cities within the county. Unfortunately, the correct city names don't seem to exist in the source data.

As an example, here is `77 BEUCLER PL`. When you type it into Google Maps, it takes you to `77 BEUCLER PL, PAGOSA SPRINGS, CO`:

https://www.google.com/maps/place/77+Beucler+Pl,+Pagosa+Springs,+CO+81147/@37.2298902,-107.1856546,14.23z/data=!4m5!3m4!1s0x873dd1dd7c3738db:0x2410396fefbc78b1!8m2!3d37.2274441!4d-107.1718542

I checked the parcel source as well, and that also has no city field.

Since these addresses are technically incorrect, should they stay as part of OpenAddresses?

**Comment by ingalls** [comment]
@rbrtmrtn Thanks for reporting this. I've created a Pull Request to remove the city field. As you found, I don't see any fields with the proper city field so this source will remain, however the addresses won't contain a city field in the output.

**Comment by rbrtmrtn** [comment]
Thank you for taking a second look at it @ingalls. Glad to hear about the resolution!
