### ISSUE TITLE
No attribution field

### ISSUE THREAD

**Issue by fishcharlie** [openaddresses/openaddresses#5794]
How should no attribution field in a sources JSON file be interpreted? Does this mean that attribution is not required and the data is in the public domain?

**Comment by iandees** [comment]
No, the lack of license information does not mean there is no license. It means we haven't found the license information yet.

**Comment by fishcharlie** [comment]
So will sources with public domain data just be marked as "Public Domain" in the attribution property then?

Also. If license data can not be found, how is it verified that the data is truly openly licensed?

**Comment by iandees** [comment]
> will sources with public domain data just be marked as "Public Domain" in the attribution property then?

There are more properties on a source that describe licensing information than `attribution`. For example, here's the Massachusetts statewide dataset that we've marked as "Public Domain": https://github.com/openaddresses/openaddresses/blob/master/sources/us/ma/statewide.json#L17

There's more information about the properties on a source documented [here](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#optional-address-tags).

> If license data can not be found, how is it verified that the data is truly openly licensed?

OpenAddresses doesn't guarantee that the data is "truly openly licensed". It's up to you to understand the licenses of the sources you use and make sure they match what you're doing with the data. We aren't lawyers, and we definitely aren't your lawyer :-).

**Comment by fishcharlie** [comment]
Understood. One suggestion. On the website it says:

> OpenAddresses is open data. All data is openly licensed. Most sources only require attribution.

Seems like that is misleading if OpenAddresses doesn't guarantee that the data is "truly openly licensed". What is the difference between "truly openly licensed" and "openly licensed"? From my perspective there isn't a difference.

Probably fair to say that the data is open. But using the term "openly licensed" just feels really misleading.

---

All of that being said, if there is confidence that checks are being done to ensure that OpenAddresses data is openly licensed and it's just a matter of missing `attribution` or `license` values as opposed to not having found the license field, then I think that statement on the website is fine. But that isn't what I gathered from the original comment.

**Comment by iandees** [comment]
Thanks for the feedback on the messaging on the website. We can definitely do a better job of making that clearer.

Bottom line is that OpenAddresses isn't re-licensing data. We're indexing and sharing data that is publicly available on the internet. If you have a particular licensing bar you need to meet for your use, you should make sure the data meets that bar.

**Comment by fishcharlie** [comment]
@iandees Appreciate you being so receptive to the feedback. Thank you for also being so responsive in terms of this inquiry.

I will be closing this issue since my question has been answered. Please let me know if you'd like me to create a separate issues to track the website language suggestion.
