### ISSUE TITLE
City of Arvada CO Data Source Error

### ISSUE THREAD

**Issue by fishcharlie** [openaddresses/openaddresses#5803]
The current `data` URL for `sources/us/co/city_of_arvada.json` leads to an error:

<img width="729" alt="image" src="https://user-images.githubusercontent.com/860375/124665449-f8152600-de69-11eb-9530-bb0025f727d3.png">

I found [this source](https://gis-arvada.opendata.arcgis.com/datasets/8f04daa3938b4c40b56325bb218ff0fa_0/about) that looks to be identical data (but I'm unsure). It looks to have CSV, KML, Shapefile, and GeoJSON formats.

It also lists the data as `CC0 License`.

This link was found by searching for `City of Arvada Open Data` on DuckDuckGo, and navigating to the [first result](https://gis-arvada.opendata.arcgis.com). Near the bottom of that page there is a search field where you can enter address, which leads you to that link above.

It looks like there is also Parcel data that can be added here.

I'm unsure how to handle this. Is it ok to replace this with this new (or maybe updated) data source I found? Which format is preferred between CSV, KML, Shapefile, and GeoJSON formats? How should I handle the existing `conform` object if I do update this?

**Comment by iandees** [comment]
Thanks for finding this. It's ok to modify the existing source with the new link. I started a PR with the URL and conform change linked above. If you'd like to add the parcels to my branch that's ok. We could add the license information, too.

**Comment by fishcharlie** [comment]
@iandees Awesome! I will work on this later today. I think I'll need some type of permissions to push to that branch tho, correct?

**Comment by iandees** [comment]
I added you as a member to the repository so you should be able to pull down that branch directly.

**Comment by fishcharlie** [comment]
@iandees Looks like @ingalls merged in that PR. I made another one with the final updates here. Hopefully I did everything correctly #5804.
