### ISSUE TITLE
Portugal Addresses with good license

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#5819]
https://snig.dgterritorio.gov.pt/rndg/srv/por/catalog.search#/metadata/1b772914-e3e9-4663-8557-a6aef5aa596a?tab=responsible

license now looks good.

more info here:
https://wiki.openstreetmap.org/wiki/Portugal/Projetos/Importa%C3%A7%C3%A3o_de_endere%C3%A7os
https://www.openstreetmap.org/user/Jorge%20Gustavo%20Rocha/diary

**Comment by sergiyprotsiv** [comment]
I think that's exactly the source we are using: https://github.com/openaddresses/openaddresses/blob/master/sources/pt/countrywide.json

Though maybe the license needs to be added if it is evident.

**Comment by justinelliotmeyers** [comment]
@sergiyprotsiv thanks - I think you are right. I know we had to pull the census data a while back - didnt realize we got a new open source one.  Thanks!
