### ISSUE TITLE
us/co/denver Duplicate Entries

### ISSUE THREAD

**Issue by fishcharlie** [openaddresses/openaddresses#5838]
In `us/co/denver` there are duplicate entries for `4303 N Brighton Blvd Rear`. OpenAddresses Hash: `a4f552c5a3f25ca0`.

In the raw data it looks like these should be two different entries:

```
4303 N Brighton Blvd Bldg 1 Rear
4303 N Brighton Blvd Bldg 2 Rear
```

I'm not sure how to fix this. I think adding those properties to the `conform` property will add a bunch of bad data to the output.

Any ideas how to proceed here?

**Comment by iandees** [comment]
The "Bldg 1 Rear" and "Bldg 2 Rear" should probably end up in the unit field. What field(s) are you quoting from the raw data?

**Comment by fishcharlie** [comment]
@iandees I downloaded the CSV file. I'm unsure if the property names are the same.

But `BUILDING_TYPE` and `BUILDING_IDENTIFIER` in the CSV file.

Not sure if there is an application or something to work with shapefiles easily.

```
ADDRESS_TYPE,X_COORD  ,Y_COORD    ,LATITUDE     ,LONGITUDE    ,ADDRESS_NUMBER_PREFIX,ADDRESS_NUMBER,ADDRESS_NUMBER_SUFFIX,PREMODIFIER,PREDIRECTIONAL,STREET_NAME,POSTTYPE,POSTDIRECTIONAL,POSTMODIFIER,BUILDING_TYPE,BUILDING_IDENTIFIER,UNIT_TYPE,UNIT_IDENTIFIER,COMPOSITE_UNIT_TYPE,COMPOSIT_UNIT_IDENTIFIER,FULL_ADDRESS
S           ,3148519.0,1708673.0  ,39.77792858  ,-104.97159139,None                 ,4303.0        ,None                 ,None       ,N             ,Brighton   ,Blvd    ,None           ,None        ,Bldg         ,1                  ,Rear     ,None           ,Rear               ,None                    ,4303 N Brighton Blvd Bldg 1 Rear
S           ,3148519.0,1708673.0  ,39.77792858  ,-104.97159139,None                 ,4303.0        ,None                 ,None       ,N             ,Brighton   ,Blvd    ,None           ,None        ,Bldg         ,2                  ,Rear     ,None           ,Rear               ,None                    ,4303 N Brighton Blvd Bldg 2 Rear
```

**Comment by iandees** [comment]
Ah, I bet the "unit" field in the conform has just `["UNIT_TYPE", "UNIT_IDENTIFIER"]`. Maybe we should add the other UNIT columns to that list, too?

**Comment by fishcharlie** [comment]
@iandees My concern is a lot of the fields have `None`. Those `None` values shouldn't be included. Maybe that is specific to the CSV file tho?? Especially since some of the `UNIT_IDENTIFIER`'s are `None`.

It looks like the current source is using a shapefile, which I'm not sure how to open and view on my computer.

Would be happy to try to test this and put up a PR. Is there a good method for viewing the raw shapefile data tho to verify before doing that?

**Comment by iandees** [comment]
The falsey stuff like `None` and `""` should get filtered out when joined into a single string, so it should be ok to add these extra fields.

**Comment by fishcharlie** [comment]
@iandees Awesome. I'll try to do some Googling to figure out how to find the correct shapefile attribute names and get a PR up this afternoon/tonight.

**Comment by fishcharlie** [comment]
@iandees PR up for this: #5840. However I found a record with `Bldg 1 Bldg 1` as the `unit` value. Not sure how to fix this tho. Any ideas?
