### ISSUE TITLE
Drop in US sources

### ISSUE THREAD

**Issue by ilissablech** [openaddresses/openaddresses#5843]
I am noticing that few sources experienced a data drop.

|source|count discrepancy| Ref |
| --- | --- | --- |
**us/fl/statewide2 | -399813** |
us/fl/collier | -226299 | :green_circle: https://github.com/openaddresses/openaddresses/pull/5875
**us/ar/pulaski | -185843** | :green_circle: https://github.com/openaddresses/openaddresses/pull/5844
us/ca/sonoma | -90508 | :green_apple: https://github.com/openaddresses/openaddresses/pull/5878
|us/nh/statewide|458322| :red_circle: Statewide source has removed addresses. I've reached out but nothing yet.
|us/ri/statewide|381835| :green_circle: https://github.com/openaddresses/openaddresses/pull/5872
|us/oh/butler|147297| :green_circle:  https://github.com/openaddresses/openaddresses/pull/5869
|us/ny/sullivan|111408| :green_circle: https://github.com/openaddresses/openaddresses/pull/5845
|us/tn/city_of_chattanooga|102759|See Note
|us/nc/davidson|73339|https://github.com/openaddresses/openaddresses/pull/5868
|us/ak/matanuska_susitna_borough|60879|https://github.com/openaddresses/openaddresses/pull/5867
|us/ca/city_of_rancho_cucamonga|50062| :green_circle: https://github.com/openaddresses/openaddresses/pull/5866
|us/pa/adams|45709| :red_circle: Could not find alternative source
|us/va/bedford|37167| https://github.com/openaddresses/openaddresses/pull/5884
|us/il/adams|29562|:green_circle:https://github.com/openaddresses/openaddresses/pull/5865
|us/id/bonner|29507|:green_circle:https://github.com/openaddresses/openaddresses/pull/5864
|us/nm/valencia|29235| :green_circle: https://github.com/openaddresses/openaddresses/pull/5847
|us/mn/douglas|29230| :green_circle: https://github.com/openaddresses/openaddresses/pull/5863
|us/la/caddo|24962| :green_circle: https://github.com/openaddresses/openaddresses/pull/5862
|us/ia/cerro_gordo|21971|:green_circle: https://github.com/openaddresses/openaddresses/pull/5861
|us/mn/mille_lacs|18852|:green_circle: https://github.com/openaddresses/openaddresses/pull/5860
|us/ms/city_of_biloxi|15790|:green_circle: https://github.com/openaddresses/openaddresses/pull/5859
|us/wi/green_lake|10599| :green_circle: https://github.com/openaddresses/openaddresses/pull/5848
|us/mn/dodge|10471| :green_circle:https://github.com/openaddresses/openaddresses/pull/5858
|us/ak/city_of_juneau|10030| :green_circle:https://github.com/openaddresses/openaddresses/pull/5857
|us/mn/chippewa|6389| :green_circle:https://github.com/openaddresses/openaddresses/pull/5849
|us/mn/yellow_medicine|4398| :green_circle: https://github.com/openaddresses/openaddresses/pull/5856
|us/wa/city_of_snohomish|4095| :green_circle: https://github.com/openaddresses/openaddresses/pull/5855
|us/or/wheeler|342| :green_circle: https://github.com/openaddresses/openaddresses/pull/5854
|us/tn/maury|6| :green_circle: https://github.com/openaddresses/openaddresses/pull/5853

What's the best way to QC these address drops? The `us/fl/statewide2` and `us/ar/pulaski` drops are the most worrysome, as those states also experienced the largest overall drops.

---

Hi @ingalls. 

I did a further QC of our newly ingested OA set and here is a list of 27 sources that we have had to filter our fully due to having no house number and/or no street name across the entire data set.

**Comment by ilissablech** [comment]
Hi @ingalls. 

I did a further QC of our newly ingested OA set and here is a list of 27 sources that we have had to filter our fully due to having no house number and/or no street name across the entire data set.

|source|count discrepancy|
|--|--|
|us/nh/statewide|458322|
|us/ri/statewide|381835|
|us/ar/pulaski|223935|
|us/oh/butler|147297|
|us/ny/sullivan|111408|
|us/tn/city_of_chattanooga|102759|
|us/nc/davidson|73339|
|us/ak/matanuska_susitna_borough|60879|
|us/ca/city_of_rancho_cucamonga|50062|
|us/pa/adams|45709|
|us/va/bedford|37167|
|us/il/adams|29562|
|us/id/bonner|29507|
|us/nm/valencia|29235|
|us/mn/douglas|29230|
|us/la/caddo|24962|
|us/ia/cerro_gordo|21971|
|us/mn/mille_lacs|18852|
|us/ms/city_of_biloxi|15790|
|us/wi/green_lake|10599|
|us/mn/dodge|10471|
|us/ak/city_of_juneau|10030|
|us/mn/chippewa|6389|
|us/mn/yellow_medicine|4398|
|us/wa/city_of_snohomish|4095|
|us/or/wheeler|342|
|us/tn/maury|6|

**Comment by ingalls** [comment]
@ilissablech I'm not seeing a drop on my side for the City of Chatanooga
Ref: https://batch.openaddresses.io/data/1897/history

I've updated Hamilton County, TN data which includes the city: https://github.com/openaddresses/openaddresses/pull/5871

**Comment by ilissablech** [comment]
Thanks for the update @ingalls! I'll double check was might have been going on on my end for the City of Chatanooga.

**Comment by ingalls** [comment]
Clear Creek CO - switched from Parcel Source -> Actual Address Source. Decrease is likely due to cleaner data?

**Comment by ingalls** [comment]
@ilissablech I'm going to close this ticket as I've worked through the initial batch of requested sources and a bunch of the subsequent sources. Could you regenerate a list that you want looked at and I'll dive in? This ticket is starting to get rather scattered.

**Comment by ilissablech** [comment]
Thanks @ingalls! I'll take a look today or Monday and let you know if I'm still seeing any drops.
