### ISSUE TITLE
nz_countrywide has lat/lon values flipped

### ISSUE THREAD

**Issue by missinglink** [openaddresses/openaddresses#5906]
Heya,

I downloaded the `nz_countrywide-addresses-country.geojson.gz` file today and noticed that the lat/lon coordinates are reversed.

Looking at the source it seems to be mapped correctly 🤷 
https://github.com/openaddresses/openaddresses/blob/master/sources/nz/countrywide.json#L29-L30

> note: latitude values >90.0

```bash
gzcat ~/Downloads/nz_countrywide-addresses-country.geojson.gz | head -n2 | jq .geometry
{
  "type": "Point",
  "coordinates": [
    -36.6304294,
    174.4978477
  ]
}
{
  "type": "Point",
  "coordinates": [
    -36.630864,
    174.4972355
  ]
}
```

I also checked another file file from NZ and it was correct:

```bash
gzcat ~/Downloads/nz_greater_wellington-addresses-city.geojson | head -n2 | jq .geometry
{
  "type": "Point",
  "coordinates": [
    174.9550451,
    -40.9808712
  ]
}
{
  "type": "Point",
  "coordinates": [
    174.954071,
    -40.981851
  ]
}
```

**Comment by andrewharvey** [comment]
probably the same as https://github.com/openaddresses/openaddresses/issues/5919#issuecomment-932901048

**Comment by ingalls** [comment]
I'm so sorry it's taken me so long to get to this. The last couple of months have been incredible busy.

Have a test running on the (:crossed_fingers:) fixed CSV parsing code

Ref: https://batch.openaddresses.io/run/1335

**Comment by ingalls** [comment]
Fixed; https://batch.openaddresses.io/job/210646
