### ISSUE TITLE
ee/countrywide addresses

### ISSUE THREAD

**Issue by ilissablech** [openaddresses/openaddresses#5908]
On the [2020-08-21](https://batch.openaddresses.io/job/2832) address set for Estonia we had address points with coordinates over land.

![image](https://user-images.githubusercontent.com/25749483/135319860-2b14e06d-6330-4656-9b75-6a13cf4e2654.png)

The [most recent build](https://batch.openaddresses.io/job/158444) is over water.
![image](https://user-images.githubusercontent.com/25749483/135319823-075d53d7-4887-47b2-906e-4b2e6e1f26f6.png)

Is there a way to get the coordinates rotated property? Thanks!

**Comment by stefanb** [comment]
This seems to be happening even if there are no meaningful changes in the JSON source definition, 
see https://batch.openaddresses.io/job/161026 from PR #5909 
![image](https://user-images.githubusercontent.com/319826/135338209-a25e1f94-9b42-436d-b74b-b8a344d6a91d.png)

While https://batch.openaddresses.io/job/109044 from master branch seems ok:
![image](https://user-images.githubusercontent.com/319826/135338228-03d1eccb-01dd-4ee4-88e2-c25d917029c9.png)

@ilissablech's [Estonia](https://batch.openaddresses.io/job/158444) also seems to be rotated and positioned into the Arabian sea: 
![image](https://user-images.githubusercontent.com/319826/135338558-1261bc64-e261-45ad-b975-ee6b8da372c2.png)

**Comment by stefanb** [comment]
New Zealand https://batch.openaddresses.io/job/158701 has no preview image and clicking the "map" button reports
> Invalid LngLat latitude value: must be between -90 and 90

**Comment by ingalls** [comment]
:eyes: I'll dig into these today, nothing has changed in the task processor in recent times so not sure why these are changing unless there is some non-deterministic library installs going on.

**Comment by stefanb** [comment]
I randomly found also South Korea: https://batch.openaddresses.io/job/158603 plotted south of Japan

**Comment by stefanb** [comment]
Japan: https://batch.openaddresses.io/job/158579

**Comment by ingalls** [comment]
Fixed Estonia. https://github.com/openaddresses/openaddresses/pull/5910

Our GDAL upgrade appears to be at fault. It changes a bunch of defaults around coordinate order and was pretty deep into our stack. @stefanb Can we open a new ticket for each source you find with bugs? I'll also start a comprehensive review. Just long years of experience tickets with multiple potentially unrelated problems/sources quickly become unmanagable.

I'll migrate the current bugs you've found from this ticket into their own :)

**Comment by ingalls** [comment]
Japan: https://github.com/openaddresses/openaddresses/issues/5912
Korea: https://github.com/openaddresses/openaddresses/issues/5911

**Comment by ilissablech** [comment]
Thanks @ingalls !
