### ISSUE TITLE
Korea Coords Flip

### ISSUE THREAD

**Issue by ingalls** [openaddresses/openaddresses#5911]
Ref: https://batch.openaddresses.io/job/158603

**Comment by stefanb** [comment]
Also
- https://batch.openaddresses.io/job/161536
- https://batch.openaddresses.io/job/161532
- ...

**Comment by ingalls** [comment]
Fixed: https://batch.openaddresses.io/job/210643

**Comment by ingalls** [comment]
Fix remaining sources: https://github.com/openaddresses/openaddresses/pull/5997
