### ISSUE TITLE
Australia has wrong lng/lat projection

### ISSUE THREAD

**Issue by flatwhite0928** [openaddresses/openaddresses#5919]
The lng/lat in:
- `au/countrywide - addresses - country`: https://batch.openaddresses.io/job/161058
- `au/qld/brisbane_city_council - addresses - city`: https://batch.openaddresses.io/job/70545

**Comment by stefanb** [comment]
Possibly due to https://github.com/openaddresses/batch/issues/90, similar to https://github.com/openaddresses/openaddresses/issues/5917

**Comment by ingalls** [comment]
https://batch.openaddresses.io/run/1329
