### ISSUE TITLE
Any (opensource) webservices using openaddresses data for geocoding?

### ISSUE THREAD

**Issue by svego** [openaddresses/openaddresses#5956]
Are there any opensource geocoding webservices that use data from the openadresses project? 

I would like to make a (forward) geocoding webservice that can search by city/street/address/country fields and return some coordinates.

**Comment by iandees** [comment]
I know that [Pelias](https://pelias.io/) has support for OpenAddresses as its primary street address data.

**Comment by ingalls** [comment]
The current list of geocoders that I am aware of that use OpenAddresses data are:

In alphabetical order:
geocod.io
geocode.earth
geoservices.tamu.edu
Mapbox.com
SmartyStreets.com
