### ISSUE TITLE
Poland reversed coordinates

### ISSUE THREAD

**Issue by peterschinkel80** [openaddresses/openaddresses#5974]
As far as we saw the coordinates of all countries are in lon/lat format, except for Poland which are in lat/lon format.

For example pl/dolnoslaskie-addresses-state.geojson:
{"type":"Feature","properties":{"hash":"1606d482d1df2e9b","number":"2b","street":"Wałowa","unit":"","city":"Bolesławiec","district":"bolesławiecki","region":"dolnośląskie","postcode":"59-700","id":"16569eef-59a6-435c-a85e-f71bb1e29078"},"geometry":{"type":"Point","coordinates":[51.2780451,15.5654271]}}

VS cz/countrywide-addresses-country.geojson
{"type":"Feature","properties":{"hash":"c53a5e83a10ae58e","number":"9/10","street":"Jiřská","unit":"","city":"Praha 1","district":"","region":"","postcode":"11900","id":""},"geometry":{"type":"Point","coordinates":[14.40381,50.091628]}}

**Comment by ingalls** [comment]
Fixed: https://batch.openaddresses.io/job/210638

**Comment by peterschinkel80** [comment]
Thanks!!!

**Comment by ingalls** [comment]
@peterschinkel80 No problem, sorry it took so long, the holidays took up a bunch of my time this year. All the best!
