### ISSUE TITLE
us/tn/city_of_chattanooga swapped address coordinates

### ISSUE THREAD

**Issue by ilissablech** [openaddresses/openaddresses#5989]
With Job #119905 for `us/tn/city_of_chattanooga` address coordinates seem to have been flipped.

2021-06-18; Job #119905
![image](https://user-images.githubusercontent.com/25749483/149573179-1dafedb9-512a-465a-81fd-ac7ebb1c249d.png)

2021-06-11; Job #117059
![image](https://user-images.githubusercontent.com/25749483/149573271-a73d4e3c-194d-4d5a-a5b5-5672c2bc79cf.png)

cc @ingalls

**Comment by ingalls** [comment]
We've seen a few of these unfortunately since our last GDAL upgrade. This one is going to take a little longer to fix - I started looking into it last week - should have an update later this week

**Comment by ilissablech** [comment]
Thanks @ingalls!

**Comment by ingalls** [comment]
@ilissablech This one was a head scratcher. I've narrowed down to sources that meet **all** of the following:
- Sources with an input type of CSV (In the US this is only: `us/tn/city_of_chattanooga`)
- Sources that specify an `srs` value

I've mitigated the City of Chatanooga directly by adding a short-circuit check to avoid a coordinate transformation if the source is already in `EPSG:4326`.
I'm currently validating the deeper fix of reversed coordinate order on the Korean sources which also match the above criteria and exhibit this same behavior

**Comment by ilissablech** [comment]
Thanks for the update @ingalls!

**Comment by ingalls** [comment]
Fixed: https://batch.openaddresses.io/job/210634

**Comment by ilissablech** [comment]
Thanks @ingalls!
