### ISSUE TITLE
Texas Statewide Missing

### ISSUE THREAD

**Issue by d3mon187** [openaddresses/openaddresses#6009]
I noticed that for Texas the main statewide.json file is missing it's geojson.  It seems like https://github.com/openaddresses/openaddresses/pull/5983 made the switch from the individual county files with the 2019 data to 2021, but I'm not seeing the new statewide geojson in the data collections or layers.  This link https://batch.openaddresses.io/job/202431 has the file available to download, but I can't find any reason why it isn't included in the collections?

**Comment by StephanGeorg** [comment]
I can confirm that. It is not available in the `us-south` collection and also not available as a single `us/tx/statewide` download. 

File is still available and accessible

https://github.com/openaddresses/openaddresses/blob/777e3371db16d008c0bbd33516d90a360cb7d22c/sources/us/tx/statewide.json#L14

**Comment by StephanGeorg** [comment]
I'm not so familiar with the syntax but could it be that

```json
{ 
"compression": "zip"
}
```
is missing in 

https://github.com/openaddresses/openaddresses/blob/777e3371db16d008c0bbd33516d90a360cb7d22c/sources/us/tx/statewide.json#L13-L22

**Comment by StephanGeorg** [comment]
Have you @MiniCodeMonkey ever seen this file was processed?

**Comment by StephanGeorg** [comment]
I added a PR https://github.com/openaddresses/openaddresses/pull/6010 to fix missing compression. Hope that helps.

**Comment by StephanGeorg** [comment]
Closed by #6010

**Comment by StephanGeorg** [comment]
@ingalls why is `us/tx/statewide`still not listed at https://batch.openaddresses.io/data and not part of the collection?
