### ISSUE TITLE
Hash field in exported data.

### ISSUE THREAD

**Issue by idurotPauley** [openaddresses/openaddresses#6028]
Hi, 

I have a question in regards to how the HASH value in the exported CSV/json files are generated.

What fields are used to create this hash? 

I am hoping that I am able to use the hash almost as a unique id and as identifier to determine if an address point should be reprocessed.

Are hashes guaranteed uniqueness across all data sources?

**Comment by iandees** [comment]
More discussion about the hash value can be found in this ticket here: https://github.com/openaddresses/machine/issues/683

**Comment by missinglink** [comment]
See also: https://github.com/pelias/openaddresses/pull/442

**Comment by idurotPauley** [comment]
Thanks all!
