### ISSUE TITLE
Where can I download the changeset?

### ISSUE THREAD

**Issue by kokoskiwi** [openaddresses/openaddresses#6031]
Hi on https://batch.openaddresses.io/data I can only download the actual data. But where can I download the changeset (edited data, new data, deleted data)?

**Comment by iandees** [comment]
We don't capture changes between runs of data fetches. You can download between different runs and check for changes yourself, if you'd like.

**Comment by kokoskiwi** [comment]
> We don't capture changes between runs of data fetches. You can download between different runs and check for changes yourself, if you'd like.

so I basically code a script that compares changes between both versions, and e.g uploads changes directly into my DB. is that correct?

thank you very much bro!!

**Comment by iandees** [comment]
Yep, that's right.
