### ISSUE TITLE
Wiki links not working

### ISSUE THREAD

**Issue by rbrtmrtn** [openaddresses/openaddresses#6044]
Hello OpenAddresses friends! 👋 

I have a dataset to contribute and was just walking through `CONTRIBUTING.md`. I noticed that the links to the various wikis (commercial, outreach, etc.) seem to be broken for me. For example this URL:

https://github.com/openaddresses/openaddresses/wiki/Commercial-sources

redirects back to the repo landing page. Just wanted to flag this—thank you for this tremendous project!

**Comment by iandees** [comment]
Thanks for letting us know! I disabled the Github wiki a while ago because those pages had gotten stale. I'll look into updating the CONTRIBUTING.md file with new instructions.

**Comment by iandees** [comment]
I re-enabled the wiki. There's still some useful information there!

**Comment by rbrtmrtn** [comment]
Awesome, thanks for addressing this so quickly @iandees. Looking forward to contributing 😄
