### ISSUE TITLE
data download best practices

### ISSUE THREAD

**Issue by JosephKuchar** [openaddresses/openaddresses#6059]
Hi all,

I'm working on a Canada-specific Pelias implementation, so I was going to download all the openaddresses Canada data. The new download service doesn't have a Canada or North America minus USA bulk options, so I'm wondering what's recommended for downloading lots of data from the server? 
Thanks for the help,
Joseph

**Comment by ingalls** [comment]
Hey @JosephKuchar, <3 supporting you guys. I'll add a Canada Collection.

**Comment by JosephKuchar** [comment]
Hi @ingalls ! Thanks for the help! No worries, I think got there in the end! And this one isn't for StatCan, actually - I'm temporarily assisting another department. Though speaking of StatCan and addresses, I don't know if you're aware but StatCan has a relatively new  [geocoding API](https://www.statcan.gc.ca/en/developers/nar). 

I wasn't sure how to get all sources starting with 'ca/' using the API, so instead I git cloned the sources directory from github, then for every Canadian source name there I queried the data API to get the job ID, then queried the job API to download the geojson. There's probably a cleaner way to do it, but it seems to have worked.
