### ISSUE TITLE
Improved Canadian Postal Code Coverage

### ISSUE THREAD

**Issue by jkao** [openaddresses/openaddresses#6064]
I recognize the troubling parts around dealing with postal code coverage in Canada:

https://github.com/openaddresses/openaddresses/issues/5650

But I'd like to point out an interesting open-data source from the government of Canada: 

https://open.canada.ca/data/en/dataset/0032ce54-c5dd-4b66-99a0-320a7b5e99f2

They have a ton of structured business addresses (new and old) with postal codes.

If we haven't already ingested this, we could join that data with:

https://www.statcan.gc.ca/en/lode/databases/oda

In order to get addresses with lat, lng and postal codes in Canada.

**Comment by ingalls** [comment]
@jkao We pull in postal codes where the sources have then, but generally speaking these are very rare. OpenAddresses does not have the ability to do cross source joins at this time, but if you were to start a project to attempt such a joinn, I would be more than happy to make note of it here and direct users to run our data against your post-processing scripts!

The ODA is actually a collaboration between OpenAddresses and Census Canada and most if not all of their sources will already be present in the OA source collection.
