### ISSUE TITLE
Build untuk Desa Modisi Tidak Ada

### ISSUE THREAD

**Issue by bili29** [openaddresses/openaddresses#6082]
Bentuk bangunan yang sudah di edit di openstreermap belum muncul di facebook serta fasilitas yang lainya juga tidak ada

@Modisi 95777, Sulawesi Utara, Indonesia

**Comment by iandees** [comment]
Translated:
> The edited form of the building in Openstreermap has not appeared on Facebook and other facilities are also missing

This project is not related to OpenStreetMap. Please contact the OpenStreetMap community in your area for more help.

Translated:

Proyek ini tidak terkait dengan OpenStreetMap. Silakan hubungi komunitas OpenStreetMap di daerah Anda untuk bantuan lebih lanjut.
