### ISSUE TITLE
Update Sumter County Florida

### ISSUE THREAD

**Issue by zyphlar** [openaddresses/openaddresses#6088]
New subdivisions have been built and reflected in county GIS data, which has been added to OSM but not OA. Rerunning [this OA batch job would hypothetically bring in those changes](https://batch.openaddresses.io/job/68858).

Sanity spot checks:
- https://www.openstreetmap.org/#map=18/28.81211/-82.00920
- https://www.openstreetmap.org/#map=19/28.83368/-82.02723
- https://www.openstreetmap.org/#map=18/28.82356/-82.03689

**Comment by zyphlar** [comment]
Is this project still active? All we need to do is run a batch and then a whole city can use their GPS app again @iandees @ingalls

**Comment by iandees** [comment]
It's definitely still active, but I have yet to figure out why the jobs aren't running. I'll try to find some time this weekend to dig in.

**Comment by zyphlar** [comment]
Thanks! I have a little bit of funding so if there's an area I'm able to help with lmk. My username at Gmail is a valid contact method.

**Comment by zyphlar** [comment]
Thanks! I have a little bit of funding so if there's an area I'm able to help with lmk. My username at Gmail is a valid contact method.

**Comment by zyphlar** [comment]
@iandees just checking in! Apparently this data is required for mapbox to have accurate addresses, which is then required for the #5 paid gps app in the app stores to work, so the owner of that app is saying he's willing to pay for your time in getting this working, it's just at a standstill in the meantime

**Comment by iandees** [comment]
I updated to a seemingly-newer data source in #6093. The data should be available shortly.

**Comment by zyphlar** [comment]
@iandees thank you so much!

**Comment by zyphlar** [comment]
@iandees it looks like the job failed without producing a log? I'd love to help debug this but all the build environment / job running documentation / code / issues / wiki seem incredibly obtuse, as if three people know how to do it and nobody else is allowed. https://batch.openaddresses.io/job/315234

**Comment by iandees** [comment]
I encourage you to read our documentation and give constructive feedback.

**Comment by zyphlar** [comment]
This is as far as I got, my use case is trying to run the Sumter County job to see why it's failing.
https://github.com/openaddresses/batch-machine/issues/29

**Comment by zyphlar** [comment]
Should be correct with this PR https://github.com/openaddresses/openaddresses/pull/6097

**Comment by zyphlar** [comment]
@iandees can I get an admin token so at least I can rerun existing jobs? I'm trying to help debug what's going on but it seems internal to the batch runner and I can't poke anything to make anything happen anyway.

**Comment by iandees** [comment]
@ingalls is working on fixing some bugs in the backend/build system still, so kicking off new runs probably won't help.

In this case, it looks like a recent rebuild of the Sumter data worked (https://batch.openaddresses.io/job/315253/log), but the job is marked as a failure because the verified data process failed.

**Comment by zyphlar** [comment]
Thanks, I hope to contribute further but understand sometimes the one in charge just needs to dig into the inner workings solo.

**Comment by EWCDesigns** [comment]
Hey guys, thank you so much for helping me out with this issue. 

The Villages city in Florida has been expanding at a rapid rate by buying up land in neighboring cities like Wildwood and we are just trying to keep up with the addresses, custom Multi Model roads and the changing of the name of the new section of Wildwood to The Villages. 

This will be going on for at least the next two years from what I understand.  

If I can send a tip to you guys, let me know. We need the help.  Send me an email to let me know where to send it. 

Have a Very Merry Christmas!
