### ISSUE TITLE
us-wi-kewaunee

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#609]
Kewaunee	
https://kewauneeco.ags.ruekert-mielke.com/

**Comment by geobrando** [comment]
Geocortex map

**Comment by iandees** [comment]
These Ruekert Mielke map services have a fairly consistent way of retrieving an ArcGIS REST token. I might hack my local copy of machine to support it and cache the resulting data in S3.

**Comment by slibby** [comment]
Layer found here: https://maps.ags.ruekert-mielke.com/ags/rest/services/KewauneeCo/KewauneeCoFeature/FeatureServer/2

And tracked here: https://github.com/openaddresses/openaddresses/blob/master/sources/us/wi/kewaunee.json
