### ISSUE TITLE
Jobs and runs stalled

### ISSUE THREAD

**Issue by stefanb** [openaddresses/openaddresses#6104]
It seems that the last activity was on 2022-11-11:
* https://batch.openaddresses.io/run (last run 2022-11-11)
* https://batch.openaddresses.io/job (logs expired?)
* https://batch.openaddresses.io/data (clicking on random sources on map reveals latest date 2022-11-11)

**Comment by ingalls** [comment]
Should be fixed! So sorry this took longer than I had hoped, between work and Search & Rescue I've been stretched very thin.

**Comment by stefanb** [comment]
Thanks, it seems to be working now!
