### ISSUE TITLE
[update data] Cook County, Illinois

### ISSUE THREAD

**Issue by rbrtmrtn** [openaddresses/openaddresses#6105]
It looks like there's once again a single ArcGIS Online dataset for Cook County address points:

https://hub-cookcountyil.opendata.arcgis.com/datasets/5ec856ded93e4f85b3f6e1bc027a2472

Wondering if this may obviate the need for the current downloader [script](https://github.com/openaddresses/openaddresses/tree/master/scripts/us/il/cook)?

**Comment by ingalls** [comment]
Thanks a ton @rbrtmrtn
