### ISSUE TITLE
Consistent naming convention for U.S. counties

### ISSUE THREAD

**Issue by rbrtmrtn** [openaddresses/openaddresses#6112]
Hello!

I noticed that U.S. county sources generally don't include `county` in the filename (`/co/adams.json`), but sometimes do (`/ks/allen_county.json`). I have a use case where I'm looping over a list of U.S. counties and would like to check to see if they exist in OA, and this makes it a little tricky to construct the source's JSON path programmatically. Not a huge deal, but wanted to flag this as a potential improvement (and would be happy to take a stab at it, provided it won't break anything.)

A similar finding — parishes in Louisiana sometimes contain `parish` in the filename, and other times not. When I Google them I see they're all technically parishes.

Thank you!

**Comment by iandees** [comment]
I wouldn't rely on the file name of the source JSON for this. Take a look inside the source JSON file for `coverage`, which will have a FIPS code for the county. You can match that up with the US Census data to get an understanding of coverage and completeness.

**Comment by ingalls** [comment]
Going to close as we don't have a plan to mass migrate source names in the near future as we consider them to simply be a container for the persistent `coverage` tag as Ian explained above.

If you have any questions about parsing the coverage object feel free to open a ticket and tag @iandees and @ingalls
