### ISSUE TITLE
Tooling for normalizing addresses

### ISSUE THREAD

**Issue by rbrtmrtn** [openaddresses/openaddresses#6124]
Hello, OA!

I have use case at the moment (analyzing broadband coverage in the U.S.) where OA addresses would make a great starting point, but I need to get them closer to complete and normalized postal addresses to get much further. It's OK if the normalized form is a best guess and not perfect, but the idea is that the concatenated OA address (say `123 Main Street 92240`) should be fleshed out to a more canonical USPS one like `123 MAIN ST, DESERT HOT SPRINGS, CA 92240`.

I've been thinking about how to backfill missing fields in my copy of the OA data (I've noticed a number of data sources understandably don't include their own city or state) and some of the challenges/pitfalls there. Before I go much deeper, I thought I'd check in here and see if anyone else has taken a stab at this. I've dug through old issues and am not seeing a lot of prior art, but would greatly appreciate a 👍 / 👎 if I'm reinventing the wheel on this.

Thanks everyone!

**Comment by iandees** [comment]
You might look at what the Pelias project does with OpenAddresses data in https://github.com/pelias/openaddresses.

**Comment by rbrtmrtn** [comment]
That's a great pointer, thanks @iandees!
