### ISSUE TITLE
Dot map on home page is missing some Pennsylvania counties

### ISSUE THREAD

**Issue by bertday** [openaddresses/openaddresses#6238]
Hello!

This is a minor flag — I noticed that Indiana County, PA has [all successful runs](https://batch.openaddresses.io/data/2847/history) in batch, but doesn't show any address points on the dot map at openaddresses.io:

![Screenshot 2023-01-31 at 6 21 24 PM](https://user-images.githubusercontent.com/1463553/215914249-da4e1297-3fcd-4bb0-ba44-379021f37d87.png)

It looks like Bradford is empty too, despite having a healthy history (it's the polygon where Towanda is):

![Screenshot 2023-01-31 at 6 23 43 PM](https://user-images.githubusercontent.com/1463553/215914624-264b3138-2d5c-4ef3-9917-2d8106e22b0f.png)

I'm still getting to know OpenAddresses so not sure yet what troubleshooting I can do as a contributor, but please let me know if I can help!

**Comment by arch0345** [comment]
https://github.com/openaddresses/openaddresses.io might be a better place for this issue

**Comment by bertday** [comment]
This has been superseded by the discussion over at openaddresses/batch#375 — will close it out!
