### ISSUE TITLE
Building sources + contact info

### ISSUE THREAD

**Issue by rbrtmrtn** [openaddresses/openaddresses#6243]
Hello!

I tried pushing an update that added a `contact` to a building source and I got an [error](https://app.circleci.com/pipelines/github/openaddresses/openaddresses/3583/workflows/a74b1593-470a-4e70-bf7c-d500c408e28d/jobs/5095) in CircleCI that it was an additional keyword and not allowed. I removed it and the tests passed. Barring me fat-fingering something with the JSON... is it correct that building sources shouldn't have a `contact`? If so, just curious what makes them different in that regard from addresses and parcels. Will keep this in mind going forward 😄

**Comment by iandees** [comment]
Looks like an oversight in our jsonschema. The [address](https://github.com/openaddresses/openaddresses/blob/master/schema/layers/address.json#L45-L47) file has contact but the [building](https://github.com/openaddresses/openaddresses/blob/master/schema/layers/building.json) does not.

**Comment by rbrtmrtn** [comment]
Awesome, thanks for taking a look @iandees! I made a PR in case it's an easy change. Not sure if there are bigger side-effects that need to be thought through.
