### ISSUE TITLE
McKean County, PA missing data

### ISSUE THREAD

**Issue by rbrtmrtn** [openaddresses/openaddresses#6245]
https://batch.openaddresses.io/data/1787/history

Notable drops in address count:
- 3/3/2021: ~34,000 => ~22,000
- 10/7/2022: ~22,000 => ~400

h/t @n-fink for catching this

**Comment by rbrtmrtn** [comment]
It looks like parcel counts have dropped too:

https://batch.openaddresses.io/data/2816/history

12/10/2021: ~27,000 => ~4,600

**Comment by rbrtmrtn** [comment]
McKean's [parcel viewer](https://mckeancounty.maps.arcgis.com/apps/webappviewer/index.html?id=ff364c1ccc574a7180bad671eb47ec78) seems to be displaying all addresses:

https://gismaps.mckeancountypa.org/arcgis/rest/services/BasicParcelViewer2/MapServer/1

<img width="442" alt="image" src="https://user-images.githubusercontent.com/1463553/216458912-033c12e3-2dc4-4c1d-9f37-3c1919ecda60.png">

This is calling the same Esri REST service as what's [currently](https://github.com/openaddresses/openaddresses/blob/master/sources/us/pa/mckean.json#L17) in OpenAddresses. So, at first glance it doesn't seem to be an issue with the source data. Could it be a rate-limiting issue, or something like that? I'm having trouble viewing the logs for the most recent runs for McKean but will create a separate issue for that 🧐

**Comment by rbrtmrtn** [comment]
Hello @iandees ! Would it be possible to rerun this job:

https://batch.openaddresses.io/job/314795

so we have some fresh logs? I hope to figure out why this job is returning zero rows that way. Thank you!!

**Comment by iandees** [comment]
Hit the rerun button!

**Comment by rbrtmrtn** [comment]
Thanks @iandees! I'm still not able to see a rerun job — are you on your end?

https://batch.openaddresses.io/data/1787/history

**Comment by rbrtmrtn** [comment]
Doing some more digging — it looks like this was updated not too long ago in #6099. Now the source:

https://gismaps.mckeancountypa.org/arcgis/rest/services/BasicParcelViewer2/MapServer/1

is throwing an error:

> Could not access any server machines. Please contact your system administrator.

I'll try this again next week and see if it's back up and running. Otherwise, may need to reach out to someone at the county.

**Comment by rbrtmrtn** [comment]
OK, sure enough, server was just offline for the weekend 😆 Now that it's back up I poked around and realized some of the field names had changed, so hopefully that restores the attributes.
