### ISSUE TITLE
[update] Mifflin County, PA

### ISSUE THREAD

**Issue by rbrtmrtn** [openaddresses/openaddresses#6260]
The current source for Mifflin County, PA:

http://gis.co.mifflin.pa.us/arcgis/rest/services/parcel_program/MapServer/5

is not working. The city has an Everything Bagel viewer (_moment of appreciation they have an everything bagel viewer_):

https://gisportal.co.mifflin.pa.us/portal/apps/webappviewer/index.html?id=103267933af14019b82af229f22fc644

that has parcels:

https://gisportal.co.mifflin.pa.us/arcgis/rest/services/Hosted/parcels_020223/FeatureServer/0

and on the same server there are buildings:

https://gisportal.co.mifflin.pa.us/arcgis/rest/services/Hosted/buildings_020223/FeatureServer/0

**Comment by iandees** [comment]
This seems to require a username/password.
