### ISSUE TITLE
Canada data collection URL points to global download, it should point to Canada data collection

### ISSUE THREAD

**Issue by diegoripley** [openaddresses/openaddresses#6368]
When I click on the "ca" collection on [1] it points to [2]. Instead, this link should point to [3].

[1] https://batch.openaddresses.io/data
[2] https://v2.openaddresses.io/batch-prod/collection-global.zip
[3] https://v2.openaddresses.io/batch-prod/collection-ca.zip

**Comment by arch0345** [comment]
This seems to have been fixed now

**Comment by iandees** [comment]
Great, I think this was fixed in https://github.com/openaddresses/batch/pull/334

**Comment by diegoripley** [comment]
Thank you guys!
