### ISSUE TITLE
[Update] Allegheny County, PA, US

### ISSUE THREAD

**Issue by saylorsd** [openaddresses/openaddresses#6371]
The  data for Allegheny County is stale.  [According to the Western PA Regional Data Center](https://data.wprdc.org), who works with Allegheny County to publish their open data, the current authoritative source is pasda.psu.edu. 

## Address Points
[WPRDC Page](https://data.wprdc.org/dataset/allegheny-county-addressing-address-points2)
**[PADSA Page](https://www.pasda.psu.edu/uci/DataSummary.aspx?dataset=1219)**

## Parcel Boundaries
[WPRDC Page](https://data.wprdc.org/dataset/allegheny-county-parcel-boundaries1)
**[PADSA Page](https://www.pasda.psu.edu/uci/DataSummary.aspx?dataset=1214)**

## Building Footprints
https://www.pasda.psu.edu/uci/DataSummary.aspx?dataset=1195

**Comment by rbrtmrtn** [comment]
Hello @saylorsd ! I updated the data source for Allegheny a few months back in #6241. I think that fixed the issue with missing features, if you look at the far right of this chart:

![image](https://user-images.githubusercontent.com/1463553/232936844-9bf2cc61-fc1f-4bde-ae8c-51d5fd8fe52f.png)
(source: https://batch.openaddresses.io/data/1852/history)

Not personally opposed to switching to PASDA, but just wanted to flag that I think there may be a separate issue that's preventing the fresh data from making its way to the bulk downloads. When I fetch the US Northeast package I'm still seeing low feature counts for Allegheny, despite the fix.

**Comment by saylorsd** [comment]
Thanks @rbrtmrtn for the thorough follow-up! It sounds like I should wait to see what happens with #6376 before seeing if it's worth updating the sources.

**Comment by saylorsd** [comment]
I'm going to close since the current data sources are now working per https://github.com/openaddresses/openaddresses/issues/6376#issuecomment-1517197730.
