### ISSUE TITLE
us-wy-cheyenne

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#638]
Cheyenne  
http://www.clcgisc.com/Downloads/GISDataDownload.htm

**Comment by nvkelso** [comment]
These are shapefile downloads (address points).

**Comment by nvkelso** [comment]
On the map now, closing.

<img width="340" alt="screen shot 2017-07-25 at 20 32 04" src="https://user-images.githubusercontent.com/853051/28603359-5f37ffdc-7178-11e7-8009-7f1f4c1e740c.png">
