### ISSUE TITLE
us-wy-sublette

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#642]
Sublette County 
http://www.sublettewyo.com/index.aspx?NID=182

**Comment by nvkelso** [comment]
Might not be needed anymore with Add Wyoming statewide parcels (#2132) landing.

**Comment by nvkelso** [comment]
Confirmed we have coverage in this county now via state-wide source, closing.

<img width="702" alt="screen shot 2017-04-07 at 12 18 17" src="https://cloud.githubusercontent.com/assets/853051/24816090/57190e14-1b8c-11e7-9d05-250fbdffa472.png">
