### ISSUE TITLE
Can you set an attribute to a constant value?

### ISSUE THREAD

**Issue by rbrtmrtn** [openaddresses/openaddresses#6424]
Hello!

I'd like to concatenate address fields to get as close to a postal address as possible, but I'm noticing that quite a few sources are missing things like `region` (makes sense — it's probably very clear to the authors of this data what state they're in, etc. 😄)

Is it possible to set an attribute to a constant value which a) you know ahead of time, and b) will always be the same?

**Comment by rbrtmrtn** [comment]
Ah, forgot to search the issues. Looks like this is covered by #1515 and has some support. I might take a stab at it if you're still in favor @iandees — will close this as a dupe for now.

**Comment by iandees** [comment]
Yep, a `constant` function probably makes sense. This would be a change in `batch-machine` and a change to the schema in here.
