### ISSUE TITLE
us-pa-bedford

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#646]
http://www.bedfordcountypa.org/ 
Bedford County GIS

**Comment by geobrando** [comment]
No GIS data. Contacted Direct of Planning Commission.

**Comment by justinelliotmeyers** [comment]
https://services2.arcgis.com/tXFMtuwRfEDEFdnG/ArcGIS/rest/services/Bedford_County_Addresses/FeatureServer/0

**Comment by justinelliotmeyers** [comment]
@ingalls newer source than what we have and pulls more addresses. Current source: http://results.openaddresses.io/sources/us/pa/bedford
