### ISSUE TITLE
Autorisation pour le téléchargement 

### ISSUE THREAD

**Issue by 5212BABA** [openaddresses/openaddresses#6481]
Bonjour les administrateur et les contributeurs j'ai besoin d'autoriser mon compte pour le le téléchargement de données @mcolyer @sesam @palewire @s01ipsist @s01ipsist

**Comment by iandees** [comment]
You can sign up at batch.openaddresses.io to download data.

**Comment by 5212BABA** [comment]
J'ai déjà créer mon compte mais on me demande de demander l'autorisation
auprès d'un administrateur

**Comment by iandees** [comment]
When you sign up, you will receive an email asking you to confirm your email address. Click the link in that email and you should be authorized.
