### ISSUE TITLE
Données brutes json

### ISSUE THREAD

**Issue by 5212BABA** [openaddresses/openaddresses#6484]
{
	"type": "FeatureCollection",
	"generator": "overpass-ide",
	"copyright": "The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.",
	"timestamp": "2023-06-05T01:07:32Z",
	"features": [{
			"type": "Feature",
			"properties": {
				"@id": "node/8479208384",
				"ford": "yes"
			},
			"geometry": {
				"type": "Point",
				"coordinates": [
					-10.1965228,
					11.7315962
				]
			},
			"id": "node/8479208384"
		},
		{
			"type": "Feature",
			"properties": {
				"@id": "node/10784217938",
				"addr:city": "Tomba kanssa",
				"name": "C.rural de tomba kanssa Baba taré",
				"office": "government",
				"survey:date": "2023-04-28"
			},
			"geometry": {
				"type": "Point",
				"coordinates": [
					-10.1893277,
					11.7216037
				]
			},
			"id": "node/10784217938"
		},
		{
			"type": "Feature",
			"properties": {
				"@id": "node/10815709015",
				"ford": "yes"
			},
			"geometry": {
				"type": "Point",
				"coordinates": [
					-10.1956897,
					11.7239363
				]
			},
			"id": "node/10815709015"
		},
		{
			"type": "Feature",
			"properties": {
				"@id": "node/10821302816",
				"admin_level": "8",
				"name": "Tomba kanssa",
				"place": "town",
				"source": "GNS;aerial imagery;Wikipédia;local knowledge",
				"wikidata": "Q116464161",
				"wikipedia": "en:Tomba Kanssa"
			},
			"geometry": {
				"type": "Point",
				"coordinates": [
					-10.1890993,
					11.7285422
				]
			},
			"id": "node/10821302816"
		},
		{
			"type": "Feature",
			"properties": {
				"@id": "node/10856413401",
				"ford": "yes"
			},
			"geometry": {
				"type": "Point",
				"coordinates": [
					-10.1983001,
					11.7248511
				]
			},
			"id": "node/10856413401"
		},
		{
			"type": "Feature",
			"properties": {
				"@id": "node/10856421817",
				"ford": "yes"
			},
			"geometry": {
				"type": "Point",
				"coordinates": [
					-10.1971811,
					11.7245052
				]
			},
			"id": "node/10856421817"
		},
		{
			"type": "Feature",
			"properties": {
				"@id": "node/10947493273",
				"addr:city": "Tomba kanssa",
				"air_conditioning": "no",
				"amenity": "place_of_worship",
				"name": "grande Mosquée",
				"religion": "muslim"
			},
			"geometry": {
				"type": "Point",
				"coordinates": [
					-10.1894166,
					11.725703
				]
			},
			"id": "node/10947493273"
		}
	]
}

**Comment by 5212BABA** [comment]
Comment ajouter les données brutes json dans la base de données @mcolyer @sesam @s01ipsist

**Comment by iandees** [comment]
OpenAddresses only fetches data from official sources. It can not pull data from OpenStreetMap as the license is too restrictive.

**Comment by 5212BABA** [comment]
How to find official openAddress data?  Like the one from openstreetmap @iandees

**Comment by iandees** [comment]
Work with your local government to have them post address data on the internet.
