### ISSUE TITLE
us-pa-carbon (Jim Thorpe)

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#651]
http://www.carboncounty.com/GIS.htm Carbon County GIS

**Comment by geobrando** [comment]
No data available.  Emailed the GIS coordinator.

**Comment by geobrando** [comment]
See response from county: https://gist.github.com/geobrando/22cf00420eee2a42ac3a

**Synopsis** - County has no open data policy and does not seem sympathetic to the OA mission.  Dissemination would likely come with a restrictive license anyway

**Comment by iandees** [comment]
These are the kind of places I would love to FOIA... They have the data but don't want to give it out until they get something in return.

**Comment by geobrando** [comment]
I responded kindly with a couple examples of potential benefits to the county and their constituents but don't expect anything to come of it.

**Comment by nvkelso** [comment]
County seat is Jim Thorpe, decent sized town.

**Comment by nvkelso** [comment]
Looks like this has data:

http://services.arcgis.com/zIzHhk5p87uNK9TM/ArcGIS/rest/services/CountyCo_Parcels/FeatureServer/0

Found via https://github.com/openaddresses/openaddresses/issues/1978#issuecomment-283331059.

<img width="1098" alt="screen shot 2017-03-01 at 15 14 54" src="https://cloud.githubusercontent.com/assets/853051/23485824/0fa61458-fe92-11e6-896c-a79dcda903b0.png">

**Comment by justinelliotmeyers** [comment]
https://carbongis.maps.arcgis.com/home/index.html

**Comment by justinelliotmeyers** [comment]
https://gis.carboncounty.com:6443/arcgis/rest/services/Address_Points_2019/FeatureServer/0

**Comment by justinelliotmeyers** [comment]
@iandees or @ingalls can we do this one as well?  gracias amigos!
