### ISSUE TITLE
us-pa-delaware

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#657]
http://www.co.delaware.pa.us/planning/gisinfoservices/geninfo.html Delaware County GIS

**Comment by geobrando** [comment]
May offer addresses under "Other data" but at a price

http://www.co.delaware.pa.us/planning/gisinfoservices/digitalpricelist.pdf

**Comment by nvkelso** [comment]
This needs a fresh look.

**Comment by justinelliotmeyers** [comment]
hello!
https://dcgis.co.delaware.pa.us/arcgis/rest/services/Hosted/Delaware_County_Parcels/FeatureServer/0

![d](https://user-images.githubusercontent.com/5324316/92671272-cb44c080-f2e3-11ea-9181-7c940d85f3ac.jpg)

**Comment by justinelliotmeyers** [comment]
@iandees or @ingalls can we get this one going? wayyyy in the backlog and want to fix it if we can. Thanks amigos!
