### ISSUE TITLE
us-pa-fulton

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#659]
http://gis.co.fulton.pa.us/ Fulton County GIS

**Comment by geobrando** [comment]
Registering only gives access to a god awful Flex map

**Comment by slibby** [comment]
Parcel map service is here: http://gis.co.fulton.pa.us/arcgis/rest/services/WebToolMap/MapServer/6

**Comment by slibby** [comment]
tracked and added here: https://github.com/openaddresses/openaddresses/blob/master/sources/us/pa/fulton.json
