### ISSUE TITLE
Docs link broken

### ISSUE THREAD

**Issue by AaronMBMorse** [openaddresses/openaddresses#6669]
To reproduce issue
1. Open https://batch.openaddresses.io/data 
2. Press on the docs button on the nav bar (https://batch.openaddresses.io/docs)

**Comment by davidtorosyan** [comment]
Opened an issue in the batch repo which actually hosts the site (https://github.com/openaddresses/batch/issues/356).

**Comment by ingalls** [comment]
Closing in favour of the Batch Repo Issue. This will be fixed by end of day.
