### ISSUE TITLE
[update] Adams County, IL

### ISSUE THREAD

**Issue by bertday** [openaddresses/openaddresses#6672]
Attribute names have changed. Sample rows [here](https://www.adamscountyarcserver.com/adamscountyarcserver/rest/services/Adams_County_Basemap_Complete/MapServer/1/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&having=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&historicMoment=&returnDistinctValues=false&resultOffset=&resultRecordCount=10&queryByDistance=&returnExtentOnly=false&datumTransformation=&parameterValues=&rangeValues=&quantizationParameters=&f=html) (scroll down past form fields).

**Comment by Vainock** [comment]
If you are still around, do you remember what exactly this was about? I'm unsure at what to look at on the page you linked.

**Comment by iandees** [comment]
The link is a sample of the data in the Adams County, IL source. The source file needs to get updated with the new column names.

**Comment by Vainock** [comment]
Already fixed by https://github.com/openaddresses/openaddresses/pull/7126, this issue can be closed. That's why I was confused.
