### ISSUE TITLE
us-ak-ketchikangateway_borough

### ISSUE THREAD

**Issue by aferlitsch** [openaddresses/openaddresses#677]
Streets and Street Centerlines

https://ak-ketchikangatewayborough.civicplus.com/196/GIS-Maps

**Comment by slibby** [comment]
I reached out to the Ketchikan Gateway Bureau GIS alias on October 20, 2015 - no reply yet.

**Comment by justinelliotmeyers** [comment]
currently have a source: http://results.openaddresses.io/sources/us/ak/ketchikan
