### ISSUE TITLE
au-sa-heritage-places

### ISSUE THREAD

**Issue by sbma44** [openaddresses/openaddresses#681]
Southern Australia maintains a registry of "heritage places" that achieves useful density in some areas and is licensed under CC-BY. 

https://www.sa.gov.au/topics/housing-property-and-land/building-and-development/land-supply-and-planning-system/planning-data-for-research-and-mapping/spatial-data-downloads#title1

for a tabular example:
http://apps.planning.sa.gov.au/HeritageSearch/SearchResultPage.aspx?p_searchtype=LOCATION&p_suburb=ADELAIDE&p_lga=ALL&p_class=ALL

visual sample of Adelaide:
http://f.cl.ly/items/1Z3t0O0I291f0r28452z/Image%202014-10-29%20at%204.25.36%20PM.png

**Comment by ingalls** [comment]
Going to close this since the GNAF release should cover these.
