### ISSUE TITLE
swiss data

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#691]
switzerland published this recently, although idk if it helps because i don't speak french or german.
http://www.geo.admin.ch/internet/geoportal/de/home/topics/geobasedata.html

**Comment by katossky** [comment]
The addresses for *Canton de Vaud* are available for consultation [here](http://www.geo.vd.ch/theme/localisation_thm) but [the link to the data provider](http://www.asitvd.ch/md/609) seems to be dead at the moment of my writing.

**Comment by sergiyprotsiv** [comment]
The data costs 80 CHF (which is manageable I suppose), but I do not expect the data to be shareable (the license is in French and seems to imply that the data is not transferrable).

**Comment by katossky** [comment]
Where have you found this information?

**Comment by sergiyprotsiv** [comment]
@katossky I followeed the second link you posted and tried to order the data. It's pretty clear thhat redistribution to third parties is not allowed... https://dwa.vd.ch/prod/dinf/publicationdinf1_p.nsf/NORM/AB33A0F2E5159579C125712B0044F3F6/$FILE/8401.pdf?OpenElement

**Comment by justinelliotmeyers** [comment]
we now have it - closing issue
