### ISSUE TITLE
uk addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#6967]
I'm going to attempt to build out a public domain dataset of address points for the uk. loose plan:
get three or more sources of address point data. mash and derive one point per agreed upon situs address within a tolerance. create a new unique point in space (x,y) and share openly.
Bad Idea I'm moving forward with:
Asking companies who charge hundreds of thousands/ millions of dollars to give me their data for free to do this.
Will create new plan if they say no or i dont get three sources.

Please give feedback about why this is a bad idea or the greatest idea.

**Comment by iandees** [comment]
I think it's a great idea, as long as you can convince these companies to give you the data without any licensing terms that prevent you from redistributing it.

**Comment by justinelliotmeyers** [comment]
Need to get UK data, but need a better thought out plan vs this idea.
