### ISSUE TITLE
Official addresses for Austria

### ISSUE THREAD

**Issue by StephanGeorg** [openaddresses/openaddresses#7071]
The provided source for Austria is outdated and not available anymore.

There is a new source available:

+ WEBSITE: https://geometadatensuche.inspire.gv.at/metadatensuche/srv/ger/catalog.search#/metadata/bd28c2b0-4ea5-41c2-8847-b7e8711a6512
+ DATA: https://data.bev.gv.at/download/Adressregister/AT-INSPIRE_AD_Address_CSV_20231022.zip
+ LICENSE: [CC BY 4.0 DEED](https://creativecommons.org/licenses/by/4.0/)
+ ATTRIBUTION: **© Österreichisches Adressregister, Stichtagsdaten vom TT.MM.JJJJ**

Address information is distributed across several CSV files. I used [duckdb](https://duckdb.org/) to merge the data and transform the geometries:

```sql
LOAD spatial;

-- source https://geometadatensuche.inspire.gv.at/metadatensuche/srv/ger/catalog.search#/search?resultType=details&sortBy=relevance&any=Adresse%20Relationale%20Tabellen&fast=index&_content_type=json&from=1&to=20

CREATE temp TABLE addresses AS FROM (
  SELECT 
    a.ADRCD
    , a.HNR_ADR_ZUSAMMEN
    , a.HAUSNRTEXT
    , a.HAUSNRZAHL1
    , a.HAUSNRBUCHSTABE1
    , a.HAUSNRVERBINDUNG1
    , a.HAUSNRZAHL2
    , a.HAUSNRBUCHSTABE2
    , a.HAUSNRBEREICH
    , a.HOFNAME
    , s.STRASSENNAME
    , s.STRASSENNAMENZUSATZ
    , s.SZUSADRBEST
    , s.ZUSTELLORT
    , o.ORTSNAME
    , g.GEMEINDENAME
    , a.PLZ::varchar as PLZ
    , a.EPSG
    , ST_Point(a.HW::double, a.RW::double) AS "geometry"
    , 0.0::double AS "lat"
    , 0.0::double AS "lon"
  FROM 
    'ADRESSE.csv' a
    LEFT JOIN  'STRASSE.csv' s ON a.SKZ = s.SKZ
    LEFT JOIN 'ORTSCHAFT.csv' o ON a.OKZ = o.OKZ
    LEFT JOIN 'GEMEINDE.csv' g ON a.GKZ = g.GKZ
);

-- transform coordinates
UPDATE addresses SET geometry = ST_FlipCoordinates(ST_Transform("geometry", 'EPSG:31254', 'EPSG:4326')) WHERE EPSG = '31254';
UPDATE addresses SET geometry = ST_FlipCoordinates(ST_Transform("geometry", 'EPSG:31255', 'EPSG:4326')) WHERE EPSG = '31255';
UPDATE addresses SET geometry = ST_FlipCoordinates(ST_Transform("geometry", 'EPSG:31256', 'EPSG:4326')) WHERE EPSG = '31256';

-- fix empty data
UPDATE addresses SET HAUSNRBEREICH = NULL WHERE HAUSNRBEREICH = 'keine Angabe';
UPDATE addresses SET lat = ST_Y("geometry"), lon = ST_X("geometry");

-- Export data with
-- COPY(SELECT * EXCLUDE(EPSG, "geometry") FROM addresses) TO 'AT-addresses.csv';
```

How can I proceed to make this data available with openaddresses? 
FYI @justinelliotmeyers

**Comment by iandees** [comment]
Can you please upload to Dropbox and I'll work on getting it available for use with an OpenAddresses source.

https://www.dropbox.com/request/rUcmasTnxZkiDR6rJc4l

**Comment by StephanGeorg** [comment]
1. **AT-addresses.csv.zip**: https://github.com/openaddresses/openaddresses/pull/7079
2. **hk-bb.zip**: https://github.com/openaddresses/openaddresses/pull/7049

**Comment by iandees** [comment]
Uploaded to:

s3://data.openaddresses.io/cache/uploads/StephanGeorg/c12cc8/AT-addresses.csv.zip
