### ISSUE TITLE
Slovenia countrywide lost about half of its streets

### ISSUE THREAD

**Issue by bertday** [openaddresses/openaddresses#7091]
https://batch.openaddresses.io/data/591/history#map=5.84/45.717/16.54

![image](https://github.com/openaddresses/openaddresses/assets/1463553/56ad505d-7b04-48c7-bdd7-530b6a481967)

Last run with streets intact was Jan 25, 2023, which coincides with the last commit affecting this source (9d033d76882a812193622768fe47989e8aa664e5). So this seems like an upstream data issue.

Kindly throwing this on your radar @stefanb, if you happen to see anything amiss! 😄

**Comment by stefanb** [comment]
Ah yes, in smaller places (villages) there are no streets and the source CSV column is empty there since beginning of march. See announcement on 2024-02-05 on: https://ipi.eprostor.gov.si/jgp/notifications

The empty street field should get the value from the name of the village in such cases.

**Comment by bertday** [comment]
Nice sleuthing work @stefanb. I don't personally know of a way to default from one field to another if one is null, but perhaps it's possible. Otherwise maybe it would require a script?

Good to have documented what happened with the source data, in any case.

**Comment by bertday** [comment]
Edit: I forgot there _is_ a function that iterates over fields until it finds a not-null one! Referenced in #6425.

**Comment by stefanb** [comment]
It seems that the `first_non_empty` function isn't passing the regexp validation:

````
Schema validation errors were encountered.
  sources/si/countrywide.json::$.layers.addresses[0].conform.street: {'function': 'first_non_empty', 'fields': ['ULICA_NAZIV', 'NASELJE_NAZIV']} is not valid under any of the given schemas
  Underlying errors caused this.

  Best Match:
    $.layers.addresses[0].conform.street: 'field' is a required property
  Best Deep Match:
    $.layers.addresses[0].conform.street.function: 'first_non_empty' is not one of ['regexp']
````

**Comment by iandees** [comment]
The first_non_empty function is documented now.

**Comment by bertday** [comment]
Thanks for the quick implementation + documentation @iandees!

**Comment by stefanb** [comment]
@iandees, the pre-commit validation succeeds, but batch is still failing, see last run of #7094 : https://batch.openaddresses.io/run/2989
