### ISSUE TITLE
Bayfield County, Wisconsin

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#7097]
Currently getting clear terms of use/ copyright information from the county. Spoke to Carmen Novak (715-373-3426) today. Data lives in rest services. Need to find addresses, but will clear up with back and forth in formal email process about copyright.
Main rest: https://maps.bayfieldcounty.wi.gov/ArcGIS/rest/services/BayfieldCoBaseMap/MapServer
Addresses:
Buildings: https://maps.bayfieldcounty.wi.gov/ArcGIS/rest/services/BayfieldCoBaseMap/MapServer/0
Parcels: https://maps.bayfieldcounty.wi.gov/ArcGIS/rest/services/BayfieldCoBaseMap/MapServer/14
Copyright: 

Will update. Stay tuned!

Carmen Novak

GIS Technician | Bayfield County Land Records

715-373-3426 | [Carmen.Novak@bayfieldcounty.wi.gov](mailto:Carmen.Novak@bayfieldcounty.wi.gov)

Email sent:
Carmen,
Thanks for the call today! Brief recap/ overview and a few questions. I am participating in an opensource project Openaddresses. I am one of the many people out there looking for data for addresses, buildings and parcels to add to the dataset/ project. The project heavily relies on open data and clear copyright/ terms of use. We try to find the best official resources that have consistent updates. In the past I've emailed you or Scott about parcels, and more recently your team has put together the rest services (*thank you*). So we would like to use the data from there for the project: https://maps.bayfieldcounty.wi.gov/arcgis/rest/services/BayfieldCoBaseMap/MapServer

The project is here: https://openaddresses.io/Github here: https://github.com/openaddresses/

Again, we would love to use the counties data in the project. I'd like to confirm/ clarify the terms of use or copyright on the data. One county I always look to for understanding this is Dakota County, Minnesota: https://resources.gisdata.mn.gov/pub/gdrs/data/pub/us_mn_co_dakota/plan_parcels/metadata/metadata.html
but there are so many variations of licenses: https://creativecommons.org/share-your-work/cclicenses/

so the questions:1)does the county have address points in the rest services somewhere?2)can you somehow update your site or within the rest services/ maps to clarify the terms of use/ copyright?

If you have any questions for me, please ask. Again, really appreciate your team putting these layers together and always helping me with data!
Thanks,Justin

**Comment by iandees** [comment]
FYI @justinelliotmeyers, Github doesn't send email notifications when a field is edited in the issue. Can you add updates as comments in the future so I get the email? Thank you sir!

**Comment by justinelliotmeyers** [comment]
Carmen followed up:
Hi Justin,
We are still looking into a copyright addition/clarification on the website, but I wanted to follow up on your second question on the address data published service, which is available here: https://maps.bayfieldcounty.wi.gov/ArcGIS/rest/services/BayfieldCoBaseMap/MapServer/0.
Thanks!
Carmen Novak

**Comment by justinelliotmeyers** [comment]
![Screenshot_20240904_163952_Gmail](https://github.com/user-attachments/assets/5bfab5bf-93a1-416a-8705-04569b7d361b)


Data is public domain!

**Comment by iandees** [comment]
I updated the buildings. Addresses and parcels were already updated.

**Comment by iandees** [comment]
Thanks for contacting them, too!
