### ISSUE TITLE
Kentucky Statewide Addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#7098]
addresses: https://services3.arcgis.com/ghsX9CKghMvyYjBU/arcgis/rest/services/Ky_911_Site_Structure_Address_Points_gdb/FeatureServer/1
copyright: public domain

**Comment by justinelliotmeyers** [comment]
![Screenshot_20240327_091637_Gmail](https://github.com/openaddresses/openaddresses/assets/5324316/ec7d3e4d-acb1-488d-97d4-64efe1e576e0)

**Comment by justinelliotmeyers** [comment]
Let me know if anything else is needed.  I followed up thanking them and asking about statewide building footprints and parcels. Long shot, but asked.

**Comment by iandees** [comment]
Thanks Justin!

**Comment by justinelliotmeyers** [comment]
1)I added copyright 
2)don't care how we do this but should be named correctly either way. So let me know your thoughts @arch0345

**Comment by justinelliotmeyers** [comment]
Closing, will upload copyright to other page and a few notes. Appreciate you calling this out @arch0345 

Will double check before I start to create new issues, but I did and didnt see anything kentucky state etc - So I'll be more thorough. **attached is why** so, not sure how/ why that is happening?
![Screenshot 2024-03-27 210100](https://github.com/openaddresses/openaddresses/assets/5324316/2ba23bf4-9ba7-441d-b753-58ac86337480)
![Screenshot 2024-03-27 210114](https://github.com/openaddresses/openaddresses/assets/5324316/dac32b15-1b12-4bfc-ab96-15271241540f)


Ideally I want to add new sources and clear copyright. I want to also back apply clear license/ terms of use where we have data. If you have any ideas/ thoughts, please ping me. Thank you!

**Comment by iandees** [comment]
We need to capture the license information in the source data still.

**Comment by justinelliotmeyers** [comment]
@iandees put in here:https://github.com/openaddresses/openaddresses/pull/6965

Let me know if that works or best way to maintain an email confirmation like that.

Thanks 'eh

**Comment by iandees** [comment]
I'll add it in to the source JSON too. Putting it in the ticket is perfect!
