### ISSUE TITLE
Potential Sources & Updated Tests

### ISSUE THREAD

**Issue by ingalls** [openaddresses/openaddresses#716]
As per out decision a few months ago to not include potential sources in the repo, the following don't have data tags and need to be investigated. Also the tests have been updated to require a `data` attribute.

- [x] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/ca-ns.json
- [x] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/ca-on-york.json
- [x] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-az-pima.json
- [x] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-co-adams.json
- [x] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-co-douglas_county.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-fl-pinellas_county.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-fl-tampa.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-fl.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-il-chicago.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-in-fort_wayne.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-ks-riley.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-ks-sedgwick_county.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-ma-boston.json
- [x] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-md-baltimore_city.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-mn-beltrami.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-mn-benton.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-mn-blue_earth.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-mn-brown.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-mn-carlton.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-mn-clearwater.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-mn-cook.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-ne-lincoln.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-nj-woodbridge.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-ny-cattaraugus.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-oh-akron.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-oh-geauga.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-sc-darlington.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-tx-lubbock.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-va-poquoson.json
- [ ] https://github.com/openaddresses/openaddresses/blob/aed30d5001014a9218cd2d4acec5bed79ce447db/sources/us-va-suffolk.json

**Comment by eczajk1** [comment]
Baltimore City had a bad URL.  i found the correct one.  Is it best to just do a new pull request?

**Comment by ingalls** [comment]
@eczajk1 Yeah a PR would be gladly accepted

**Comment by ingalls** [comment]
Stale
