### ISSUE TITLE
us-fl-polk

### ISSUE THREAD

**Issue by colemanm** [openaddresses/openaddresses#721]
Polk County, FL has data published on the web, but can't find anything with addresses. They have a [GIS data downloads page](http://www.polkpa.org/Downloads/DataFiles.aspx) published, but no license info that I can see, either.

I've reached out to [their help desk](pahelpdesk@polk-county.net) and will update with more info if I hear from them.

**Comment by b-may** [comment]
All public data in Florida is public domain unless specifically exempted by FL Statute Chapter 119. GIS data is not exempt.

Polk county address points are available here:

ftp://psftp:psftp2005@psftp.polkfl.com/GIS Data/SitePoints.shp

Site is not responding at the moment, but I grabbed the data from there the other day.

**Comment by ingalls** [comment]
Closing as stale.
