### ISSUE TITLE
us-fl-pasco

### ISSUE THREAD

**Issue by colemanm** [openaddresses/openaddresses#722]
Polygon parcels Pasco county. Address info may need some processing; `number` and `street` are bound up in a single column called `ADDR_1` in the dataset that would need splitting.

```
{
    "coverage": {
        "US Census": {
            "geoid": "12101",
            "name": "Pasco County",
            "state": "Florida"
        },
        "country": "us",
        "state": "fl",
        "county": "Pasco"
    },
    "website": "http://downloads.pascogov.com/",
    "data": "ftp://ftp.pascogov.com/pub/arcshape/pascopcl.zip",
    "license": "Indemnification",
    "year": "2014",
    "type": "ftp",
    "compression": "zip",
}
```

**Comment by colemanm** [comment]
Followed up again with the PA office on download of the data listed [here](https://www.hernandocountygis-fl.us/CentralGISWebsite/Default.aspx?xml=Addressingdl). Will post back with update if I can find where the data's hosted (if it's freely available).

**Comment by b-may** [comment]
Addresses for Pasco county are available in a comma delimited file called physadd.txt located here: ftp://ftp.pascogov.com/pub/appraisal/Physaddrecs.zip

Here is the header:
'PHYS_ID','PHYS_STRNAME','PHYS_DIRECT','PHYS_STRNO','PHYS_SUFFIX','PHYS_CITY_STATE','PHYS_ZIP','PHYS_ZIP4','PHYS_EW','PrimaryAddress' 

Everything is broken out except street type, e.g. HICKS RD is in the PHYS_STRNAME column. The file contains a PIN column for joining to parcel polygons or centroids.

**Comment by justinelliotmeyers** [comment]
https://pascogis.pascocountyfl.net/gisweb/rest/services/Accela/PascoAccela/MapServer/0
