### ISSUE TITLE
Norway country-wide addresses source is invalid

### ISSUE THREAD

**Issue by pheersink** [openaddresses/openaddresses#7270]
Correct open address path: [https://kartkatalog.geonorge.no/metadata/matrikkelen-adresse-leilighetsnivaa/365b0591-b536-42a6-a20d-22e404fbfe55?search=address](https://kartkatalog.geonorge.no/metadata/matrikkelen-adresse-leilighetsnivaa/365b0591-b536-42a6-a20d-22e404fbfe55?search=address)
While you are at it, map _kommunavn_ to _city_

**Comment by iandees** [comment]
It looks like the data is split into a few hundred individual files by region here: https://kartkatalog.geonorge.no/metadata/matrikkelen-adresse-leilighetsnivaa/365b0591-b536-42a6-a20d-22e404fbfe55

Do you know if there's a single file that has everything?

**Comment by pheersink** [comment]
Just tried the link you listed and it all looks like one file to me with many different file download options.

**Comment by pheersink** [comment]
![Capture](https://github.com/openaddresses/openaddresses/assets/8008093/ca914b35-9ca1-475e-9c84-42ce87ee1907)
This is what I'm looking at. You can select the area of interest (whole country), then the projection and file type. It all comes in as one file for me.

**Comment by jwass** [comment]
I downloaded the file and can upload it with a link. Just need to figure out the column mappings.

```
kommunenummer
kommunenavn
adressetype
adressetilleggsnavn
adressetilleggsnavnKilde
adressekode
adressenavn
nummer
bokstav
gardsnummer
bruksnummer
festenummer
seksjonsnummer
undernummer
bruksenhetId
bruksenhetsnummerTekst
offisiellAdresseTekst
offisiellAdresseTekstUtenAdressetilleggsnavn
EPSG-kode
Nord
Øst
postnummer
poststed
grunnkretsnummer
grunnkretsnavn
soknenummer
soknenavn
organisasjonsnummer
tettstednummer
tettstednavn
valgkretsnummer
valgkretsnavn
oppdateringsdato
datauttaksdato
adresseId
uuidAdresse
uuidBruksenhet
atkomstId
uuidAtkomst
atkomstNord
atkomstØst
sommeratkomstId
uuidSommeratkomst
sommeratkomstNord
sommeratkomstØst
vinteratkomstId
uuidVinteratkomst
vinteratkomstNord
vinteratkomstØst
```

**Comment by pheersink** [comment]
Here is my take on how it should fall out:

After some further investigation, it appears that the database called Basisdata_0000_Norge_25833_MatrikkelenAdresseLeilighetsniva_FGDB.gdb found [here](https://kartkatalog.geonorge.no/metadata/cadastre--address-apartment-level/365b0591-b536-42a6-a20d-22e404fbfe55?search=matrikkelen%20adresse%20lei) is probably the one we need to use. Within this feature class - you may want to download in a different format - there is a feature class / data layer called _vegadressbruksenhet_, translated roughly as street address utility unit.

My best guess as to fields to use:

_nummer_ (street / civic number)
_adressenavn_ (street name)
_kommunavn_ (town / city)
_bruksenhetsnummertekst_ (apartment / unit number)
_adresskode_ (postal code)
_offisielladressetekst_ puts the local address altogether in one string (i.e. street name, street number, unit number)

Norwegian address format is street name, street number (with unit number), postal code, city.

**Comment by iandees** [comment]
> You can select the area of interest (whole country), then the projection and file type. It all comes in as one file for me.

Is there a link to download the file directly without going through a process to select which data to download? Our download system won't automatically go through that process and I would prefer to not have a human have to download the new data every time it gets updated.

**Comment by pheersink** [comment]
Don't know of any automatically available download link that doesn't require you to step through the selection process. I right-clicked on the download button and got this [link](https://nedlasting.geonorge.no/api/download/order/223c4529-b116-4b63-96c0-a8e2f2b4ec4d/478ee84b-ab9a-473b-9475-fa6de78be236). Would that work as sort of permanent link?

**Comment by iandees** [comment]
It looks like that URL still works, but usually "shopping cart" style data download systems expire the results after some number of hours, making them hard to use for our system.

**Comment by eisams** [comment]
Not sure how it works, but for reference this is the code that keeps OSM updated against the official data:
https://github.com/NKAmapper/addr2osm

The Norwegian community do not manually edit addresses in OSM, but take it directly from Kartverket (and report errors to them)

**Comment by pheersink** [comment]
Resurrecting this issue. This is how I currently see the Norway addresses:

  1.  The source url listed<http://data.kartverket.no/download/content/elveg-utm-33-hele-landet> in OpenAddresses.io appears to be a dead link.
  2.  Doing a search for Norway addresses rings me to this site<https://kartkatalog.geonorge.no/metadata?text=address&type=dataset> that lists a number of potential address files.
  3.  The best one seems to be Matrikkelen - Adresse Leilighetsnivå<https://kartkatalog.geonorge.no/metadata/matrikkelen-adresse-leilighetsnivaa/365b0591-b536-42a6-a20d-22e404fbfe55?search=address> (Cadastre – Address Apartment Level).
  4.  To download requires picking options in dropdown boxes.
  5.  I downloaded the gdb (there are other formats) and in this gdb is a file called vegadressebruksenhet (“street address use name” or something like that.)
  6.  There are about 3.5 million records in this file and they should be fieldmapped this way:

     *   Number = nummer
     *   Unit = bokstav
     *   Street = addressenavn
     *   City = kommunenavn
     *   Postcode = postnummer

  1.  From what I understand of this email trail @Ian ***@***.***> is that you’re having difficulty automating the download process because of the need to step through all the dropdown choices.

Is this a correct understanding? If so, how can we help you get over this hurdle?

Paul Heersink | Program Manager, Roads and Addresses
Esri Canada | 900-12 Concorde Pl | Toronto ON M3C 3R8
T 416-386-6418 | M 416-577-5069 | esri.ca<http://esri.ca/>

**Comment by jwass** [comment]
@iandees Do you think we're SOL to be able to automate downloading from this site due to the "shopping cart" style download?

**Comment by iandees** [comment]
I don't think we're SOL, but I was looking for a more reliable data download option that doesn't involve us clicking through a form that we can't automate.

Having said that, it looks like the URL from back on July 10th is still working, so maybe these stick around longer than I expected.

**Comment by eisams** [comment]
I just checked the readme of addr2osm and you can find the data here updated as a csv dump here:
https://nedlasting.geonorge.no/geonorge/Basisdata/MatrikkelenVegadresse/CSV/
