### ISSUE TITLE
Updated addresses just release for Canada

### ISSUE THREAD

**Issue by pheersink** [openaddresses/openaddresses#7272]
New data set out today: [https://www150.statcan.gc.ca/n1/pub/46-26-0002/462600022022001-eng.htm](https://www150.statcan.gc.ca/n1/pub/46-26-0002/462600022022001-eng.htm)

Same schema as earlier versions.

**Comment by jwass** [comment]
@pheersink I updated the Canada script I wrote for the new 2024 data. See #7273 

@iandees I can upload the new file if you can provide another dropbox link.

**Comment by iandees** [comment]
Thanks for updating. If you want to use the same Dropbox link go ahead: https://www.dropbox.com/request/rUcmasTnxZkiDR6rJc4l
