### ISSUE TITLE
Bradford:Pennsylvania

### ISSUE THREAD

**Issue by tlpinney** [openaddresses/openaddresses#73]
http://www.epaymentnow.com/assess/bradco/MainPage.htm

Have to pay 50$ a month to access the data. License unknown.

**Comment by nvkelso** [comment]
There's a annual option of $500. We should research if we have rights to the data after the `1 month` window – it if's an access window I'd be fine paying once to get an archived version, and then if we wanted to later we could pay again to cache another machine update.

```
$30 � 14 day unlimited use
$50 � 1 month unlimited use
$500 � 1 year unlimited use
````
