### ISSUE TITLE
us-fl-baker

### ISSUE THREAD

**Issue by colemanm** [openaddresses/openaddresses#730]
Added [this site](http://g2.bakerpa.com/GIS/?GIS) to the raster sources, and also reached out to their [GIS coordinator](http://g2.bakerpa.com/Contact_Us.asp) listed. Tracking this here and will update with response.

**Comment by ingalls** [comment]
Stale - Feel free to reopen if new details emerge.

**Comment by colemanm** [comment]
:+1:

Never heard back. I'm planning to follow back up with several of the rural FL gov't contacts soon, but haven't had time. Will reopen if there's any motion.
