### ISSUE TITLE
us-fl-duval

### ISSUE THREAD

**Issue by colemanm** [openaddresses/openaddresses#734]
Reached out to the [PA office](http://www.coj.net/departments/property-appraiser/contact-us.aspx) for the full address dataset. Added their [web map URL](http://maps.coj.net/website/DuvalMapsSQL/viewer.htm) to the raster sources wiki.

**Comment by b-may** [comment]
The County GIS Department maintains most of the GIS data - its not clear if they have address points or not - need to contact them. Looks like they have building footprints.

I have a recent copy of the parcels and an address file from the Property Appraiser. The PA provides their CAMA data in one big file and its a bit of a PITA to extract info from it. I can provide just the site addresses and pin. The addresses are properly broken out into all components.

**Comment by ingalls** [comment]
Closing as stale.
