### ISSUE TITLE
Merging of datasets

### ISSUE THREAD

**Issue by colemanm** [openaddresses/openaddresses#735]
The data available for [Escambia County, FL](http://www.escpa.org/MapMain.aspx) is available, but in two parts:
- [Parcels](http://www.escpa.org/snapshots/downloads/County/shapefile/Parcel.zip)
- [Owner mailing data](http://www.escpa.org/files/misc/ecpa_mail.zip)

The parcel data doesn't contain the address info, but has geometry (parcel polygons). The mailing data is an address list with no geo information, but could be joined to the parcel data with the folio number. This seems like a challenging thing to build a processing pipeline around. Any thoughts?

**Comment by ingalls** [comment]
Closing as stale
