### ISSUE TITLE
Using a string to define an attribute field

### ISSUE THREAD

**Issue by jeffdefacto** [openaddresses/openaddresses#7442]
Is it possible to define an attribute like city using a string rather than a column? Some of the city based datasets do not have the city name stored within the data itself so I would like to supply that in the json file directly.

**Comment by iandees** [comment]
There is a `constant` function that was added as part of https://github.com/openaddresses/openaddresses/issues/6426. It looks like documentation/schema updates were never completed, though. You can try that out and see what happens. We can adjust documentation/jsonschema, too.

**Comment by jeffdefacto** [comment]
Thanks @iandees. I believe I have the data formatted correctly in the PR below but the build and tests fail. Maybe the schema needs updating first?

https://github.com/openaddresses/openaddresses/pull/7445
