### ISSUE TITLE
Slovakia data in rar format

### ISSUE THREAD

**Issue by jeffdefacto** [openaddresses/openaddresses#7444]
I noticed that the Slovakia datasource was dead and found an updated dataset, however its compressed as a rar which does not seem to be supported. What is the typical approach for dealing with these sorts of situations? Upload and host on OpenAddresses as a zip or csv?

I have a draft PR to utilize the new data here once its usable.
https://github.com/openaddresses/openaddresses/pull/7443

**Comment by iandees** [comment]
Yea, normally it gets rehosted after getting converted from .rar. Is it small enough that you could post it to github as a zip here?

**Comment by jeffdefacto** [comment]
Its slightly too big at 30.9 mb unfortunately but I've tossed it on my own webhosting for now. 

https://jeffu.dev/data/Adresy_kraje_04_2023_UTF8.csv.zip

**Comment by jeffdefacto** [comment]
Closing as complete
