### ISSUE TITLE
us/ms/rankin containing incorrect cities and postalcodes

### ISSUE THREAD

**Issue by AnBowell** [openaddresses/openaddresses#7473]
Currently data for `us/ms/rankin` includes data with the wrong town and state. The street number and street name appear to be correct, along with the actual location of the address. However, the town, state, and zipcode appear to reference a different town in a different state. 

I've taken a quick look at the [Rankin County Map Viewer](https://gis.cmpdd.org/arcgis/apps/webappviewer/index.html?id=2a84c1decebc4733b91fb86c928b402a) with the `Houses` data layer on and it seems some of the data only has a street number and name, so I presume in some cases the filling in of a zipcode, town, and state is going wrong. 

An example can be seen in the processing job: https://batch.openaddresses.io/job/259421 and I've attached some of the problematic data below. The first two have been incorrectly labelled CO.

```
{"type":"Feature","properties":{"hash":"becac994fafb3b9b","number":"600","street":"INDUSTRIAL DR","unit":"","city":"LOUISVILLE","district":"","region":"CO","postcode":" ","id":""},"geometry":{"type":"Point","coordinates":[-90.1535056,32.2084325]}}
{"type":"Feature","properties":{"hash":"a27ded555f4c1d7e","number":"600","street":"INDUSTRIAL DR","unit":"","city":"LOUISVILLE","district":"","region":"CO","postcode":"80027","id":""},"geometry":{"type":"Point","coordinates":[-90.1532658,32.2081806]}}
{"type":"Feature","properties":{"hash":"ced774a346801ef8","number":"520","street":"INDUSTRIAL DR","unit":"","city":"RICHLAND","district":"","region":"MS","postcode":"39218","id":""},"geometry":{"type":"Point","coordinates":[-90.1546102,32.2097352]}}
```

**Comment by iandees** [comment]
Usually this happens because the data we're pulling from has "owner" address info instead of "situs" address.
