### ISSUE TITLE
Add Romania postal zip codes and address

### ISSUE THREAD

**Issue by raku** [openaddresses/openaddresses#802]
Add also Romania postal zip codes from here http://date.gov.ro/dataset/coduri-postale-romania 
This also contains address 
Is licensed unde Open Government License
I hope will help you this resource.

**Comment by romanbilinsky** [comment]
We have more than 1mln address points with coord for Romania and other countries. roman.bilinsky@gmail.com

**Comment by justinelliotmeyers** [comment]
@romanbilinsky amazing! could you tell us more? Source, dates, etc? Should I reopen the ticket?

We appreciate it!
Justin
