### ISSUE TITLE
data.openaddresses.io checking map display

### ISSUE THREAD

**Issue by jmkelly** [openaddresses/openaddresses#809]
Was just wondering how often the data.openaddress.io page is rebuilt?  I've added an ISO code that *should* show up, but as it stands, I have no way of checking / testing.

**Comment by migurski** [comment]
I’m running it twice weekly, typically Tuesdays and Fridays.

**Comment by migurski** [comment]
Also, currently only the country-level ISO codes will show; we’ve only got Admin-0 geography in the repository.

**Comment by jmkelly** [comment]
So as it stands at the moment, the only way to get a sub-country level area to show up on the map is to provide a geojson outline of the region?

**Comment by jmkelly** [comment]
I think I've answered my own question.  Thanks for the tip on ISO codes, I'll go ahead and generate some geojson for the coverage extents.

**Comment by migurski** [comment]
Looks like [Natural Earth might have us covered for Admin-1](http://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-1-states-provinces/); I’ll determine if it’s addable.

**Comment by migurski** [comment]
…if you generate GeoJSON, can you be sure to add the ISO-3166-2 codes as well? Natural Earth doesn't have the complete codes, but it does have space for them and I may add them in a PR.

**Comment by migurski** [comment]
Support for these codes is in-progress at https://github.com/openaddresses/machine/pull/27
