### ISSUE TITLE
Access to the extents of datasets

### ISSUE THREAD

**Issue by jmkelly** [openaddresses/openaddresses#810]
I was wondering if it was possibly to include somewhere (either the repo or on the website) the geojson that links extents to datasets?  I presume this is generated on build, because it shows on the map at data.openaddress.io. That way, given a lat / lon, it would be trivial to determine which datasets are available for a location.

**Comment by migurski** [comment]
That’s actually [what `coverage` is for](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#coverage-object). It’s different from the GeoJSON of address points, because it provides the jurisdiction where addresses are possible.

**Comment by jmkelly** [comment]
I was reading it the wrong way.  I presumed that geojson was only provided if the ISO wasn't.  Makes perfect sense,  I'll just add it as well.

**Comment by migurski** [comment]
Great! GeoJSON is for when we can't find an obvious code for an area. It looks like we'll need to add ISO-3166-2 codes.
