### ISSUE TITLE
Norway (could use a second opinion)

### ISSUE THREAD

**Issue by sbma44** [openaddresses/openaddresses#816]
![image](https://cloud.githubusercontent.com/assets/31717/5606778/cf2e1d12-940d-11e4-9e57-bd63fca71626.png)

Norway has open address point data, available under CC-BY but behind a registration wall:

http://data.kartverket.no/download/content/elveg-utm-33-hele-landet

The archive consists of 400some zipfiles totaling ~685M compressed. This seems to include road geometry and other non-address info, but from the filesize and some investigations in QGIS I'm tentatively optimistic. There is definitely point data, though it might be that many lack street names, forcing us to use "village" or its equivalent a la Poland. 

The archives uses the Norway-specific .SOS format. Thanks to @oeon, I've been able to turn some samples into shapefiles using [sosicon](http://sosicon.espenandersen.no/). One SOSI file can create multiple shapefiles. Plotting the shapefiles in QGIS shows promising-looking points. However, the data's CRS seems to be messed up. 

[Here is the output of `sosicon -stat` for one of the files](https://gist.github.com/sbma44/737ae6f8498f30bbc317). `KOORDSYS 23` indicates (per page 30 of [this PDF](http://www.statkart.no/Documents/Standard/SOSI-standarden%20del%201%20og%202/SOSI%20standarden/del1_2_RealiseringSosiGml_2012-05-02.pdf)) EPSG:25833. I've messed around a bit in QGIS and with `ogr2ogr` but without results. I think my lingering geo n00b status might be showing.

@oeon also pointed me to [gdal-sosi](https://github.com/OSGeo/homebrew-osgeo4mac/) but I've been hesitant to mess with my local GDAL environment just yet.

[Here's a 154k tarball of a representative SOSI file and the two shapefiles that can be generated from it](https://drive.google.com/file/d/0Bz3S9Py_hK86OXZJN091NUFkcUU/view?usp=sharing) with `sosicon`. Anyone feel like having a look? If anyone is able to give me a hand with the coordinate system, I should be able to handle the conversion from there.

**Comment by oeon** [comment]
When I open your sosicon converted .shp's, my QGIS tells me they're EPSG:3006. Yet if I upload the .prj file of your .shp's to http://prj2epsg.org/search it says it's EPSG:25833.

I downloaded the original .sos achives, installed gdal-sosi. Running `ogrinfo -al -so 0101Adresser.SOS` and pasting the WKT piece into http://prj2epsg.org/search tells me it's in EPSG:3045 and converting them with `ogr2ogr -f "esri shapefile" -t_srs EPSG:4326 out.shp 0101Adresser.SOS` seems to line up cleanly with Natural Earth country boundaries.
![screen shot 2015-01-04 at 2 23 20 pm](https://cloud.githubusercontent.com/assets/271851/5607759/4d1783a8-941d-11e4-8132-c50d792cce42.png)

I think `brew tap osgeo/osgeo4mac` will only install gdal-sosi as a plugin and leave your normal homebrew GDAL alone (if that's how you're using GDAL already).

**Comment by sbma44** [comment]
@oeon thank you so much for this! We've just had @kelvinbrokwa start here at Mapbox and I think this import might make a great first-week task now that you've figured out the confusing bits.

**Comment by oeon** [comment]
great work @bsyu1125! I forgot a couple things: we'll need to add a 2 parameters to the ogr2ogr line. I think we want it to be: `ogr2ogr -f csv -lco GEOMETRY=AS_XY -t_srs EPSG:4326 $temp $i`

`-lco GEOMETRY=AS_XY` to add X and Y coordinate columns to the .csv

`-t_srs EPSG:4326` to convert the projection

Example output:

```
X,Y,PUNKT,KOMM,OBJTYPE,GATENR,GATENAVN,HUSNR,POSTNR,POSTNAVN,TRANSID,BOKST
11.390082903909805,59.118884037250723,1:,0101,Gateadresse,1000,Adelgata,1,1767,HALDEN,145098751,
11.390008901777687,59.119088722395944,2:,0101,Gateadresse,1000,Adelgata,3,1767,HALDEN,145098751,
11.38992029881431,59.119266034229277,3:,0101,Gateadresse,1000,Adelgata,5,1767,HALDEN,145098751,
```

**Comment by sbma44** [comment]
awesome. @kelvinabrokwa & I got this running this afternoon, and missing geometry was just where we left things. this'll be great to pick up tmw.

**Comment by sbma44** [comment]
Today's PR was a huge step forward but I think the PR still needs a little love. Here's the output I'm getting:

```
LON,LAT,NUMBER,STREET
11.390082903909805,59.118884037250723,1,1000
11.390008901777687,59.119088722395944,3,1000
11.38992029881431,59.119266034229277,5,1000
11.429537926299012,59.111185424780992,1,1020
11.429905181286575,59.111519132872367,2,1020
11.430005988309595,59.111054493687512,3,1020
11.430328425943006,59.111315056508694,4,1020
11.430508902879785,59.110924520500042,5,1020
11.430913819774025,59.111232296253071,6,1020
```

There are also a few extraneous fields in the `conform` object -- "city", etc. @kelvinabrokwa can you take a look at this?

**Comment by kelvinabrokwa** [comment]
@sbma44 I'm on it.

**Comment by kelvinabrokwa** [comment]
Just one little problem: "GATENAVM" (not "GATENR") should map to "street".

**Comment by bsyu1125** [comment]
Sorry about that!

**Comment by sbma44** [comment]
@bsyu1125 don't sweat it, this is a very minor thing. **thank you** for all the work you put into this.

**Comment by iandees** [comment]
I think this is covered by https://github.com/openaddresses/openaddresses/pull/827 and https://github.com/openaddresses/openaddresses/pull/830, so I'm closing.
