### ISSUE TITLE
Virginia data has gone missing

### ISSUE THREAD

**Issue by waldoj** [openaddresses/openaddresses#819]
[The Virginia address points file](https://github.com/openaddresses/openaddresses/blob/master/sources/us-va.json) should be found at [https://ftp.vgingis.com/Download/VA_SiteAddressPoint.txt.zip](https://ftp.vgingis.com/Download/VA_SiteAddressPoint.txt.zip), but that leads to a 404 now. Thanks to @jalbertbowden and @cornexo for pointing that out.

I have contacted the Virginia Geographic Information Network, who is responsible for the data, to ask what's up, and to offer any help that might be needed.

**Comment by sbma44** [comment]
well that's a drag. anyone have a copy of the source file? we can pop it into /cache if so

**Comment by MiniCodeMonkey** [comment]
Ugh, that's too bad. Hope that it was just a mistake.

Here's a copy of the file from October 31st. https://geocodio-data.s3.amazonaws.com/VA_SiteAddressPoint.txt.zip

**Comment by waldoj** [comment]
VGIN tells me that it's just a mistake. They'll restore it soon. Let's leave this open until it's confirmed to be available.

**Comment by waldoj** [comment]
Not only have they [restored the file](https://ftp.vgingis.com/Download/VA_SiteAddress.txt.zip), but they've set up [a public page advertising its existence](http://vgin.maps.arcgis.com/home/item.html?id=100e5e12ddc14748a5ec3b8b997af13a), which is really great. (Previously, you had to know the URL.) Best of all, they affirm that "as of January 1, 2015, the VGIN Site Address Point database is public domain." Big improvements in Virginia!

**Comment by MiniCodeMonkey** [comment]
This is awesome! :+1:

**Comment by iandees** [comment]
Awesome! Thanks for poking them on this, @waldoj.

**Comment by cornexo** [comment]
Thanks @waldoj. Could you suggest they somehow version the file or filename? No way of easily knowing if the file has been updated since I last processed it.

**Comment by waldoj** [comment]
@cornexo, I think they do provide a date, on [its webpage](http://vgin.maps.arcgis.com/home/item.html?id=100e5e12ddc14748a5ec3b8b997af13a). It says it was last modified on December 8. It's possible that the "last modified" date isn't for the data, but for the page describing the data, but that sure seems like a weird design decision on the part of Esri.

**Comment by iandees** [comment]
The IIS server that is serving the .txt.zip file is reporting a `Last-Modified: Wed, 17 Dec 2014 21:16:38 GMT` header, which seems reasonable.

**Comment by cornexo** [comment]
Exactly my point. Was it Dec 18th? or Dec 17th? Does the modification date show on the webpage refer to when the page was updated or the file? Because currently that info conflicts as Dec 17 9PM GMT is earlier in the day here rather than later.

**Comment by waldoj** [comment]
I'm pretty sure that this is a limitation of ArcGIS, and that this agency can't do anything about it. I'd use the `Last-Modified` header...if only because the web page for the dataset is assembled with Javascript, and consequently difficult to scrape.
