### ISSUE TITLE
2014 Address Pts for US-NC available

### ISSUE THREAD

**Issue by geomantic** [openaddresses/openaddresses#826]
Announced by NC CGIA on 7 Jan via NC GIS listserv:
http://nconemap.com/NCOneMapBlog/tabid/679/EntryId/1037/2014-Address-Points-Now-Available.aspx
Data in the public domain.

**Comment by MiniCodeMonkey** [comment]
This is great news!!

I just looked into this and I'm a little unclear about the license. Here's what the download page says:
```
Constraints: Public Use with Secondary Distribution Constraints
Legal Constraints:
Access Constraints: Other Restrictions
Use Constraints: Other Restrictions
Other Constraints: NCCGIA does not support secondary distribution of this dataset without its current, compliant metadata record.
Security Constraints:
Classification: unclassified
```

Where do they specify that it's public domain?

**Comment by geomantic** [comment]
Hm...not certain. Nor am I an attorney. It is my understanding and experience that all data collected & maintained by governments in NC are placed in the public domain. Is the reqt for inclusion of the NCCGIA metadata record to insure the provenance of data is passed with any redistribution?

**Comment by iandees** [comment]
I feel pretty comfortable with including all government-sourced address datasets in OpenAddresses as "Public Domain". Addresses and their locations are fact and thus not copyrightable, so as long as we're not breaking any contract law by accessing the data (which is hard to do when there's a direct download link), then I think we're ok.

**Comment by iandees** [comment]
All (United States or United States municipal) government-sourced, that is.

**Comment by sbma44** [comment]
@iandees I agree with the upshot of your argument for the project but at the risk of being horribly pedantic: the public domain guarantee only obtains for U.S. federal data. Many states assert copyright over their geodata (and even laws). There's [encouraging movement on this front](http://www.gislounge.com/california-supreme-court-rules-that-gis-data-are-public-record/) but it's very much a state-by-state process.

(I'd be careful about that interpretation of Feist v. Rural, too. But in general I think we can expect to get a nastygram if we accidentally add any closed data, and as long as we hustle to correct the problem there shouldn't be any damage done.)

**Comment by iandees** [comment]
I think for the purposes of this project at this point we should consider all addresses and their locations as facts no matter where they are from. I was careful with my words in that comment because in some cases the data has "hidden" contractual restrictions that aren't immediately apparent, but when a government entity in the United States (not just the United States federal government) dumps a list of facts (like addresses) on a website without further click-wrappers or contracts I think this project can safely assume it comes without restriction.

**Comment by geomantic** [comment]
@sbma44 @iandees @MiniCodeMonkey I worked in NC govt for many years and don't believe the state asserts any copyright over the data. In VA, however, the counties do assert a copyright over data[1], though VA too regards the data in the public domain. I'm not entirely clear what this means in practical terms.

http://gis.henrico.us/ExternalViewer/Account/Logon

**Comment by sbma44** [comment]
@iandees I agree with you about how we should go forward, but do think it's important to note that copyright and/or EU database rights don't depend on whether a database is composed of facts. In the US this is inadequately litigated, but the dividing line relates to the creativity involved in the arrangement of the facts. In the EU IP rights attach much more easily.

This is academic for now, but if we get a takedown notice for a source it'll be important to be able to work through this quickly.

**Comment by iandees** [comment]
Yep, totally agree @sbma44. Good summary. :+1:

**Comment by geobrando** [comment]
NC distributes their statewide layer after breaking up into 10 regions

![NC regions](http://www.cgia.state.nc.us/portals/0/images/examples/MADB_regions.jpg)

Data urls from our current sources named us-nc-1 to us-nc-10 point are broken.  These urls need to be edited to point to new files and conform objects edited to reflect their new schema.  CSVs with lat/lon are provided but use a ```|``` separator, which I don't believe is currently supported. Portal is [here](http://www.cgia.state.nc.us/Services/NCMasterAddress/tabid/411/Default.aspx)

Although shapefiles are preferred, they have Esri server with statewide data [here](http://services.nconemap.com/arcgis/rest/services/NC1Map_Location/MapServer/0) which can be added as a single source.

[This](http://data.nconemap.com/geoportal/catalog/search/resource/details.page?uuid=%7B9E039D56-5202-43E7-8D36-D09414C0DBD6%7D) page provides a link to a statewide file but is actually a bunch of zipped shapefiles, CSVs, and a geodatabase.  If this seems to be common practice, we could have add functionality that would process all of the data files of a source from a single download or find a single nested file, which was mentioned in openaddresses/openaddresses-conform#16.  I believe ```file``` currently only accepts a single path.

**Comment by iandees** [comment]
I made #920 to add the ESRI source so we can get the data. It might be faster to just download the 900MB statewide zip file, but it does have a ton of other stuff that we don't care about.
