### ISSUE TITLE
Add France open address from bano project.

### ISSUE THREAD

**Issue by gatemezing** [openaddresses/openaddresses#837]
Hi, I know of the BANO project (cc @cquest) which making something similar just for the French territory. All the data can be downloaded at http://bano.openstreetmap.fr/data/. Maybe both initiatives can joint force?

**Comment by sbma44** [comment]
@gatemezing thanks! We've talked through this before: https://github.com/openaddresses/openaddresses/pull/236

But despite that PR, the maps make it clear that the data isn't presently merged. As you'll see, there are some licensing concerns.

Worth noting: many of BANO's largest datasets are not ODbL licensed, meaning OA could ingest them without trouble.

**Comment by cquest** [comment]
It looks like BANO has been replaced by the less open version of BAN a month ago (https://github.com/openaddresses/openaddresses/commit/2bd51162fad20b7a665f2fa5a21589ea4f2c052a)

**Comment by sbma44** [comment]
Yes @cquest, this was a decision that was made by the project's core contributors. I made the strongest case I could for keeping the dataset free of ODbL but ultimately my argument did not carry the day. However, @migurski has been doing great work laying the foundation for per-license OA downloads, which should minimize the impact of this change.

**Comment by cquest** [comment]
Free from ODbL but fine with **less** open than ODbL content ? Strange...

**Comment by sbma44** [comment]
@cquest the decision was to collect any license that plausible allows reuse under open term and to index them appropriately, rather than making judgments about which open licenses are the most desirable. As I said, I prefer to stake out a stronger position.

**Comment by cquest** [comment]
Some more details...

The "BAN" is available under 2 licences, ODbL and a specific (less open) one. OpenStreetMap France is in charge of publishing the ODbL version.

The one currently appearing here is the second one. Maybe nobody understood the french (only) text of this specific license and its much stronger share-alike terms compared to ODbL..

FYI, I've been in charge of negociating the licensing of this dataset with the geographic instute and the post office so I know its license and content quite well.

Please see also my comment on https://github.com/openaddresses/openaddresses/commit/2bd51162fad20b7a665f2fa5a21589ea4f2c052a

There is another ODbL dataset (BANO) which contains less addresses but is more up to date.
I'm working on merging both.

**Comment by sbma44** [comment]
Tagging @migurski again, as he's the one who handled this. FWIW I would like to bring in the more-open resources that make up these datasets separately -- specifically FANTOIR -- and keep the ODbL sources limited to the few cities that are employing that license specifically and tainting the larger dataset.

**Comment by gatemezing** [comment]
@cquest Good point re the license terms in FR. Could it be possible to add a copy of the license in ENG? I guess this could be useful for other users as well? OK, not pretending ENG is he "universal languqge", but at least we can reach out more users than the-only-FRench version. WDYT?

**Comment by cquest** [comment]
FANTOIR does not contain addresses, nor geographic data. It is only a list of all street and locality names in France.

There is no english version of the BAN specific (non ODbL) licence. The strong "share-alike" is article 4.1 which says something like "licensee will provide an electronic copy of any enriched data back to the licensor every 3 months". There are other problems like: you are not allowed to use this dataset in conjunction with personal private data. By providing the enriched data back you also grant the licensor to freely reuse the data (all of it). etc..

This explain why many opendata advocate in France complained about this licence considering it non open.

**Comment by migurski** [comment]
I have read and re-read this a few times, and I still don’t understand which version of the data has which license.

**Comment by cquest** [comment]
The data you can download after filling a form on adresse.data.gouv.fr is provided with a specific licence.

The data you can download (with a direct link) at http://bano.openstreetmap.fr/BAN_odbl/ is under ODbL.
The difference in the content is:
- 2 fields removed in the ODbL version
- cleaning of street names in the ODbL version
- 2 fields added to relink with the FANTOIR dataset where possible

I'll make a PR to switch if you're ok.

**Comment by NelsonMinar** [comment]
We're still where we were last year when we discussed this in #236; OpenAddresses currently can't accept ODbL licensed data. We've had discussions about creating a special ODbL-only collection so as to not have to license the rest of our data under ODbL, but so far that work has not been done.

Do we have a copy of the license for the data we are currently getting from http://adresse.data.gouv.fr/download/ ? I can't find one on the site without filling out a form with my email address. French is fine.

It's weird we're having this extended conversation on a closed issue.

**Comment by NelsonMinar** [comment]
I found the BAN license; it's at https://adresse.data.gouv.fr/static/pdf/BAN%20Licence%20de%20repartage.pdf

I ran it through Google translate to get rough english: https://gist.github.com/NelsonMinar/b149c59188cc8e75f26e

The Clause 4.1 that @cquest says is a problem translates like this:

> 4.1. Le Licensee agrees to return to the Licensor a complete electronic copy of any enrichment of the NAO every three (3) months following the procedure communicated by the Licensor and available on the website and it publishes provides historical events management in respect of the Parties.

That does sound like a share-alike license. OpenAddresses itself could comply with this easily enough, and may effectively already do so. I'm not sure if our users will want to use data with this license on it.

**Comment by migurski** [comment]
That sounds like share-alike to me as well. I think we’re effectively doing this already, and we should mark the downloads as SA.

**Comment by cquest** [comment]
So, it looks to me like you're blindly accepting a license you don't understand in favor of the ODbL that you do understand but don't like ? Is this some primary anti ODbL thinking or what ?

**Comment by iandees** [comment]
@cquest It sounds like both of these licenses have share-alike provisions and thus for our purposes are equivalent. OpenAddresses would prefer to only accept more liberal licenses, and we are writing code to segment data by license so that share-alike data can be released in a separate dataset.

**Comment by sbma44** [comment]
Thanks for the clarification, @cquest. I'm disappointed to learn that FANTOIR is not a complete cadastral dataset, as my research had led me to believe.

FWIW, here is a list of sources from within the BANO project. The ones that are License Ouverte should probably be separate sources within OpenAddresses. I have promised to look at Mexico's data first, but will turn to this next.

**Comment by cquest** [comment]
BANO scripts could output a non ODbL dataset made of cadastre extracted data + non ODbL opendata.
We just did not work on this (days are only 24 hours long in France too) as we have no problem with ODbL and because this would create a smaller dataset and a full one is much more usefull in the case of addresses.

**Comment by sbma44** [comment]
Interesting. I will take a closer look at getting BANO running, with a goal of segmenting the dataset within OpenAddresses.

**Comment by cquest** [comment]
I doubt you can easily run BANO scripts as you'll have to scrap 1M+ PDF files from the cadastre web site, which takes a couple of weeks...

**Comment by sbma44** [comment]
That should be fine. Is the limit the cadastre webserver? Does BANO cache these anywhere?

**Comment by cquest** [comment]
Yes, BANO caches the PDF files to avoid hitting the cadastre server too hard too often.

**Comment by sbma44** [comment]
Got it, what I meant was: does BANO make those files available for download?

For now I will begin the collection. Am I correct in assuming that commenting out this line disables ODbL datasources?

https://github.com/osm-fr/bano/blob/38383ca020d042d6123aad633db701243261f61a/update-all.sh#L5

**Comment by cquest** [comment]
BANO does not make the PDF files available for download for several reasons:
- we are not allowed to provide a full copy of the cadastre data, only allowed to reuse PARTS of the cadastre data in a COMPOSITE database
- the way these files are stored makes sense only to BANO scripts

If you really want to test BANO scripts and need access to these files, I can arrange that.

Commenting this single line will not make BANO ODbL free as OSM data are used in several places, including when extracting address points from the cadastre to match with streets, buildings and so on. Street names for example are "improved" using OSM data: "RUE DU GAL DE GAULLE" > "Rue du Général de Gaulle"

**Comment by tuxayo** [comment]
So in the end, what happened? There isn't BANO (thus OSM thus ODBL) data in openaddresses but it's accepts other data that have some other copyleft licenses?

**Comment by iandees** [comment]
We ended up switching to a different dataset that has CC-BY licensing in https://github.com/openaddresses/openaddresses/pull/4693.
