### ISSUE TITLE
Parks obscuring addresses in coverage map

### ISSUE THREAD

**Issue by wboykinm** [openaddresses/openaddresses#839]
Pull park land use out of the reference overlay and put it in the base layer; it's [wiping out whole counties in Vermont](https://www.mapbox.com/bites/00085/#10/43.0543/-72.9849) :smiley_cat: 

![2015-01-09_1126](https://cloud.githubusercontent.com/assets/735463/5683095/25d52442-97f3-11e4-9c95-ac372285ea4b.png)

**Comment by sbma44** [comment]
Good catch. Have fixed the style; tiles are regenerating now.
