### ISSUE TITLE
Address File Publicly Available for North California

### ISSUE THREAD

**Issue by wheredoesyourmindgo** [openaddresses/openaddresses#840]
There is a address point data file that can be downloaded from the Placer County Website, which contains address points for then entire county. Is this something that can be loaded?

ftp://ftp1.placer.ca.gov/cdra/gis/parcel_point_ByAddress.zip

**Comment by hampelm** [comment]
Good stuff! Looks like the OA team already has this in at [us-ca-placer_county.json](https://github.com/openaddresses/openaddresses/blob/master/sources/us-ca-placer_county.json)
