### ISSUE TITLE
Korean source CSV files have an inconsistent number of columns

### ISSUE THREAD

**Issue by NelsonMinar** [openaddresses/openaddresses#851]
The `kr-seoul-*` files name CSV sources stored in our own S3 bucket, at URLs like http://s3.amazonaws.com/data.openaddresses.io/cache/kr-seoul-songpagu.zip

The CSV files stored there are not well-formed. They mostly have 12 columns per row, but occasionally a  row has 13 columns. Is this fixable in the data source?

An example source with this problem is kr-seoul-chongnogu. Here's 5 rows from it, the middle row has an extra column. Note that the source encoding is EUCKR.

````
서울특별시,종로구,명륜2가,4,0,창경궁로,265,0,아남아파트,102동,199967.6616,454036.4788
서울특별시,종로구,명륜2가,4,0,창경궁로,265,0,아남아파트,103동,199970.6174,453969.5493
서울특별시,종로구,명륜2가,4,0,창경궁로,265,0,아남아파트,경로당,관리사무실,199985.4176,453957.7999
서울특별시,종로구,효제동,98,0,대학로,28,0,,D동,200272.9246,452712.8438
서울특별시,종로구,효제동,98,0,대학로,28,0,,,200237.5673,452699.3256
````

Here's [a Python script](https://gist.github.com/NelsonMinar/f67a5900c9e81d2c111d) to help identify problem CSV files. A quick shell snippet to find 13 column rows:

````
iconv -f EUCKR -t utf-8 < /tmp/korea/kr-seoul-chongnogu.csv | egrep '(.*,){12}'
````

**Comment by NelsonMinar** [comment]
It looks like it's the third-to-last column that's supicious. That's labelled "상세건물명" or "DET_BD_NM", which apparently is "Details Building Name". A good value for that is 102동, which means "102 East". A bad falue for that is "경로당,관리사무실", which Google Translate tells me means "Per path, administration office". I wonder if the source data just isn't quoted properly, that the comma is intended to be part of the address rather than a field separator?

I'm just going off of Google Translate; it'd be nice to have someone with Korean language skills look at this.

**Comment by sbma44** [comment]
I did some of the research for this data in a private repo (stupidly), but here are my notes. After reviewing them I feel pretty certain that the source data is untouched by my scripts -- if there are varying numbers of columns, it's probably in the source data. I strongly suspect that this is the result of someone rolling their own CSV creation script and failing to escape commas. 

@NelsonMinar can you ballpark how many rows are affected? We might be able to fix them manually or just throw them out.

Alternately, we do have a Korean speaker that we found and retained to make some phone calls to MLIT. I bet he'd be willing to look at this if we can isolate a good example of good rows versus bad rows (and perhaps test the above hypothesis about unescaped commas).

----

# Korean Open Address Data
The South Korean open data site is just horrible. The following files were collected by hand, with lots of clicking and filling out of fake filter criteria that match all records. It is probably possible to write a scraper but I do not envy the poor souls who try.

## License
There is a use license (in Korean) associated with data.seoul.go.kr, which has to be accepted prior to downloading each dataset. The data itself is licensed under CC-BY, as these UI elements of the dataset pages indicate.

Clicking the highlighted blue box:
![image](https://cloud.githubusercontent.com/assets/31717/5076556/e495de16-6e69-11e4-87e8-58f758a72f80.png)

Will reveal:
http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1084
![image](https://cloud.githubusercontent.com/assets/31717/5076376/87ad9802-6e68-11e4-882d-9d278c610d90.png)

## Transformations
Original downloaded filenames are preserved in the corresponding CSV. I was unable to transliterate them properly, so they are retained for historical interest. 

CSVs are in EUC-KR encoding, easily managed with `iconv`.

## Old/New Addresses
[Korea recently switched address systems](http://english.visitkorea.or.kr/enu/FU/FU_EN_15.jsp?cid=1886379). This data appears to contain fields for both styles of addresses within each record.

## Columns
```
1. attempt names (?)
2. sigungu name - same for all rows
3. eup/myeon/dong - town/township/neighborhood
4. old address system building bonbeon (street number)
5. old address system building bubeon (door)
6. road name
7. new address system building bonbeon (street number)
8. old address system building bubeon (door)
9. building name
10. building name contd
11. longitude
12. latitude
```

cf http://www.isotc211.org/Workshop_Busan/Presentations/Piotrowski.pdf & `annotated_fieldnames.png` in this repo.

## Source URL list
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1072
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1084
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1085
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1086   
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1082
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1080
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1078
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1067
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1064
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1076
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1075
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1074
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1073
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1090
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1089
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1088
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1083
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1081
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1079
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1077
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1068
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1069
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1070
-  http://data.seoul.go.kr/openinf/sheetview.jsp?infId=OA-1071

**Comment by NelsonMinar** [comment]
Thanks for the details! It's a very small number of rows, about 1 in 1000 for kr-seoul-chongnogu.csv and kr-seoul-songpagu.csv. A bit more looking suggests it's not always the third column from the last. None of the source CSV contains quoted text, so I bet it's a lack of quoting that's to blame.

I hate to volunteer for the extra work, but I think rather than trying to hand-patch a few sources we should make the conform parsing code more tolerant of malformed input. It's simple enough conceptually to just skip unparseable rows, although it's a PITA to implement with Python's CSV module.

**Comment by sbma44** [comment]
Yeah, agreed. Tossing broken rows is the way to go. I would probably just do something hacky like 

```
try:
    row = next(csv_reader)
except:
    continue
```

but I haven't done this in python 3.

**Comment by NelsonMinar** [comment]
OK I moved this to a [machine code issue](https://github.com/openaddresses/machine/issues/36).
