### ISSUE TITLE
Mexico

### ISSUE THREAD

**Issue by sbma44** [openaddresses/openaddresses#852]
[INEGI has recently opened their data](http://www.inegi.org.mx/terminos/terminos_info.aspx?bi=1), and it looks to me like this includes address numbers. Here's the relevant product page(?):

http://www.inegi.org.mx/geo/contenidos/urbana/sintesis.aspx

A useful PPT about this:

http://www.inegi.org.mx/geo/contenidos/urbana/?_file=/geo/contenidos/urbana/doc/localidad_urbana_capa_de_numeros_exteriores.ppt

A search engine(?) that seems to indicate which localities have address data (numeros exteriores):

http://www.inegi.org.mx/geo/contenidos/topografia/productos_geograficos.aspx

Still searching for whether this data can be found online at all.

**Comment by sbma44** [comment]
FTP site! ftp://rgnaftp:rgnaftp@geodesia.inegi.org.mx/ via http://www.inegi.org.mx/geo/contenidos/geodesia/procedimiento.aspx

**Comment by sbma44** [comment]
FTP site is a dead-end (just GPS calibration data) but there are shapefiles available here:

http://www3.inegi.org.mx/sistemas/productos/default.aspx?c=265&upc=0&s=est&tg=3604&f=2&cl=0&pf=prod&ef=0&ct=201100000&pg=2

I've confirmed that this includes address points:

![image](https://cloud.githubusercontent.com/assets/31717/5746501/17cb9390-9bfe-11e4-8b6d-998084238cf9.png)

I've spent some time looking for web downloads outside of this form but have come up empty. We've got some feelers out to contacts at INEGI about a bulk download, but if that's not viable we'll write a scraper.

**Comment by rodowi** [comment]
Hey @sbma44 I can help you contact INEGI to avoid writing a scraper, life is too short

**Comment by rodowi** [comment]
By the way, a smaller but useful dataset is the full list of postal codes that the Postal Service just published today: http://busca.datos.gob.mx/#/conjuntos/ubicacion-de-codigos-postales-en-mexico

**Comment by sbma44** [comment]
Thanks @rodowi! This is good stuff. I have already scraped INEGI months ago, but I didn't actually convert the points into an OA datasource -- I need to do that. A more definitive source would be welcome, though, as I had to guess which of the agency's many shapefiles were the correct ones to use.

Having a look at DENUE too, thanks for the pointer!

**Comment by sbma44** [comment]
PR over here for the DENUE data: https://github.com/openaddresses/openaddresses/pull/1298

**Comment by slibby** [comment]
@sbma44 can this be closed? It looks like you got all the available sources added.

**Comment by sbma44** [comment]
yep!
