### ISSUE TITLE
FOIA department of transportation for states

### ISSUE THREAD

**Issue by kelvinabrokwa** [openaddresses/openaddresses#868]
Yesterday, @sbma44  mentioned that we may be able to use the FOIA to request signage data (turn restrictions, bridge weight limits and all that jazz) from departments of transportation for each state. @ingalls pointed me to the [NFOIC website](http://www.nfoic.org/state-sample-foia-request-letters) which contains some handy dandy request templates for each state. Georgia, is shown at the bottom for example (it is a typical one).

I wrote a [scraper](https://gist.github.com/kelvinabrokwa/6d288e10cced7fbe69da) that picked up all of the webpages individually and parse them for the form data so I now have text files for every state. It seems that there is a general template that they follow but I need a bit of guidance filling in the blanks (especially the cost and public interest blanks). Nick suggested templating with mutache.js so once we get the language down we can just push it to all states and we'll have 50 letters ready to roll out.

>[Your Name]
>[Street Address]
>[City, ST ZIP Code]
>[Date]

>[Name of Custodian of Records]
>[Title]
>[Company Name]
>[Street Address]
>[City, ST ZIP Code]

>Dear [custodian of records]:

>	Under the Georgia Open Records Act § 50.18.70 et seq., I am requesting an opportunity to inspect or obtain copies of public records that [Describe the records or information sought with enough detail for the public agency to respond.  Be as specific as your knowledge of the available records will allow. But it is more important to describe the information you are seeking.]

>	If there are any fees for searching or copying these records, please inform me if the cost will exceed $______.  However, I would also like to request a waiver of all fees in that the disclosure of the requested information is in the public interest and will contribute significantly to the public’s understanding of ___________ [Here, you can identify yourself as a representative of the news media if applicable and state that your request is related to news gathering purposes.]  This information is not being sought for commercial purposes.

>	The Georgia Open Records Act requires a response time within three business days.  If access to the records I am requesting will take longer than three days, please contact me with information about when I might expect copies or the ability to inspect the requested records.

>	If you deny any or all of this request, please cite each specific exemption you feel justifies the refusal to release the information and notify me of the appeal procedures available to me under the law.

>	Thank you for considering my request.

>	Sincerely,
>[Your Name]
>[Your Phone number]

**Comment by iandees** [comment]
I would also encourage you to use [FOIA Machine](https://www.foiamachine.org/).

**Comment by sbma44** [comment]
Muckrock.com is another good option. Excited to see what this turns up!

**Comment by kelvinabrokwa** [comment]
For [muckrock](https://www.muckrock.com/) are we feeling $20 per 4 requests?

**Comment by iandees** [comment]
@kelvinabrokwa can we do a free one? Maybe try contacting them and asking for more information about discounts or supporting organizations like this one?

**Comment by sbma44** [comment]
If it offers advantages over FOIA Machine, sure, Mapbox can pick this up. If FOIA Machine is sufficient, we should just go with that, of course.

**Comment by ingalls** [comment]
See https://github.com/ingalls/node_ingester/issues
