### ISSUE TITLE
at-tirol.json

### ISSUE THREAD

**Issue by rowanwins** [openaddresses/openaddresses#871]
{
"attribution": "Office of the Provincial Government of Tyrol",
"website": "https://www.data.gv.at/katalog/dataset/d8beefc9-cf72-4e2c-9a78-fa1532dee407",
"type": "http",
"data": "https://gis.tirol.gv.at/ogd/geografie_planung/Raumordnung/Adressen.json",
"coverage": {
"ISO 3166": {"alpha2": "AT-7", "region": "Tirol", "country": "Austria"},
"region": "Tirol",
"country": "at"
},
"license": "https://creativecommons.org/licenses/by-sa/3.0/"
}

**Comment by geobrando** [comment]
tirol added [here]( https://github.com/openaddresses/openaddresses/blob/c56fb97441e22c0a7f182aecc48be7a1bcf0a2af/sources/at/tirol.json)
