### ISSUE TITLE
Fix source for San Juan County WA

### ISSUE THREAD

**Issue by npeihl** [openaddresses/openaddresses#894]
The source data is changing for San Juan County WA. The current source should be http://sjcgis.org/arcgis/rest/services/Polaris/Buildings/MapServer/0. 

Please let me know if you have any questions. I maintain the services.

**Comment by migurski** [comment]
Like this? https://github.com/openaddresses/openaddresses/pull/895/files

**Comment by npeihl** [comment]
I think so. Some of the fields did change since the first time I've submitted the source. Does that matter?

**Comment by migurski** [comment]
Yes, the fields should be updated in the conform part of the source; see: https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#conform-object
