### ISSUE TITLE
ca-bc-north_vancouver.json

### ISSUE THREAD

**Issue by MiniCodeMonkey** [openaddresses/openaddresses#898]
It looks like the dataset in https://github.com/openaddresses/openaddresses/blob/master/sources/ca-bc-north_vancouver.json is missing lat/lon.

I haven't double checked, but we might be able to link geodb_oid to this dataset http://geoweb.dnv.org/Products/Data/SHP/CadParcelPoint_shp.zip

**Comment by geobrando** [comment]
See my comments in #1262

**Comment by justinelliotmeyers** [comment]
closing as per updated source: https://github.com/openaddresses/openaddresses/issues/3856
