### ISSUE TITLE
Arkansas's data URL 404s

### ISSUE THREAD

**Issue by waldoj** [openaddresses/openaddresses#904]
[Arkansas' source file](https://github.com/openaddresses/openaddresses/blob/master/sources/us-ar.json) specifies `"data": "http://www.geostor.arkansas.gov/ArcGIS/rest/services/FEATURE_SERVICES/GEOSTOR_STRUCT/MapServer/0",` but [that URL doesn't work anymore](http://www.geostor.arkansas.gov/ArcGIS/rest/services/FEATURE_SERVICES/GEOSTOR_STRUCT/MapServer/0). I gather that they moved to an S3 URL. We'll need to track down that URL and update `us-ar.json`.

**Comment by waldoj** [comment]
[This appears to be the new page for their address points file](http://gis.arkansas.gov/?product=situs-address-points), but I don't know which file is appropriate for OpenAddresses' purposes. Somebody who knows the difference between a "Web Map Service" and a "Web Feature Service"—as I assuredly do not—should probably update `us-ar.json` to point to the right `data` URL, and update the `website` field while they're at it.

**Comment by waldoj** [comment]
FWIW, I think that the URL changed as a part of [their website relaunch on January 5](http://gis.arkansas.gov/?p=8174).

**Comment by iandees** [comment]
I put together a PR that updates the URL and adds to the conform object.
