### ISSUE TITLE
us-de

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#910]
came across delaware's arcgis portal, if thats useful  
http://firstmap.gis.delaware.gov/arcgis/rest/services

**Comment by geobrando** [comment]
Thanks. Don't see any address layers but found parcels, which I just added to the wiki.

Found their download portal but no addresses there either.  We'll have to keep an eye on these as state clearinghouses seem to be coming more prevalent.

https://dataexchange.gis.delaware.gov/dataexchange/download.aspx

**Comment by slibby** [comment]
I reviewed their statewide service when looking at the county-wide services and was unable to find any statewide addresses or parcels with address info. There are only three counties in DE and I think we have decent to good coverage for each from county-specific sources aleady. I suggest this issue be closed unless a good statewide source is available.
