### ISSUE TITLE
German data not showing on coverage map

### ISSUE THREAD

**Issue by KathleenLD** [openaddresses/openaddresses#911]
I noticed that there's nothing in Germany on the OpenAddresses.io coverage map, but PR #705 mentions several German cities that have been added. 

cc @sevko

**Comment by iandees** [comment]
The sources need to have [`conform` objects](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#conform-object) added so that we know where to find the address details in the source data.
