### ISSUE TITLE
us-ma source broken

### ISSUE THREAD

**Issue by geobrando** [openaddresses/openaddresses#912]
Zipped shapefile no longer found at [```data``` url] (https://www.dropbox.com/s/4dm6v0yeb96ulip/SHPStatewideParcelsAug2014.zip?dl=1) from [```us-ma.json```](/openaddresses/openaddresses/blob/master/sources/us-ma.json)

@ingalls Was this something you created from county shapefiles or was it being hosted by someone from the state?  Couldn't find a statewide layer at the [portal](http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/ftpl3parcels.html)

**Comment by iandees** [comment]
See also https://github.com/openaddresses/openaddresses/pull/720

**Comment by ingalls** [comment]
@geobrando This was a link that used to be on their site. It was provided by them

**Comment by geobrando** [comment]
@ingalls If it's not in the cache we'll have to get it from MassGIS, unless someone is interested in downloading and processing the individual county layers.  I emailed the contact there but I got an out-of-office reply until March 10th

cc @MiniCodeMonkey
