### ISSUE TITLE
Could I have commit privileges to this repo?

### ISSUE THREAD

**Issue by NelsonMinar** [openaddresses/openaddresses#913]
Hey, would it be OK if I got commit privileges to this repo? I keep fixing problems with sources as I work on the code and it'd be nice to commit them. Right now I have a literally one character change for #904 to fix all of `us-ar` am hoping to not have to go through the whole fork / branch / pull request rigamarole. More generally I'd like to be able to make fixes easily.

**Comment by iandees** [comment]
I can definitely add you, but having pull requests makes it a whole lot easier to know what's going on in the repo and to collaborate around the changes that are made.

**Comment by iandees** [comment]
Added!

**Comment by migurski** [comment]
:+1: to PR’s, :+1: to ability to make them directly on the repo instead of in a fork.

**Comment by iandees** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by geobrando** [comment]
Well as long as you're handing out privileges... :smile:

**Comment by migurski** [comment]
![+1](http://upload.wikimedia.org/wikipedia/commons/a/ab/Monty_python_foot.png)

**Comment by NelsonMinar** [comment]
Thanks for the privileges! I went ahead and recklessly committed 94df55bf12dbb003e myself. In the future do you want a pull request to review changes like that before they go in? I'm all for documenting changes carefully, but not sure something so simple merits review.

**Comment by iandees** [comment]
Nah, I think that's fine.
