### ISSUE TITLE
Source us-ca-placer_county status

### ISSUE THREAD

**Issue by wheredoesyourmindgo** [openaddresses/openaddresses#919]
This datasource was listed as completed, however, the address points don't appear on the web map @ http://openaddresses.io

**Comment by geobrando** [comment]
Might be related to openaddresses/openaddresses.io#41

**Comment by migurski** [comment]
I’m unsure how often the point map is updated. Placer County does look to be on the current [data status map](http://data.openaddresses.io/runs/1425022188.203/index.html).

**Comment by geobrando** [comment]
@wheredoesyourmindgo This look right to you now?

![placer_county](https://cloud.githubusercontent.com/assets/1833870/6763406/c0bc74fc-cf51-11e4-8833-9939473490fa.png)

**Comment by wheredoesyourmindgo** [comment]
Perfect.  Thanks for the reply. I'll close this out.
