### ISSUE TITLE
Recife, Brazil

### ISSUE THREAD

**Issue by astoff** [openaddresses/openaddresses#925]
http://dados.recife.pe.gov.br/dataset/area-urbana/resource/c82a414a-066f-4acc-922c-e3a63ed047f8

The address of each parcel is contained in the field endereco_completo, in the format "(street name), (house number)".

Data is under the ODbL.

**Comment by slibby** [comment]
This issue can be closed. The source still needs a conform object with a regex to extract the Street Name, but that "issue" is already captured in each /results run.
