### ISSUE TITLE
Rīga, Latvia

### ISSUE THREAD

**Issue by ansis** [openaddresses/openaddresses#942]
https://opendata.riga.lv/visas-datu-kopas.html
https://opendata.riga.lv/visas-datu-kopas.html?file=files/Opendata/Dati-Vectori/Attistiba/Adreses_shp_05_03_15.zip

license:
https://opendata.riga.lv/licence.html
http://opendatacommons.org/licenses/by/1.0/

**Comment by slibby** [comment]
Contributed here: https://github.com/openaddresses/openaddresses/pull/1371
