### ISSUE TITLE
us-fl-hernando

### ISSUE THREAD

**Issue by colemanm** [openaddresses/openaddresses#949]
Reached out to Hernando County property appraiser through the contact listed [here](https://www.hernandocountygis-fl.us/CentralGISWebsite/Default.aspx?xml=Addressingdl), requesting access to the data.

**Comment by colemanm** [comment]
Heard back from county contact. Data is available for a $30 fee. Added this to the commercial sources wiki page.

>The Hernando County Addressing GIS data is available for a fee of $30 and is not available for download.

**Comment by iandees** [comment]
Could you follow up with them about where the order form is, how they take payment, and any agreements we might have to sign as part of payment?

**Comment by colemanm** [comment]
Sure - I have a couple of documents they sent me for that. Where's the best place to house that kind of thing going forward? A lot of our counties in FL (and probably all over US) have a similar process like this. I have a fee schedule doc and an order form.

**Comment by iandees** [comment]
A good start would be to e-mail them to me. Maybe we could share a Dropbox folder or something?

We can pay for data, but it doesn't make sense to pay for data that we can't share. If there's a doc we have to sign that prevents that in any way, then we need to renegotiate or come up with another tactic.

**Comment by colemanm** [comment]
Dropbox would work for me. Is it useful to store those kinds of files on GH? Perhaps in a separate repo for "outreach" or "acquisitions" documentation?

**Comment by colemanm** [comment]
Here's a link with PDFs for the fee schedule and request form:

https://cloudup.com/cx_rigsNzoX

I also followed up again to find out if there are licensing restrictions preventing redistribution/sharing. Will post back with update.

**Comment by colemanm** [comment]
Already got feedback from the county on this. Sounds like good news:

>The only restriction on the data is the reselling of it in its delivered form, there is no restriction on use.

**Comment by b-may** [comment]
According to Florida Statutes, the data is public domain and the county cannot restrict the data in any way.

They appear to have an address points data set and its in their ArcGIS server here: https://www.hernandocountygis-fl.us/arcgis10_3/rest/services/Parcels_Addresses/MapServer/2

I checked a few locations in their online mapping app and the address points appear on top of houses instead of the parcel centroid. This is the app I looked at: https://www.hernandocountygis-fl.us/PropertySearch/

**Comment by nvkelso** [comment]
Looks like that MapServer works still, good find! Ready for PR.
