### ISSUE TITLE
us-fl-escambia

### ISSUE THREAD

**Issue by colemanm** [openaddresses/openaddresses#950]
Reached out to Escambia county's GIS department (gis@myescambia.com) to locate the address data.

**Comment by b-may** [comment]
Did you ever get a response on address points? I searched around their ArcGIS Server and didn;t see address points. The parcel polygons are here: http://www.escpa.org/snapshots/downloads/County/shapefile/Parcel.zip

There's just a PIN and ALTKEY in the parcel polygons shapefile. 

The addresses are in the non-mineral parcels.csv file from the Property Appraiser. Three columns in the file have site address info - Situs, SitCity, and SiteZip. The CAMA data is $25. I can provide a recent copy if anyone wants it.

**Comment by justinelliotmeyers** [comment]
http://arcgis4.roktech.net/arcgis/rest/services/escambia/escambia_query_new/MapServer/1
