### ISSUE TITLE
us-fl-santa_rosa

### ISSUE THREAD

**Issue by colemanm** [openaddresses/openaddresses#951]
Contacted the Santa Rosa county property appraiser (info@srcpa.org) for information on data.

**Comment by slibby** [comment]
Found a Map Service backing their interactive map:
http://arcgis4.roktech.net/arcgis/rest/services/santarosa/GoMaps/MapServer/

Parcels have no Addresses (address attributes are for owner's location): http://arcgis4.roktech.net/arcgis/rest/services/santarosa/GoMaps/MapServer/23

Structures might work, and have addresses: http://arcgis4.roktech.net/arcgis/rest/services/santarosa/GoMaps/MapServer/15

**Comment by b-may** [comment]
They have changed things around a bit - this is the latest structures layer:
http://arcgis4.roktech.net/arcgis/rest/services/santarosa/GoMaps4_0/MapServer/2

Quick peek at them shows they are rooftop and not centroids. A nice bonus is they have the type of structure and common place name for example retail locations, etc.

**Comment by justinelliotmeyers** [comment]
https://data1-santarosagis.opendata.arcgis.com/datasets/parcels
