### ISSUE TITLE
us-fl-walton (corrupt dataset?)

### ISSUE THREAD

**Issue by colemanm** [openaddresses/openaddresses#952]
Found Walton county's address points dataset [here](http://www.co.walton.fl.us/index.aspx?nid=926) ([download](http://www.co.walton.fl.us/DocumentCenter/View/10308)), but it seems that the file is corrupt. Shapefile missing an `.shx` file. Anyone seen this problem before? Fixable?

**Comment by geobrando** [comment]
Thanks @colemanm. Looks like a missing shx can be easily reconstructed using the [pyshp](http://geospatialpython.com/2011/11/generating-shapefile-shx-files.html) library.

I was able to do it and uploaded a new zipped shapefile [here](https://dl.dropboxusercontent.com/u/32983619/AddressPoints.shp_201503050751344749.zip).  I'll leave it up to the @openaddresses/owners to decide if they want to upload this to S3 and have us add this as a source.

You could also email Walton County and alter them to the error and see if they'll fix it.

**Comment by colemanm** [comment]
Nice @geobrando - I tried using pyshp to rebuild, but couldn't get something that would open up in QGIS. Looks like yours works great. I've emailed the county GIS contact to see if the error can be fixed in their hosted file.

**Comment by sbma44** [comment]
@geobrando I just tried loading your fixed shapefile in OS X QGIS 2.6 without luck. Not sure what's going on (the contents look ok in `ogrinfo`). Can you confirm that they're rendering for you properly in QGIS or similar?

**Comment by geobrando** [comment]
@sbma44 Hmm.. I used Arc and had no problem.  Can check with QGIS when I get home tonight but I think the important question is if ogr is able to handle it. Can you try to convert it?

**Comment by sbma44** [comment]
@geobrando looks like it's the use of a coordinate system that's expressed in an odd way that's tripping up QGIS. From the PRJ file:

```
PROJCS["NAD_1983_StatePlane_Florida_North_FIPS_0903_Feet",GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["False_Easting",1968500.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-84.5],PARAMETER["Standard_Parallel_1",29.58333333333333],PARAMETER["Standard_Parallel_2",30.75],PARAMETER["Latitude_Of_Origin",29.0],UNIT["Foot_US",0.3048006096012192]]
```

Works fine when I specify EPSG:3515. Good enough!

**Comment by geobrando** [comment]
@sbma44 Great! Yeah, unrelated to the missing `.shx` file I believe.  That shapefile was tore up.

**Comment by colemanm** [comment]
Heard back from GIS team at the county. They repaired the file and updated the link on the site. Just contributed a sources file in #958 that should work. Check it out and let me know if that looks correct.

Thanks!

**Comment by sbma44** [comment]
Looks good. Nice work!
