### ISSUE TITLE
us-fl-gulf

### ISSUE THREAD

**Issue by colemanm** [openaddresses/openaddresses#953]
Reached out to the Gulf county GIS department (gis@gulfcounty-fl.gov) about their data. There's address data available through their [online map interface](http://maps2.roktech.net/gulf/#), but couldn't find a download.

**Comment by slibby** [comment]
@colemanm I think this can be closed now, I added the ArcGIS Server service behind the map here: https://github.com/openaddresses/openaddresses/pull/1358

**Comment by colemanm** [comment]
Awesome!
