### ISSUE TITLE
1 missed record in us-ca-alameda_county.csv

### ISSUE THREAD

**Issue by xjlin0** [openaddresses/openaddresses#993]
There is a record in us-ca-alameda_county.csv with empty street name, around row 525352.  It should be Bigge St. Thanks for your efforts!

https://www.google.com/maps/place/10700+Bigge+St,+94577
https://www.google.com/maps/place/37°43'36.7"N+122°11'15.4"W/@37.7268605,-122.1876111

**Comment by geobrando** [comment]
Hi @xjlin0. Thanks for the information. Since openaddresses is pulling directly from the authoritative source, one would have to contact the county directly with any corrections.  Want to take the lead and contact them?

In the future I think the intent is that there will be mechanism built in to allow reporting of errors to municipalities.

**Comment by xjlin0** [comment]
Hi Brando:

In addition, there are about ~100 records missing zip codes, could you tell me where's the source you pull from?  I might be able to find the possibilities to contact them.  

Meanwhile, if I fill the empty cells, should I send you back the curated data instead?

Thanks!

**Comment by geobrando** [comment]
So if you navigate [here](https://github.com/openaddresses/openaddresses/tree/master/sources) you'll find the list of sources, with each in a separate JSON file.  If you click on [us-ca-alameda_county.json](https://github.com/openaddresses/openaddresses/blob/master/sources/us-ca-alameda_county.json) you will find the source metadata.  The `data:` field is the path to the source data.  Sometimes you will find a `website` field that might take you to the city/county/etc website.  Though there's not one for this source.

It's likely the county assessor's office. http://acgov.org/assessor/resources/

If the county makes any changes to their data it will reflected in this repository during the next run.

**Comment by ingalls** [comment]
Closing - @xjlin0 feel free to reopen open another ticket if you have any more questions.
