### ISSUE TITLE
Fix incorrect PL-Łódzkie source

### ISSUE THREAD

**Issue by migurski** [openaddresses/openaddresses#994]
Looking at the results of https://github.com/openaddresses/openaddresses/pull/872, I can see that the file labeled `pl-lodzkie` actually covers the Śląskie area further to the south. What other errors lurk in this set of sources?

**Comment by sbma44** [comment]
the labeling is the only error source I know of. The source zip had character encoding issues that couldn't be fixed programmatically, and toponyms that aren't easily mapped to their English transliterations. So I went through making best guesses based on location, name similarity & process of elimination (working off a wikipedia list of vovoideships). Could *definitely* use more eyes, though.

**Comment by migurski** [comment]
I’ll run through them all to try to fix inconsistencies.

**Comment by migurski** [comment]
* Łódzkie and Śląskie are switched.
* Mazovieckie is missing.

**Comment by migurski** [comment]
Fixed the switched ones directly in the source data, and fixed Lubelskie display in https://github.com/openaddresses/machine/commit/3b8e757c892c2262e876092a7e19eb949b748262. Mazowieckie turned out to be fine.
